import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch07: Record<string, EditorialQuizSet> = {
  "besogne:besogne_work": {
    early: "La besogne de ce matin consiste à réparer la clôture.", englishChoices: ["task", "reward", "rest", "journey"],
    intermediate: "Il reste une longue _____ à accomplir avant de fermer l’atelier.", frenchChoices: ["besogne", "pause", "récompense", "promenade"],
    advanced: "Après le déjeuner, la besogne reprend dans l’atelier : chacun doit terminer une commande. Une pause est prévue plus tard, et la livraison aura lieu demain.",
    prompt: "Quel mot désigne le travail à accomplir dans l’atelier ?", advancedChoices: ["besogne", "pause", "livraison", "déjeuner"],
  },
  "besoin:besoin_need": {
    early: "Après trois heures de marche, les randonneurs ont besoin d’eau.", englishChoices: ["need", "surplus", "memory", "offer"],
    intermediate: "Le toit fuit ; nous avons _____ d’un couvreur dès aujourd’hui.", frenchChoices: ["besoin", "souvenir", "envie", "preuve"],
    advanced: "Sans chauffage, cette famille a besoin d’un abri pour la nuit. Le maire propose une salle, tandis que les voisins apportent des couvertures.",
    prompt: "Quel mot exprime une nécessité pour cette famille ?", advancedChoices: ["besoin", "abri", "salle", "couvertures"],
  },
  "bientôt:bientot_soon": {
    early: "Le train arrive bientôt : il sera là dans cinq minutes.", englishChoices: ["soon", "yesterday", "rarely", "secretly"],
    intermediate: "Le spectacle commence dans deux minutes ; les lumières vont _____ s’éteindre.", frenchChoices: ["bientôt", "hier", "rarement", "dehors"],
    advanced: "Le soleil se couchera bientôt. Les enfants jouent encore dehors, puis ils rentreront avant la nuit.",
    prompt: "Quel mot indique que le coucher du soleil est proche ?", advancedChoices: ["bientôt", "encore", "dehors", "avant"],
  },
  "bienveillant:bienveillant_kind": {
    early: "Le professeur bienveillant rassure chaque élève qui se trompe.", englishChoices: ["kind", "hostile", "indifferent", "impatient"],
    intermediate: "Même après l’erreur de Paul, le professeur reste _____ et l’encourage à réessayer.", frenchChoices: ["bienveillant", "méprisant", "hostile", "cruel"],
    advanced: "Le directeur bienveillant écoute les nouveaux employés et les aide à trouver leurs repères. Son adjoint impatient réclame déjà les rapports.",
    prompt: "Quel mot qualifie l’attitude généreuse du directeur envers les employés ?", advancedChoices: ["bienveillant", "impatient", "nouveaux", "déjà"],
  },
  "bondisse:bondir_leap": {
    early: "La foule attend que le danseur bondisse au-dessus du banc.", englishChoices: ["leaps", "falls", "sleeps", "whispers"],
    intermediate: "Le public veut que l’acrobate _____ par-dessus la corde, d’un seul élan.", frenchChoices: ["bondisse", "rampe", "marche", "s’arrête"],
    advanced: "Le dresseur attend que le chien bondisse par-dessus la barrière au signal. Le chat reste couché et le cheval avance lentement.",
    prompt: "Quel mot exprime le saut soudain attendu du chien ?", advancedChoices: ["bondisse", "couché", "avance", "lentement"],
  },
  "bonheur:bonheur_happiness": {
    early: "Retrouver sa famille après un an d’absence lui procure un grand bonheur.", englishChoices: ["happiness", "anger", "fear", "shame"],
    intermediate: "Elle sourit en retrouvant son frère : quel _____ de le revoir !", frenchChoices: ["bonheur", "chagrin", "ennui", "effroi"],
    advanced: "Le bonheur de Léa se lit sur son visage quand elle retrouve son frère. Paul partage sa joie, tandis que leur mère essuie une larme.",
    prompt: "Quel mot désigne la satisfaction profonde de Léa ?", advancedChoices: ["bonheur", "visage", "joie", "larme"],
  },
  "bordereau:bordereau_document": {
    early: "Le greffier classe le bordereau avec les autres documents du dossier.", englishChoices: ["document", "witness", "verdict", "building"],
    intermediate: "Le juge demande à voir le _____, ce document écrit versé au dossier.", frenchChoices: ["bordereau", "témoin", "procès", "tribunal"],
    advanced: "Dans les archives, le bordereau porte une liste écrite à la main. Le greffier ouvre le dossier, compare les signatures et note la date.",
    prompt: "Quel mot désigne le document conservé dans les archives ?", advancedChoices: ["bordereau", "greffier", "signatures", "date"],
  },
  "bottes:botte_boot": {
    early: "Elle met ses bottes avant de traverser le champ boueux.", englishChoices: ["boots", "gloves", "hats", "scarves"],
    intermediate: "Pour garder les pieds au sec dans la boue, les enfants enfilent leurs _____.", frenchChoices: ["bottes", "gants", "bonnets", "écharpes"],
    advanced: "Les bottes de Luc montent jusqu’aux genoux et protègent ses pieds de l’eau. Son manteau sèche près du feu, et son chapeau repose sur une chaise.",
    prompt: "Quel mot désigne les chaussures hautes de Luc ?", advancedChoices: ["bottes", "manteau", "chapeau", "chaise"],
  },
  "bouches:bouche_mouth": {
    early: "Toutes les bouches se taisent quand la chanteuse entre en scène.", englishChoices: ["mouths", "hands", "eyes", "ears"],
    intermediate: "Les enfants ouvrent la bouche pour chanter ; bientôt, toutes les _____ reprennent le refrain.", frenchChoices: ["bouches", "mains", "oreilles", "jambes"],
    advanced: "Quand le conteur s’arrête, plusieurs bouches reprennent son refrain dans la salle. Les mains battent la mesure et les yeux suivent le chef de chœur.",
    prompt: "Quel mot désigne ici les organes qui chantent le refrain ?", advancedChoices: ["bouches", "mains", "yeux", "salle"],
  },
  "boue:boue_mud": {
    early: "Après l’orage, les roues du vélo s’enfoncent dans la boue.", englishChoices: ["mud", "snow", "sand", "dust"],
    intermediate: "La pluie a détrempé le chemin : nos chaussures sont couvertes de _____.", frenchChoices: ["boue", "neige", "sable", "poussière"],
    advanced: "La boue colle aux chaussures après la pluie. La neige a fondu sur les collines, mais la poussière couvre encore les étagères de la grange.",
    prompt: "Quel mot désigne la terre détrempée sur les chaussures ?", advancedChoices: ["boue", "neige", "poussière", "grange"],
  },
  "bouleverser:bouleverser_upend": {
    early: "Une fermeture soudaine risque de bouleverser la vie du village.", englishChoices: ["to disrupt", "to preserve", "to measure", "to imitate"],
    intermediate: "La nouvelle loi pourrait _____ complètement l’organisation de l’école.", frenchChoices: ["bouleverser", "préserver", "stabiliser", "maintenir"],
    advanced: "Fermer la seule école risque de bouleverser la vie du village. Les parents protestent, le maire consulte les habitants et les enseignants cherchent une solution.",
    prompt: "Quel verbe signifie changer profondément la vie du village ?", advancedChoices: ["bouleverser", "protestent", "consulte", "cherchent"],
  },
  "bousculé:bousculer_pressure": {
    early: "Dans la foule, le voyageur a été bousculé contre la porte du train.", englishChoices: ["shoved", "welcomed", "guided", "praised"],
    intermediate: "La foule l’a _____ si rudement qu’il a perdu l’équilibre.", frenchChoices: ["bousculé", "accueilli", "protégé", "félicité"],
    advanced: "Le vendeur a été bousculé par des clients pressés devant l’entrée. Sa collègue l’a aidé à se relever, puis le gardien a dégagé le passage.",
    prompt: "Quel mot indique que des clients ont poussé le vendeur avec brusquerie ?", advancedChoices: ["bousculé", "aidé", "relever", "dégagé"],
  },
  "braves:brave_good": {
    early: "Ces braves voisins gardent gratuitement le chien de leur amie malade.", englishChoices: ["good-hearted", "dishonest", "hostile", "selfish"],
    intermediate: "Ces _____ gens ont accueilli la famille sans rien demander en retour.", frenchChoices: ["braves", "cruels", "méchants", "malhonnêtes"],
    advanced: "Ces braves voisins apportent des repas à Léa pendant sa maladie. Leur geste généreux touche sa famille ; un commerçant leur prête aussi une voiture.",
    prompt: "Quel mot qualifie les voisins honnêtes et serviables ?", advancedChoices: ["braves", "repas", "commerçant", "voiture"],
  },
  "bravoure:bravoure_courage": {
    early: "Le pompier a montré sa bravoure en entrant dans l’immeuble en feu.", englishChoices: ["bravery", "carelessness", "hesitation", "anger"],
    intermediate: "Elle a affronté le danger pour sauver les enfants : chacun salue sa _____.", frenchChoices: ["bravoure", "lâcheté", "indifférence", "jalousie"],
    advanced: "En sauvant deux nageurs malgré les vagues, Nina a fait preuve de bravoure. Le sauveteur l’a rejointe, puis la foule les a applaudis.",
    prompt: "Quel mot désigne le courage de Nina face au danger ?", advancedChoices: ["bravoure", "vagues", "sauveteur", "foule"],
  },
  "brûlantes:brulant_intense": {
    early: "Elle écrit des pages brûlantes de colère après cette injustice.", englishChoices: ["impassioned", "indifferent", "polite", "restrained"],
    intermediate: "Ses paroles _____ d’indignation émeuvent toute la salle.", frenchChoices: ["brûlantes", "froides", "neutres", "détachées"],
    advanced: "Ses paroles brûlantes d’indignation frappent l’assemblée. Le président garde un ton calme, une journaliste prend des notes et les invités restent silencieux.",
    prompt: "Quel mot souligne l’intensité ardente de ses paroles ?", advancedChoices: ["brûlantes", "calme", "silencieux", "journaliste"],
  },
  "brusque:brusque_sudden": {
    early: "Un brusque coup de vent emporte les papiers de la table.", englishChoices: ["sudden", "gradual", "gentle", "steady"],
    intermediate: "La _____ interruption du courant a plongé la salle dans le noir en une seconde.", frenchChoices: ["brusque", "longue", "lente", "douce"],
    advanced: "Un mouvement brusque du train fait tomber un sac. Le conducteur ralentit ensuite, et une passagère ramasse ses affaires.",
    prompt: "Quel mot qualifie le mouvement soudain du train ?", advancedChoices: ["brusque", "ralentit", "passagère", "affaires"],
  },
  "bureau:bureau_office": {
    early: "Le dossier est arrivé au bureau chargé des inscriptions.", englishChoices: ["department", "garden", "staircase", "restaurant"],
    intermediate: "Pour renouveler sa carte, Nina s’adresse au _____ administratif compétent.", frenchChoices: ["bureau", "jardin", "restaurant", "couloir"],
    advanced: "Le bureau des inscriptions vérifie les demandes chaque matin. À l’accueil, une agente oriente les visiteurs ; les archives conservent les anciens dossiers.",
    prompt: "Quel mot désigne le service chargé de vérifier les demandes ?", advancedChoices: ["bureau", "accueil", "archives", "visiteurs"],
  },
  "bureaux:bureau_office": {
    early: "Les bureaux du ministère ouvrent leurs guichets à neuf heures.", englishChoices: ["departments", "gardens", "restaurants", "staircases"],
    intermediate: "Les demandes sont réparties entre plusieurs _____ administratifs du ministère.", frenchChoices: ["bureaux", "jardins", "restaurants", "escaliers"],
    advanced: "Les bureaux du ministère traitent des demandes différentes. Les guichets reçoivent le public, tandis que les archives gardent les dossiers anciens.",
    prompt: "Quel mot désigne les services administratifs du ministère ?", advancedChoices: ["bureaux", "guichets", "archives", "dossiers"],
  },
  "cachent:cacher_hide": {
    early: "Les enfants cachent leurs cadeaux dans l’armoire avant la fête.", englishChoices: ["hide", "display", "open", "count"],
    intermediate: "Pour garder la surprise, les parents _____ les cadeaux dans le placard.", frenchChoices: ["cachent", "montrent", "offrent", "exposent"],
    advanced: "Les enfants cachent les biscuits derrière les livres pour que personne ne les voie. Leur mère ferme le placard et leur père prépare le dîner.",
    prompt: "Quel mot indique que les enfants mettent les biscuits hors de vue ?", advancedChoices: ["cachent", "ferme", "prépare", "voie"],
  },
  "cacher:cacher_hide": {
    early: "Pour préparer une surprise, Paul veut cacher le cadeau sous son lit.", englishChoices: ["to hide", "to display", "to offer", "to break"],
    intermediate: "Pour que personne ne voie le cadeau, il faut le _____ sous le lit.", frenchChoices: ["cacher", "montrer", "offrir", "exposer"],
    advanced: "Luc décide de cacher la lettre dans un tiroir. Nina range les livres, Marie cherche une enveloppe et Paul ferme la fenêtre.",
    prompt: "Quel verbe signifie mettre la lettre hors de vue ?", advancedChoices: ["cacher", "range", "cherche", "ferme"],
  },
  "calomnies:calomnie_slander": {
    early: "Les calomnies inventées contre la médecin ont abîmé sa réputation.", englishChoices: ["false accusations", "compliments", "requests", "promises"],
    intermediate: "Il répand des mensonges pour salir sa réputation : ses _____ sont graves.", frenchChoices: ["calomnies", "éloges", "remerciements", "excuses"],
    advanced: "Des calomnies circulent contre la directrice : on lui attribue à tort un vol. Elle apporte des preuves, et ses collègues demandent des excuses publiques.",
    prompt: "Quel mot désigne les accusations mensongères contre la directrice ?", advancedChoices: ["calomnies", "preuves", "collègues", "excuses"],
  },
  "camarades:camarade_colleague": {
    early: "Les camarades de Nina travaillent avec elle dans la même équipe.", englishChoices: ["colleagues", "strangers", "rivals", "customers"],
    intermediate: "Au laboratoire, ses _____ lui prêtent leurs notes : ils font partie de la même équipe.", frenchChoices: ["camarades", "clients", "rivaux", "inconnus"],
    advanced: "Les camarades de Paul partagent son atelier et réparent les mêmes machines. Les clients attendent dehors, tandis que le directeur inspecte les travaux.",
    prompt: "Quel mot désigne les collègues de Paul dans l’atelier ?", advancedChoices: ["camarades", "clients", "directeur", "machines"],
  },
  "campagne:campagne_campaign": {
    early: "L’association lance une campagne pour réduire les déchets dans la ville.", englishChoices: ["campaign", "vacation", "accident", "building"],
    intermediate: "Pendant un mois, l’association mènera une _____ de sensibilisation au tri des déchets.", frenchChoices: ["campagne", "vacances", "maison", "dispute"],
    advanced: "La campagne de vaccination mobilise les infirmières pendant tout le printemps. Le centre ouvre chaque jour, les patients prennent rendez-vous et le maire diffuse des affiches.",
    prompt: "Quel mot désigne l’ensemble des actions organisées pour vacciner ?", advancedChoices: ["campagne", "centre", "rendez-vous", "affiches"],
  },
  "campagnes:campagne_campaign": {
    early: "Deux campagnes de prévention ont été lancées cette année dans les écoles.", englishChoices: ["campaigns", "holidays", "accidents", "buildings"],
    intermediate: "La mairie mène plusieurs _____ de sensibilisation, l’une sur l’eau et l’autre sur le recyclage.", frenchChoices: ["campagnes", "vacances", "maisons", "disputes"],
    advanced: "Les campagnes de sécurité routière se succèdent chaque année. Les affiches changent, les écoles reçoivent des brochures et la police rencontre les élèves.",
    prompt: "Quel mot désigne les actions organisées de prévention ?", advancedChoices: ["campagnes", "affiches", "brochures", "écoles"],
  },
  "capables:capable_able": {
    early: "Avec les bons outils, ces artisans sont capables de réparer le toit.", englishChoices: ["able", "unable", "reluctant", "forbidden"],
    intermediate: "Après leur formation, ils seront _____ de réparer cette machine seuls.", frenchChoices: ["capables", "incapables", "interdits", "empêchés"],
    advanced: "Ces jeunes sont capables de construire une petite barque : ils ont les outils et connaissent la méthode. Leur professeur surveille les essais.",
    prompt: "Quel mot indique qu’ils ont les moyens de construire la barque ?", advancedChoices: ["capables", "outils", "méthode", "professeur"],
  },
  "car:car_because": {
    early: "Je ferme la fenêtre, car le vent est froid.", englishChoices: ["because", "although", "unless", "while"],
    intermediate: "La randonnée est annulée, _____ un orage approche et le chemin devient dangereux.", frenchChoices: ["car", "mais", "quoique", "pourtant"],
    advanced: "Nous restons à la maison, car la pluie rend le chemin glissant. Léa part pourtant chercher du pain ; Paul attend ici avec les enfants.",
    prompt: "Quel mot introduit la raison pour laquelle nous restons à la maison ?", advancedChoices: ["car", "pourtant", "ici", "avec"],
  },
};
