import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a lantern","a mushroom","a staircase"];
const nF:[string,string,string]=["lanterne","champignon","escalier"];
const aE:[string,string,string]=["striped","lavender-scented","cubic"];
const aF:[string,string,string]=["rayé","parfumé à la lavande","cubique"];
const vE:[string,string,string]=["to embroider","to surf","to hiccup"];
const vF:[string,string,string]=["broder","surfer","hoqueter"];

export const zolaVocabularyBatch19: ZolaVocabularySpec[] = [
 {normalized:"endormi",lemmaKey:"endormir",headword:"endormir",partOfSpeech:"verb",senseKey:"endormir_sleep",gloss:"to put to sleep; be asleep",quizMeaning:"asleep",definition:"plongé dans le sommeil",englishDistractors:["embroidered","surfed","hiccuped"],frenchDistractors:["brodé","surfé","hoqueté"]},
 {normalized:"endroits",lemmaKey:"endroit",headword:"endroit",partOfSpeech:"noun",senseKey:"endroit_place",gloss:"place; spot",quizMeaning:"places",definition:"partie déterminée d’un espace",englishDistractors:["lanterns","mushrooms","staircases"],frenchDistractors:["lanternes","champignons","escaliers"]},
 {normalized:"enfantine",lemmaKey:"enfantin",headword:"enfantin",partOfSpeech:"adjective",senseKey:"enfantin_childish",gloss:"childish; naive",definition:"qui manque de maturité ou de sérieux comme un enfant",englishDistractors:aE,frenchDistractors:["rayée","parfumée à la lavande","cubique"]},
 {normalized:"enfants",lemmaKey:"enfant",headword:"enfant",partOfSpeech:"noun",senseKey:"enfant_child",gloss:"child",quizMeaning:"children",definition:"jeune être humain qui n’a pas atteint l’âge adulte",englishDistractors:["lanterns","mushrooms","staircases"],frenchDistractors:["lanternes","champignons","escaliers"]},
 {normalized:"enferme",lemmaKey:"enfermer",headword:"enfermer",partOfSpeech:"verb",senseKey:"enfermer_confine",gloss:"to lock up; confine",quizMeaning:"locks up; confines",definition:"retenir dans un espace fermé",englishDistractors:["embroiders","surfs","hiccups"],frenchDistractors:["brode","surfe","hoquette"]},
 {normalized:"enfin",lemmaKey:"enfin",headword:"enfin",partOfSpeech:"adverb",senseKey:"enfin_finally",gloss:"finally; lastly",definition:"marque le dernier élément ou l’aboutissement d’une suite",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"enflammée",lemmaKey:"enflamme",headword:"enflammé",partOfSpeech:"adjective",senseKey:"enflamme_impassioned",gloss:"impassioned; fiery",definition:"animé d’une passion très vive",englishDistractors:aE,frenchDistractors:["rayée","parfumée à la lavande","cubique"]},
 {normalized:"engagé",lemmaKey:"engager",headword:"engager",partOfSpeech:"verb",senseKey:"engager_commit",gloss:"to commit; involve",quizMeaning:"committed; involved",definition:"faire entrer ou entrer dans une action qui crée une responsabilité",englishDistractors:["embroidered","surfed","hiccuped"],frenchDistractors:["brodé","surfé","hoqueté"]},
 {normalized:"engager",lemmaKey:"engager",headword:"engager",partOfSpeech:"verb",senseKey:"engager_commit",gloss:"to commit; involve",definition:"faire entrer ou entrer dans une action qui crée une responsabilité",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"ennemi",lemmaKey:"ennemi",headword:"ennemi",partOfSpeech:"noun",senseKey:"ennemi_adversary",gloss:"enemy; adversary",definition:"personne ou puissance hostile",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"ennemis",lemmaKey:"ennemi",headword:"ennemi",partOfSpeech:"noun",senseKey:"ennemi_adversary",gloss:"enemy; adversary",quizMeaning:"enemies; adversaries",definition:"personne ou puissance hostile",englishDistractors:["lanterns","mushrooms","staircases"],frenchDistractors:["lanternes","champignons","escaliers"]},
 {normalized:"enquête",lemmaKey:"enquete",headword:"enquête",partOfSpeech:"noun",senseKey:"enquete_investigation",gloss:"investigation; inquiry",definition:"recherche méthodique destinée à établir des faits",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"enquêtes",lemmaKey:"enquete",headword:"enquête",partOfSpeech:"noun",senseKey:"enquete_investigation",gloss:"investigation; inquiry",quizMeaning:"investigations; inquiries",definition:"recherche méthodique destinée à établir des faits",englishDistractors:["lanterns","mushrooms","staircases"],frenchDistractors:["lanternes","champignons","escaliers"]},
 {normalized:"ensuite",lemmaKey:"ensuite",headword:"ensuite",partOfSpeech:"adverb",senseKey:"ensuite_afterward",gloss:"afterward; then",definition:"après ce qui vient d’être mentionné",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"entachera",lemmaKey:"entacher",headword:"entacher",partOfSpeech:"verb",senseKey:"entacher_tarnish",gloss:"to stain; tarnish",quizMeaning:"will stain; will tarnish",definition:"porter atteinte à la réputation ou à la pureté de quelque chose",englishDistractors:["will embroider","will surf","will hiccup"],frenchDistractors:["brodera","surfera","hoquettera"]},
 {normalized:"entendus",lemmaKey:"s_entendre",headword:"s’entendre",partOfSpeech:"verb",senseKey:"s_entendre_agree",gloss:"to agree",quizMeaning:"agreed",definition:"parvenir ensemble à la même opinion ou à un accord",englishDistractors:["embroidered","surfed","hiccuped"],frenchDistractors:["brodés","surfés","hoquetés"]},
 {normalized:"enterrer",lemmaKey:"enterrer",headword:"enterrer",partOfSpeech:"verb",senseKey:"enterrer_bury",gloss:"to bury",definition:"mettre sous terre ou dissimuler profondément",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"entier",lemmaKey:"entier",headword:"entier",partOfSpeech:"adjective",senseKey:"entier_whole",gloss:"whole; entire",definition:"qui est complet et auquel rien ne manque",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"entière",lemmaKey:"entier",headword:"entier",partOfSpeech:"adjective",senseKey:"entier_whole",gloss:"whole; entire",definition:"qui est complet et auquel rien ne manque",englishDistractors:aE,frenchDistractors:["rayée","parfumée à la lavande","cubique"]},
 {normalized:"entièrement",lemmaKey:"entierement",headword:"entièrement",partOfSpeech:"adverb",senseKey:"entierement_completely",gloss:"entirely; completely",definition:"d’une manière totale, sans exception",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"entités",lemmaKey:"entite",headword:"entité",partOfSpeech:"noun",senseKey:"entite_being",gloss:"entity; abstract being",quizMeaning:"entities; abstract beings",definition:"réalité considérée comme un être distinct, parfois abstrait",englishDistractors:["lanterns","mushrooms","staircases"],frenchDistractors:["lanternes","champignons","escaliers"]},
 {normalized:"entourage",lemmaKey:"entourage",headword:"entourage",partOfSpeech:"noun",senseKey:"entourage_circle",gloss:"entourage; circle",definition:"ensemble des personnes qui vivent ou travaillent près de quelqu’un",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"entraînait",lemmaKey:"entrainer",headword:"entraîner",partOfSpeech:"verb",senseKey:"entrainer_entail",gloss:"to entail; lead to",quizMeaning:"entailed; led to",definition:"avoir pour conséquence nécessaire",englishDistractors:["embroidered","surfed","hiccuped"],frenchDistractors:["brodait","surfait","hoquetait"]},
 {normalized:"entre",lemmaKey:"entre",headword:"entre",partOfSpeech:"preposition",senseKey:"entre_between",gloss:"between; among",definition:"dans l’espace, le temps ou la relation qui sépare plusieurs éléments",englishDistractors:["beneath","despite","along"],frenchDistractors:["sous","malgré","le long de"]},
];
