import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch12: Record<string, EditorialQuizSet> = {
  "condamnant:condamner_sentence": {
    early: "En condamnant le voleur à une amende, le juge lui inflige une peine.", englishChoices: ["sentencing", "acquitting", "rewarding", "inviting"],
    intermediate: "En _____ le prévenu à une peine après l’avoir déclaré coupable, le tribunal clôt le procès.", frenchChoices: ["condamnant", "acquittant", "libérant", "félicitant"],
    advanced: "En condamnant le prévenu à une amende, le juge sanctionne le vol. L’avocat prépare un recours, le greffier note la décision et le témoin sort de la salle.",
    prompt: "Quel mot indique que le juge prononce une peine contre le prévenu ?", advancedChoices: ["condamnant", "prépare", "note", "sort"],
  },
  "conduire:conduire_lead": {
    early: "Léa va conduire les visiteurs jusqu’à la salle de réunion.", englishChoices: ["to lead", "to abandon", "to conceal", "to follow"],
    intermediate: "Le guide doit _____ le groupe jusqu’au sommet par le sentier balisé.", frenchChoices: ["conduire", "abandonner", "égarer", "retenir"],
    advanced: "Nina propose de conduire les nouveaux élèves jusqu’à leur classe. Paul ouvre la porte, Luc distribue les cahiers et Marie vérifie les noms.",
    prompt: "Quel verbe signifie guider les élèves vers leur classe ?", advancedChoices: ["conduire", "ouvre", "distribue", "vérifie"],
  },
  "conduit:conduire_lead": {
    early: "Le guide a conduit les randonneurs au refuge avant la nuit.", englishChoices: ["led", "abandoned", "followed", "forgot"],
    intermediate: "Le bénévole a _____ les visiteurs jusqu’à l’entrée du musée.", frenchChoices: ["conduit", "égaré", "retenu", "abandonné"],
    advanced: "Le moniteur a conduit les enfants jusqu’au lac par un chemin sûr. Paul a porté les sacs, Nina a préparé le repas et Léa a photographié les oiseaux.",
    prompt: "Quel mot indique que le moniteur a guidé les enfants jusqu’au lac ?", advancedChoices: ["conduit", "porté", "préparé", "photographié"],
  },
  "confiante:confiant_trusting": {
    early: "Après avoir répété son discours, Nina se sent confiante avant la réunion.", englishChoices: ["confident", "doubtful", "frightened", "indifferent"],
    intermediate: "La joueuse se sait bien préparée ; elle arrive _____ au début du match.", frenchChoices: ["confiante", "inquiète", "terrifiée", "découragée"],
    advanced: "Léa est confiante avant son examen : elle a beaucoup révisé et connaît le programme. Paul reste inquiet, Nina relit une page et Marc attend dehors.",
    prompt: "Quel mot indique que Léa a confiance en elle ?", advancedChoices: ["confiante", "inquiet", "page", "dehors"],
  },
  "confondre:confondre_expose": {
    early: "Les reçus permettent de confondre le fraudeur en prouvant qu’il a menti.", englishChoices: ["to expose", "to defend", "to excuse", "to reward"],
    intermediate: "L’enregistrement prouve son mensonge et suffit à le _____ devant le juge.", frenchChoices: ["confondre", "innocenter", "protéger", "féliciter"],
    advanced: "Le témoin apporte une lettre capable de confondre le voleur : elle montre qu’il était sur les lieux. L’avocat consulte le dossier et le juge écoute la déposition.",
    prompt: "Quel verbe signifie démontrer la faute du voleur ?", advancedChoices: ["confondre", "consulte", "écoute", "apporte"],
  },
  "connais:connaitre_know": {
    early: "Je connais cette rue : j’y habitais autrefois.", englishChoices: ["know", "forget", "avoid", "invent"],
    intermediate: "J’ai déjà travaillé avec Luc, donc je le _____ personnellement.", frenchChoices: ["connais", "cherche", "crains", "suis"],
    advanced: "Je connais le propriétaire de cette maison depuis l’enfance. Nina cherche son adresse, Paul nettoie le jardin et Léa prépare du thé.",
    prompt: "Quel mot indique que cette personne m’est familière ?", advancedChoices: ["connais", "cherche", "nettoie", "prépare"],
  },
  "connaît:connaitre_know": {
    early: "Nina connaît bien son voisin, car ils se parlent chaque jour.", englishChoices: ["knows", "forgets", "avoids", "invents"],
    intermediate: "Paul habite ici depuis toujours ; il _____ chaque rue du quartier.", frenchChoices: ["connaît", "oublie", "invente", "évite"],
    advanced: "Léa connaît le nom de chaque oiseau du jardin après des années d’observation. Paul écoute leurs chants, Nina ouvre la fenêtre et Marc dessine un arbre.",
    prompt: "Quel mot indique que Léa sait identifier les oiseaux ?", advancedChoices: ["connaît", "écoute", "ouvre", "dessine"],
  },
  "connaîtra:connaitre_know": {
    early: "Après avoir lu la lettre, elle connaîtra enfin la date du départ.", englishChoices: ["will know", "will forget", "will hide", "will guess"],
    intermediate: "Quand il recevra les résultats demain, Paul _____ sa note exacte.", frenchChoices: ["connaîtra", "oubliera", "cachera", "devinera"],
    advanced: "Après la réunion, Nina connaîtra la décision du conseil. Paul rangera les chaises, Léa rédigera le compte rendu et Marc fermera la salle.",
    prompt: "Quel mot indique que Nina aura connaissance de la décision ?", advancedChoices: ["connaîtra", "rangera", "rédigera", "fermera"],
  },
  "connue:connaitre_know": {
    early: "La nouvelle est connue de tous depuis sa diffusion à la radio.", englishChoices: ["known", "hidden", "forgotten", "invented"],
    intermediate: "Après sa publication dans le journal, la décision est _____ de toute la ville.", frenchChoices: ["connue", "ignorée", "cachée", "oubliée"],
    advanced: "La règle est connue des élèves parce que la professeure l’a expliquée plusieurs fois. Le manuel est ouvert, la porte est fermée et une affiche est accrochée au mur.",
    prompt: "Quel mot indique que les élèves ont connaissance de la règle ?", advancedChoices: ["connue", "ouvert", "fermée", "accrochée"],
  },
  "conquis:conquerir_win": {
    early: "À force de patience, Paul a conquis la confiance de ses voisins.", englishChoices: ["won", "lost", "refused", "ignored"],
    intermediate: "Après de longs efforts, l’équipe a _____ le titre de championne.", frenchChoices: ["conquis", "perdu", "refusé", "ignoré"],
    advanced: "Les danseurs ont conquis le public par leur talent et ont reçu une longue ovation. Le directeur a fermé le rideau, les musiciens ont rangé leurs instruments et Nina a quitté la salle.",
    prompt: "Quel mot signifie que les danseurs ont gagné l’admiration du public ?", advancedChoices: ["conquis", "fermé", "rangé", "quitté"],
  },
  "conscience:conscience_moral_awareness": {
    early: "Sa conscience lui reproche d’avoir menti à son ami.", englishChoices: ["conscience", "memory", "habit", "appetite"],
    intermediate: "Il sait que ce mensonge est injuste et sa _____ l’empêche de dormir.", frenchChoices: ["conscience", "mémoire", "faim", "patience"],
    advanced: "La conscience de Léa la pousse à reconnaître sa faute après avoir menti. Paul lui pardonne, Nina écoute ses excuses et Marc termine son travail.",
    prompt: "Quel mot désigne la faculté de Léa de juger moralement son acte ?", advancedChoices: ["conscience", "excuses", "faute", "travail"],
  },
  "consciences:conscience_moral_awareness": {
    early: "Après cette injustice, les consciences des témoins les poussent à parler.", englishChoices: ["consciences", "memories", "habits", "appetites"],
    intermediate: "Ayant vu une injustice, les bénévoles écoutent leurs _____ et dénoncent les faits.", frenchChoices: ["consciences", "souvenirs", "habitudes", "envies"],
    advanced: "Les consciences des jurés les obligent à examiner honnêtement les preuves. Le juge lit le dossier, les témoins attendent dehors et l’avocat prend des notes.",
    prompt: "Quel mot désigne le sens moral des jurés ?", advancedChoices: ["consciences", "preuves", "dossier", "notes"],
  },
  "conseil:conseil_council": {
    early: "Le conseil municipal vote le budget de la ville après un long débat.", englishChoices: ["council", "individual", "library", "courtroom"],
    intermediate: "Les élus se réunissent pour débattre et voter : le _____ examine le budget.", frenchChoices: ["conseil", "gardien", "marché", "jardin"],
    advanced: "Le conseil de la commune réunit les élus pour voter la rénovation de l’école. La directrice attend la décision, le concierge ferme la salle et les parents discutent dehors.",
    prompt: "Quel mot désigne l’assemblée chargée de délibérer ?", advancedChoices: ["conseil", "directrice", "concierge", "parents"],
  },
  "conseils:conseil_council": {
    early: "Les conseils des deux communes votent chacun le budget de leur école.", englishChoices: ["councils", "advisers", "buildings", "lessons"],
    intermediate: "Chaque ville possède une assemblée d’élus : leurs _____ débattent séparément.", frenchChoices: ["conseils", "bâtiments", "ponts", "documents"],
    advanced: "Les conseils des deux villages se réunissent pour décider du nouveau pont. Les maires présentent les plans, les ingénieurs calculent le coût et les habitants attendent le résultat.",
    prompt: "Quel mot désigne les assemblées des villages qui prennent une décision ?", advancedChoices: ["conseils", "maires", "ingénieurs", "habitants"],
  },
  "constatation:constatation_finding": {
    early: "La constatation du médecin est claire : la blessure a guéri.", englishChoices: ["finding", "prediction", "request", "rumor"],
    intermediate: "Après examen des chiffres, cette _____ est incontestable : les ventes ont baissé.", frenchChoices: ["constatation", "prédiction", "demande", "rumeur"],
    advanced: "La constatation du technicien repose sur ses mesures : la machine surchauffe. Le directeur étudie le rapport, Léa ouvre une fenêtre et Paul appelle un réparateur.",
    prompt: "Quel mot désigne ici le fait établi après examen ?", advancedChoices: ["constatation", "mesures", "rapport", "réparateur"],
  },
  "continuel:continuel_constant": {
    early: "Le bruit continuel des travaux dure du matin jusqu’au soir.", englishChoices: ["constant", "brief", "occasional", "silent"],
    intermediate: "Le _____ bruit de la machine ne s’arrête jamais pendant le service.", frenchChoices: ["continuel", "bref", "rare", "passager"],
    advanced: "Le bruit continuel du moteur empêche Nina de dormir toute la nuit. La fenêtre est ouverte, la lampe est éteinte et la rue est vide.",
    prompt: "Quel mot indique que le bruit ne s’interrompt pas ?", advancedChoices: ["continuel", "ouverte", "éteinte", "vide"],
  },
  "contraire:contraire_opposite": {
    early: "Il voulait partir tôt ; c’est le contraire qui s’est produit : il est arrivé tard.", englishChoices: ["opposite", "cause", "beginning", "example"],
    intermediate: "Elle croyait que la porte était ouverte, mais c’était le _____ : elle était fermée.", frenchChoices: ["contraire", "début", "modèle", "motif"],
    advanced: "Le contraire de « plein » est « vide ». Nina remplit le panier, Paul ferme le placard et Léa vérifie la liste des courses.",
    prompt: "Quel nom désigne ici la relation d’opposition illustrée par « plein » et « vide » ?", advancedChoices: ["contraire", "vide", "panier", "liste"],
  },
  "contre:contre_against": {
    early: "Nina proteste contre la fermeture de la bibliothèque.", englishChoices: ["against", "beneath", "during", "beside"],
    intermediate: "Les habitants manifestent _____ la destruction de leur jardin public.", frenchChoices: ["contre", "sous", "pendant", "près de"],
    advanced: "Les parents votent contre la fermeture de l’école, car ils souhaitent la maintenir ouverte. Le maire consulte le conseil et la directrice prépare les documents.",
    prompt: "Quel mot marque l’opposition des parents à la fermeture ?", advancedChoices: ["contre", "car", "ouverte", "conseil"],
  },
  "convaincre:convaincre_persuade": {
    early: "Paul veut convaincre ses voisins de soutenir le projet en leur montrant les chiffres.", englishChoices: ["to convince", "to ignore", "to silence", "to forget"],
    intermediate: "Elle présente des preuves solides pour _____ le conseil d’accepter sa proposition.", frenchChoices: ["convaincre", "empêcher", "décourager", "dispenser"],
    advanced: "Nina cherche à convaincre le directeur d’ouvrir la bibliothèque plus tôt en lui montrant les demandes des lecteurs. Paul classe les lettres, Léa mesure la salle et Marc nettoie les tables.",
    prompt: "Quel verbe signifie amener le directeur à accepter l’idée ?", advancedChoices: ["convaincre", "classe", "mesure", "nettoie"],
  },
  "convaincu:convaincre_persuade": {
    early: "Les chiffres ont convaincu Luc de changer son plan.", englishChoices: ["convinced", "confused", "ignored", "frightened"],
    intermediate: "Les preuves présentées par Nina ont _____ le jury de son innocence.", frenchChoices: ["convaincu", "détourné", "dispensé", "empêché"],
    advanced: "Le témoignage a convaincu Paul que le pont est sûr. Nina examine les plans, Luc consulte le maire et Léa prépare la promenade.",
    prompt: "Quel mot indique que le témoignage a amené Paul à croire le pont sûr ?", advancedChoices: ["convaincu", "examine", "consulte", "prépare"],
  },
  "converse:converser_talk": {
    early: "Léa converse avec sa voisine pendant le trajet en train.", englishChoices: ["converses", "argues", "sleeps", "flees"],
    intermediate: "Paul _____ calmement avec Marie ; ils parlent de leur voyage.", frenchChoices: ["converse", "se dispute", "se tait", "s’enfuit"],
    advanced: "Nina converse avec son collègue près de la fenêtre : ils échangent leurs idées sur le projet. Paul lit un rapport, Luc ferme la porte et Léa dessine une carte.",
    prompt: "Quel mot indique que Nina s’entretient avec son collègue ?", advancedChoices: ["converse", "lit", "ferme", "dessine"],
  },
  "conviction:conviction_belief": {
    early: "Marie exprime sa conviction que cette décision est juste, même si d’autres doutent.", englishChoices: ["firm belief", "passing suspicion", "question", "fear"],
    intermediate: "Même après le débat, elle garde la ferme _____ que son projet réussira.", frenchChoices: ["conviction", "crainte", "question", "rumeur"],
    advanced: "La conviction de Léa reste ferme : elle croit que son ami dit la vérité malgré les critiques. Nina vérifie les dates, Paul interroge un témoin et Marc cherche la lettre.",
    prompt: "Quel mot désigne la croyance ferme de Léa ?", advancedChoices: ["conviction", "critiques", "témoin", "lettre"],
  },
  "convoqué:convoquer_summon": {
    early: "Le tribunal a convoqué Paul par écrit pour qu’il se présente lundi.", englishChoices: ["summoned", "released", "ignored", "praised"],
    intermediate: "La mairie l’a officiellement _____ pour une réunion prévue demain matin.", frenchChoices: ["convoqué", "dispensé", "libéré", "félicité"],
    advanced: "Le directeur a convoqué Marc à son bureau par une lettre officielle. Nina a rangé le dossier, Paul a ouvert la porte et Léa a pris des notes.",
    prompt: "Quel mot indique que Marc a été appelé officiellement à se présenter ?", advancedChoices: ["convoqué", "rangé", "ouvert", "pris"],
  },
  "coquins:coquin_scoundrel": {
    early: "Ces coquins ont volé la caisse puis menti au propriétaire sans remords.", englishChoices: ["scoundrels", "benefactors", "witnesses", "customers"],
    intermediate: "Ils mentent et trompent tout le monde pour gagner de l’argent : quels _____ !", frenchChoices: ["coquins", "bienfaiteurs", "témoins", "clients"],
    advanced: "Les coquins ont escroqué leurs voisins en leur vendant de faux billets. Paul apporte les preuves, la juge écoute les victimes et Nina avertit le quartier.",
    prompt: "Quel mot désigne les personnes malhonnêtes qui ont trompé leurs voisins ?", advancedChoices: ["coquins", "preuves", "victimes", "quartier"],
  },
  "corps:corps_group": {
    early: "Le corps des pompiers organise une formation commune pour ses membres.", englishChoices: ["corps", "building", "vehicle", "uniform"],
    intermediate: "Tous ces agents appartiennent au même _____ de fonctionnaires.", frenchChoices: ["corps", "bâtiment", "véhicule", "uniforme"],
    advanced: "Le corps des enseignants se réunit pour discuter de ses conditions de travail. Le proviseur préside, les élèves sont en classe et les parents attendent dehors.",
    prompt: "Quel mot désigne l’ensemble organisé des enseignants ?", advancedChoices: ["corps", "proviseur", "élèves", "parents"],
  },
};
