import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a telescope", "a turnip", "a cushion"];
const nounFrench: [string, string, string] = ["télescope", "navet", "coussin"];
const feminineNounFrench: [string, string, string] = ["lanterne", "citrouille", "valise"];
const adjectiveEnglish: [string, string, string] = ["spotted", "mint-scented", "hexagonal"];
const adjectiveFrench: [string, string, string] = ["tacheté", "parfumé à la menthe", "hexagonal"];

export const zolaVocabularyBatch36: ZolaVocabularySpec[] = [
  { normalized: "passion", lemmaKey: "passion", headword: "passion", partOfSpeech: "noun", senseKey: "passion_intense_commitment", gloss: "passion; intense commitment", definition: "sentiment ou attachement très intense pour une cause, une personne ou une activité", englishDistractors: nounEnglish, frenchDistractors: feminineNounFrench },
  { normalized: "passionnément", lemmaKey: "passionnement", headword: "passionnément", partOfSpeech: "adverb", senseKey: "passionnement_passionately", gloss: "passionately", definition: "avec une grande intensité affective et un engagement profond", englishDistractors: ["quietly", "mechanically", "upstairs"], frenchDistractors: ["silencieusement", "mécaniquement", "à l’étage"] },
  { normalized: "passions", lemmaKey: "passion", headword: "passion", partOfSpeech: "noun", senseKey: "passion_intense_commitment", gloss: "passion; intense commitment", quizMeaning: "passions; intense commitments", definition: "sentiment ou attachement très intense pour une cause, une personne ou une activité", englishDistractors: ["telescopes", "turnips", "cushions"], frenchDistractors: ["télescopes", "navets", "coussins"] },
  { normalized: "patrie", lemmaKey: "patrie", headword: "patrie", partOfSpeech: "noun", senseKey: "patrie_homeland", gloss: "homeland; fatherland", definition: "pays auquel une personne se sent liée par son origine ou son attachement", englishDistractors: nounEnglish, frenchDistractors: feminineNounFrench },
  { normalized: "patriotique", lemmaKey: "patriotique", headword: "patriotique", partOfSpeech: "adjective", senseKey: "patriotique_patriotic", gloss: "patriotic", definition: "qui manifeste l’attachement et le dévouement à son pays", englishDistractors: adjectiveEnglish, frenchDistractors: ["tachetée", "parfumée à la menthe", "hexagonale"] },
  { normalized: "patriotisme", lemmaKey: "patriotisme", headword: "patriotisme", partOfSpeech: "noun", senseKey: "patriotisme_patriotism", gloss: "patriotism", definition: "attachement et dévouement envers son pays", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "payait", lemmaKey: "payer", headword: "payer", partOfSpeech: "verb", senseKey: "payer_money", gloss: "to pay", quizMeaning: "was paying", definition: "verser une somme en échange d’un bien, d’un service ou d’un travail", englishDistractors: ["was knitting", "was paddling", "was sneezing"], frenchDistractors: ["tricotait", "pagayait", "éternuait"] },
  { normalized: "paye", lemmaKey: "payer", headword: "payer", partOfSpeech: "verb", senseKey: "payer_audacity", gloss: "to put on; make a display of", quizMeaning: "puts on a display of", definition: "dans « payer d’audace », afficher une qualité ou une attitude avec hardiesse", englishDistractors: ["knits", "paddles", "sneezes"], frenchDistractors: ["tricote", "pagaie", "éternue"] },
  { normalized: "payé", lemmaKey: "payer", headword: "payer", partOfSpeech: "verb", senseKey: "payer_money", gloss: "to pay", quizMeaning: "paid", definition: "verser une somme en échange d’un bien, d’un service ou d’un travail", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricoté", "pagayé", "éternué"] },
  { normalized: "pays", lemmaKey: "pays", headword: "pays", partOfSpeech: "noun", senseKey: "pays_country", gloss: "country; land", definition: "territoire formant une unité politique ou régionale", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "pendant", lemmaKey: "pendant_preposition", headword: "pendant", partOfSpeech: "preposition", senseKey: "pendant_during", gloss: "during; while", definition: "indique la durée au cours de laquelle un fait se produit", englishDistractors: ["despite", "without", "before"], frenchDistractors: ["malgré", "sans", "avant"] },
  { normalized: "pensant", lemmaKey: "penser", headword: "penser", partOfSpeech: "verb", senseKey: "penser_think", gloss: "to think; consider", quizMeaning: "thinking; considering", definition: "former une idée ou porter son attention sur quelque chose", englishDistractors: ["knitting", "paddling", "sneezing"], frenchDistractors: ["tricotant", "pagayant", "éternuant"] },
  { normalized: "perdre", lemmaKey: "perdre", headword: "perdre", partOfSpeech: "verb", senseKey: "perdre_ruin", gloss: "to lose; ruin", definition: "priver quelqu’un de sa situation, de sa réputation ou de sa réussite", englishDistractors: ["to knit", "to paddle", "to sneeze"], frenchDistractors: ["tricoter", "pagayer", "éternuer"] },
  { normalized: "perdu", lemmaKey: "perdre", headword: "perdre", partOfSpeech: "verb", senseKey: "perdre_doomed", gloss: "to lose; be doomed", quizMeaning: "lost; doomed", definition: "être privé d’un avenir favorable ou exposé à une issue désastreuse", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricoté", "pagayé", "éternué"] },
  { normalized: "perdus", lemmaKey: "perdre", headword: "perdre", partOfSpeech: "verb", senseKey: "perdre_corrupted", gloss: "to lose; be corrupted", quizMeaning: "lost in; steeped in", definition: "être profondément engagé dans une situation moralement mauvaise", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricotés", "pagayés", "éternués"] },
  { normalized: "péril", lemmaKey: "peril", headword: "péril", partOfSpeech: "noun", senseKey: "peril_danger", gloss: "danger; peril", definition: "situation où une personne ou une chose est menacée d’un dommage grave", englishDistractors: nounEnglish, frenchDistractors: ["danger", "route", "silence"] },
  { normalized: "permettait", lemmaKey: "permettre", headword: "permettre", partOfSpeech: "verb", senseKey: "permettre_allow", gloss: "to allow; permit", quizMeaning: "was allowing; permitted", definition: "autoriser une action ou ne pas l’empêcher", englishDistractors: ["was knitting", "was paddling", "was sneezing"], frenchDistractors: ["tricotait", "pagayait", "éternuait"] },
  { normalized: "permettez", lemmaKey: "permettre", headword: "permettre", partOfSpeech: "verb", senseKey: "permettre_allow", gloss: "to allow; permit", quizMeaning: "allow; permit", definition: "autoriser une action ou ne pas l’empêcher", englishDistractors: ["knit", "paddle", "sneeze"], frenchDistractors: ["tricotez", "pagayez", "éternuez"] },
  { normalized: "permettre", lemmaKey: "permettre", headword: "permettre", partOfSpeech: "verb", senseKey: "permettre_allow", gloss: "to allow; permit", definition: "autoriser une action ou ne pas l’empêcher", englishDistractors: ["to knit", "to paddle", "to sneeze"], frenchDistractors: ["tricoter", "pagayer", "éternuer"] },
  { normalized: "pervertie", lemmaKey: "pervertir", headword: "pervertir", partOfSpeech: "verb", senseKey: "pervertir_corrupt", gloss: "to corrupt; distort", quizMeaning: "corrupted; distorted", definition: "détourner de son sens juste ou dégrader moralement", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricotée", "pagayée", "éternuée"] },
  { normalized: "pervertissant", lemmaKey: "pervertir", headword: "pervertir", partOfSpeech: "verb", senseKey: "pervertir_corrupt", gloss: "to corrupt; distort", quizMeaning: "corrupting; distorting", definition: "détourner de son sens juste ou dégrader moralement", englishDistractors: ["knitting", "paddling", "sneezing"], frenchDistractors: ["tricotant", "pagayant", "éternuant"] },
  { normalized: "pèsera", lemmaKey: "peser", headword: "peser", partOfSpeech: "verb", senseKey: "peser_burden", gloss: "to weigh on; burden", quizMeaning: "will weigh on; burden", definition: "exercer une pression morale ou produire une conséquence durable", englishDistractors: ["will knit", "will paddle", "will sneeze"], frenchDistractors: ["tricotera", "pagayera", "éternuera"] },
  { normalized: "petites", lemmaKey: "petit", headword: "petit", partOfSpeech: "adjective", senseKey: "petit_small", gloss: "small; little", definition: "de faible dimension, importance ou âge", englishDistractors: adjectiveEnglish, frenchDistractors: ["tachetées", "parfumées à la menthe", "hexagonales"] },
  { normalized: "petits", lemmaKey: "petit", headword: "petit", partOfSpeech: "adjective", senseKey: "petit_lowly", gloss: "small; lowly", quizMeaning: "the little; the lowly", definition: "de condition modeste ou dépourvu de pouvoir social", englishDistractors: adjectiveEnglish, frenchDistractors: ["tachetés", "parfumés à la menthe", "hexagonaux"] },
  { normalized: "peuple", lemmaKey: "peuple", headword: "peuple", partOfSpeech: "noun", senseKey: "peuple_population", gloss: "people; population", definition: "ensemble des habitants d’un pays ou d’une communauté", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "peut", lemmaKey: "pouvoir", headword: "pouvoir", partOfSpeech: "verb", senseKey: "pouvoir_ability", gloss: "can; be able to", quizMeaning: "can; is able to", definition: "avoir la capacité ou la possibilité de faire quelque chose", englishDistractors: ["must", "wants to", "seems to"], frenchDistractors: ["doit", "veut", "semble"] },
  { normalized: "peut-être", lemmaKey: "peut_etre", headword: "peut-être", partOfSpeech: "adverb", senseKey: "peut_etre_maybe", gloss: "perhaps; maybe", definition: "marque l’incertitude ou une simple possibilité", englishDistractors: ["certainly", "never", "already"], frenchDistractors: ["certainement", "jamais", "déjà"] },
  { normalized: "peuvent", lemmaKey: "pouvoir", headword: "pouvoir", partOfSpeech: "verb", senseKey: "pouvoir_ability", gloss: "can; be able to", quizMeaning: "can; are able to", definition: "avoir la capacité ou la possibilité de faire quelque chose", englishDistractors: ["know", "claim", "refuse"], frenchDistractors: ["savent", "prétendent", "refusent"] },
];
