import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a hammock","a pumpkin","a telescope"];
const nF:[string,string,string]=["hamac","citrouille","télescope"];
const aE:[string,string,string]=["striped","perfumed","triangular"];
const aF:[string,string,string]=["rayé","parfumé","triangulaire"];
const vE:[string,string,string]=["to weave","to dive","to snore"];
const vF:[string,string,string]=["tisser","plonger","ronfler"];

export const zolaVocabularyBatch17: ZolaVocabularySpec[] = [
 {normalized:"diffamation",lemmaKey:"diffamation",headword:"diffamation",partOfSpeech:"noun",senseKey:"diffamation_defamation",gloss:"defamation; libel",definition:"accusation qui porte atteinte à la réputation d’une personne",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"dignité",lemmaKey:"dignite",headword:"dignité",partOfSpeech:"noun",senseKey:"dignite_worth",gloss:"dignity",definition:"respect dû à une personne et sentiment de sa propre valeur",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"dilapidations",lemmaKey:"dilapidation",headword:"dilapidation",partOfSpeech:"noun",senseKey:"dilapidation_misappropriation",gloss:"misappropriation; squandering",quizMeaning:"misappropriations; waste",definition:"dépense ou détournement abusif de biens confiés",englishDistractors:["hammocks","pumpkins","telescopes"],frenchDistractors:["hamacs","citrouilles","télescopes"]},
 {normalized:"dirai",lemmaKey:"dire",existingLemmaId:"lem_dire",existingSenseId:"sns_dire_primary",headword:"dire",partOfSpeech:"verb",senseKey:"dire_say",gloss:"to say",quizMeaning:"will say",definition:"exprimer quelque chose par la parole",englishDistractors:["will weave","will dive","will snore"],frenchDistractors:["tisserai","plongerai","ronflerai"]},
 {normalized:"dire",lemmaKey:"dire",existingLemmaId:"lem_dire",existingSenseId:"sns_dire_primary",headword:"dire",partOfSpeech:"verb",senseKey:"dire_say",gloss:"to say",definition:"exprimer quelque chose par la parole",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"directeur",lemmaKey:"directeur",headword:"directeur",partOfSpeech:"noun",senseKey:"directeur_head",gloss:"director; head",definition:"personne qui dirige un service ou une organisation",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"disait",lemmaKey:"dire",existingLemmaId:"lem_dire",existingSenseId:"sns_dire_primary",headword:"dire",partOfSpeech:"verb",senseKey:"dire_say",gloss:"to say",quizMeaning:"was saying; said",definition:"exprimer quelque chose par la parole",englishDistractors:["was weaving","was diving","was snoring"],frenchDistractors:["tissait","plongeait","ronflait"]},
 {normalized:"discipline",lemmaKey:"discipline",headword:"discipline",partOfSpeech:"noun",senseKey:"discipline_obedience",gloss:"discipline",definition:"règle d’obéissance imposée aux membres d’un corps",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"discute",lemmaKey:"discuter",headword:"discuter",partOfSpeech:"verb",senseKey:"discuter_question",gloss:"to discuss; question",quizMeaning:"is discussed; is questioned",definition:"examiner une affirmation pour en débattre ou la contester",englishDistractors:["weaves","dives","snores"],frenchDistractors:["tisse","plonge","ronfle"]},
 {normalized:"disgrâce",lemmaKey:"disgrace",headword:"disgrâce",partOfSpeech:"noun",senseKey:"disgrace_disfavor",gloss:"disfavor; disgrace",definition:"perte de la faveur ou de l’estime d’une autorité",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"disparaissaient",lemmaKey:"disparaitre",headword:"disparaître",partOfSpeech:"verb",senseKey:"disparaitre_vanish",gloss:"to disappear",quizMeaning:"were disappearing",definition:"cesser d’être visible ou de se trouver à sa place",englishDistractors:["were weaving","were diving","were snoring"],frenchDistractors:["tissaient","plongeaient","ronflaient"]},
 {normalized:"disparaît",lemmaKey:"disparaitre",headword:"disparaître",partOfSpeech:"verb",senseKey:"disparaitre_vanish",gloss:"to disappear",quizMeaning:"disappears",definition:"cesser d’être visible ou de se trouver à sa place",englishDistractors:["weaves","dives","snores"],frenchDistractors:["tisse","plonge","ronfle"]},
 {normalized:"doigt",lemmaKey:"doigt",headword:"doigt",partOfSpeech:"noun",senseKey:"doigt_finger",gloss:"finger",definition:"partie articulée située à l’extrémité de la main",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"doit",lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"must; is expected to",definition:"exprimer une obligation ou un événement attendu",englishDistractors:["weaves","dives","snores"],frenchDistractors:["tisse","plonge","ronfle"]},
 {normalized:"doivent",lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"must; have to",definition:"exprimer une obligation ou un événement attendu",englishDistractors:["weave","dive","snore"],frenchDistractors:["tissent","plongent","ronflent"]},
 {normalized:"donc",lemmaKey:"donc",headword:"donc",partOfSpeech:"adverb",senseKey:"donc_therefore",gloss:"therefore; then",definition:"introduit une conséquence ou reprend fermement le raisonnement",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"donne",lemmaKey:"donner",headword:"donner",partOfSpeech:"verb",senseKey:"donner_give",gloss:"to give",quizMeaning:"gives",definition:"remettre, accorder ou fournir quelque chose",englishDistractors:["weaves","dives","snores"],frenchDistractors:["tisse","plonge","ronfle"]},
 {normalized:"donner",lemmaKey:"donner",headword:"donner",partOfSpeech:"verb",senseKey:"donner_give",gloss:"to give",definition:"remettre, accorder ou fournir quelque chose",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"donnera",lemmaKey:"donner",headword:"donner",partOfSpeech:"verb",senseKey:"donner_give",gloss:"to give",quizMeaning:"will give",definition:"remettre, accorder ou fournir quelque chose",englishDistractors:["will weave","will dive","will snore"],frenchDistractors:["tissera","plongera","ronflera"]},
 {normalized:"donneront",lemmaKey:"donner",headword:"donner",partOfSpeech:"verb",senseKey:"donner_give",gloss:"to give",quizMeaning:"will give",definition:"remettre, accorder ou fournir quelque chose",englishDistractors:["will weave","will dive","will snore"],frenchDistractors:["tisseront","plongeront","ronfleront"]},
 {normalized:"donnez",lemmaKey:"donner",headword:"donner",partOfSpeech:"verb",senseKey:"donner_give",gloss:"to give",quizMeaning:"give",definition:"remettre, accorder ou fournir quelque chose",englishDistractors:["weave","dive","snore"],frenchDistractors:["tissez","plongez","ronflez"]},
 {normalized:"dont",lemmaKey:"dont",headword:"dont",partOfSpeech:"pronoun",senseKey:"dont_whose_of_which",gloss:"whose; of which",definition:"pronom relatif qui remplace un complément introduit par de",englishDistractors:["who","where","when"],frenchDistractors:["qui","où","quand"]},
 {normalized:"dorment",lemmaKey:"dormir",headword:"dormir",partOfSpeech:"verb",senseKey:"dormir_sleep",gloss:"to sleep",quizMeaning:"sleep",definition:"être dans l’état naturel de repos nocturne",englishDistractors:["weave","dive","snore loudly"],frenchDistractors:["tissent","plongent","sifflent"]},
 {normalized:"dossier",lemmaKey:"dossier",headword:"dossier",partOfSpeech:"noun",senseKey:"dossier_case_file",gloss:"file; case file",definition:"ensemble de documents réunis au sujet d’une affaire",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"double",lemmaKey:"double",headword:"double",partOfSpeech:"adjective",senseKey:"double_twofold",gloss:"double; twofold",definition:"qui comporte deux éléments ou deux aspects",englishDistractors:aE,frenchDistractors:aF},
];
