import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEn: [string,string,string] = ["a lantern", "a cushion", "an orchard"];
const nounFr: [string,string,string] = ["lanterne", "coussin", "verger"];
const verbEn: [string,string,string] = ["to polish", "to paddle", "to yawn"];
const verbFr: [string,string,string] = ["polir", "pagayer", "bâiller"];
const advEn: [string,string,string] = ["softly", "outdoors", "sideways"];
const advFr: [string,string,string] = ["doucement", "dehors", "de côté"];

export const zolaVocabularyBatch03: ZolaVocabularySpec[] = [
  { normalized:"agissait", candidateIds:["tok_7855c4254b3877ba392191f0"], lemmaKey:"agir", headword:"agir", partOfSpeech:"verb", senseKey:"s_agir_concern", gloss:"to be a matter of; concern", quizMeaning:"was a matter of", definition:"être question de quelque chose", englishDistractors:["was polishing","was paddling","was yawning"], frenchDistractors:["polissait","pagayait","bâillait"] },
  { normalized:"agissait", candidateIds:["tok_fb4c02b87b6d1875bfeedcfe"], lemmaKey:"agir", headword:"agir", partOfSpeech:"verb", senseKey:"agir_act", gloss:"to act", quizMeaning:"was acting", definition:"accomplir une action", englishDistractors:["was polishing","was paddling","was yawning"], frenchDistractors:["polissait","pagayait","bâillait"] },
  { normalized:"agit", lemmaKey:"agir", headword:"agir", partOfSpeech:"verb", senseKey:"s_agir_concern", gloss:"to be a matter of; concern", quizMeaning:"is a matter of", definition:"être question de quelque chose", englishDistractors:["polishes","paddles","yawns"], frenchDistractors:["polit","pagaie","bâille"] },
  { normalized:"agité", lemmaKey:"agiter", headword:"agiter", partOfSpeech:"verb", senseKey:"agiter_stir", gloss:"stirred up; shaken", definition:"mis en mouvement ou troublé", englishDistractors:["polished","paddled","yawned"], frenchDistractors:["poli","pagayé","bâillé"] },
  { normalized:"agréer", lemmaKey:"agreer", headword:"agréer", partOfSpeech:"verb", senseKey:"agreer_accept", gloss:"to accept", definition:"recevoir favorablement", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"ah", lemmaKey:"ah", headword:"ah", partOfSpeech:"interjection", senseKey:"ah_emotion", gloss:"ah!", definition:"interjection exprimant une émotion vive", englishDistractors:["splash!","cock-a-doodle-doo!","tick-tock!"], frenchDistractors:["plouf","cocorico","tic-tac"] },
  { normalized:"ai", lemmaKey:"avoir", headword:"avoir", partOfSpeech:"verb", senseKey:"avoir_possess_auxiliary", gloss:"to have; auxiliary avoir", quizMeaning:"have", definition:"posséder ou servir d’auxiliaire", englishDistractors:["polish","paddle","yawn"], frenchDistractors:["polis","pagaie","bâille"] },
  { normalized:"ailleurs", lemmaKey:"ailleurs", headword:"ailleurs", partOfSpeech:"adverb", senseKey:"ailleurs_elsewhere", gloss:"elsewhere; besides", definition:"dans un autre lieu ou dans la locution d’ailleurs", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"aiment", lemmaKey:"aimer", headword:"aimer", partOfSpeech:"verb", senseKey:"aimer_love", gloss:"to love", quizMeaning:"they love", definition:"éprouver de l’affection pour", englishDistractors:["they polish","they paddle","they yawn"], frenchDistractors:["ils polissent","ils pagaient","ils bâillent"] },
  { normalized:"aimions", lemmaKey:"aimer", headword:"aimer", partOfSpeech:"verb", senseKey:"aimer_love", gloss:"to love", quizMeaning:"we loved", definition:"éprouver de l’affection pour", englishDistractors:["we polished","we paddled","we yawned"], frenchDistractors:["nous polissions","nous pagayions","nous bâillions"] },
  { normalized:"ait", lemmaKey:"avoir", headword:"avoir", partOfSpeech:"verb", senseKey:"avoir_possess_auxiliary", gloss:"to have; auxiliary avoir", quizMeaning:"has; may have", definition:"posséder ou servir d’auxiliaire", englishDistractors:["polishes","paddles","yawns"], frenchDistractors:["polisse","pagaie","bâille"] },
  { normalized:"allaient", lemmaKey:"aller", headword:"aller", partOfSpeech:"verb", senseKey:"aller_imminent", gloss:"to be going to", quizMeaning:"were going to", definition:"marquer une action imminente devant un infinitif", englishDistractors:["were polishing","were paddling","were yawning"], frenchDistractors:["polissaient","pagayaient","bâillaient"] },
  { normalized:"allais", lemmaKey:"aller", headword:"aller", partOfSpeech:"verb", senseKey:"aller_imminent", gloss:"to be going to", quizMeaning:"was going to", definition:"marquer une action imminente devant un infinitif", englishDistractors:["was polishing","was paddling","was yawning"], frenchDistractors:["polissais","pagayais","bâillais"] },
  { normalized:"allait", lemmaKey:"aller", headword:"aller", partOfSpeech:"verb", senseKey:"aller_imminent", gloss:"to be going to", quizMeaning:"was going to", definition:"marquer une action imminente devant un infinitif", englishDistractors:["was polishing","was paddling","was yawning"], frenchDistractors:["polissait","pagayait","bâillait"] },
  { normalized:"allemand", lemmaKey:"allemand", headword:"allemand", partOfSpeech:"adjective", senseKey:"allemand_german", gloss:"German", definition:"relatif à l’Allemagne", englishDistractors:["striped","wooden","mint-flavored"], frenchDistractors:["rayé","boisé","mentholé"] },
  { normalized:"alliance", lemmaKey:"alliance", headword:"alliance", partOfSpeech:"noun", senseKey:"alliance_union", gloss:"alliance", definition:"union conclue entre des États ou des groupes", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"alors", lemmaKey:"alors", headword:"alors", partOfSpeech:"adverb", senseKey:"alors_then", gloss:"then; at that time", definition:"à ce moment-là", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"amasse", lemmaKey:"amasser", headword:"amasser", partOfSpeech:"verb", senseKey:"amasser_accumulate", gloss:"accumulates; gathers", definition:"réunit progressivement en quantité", englishDistractors:["polishes","paddles","yawns"], frenchDistractors:["polit","pagaie","bâille"] },
  { normalized:"âme", lemmaKey:"ame", headword:"âme", partOfSpeech:"noun", senseKey:"ame_inner_self", gloss:"soul; inner self", definition:"principe intérieur de la vie morale et affective", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"amener", lemmaKey:"amener", headword:"amener", partOfSpeech:"verb", senseKey:"amener_bring", gloss:"to bring; lead", definition:"conduire quelqu’un à un lieu ou à une situation", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"ameutent", lemmaKey:"ameuter", headword:"ameuter", partOfSpeech:"verb", senseKey:"ameuter_stir_up", gloss:"stir up; rally", definition:"soulèvent une foule contre quelqu’un", englishDistractors:["polish","paddle","yawn"], frenchDistractors:["polissent","pagaient","bâillent"] },
  { normalized:"amicale", lemmaKey:"amical", headword:"amical", partOfSpeech:"adjective", senseKey:"amical_friendly", gloss:"friendly", definition:"inspiré par l’amitié", englishDistractors:["striped","wooden","mint-flavored"], frenchDistractors:["rayée","boisée","mentholée"] },
  { normalized:"amoncelait", lemmaKey:"amonceler", headword:"amonceler", partOfSpeech:"verb", senseKey:"amonceler_gather", gloss:"was gathering; piling up", definition:"s’accumulait en masse", englishDistractors:["was polishing","was paddling","was yawning"], frenchDistractors:["polissait","pagayait","bâillait"] },
  { normalized:"an", lemmaKey:"an", headword:"an", partOfSpeech:"noun", senseKey:"an_year", gloss:"year", definition:"durée de douze mois", englishDistractors:nounEn, frenchDistractors:["coussin","verger","fauteuil"] },
  { normalized:"angoisse", lemmaKey:"angoisse", headword:"angoisse", partOfSpeech:"noun", senseKey:"angoisse_anguish", gloss:"anguish; anxiety", definition:"inquiétude profonde et douloureuse", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"anonyme", lemmaKey:"anonyme", headword:"anonyme", partOfSpeech:"adjective", senseKey:"anonyme_unsigned", gloss:"anonymous", definition:"dont l’auteur n’est pas identifié", englishDistractors:["striped","wooden","mint-flavored"], frenchDistractors:["rayée","boisée","mentholée"] },
];
