import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a lantern", "a pumpkin", "a suitcase"];
const nounFrench: [string, string, string] = ["lanterne", "citrouille", "valise"];
const adjectiveEnglish: [string, string, string] = ["striped", "mint-scented", "cylindrical"];
const adjectiveFrench: [string, string, string] = ["rayé", "parfumé à la menthe", "cylindrique"];

export const zolaVocabularyBatch32: ZolaVocabularySpec[] = [
  { normalized: "même", candidateIds: ["tok_3f651ad3767013e3a86957e9", "tok_e5e80dd71e6e2b22cec0df7d", "tok_7dfd719c590e250e2ffd599f", "tok_c482bb2f1348b4cf0fc1a190", "tok_a6bb53062bc5be0bccb377ca", "tok_357127b0c502c2ee7eae0437", "tok_cd8439516f98078704602ff0"], lemmaKey: "meme_adverb", headword: "même", partOfSpeech: "adverb", senseKey: "meme_even", gloss: "even", definition: "souligne qu’un fait s’ajoute de manière remarquable ou inattendue", englishDistractors: ["slowly", "outside", "tomorrow"], frenchDistractors: ["lentement", "dehors", "demain"] },
  { normalized: "même", candidateIds: ["tok_9a35f25c5632a2da344d87e6", "tok_34ea2dc1088a9d8fb28b9ee0", "tok_8f7b07e21a2ad0dc9ec9123f"], lemmaKey: "meme_adjective", headword: "même", partOfSpeech: "adjective", senseKey: "meme_itself", gloss: "itself; very", definition: "renforce directement l’identité de la personne ou de la chose désignée", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "même", candidateIds: ["tok_38d4bc2780af1d2b3e1729bf"], lemmaKey: "meme_adjective", headword: "même", partOfSpeech: "adjective", senseKey: "meme_same", gloss: "same; identical", definition: "qui est identique à ce qui a déjà été mentionné", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "même", candidateIds: ["tok_963ceaa9a59dbd97f45cda5b"], lemmaKey: "de_meme", headword: "de même", partOfSpeech: "adverb", senseKey: "de_meme_similarly", gloss: "similarly; likewise", definition: "de façon semblable ou selon le même principe", englishDistractors: ["from afar", "at night", "in profile"], frenchDistractors: ["loin", "nuit", "profil"] },
  { normalized: "mêmes", lemmaKey: "meme_adjective", headword: "même", partOfSpeech: "adjective", senseKey: "meme_itself", gloss: "itself; very", quizMeaning: "themselves; very", definition: "renforce directement l’identité de la personne ou de la chose désignée", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayés", "parfumés à la menthe", "cylindriques"] },
  { normalized: "menace", lemmaKey: "menace", headword: "menace", partOfSpeech: "noun", senseKey: "menace_threat", gloss: "threat; danger", definition: "signe ou déclaration annonçant un danger possible", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "menacée", lemmaKey: "menacer", headword: "menacer", partOfSpeech: "verb", senseKey: "menacer_threaten", gloss: "to threaten; endanger", quizMeaning: "threatened; endangered", definition: "mettre en danger ou faire craindre un mal prochain", englishDistractors: ["knitted", "dived", "snored"], frenchDistractors: ["tricotée", "plongée", "ronflée"] },
  { normalized: "mené", lemmaKey: "mener", headword: "mener", partOfSpeech: "verb", senseKey: "mener_lead", gloss: "to lead; conduct", quizMeaning: "led; conducted", definition: "diriger une personne, une action ou une entreprise vers un résultat", englishDistractors: ["knitted", "dived", "snored"], frenchDistractors: ["tricoté", "plongé", "ronflé"] },
  { normalized: "mène", lemmaKey: "mener", headword: "mener", partOfSpeech: "verb", senseKey: "mener_lead", gloss: "to lead; conduct", quizMeaning: "leads; directs", definition: "diriger une personne, une action ou une entreprise vers un résultat", englishDistractors: ["knits", "dives", "snores"], frenchDistractors: ["tricote", "plonge", "ronfle"] },
  { normalized: "menées", lemmaKey: "menee_noun", headword: "menée", partOfSpeech: "noun", senseKey: "menee_scheme", gloss: "scheme; maneuver", quizMeaning: "schemes; maneuvers", definition: "action secrète et calculée destinée à parvenir à un but", englishDistractors: ["lanterns", "pumpkins", "suitcases"], frenchDistractors: ["lanternes", "citrouilles", "valises"] },
  { normalized: "mensonge", lemmaKey: "mensonge", headword: "mensonge", partOfSpeech: "noun", senseKey: "mensonge_lie", gloss: "lie; falsehood", definition: "affirmation contraire à la vérité faite pour tromper", englishDistractors: nounEnglish, frenchDistractors: ["moulin", "navet", "coussin"] },
  { normalized: "mensongers", lemmaKey: "mensonger", headword: "mensonger", partOfSpeech: "adjective", senseKey: "mensonger_false", gloss: "false; deceitful", definition: "qui contient un mensonge ou cherche à tromper", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayés", "parfumés à la menthe", "cylindriques"] },
  { normalized: "mentent", lemmaKey: "mentir", headword: "mentir", partOfSpeech: "verb", senseKey: "mentir_lie", gloss: "to lie; tell falsehoods", quizMeaning: "lie; tell falsehoods", definition: "affirmer volontairement ce que l’on sait être faux", englishDistractors: ["knit", "dive", "snore"], frenchDistractors: ["tricotent", "plongent", "ronflent"] },
  { normalized: "menteur", lemmaKey: "menteur", headword: "menteur", partOfSpeech: "adjective", senseKey: "menteur_deceptive", gloss: "lying; deceitful", definition: "qui trompe en affirmant ce qui est faux", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "mépris", lemmaKey: "mepris", headword: "mépris", partOfSpeech: "noun", senseKey: "mepris_contempt", gloss: "contempt; scorn", definition: "sentiment par lequel on juge quelqu’un indigne d’estime", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "mes", lemmaKey: "mon", headword: "mon", partOfSpeech: "determiner", senseKey: "mon_my", gloss: "my", definition: "déterminant possessif indiquant que plusieurs éléments appartiennent à la personne qui parle", englishDistractors: ["seven", "twelve", "a thousand"], frenchDistractors: ["sept", "douze", "mille"] },
  { normalized: "mesures", lemmaKey: "mesure", headword: "mesure", partOfSpeech: "noun", senseKey: "mesure_action", gloss: "measure; step", quizMeaning: "measures; steps", definition: "disposition prise pour atteindre un but ou prévenir un danger", englishDistractors: ["lanterns", "pumpkins", "suitcases"], frenchDistractors: ["lanternes", "citrouilles", "valises"] },
  { normalized: "met", lemmaKey: "mettre", headword: "mettre", partOfSpeech: "verb", senseKey: "mettre_place", gloss: "to put; place", quizMeaning: "puts; places", definition: "placer quelqu’un ou quelque chose dans une position ou un état", englishDistractors: ["knits", "dives", "snores"], frenchDistractors: ["tricote", "plonge", "ronfle"] },
  { normalized: "mets", lemmaKey: "mettre", headword: "mettre", partOfSpeech: "verb", senseKey: "mettre_place", gloss: "to put; place", quizMeaning: "put; place", definition: "placer quelqu’un ou quelque chose dans une position ou un état", englishDistractors: ["knit", "dive", "snore"], frenchDistractors: ["tricote", "plonge", "ronfle"] },
  { normalized: "mettaient", lemmaKey: "mettre", headword: "mettre", partOfSpeech: "verb", senseKey: "mettre_doubt", gloss: "to doubt; call into question", quizMeaning: "were doubting; called into question", definition: "dans « mettre en doute », refuser de tenir quelque chose pour certain", englishDistractors: ["were knitting", "were diving", "were snoring"], frenchDistractors: ["tricotaient", "plongeaient", "ronflaient"] },
  { normalized: "mettant", lemmaKey: "mettre", headword: "mettre", partOfSpeech: "verb", senseKey: "mettre_place", gloss: "to put; place", quizMeaning: "putting; placing", definition: "placer quelqu’un ou quelque chose dans une position ou un état", englishDistractors: ["knitting", "diving", "snoring"], frenchDistractors: ["tricotant", "plongeant", "ronflant"] },
  { normalized: "mettre", lemmaKey: "mettre", headword: "mettre", partOfSpeech: "verb", senseKey: "mettre_place", gloss: "to put; place", definition: "placer quelqu’un ou quelque chose dans une position ou un état", englishDistractors: ["to knit", "to dive", "to snore"], frenchDistractors: ["tricoter", "plonger", "ronfler"] },
  { normalized: "milieu", candidateIds: ["tok_cc11cda467b02dbc891f2279"], lemmaKey: "milieu", headword: "milieu", partOfSpeech: "noun", senseKey: "milieu_middle", gloss: "middle; midst", definition: "partie située entre les extrémités ou au centre d’une situation", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "milieu", candidateIds: ["tok_ef43ce9a1764b22704b9f09a", "tok_fbf647d57e7469e99e3cb30d"], lemmaKey: "milieu", headword: "milieu", partOfSpeech: "noun", senseKey: "milieu_environment", gloss: "environment; social circle", definition: "ensemble social, culturel ou professionnel dans lequel une personne évolue", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "militaire", lemmaKey: "militaire_adjective", headword: "militaire", partOfSpeech: "adjective", senseKey: "militaire_armed_forces", gloss: "military", definition: "qui appartient à l’armée ou concerne les forces armées", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "militairement", lemmaKey: "militairement", headword: "militairement", partOfSpeech: "adverb", senseKey: "militairement_by_military_power", gloss: "militarily; by military authority", definition: "selon les méthodes, la discipline ou l’autorité de l’armée", englishDistractors: ["slowly", "outside", "tomorrow"], frenchDistractors: ["lentement", "dehors", "demain"] },
  { normalized: "militaires", lemmaKey: "militaire_adjective", headword: "militaire", partOfSpeech: "adjective", senseKey: "militaire_armed_forces", gloss: "military", definition: "qui appartient à l’armée ou concerne les forces armées", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayés", "parfumés à la menthe", "cylindriques"] },
  { normalized: "ministère", lemmaKey: "ministere", headword: "ministère", partOfSpeech: "noun", senseKey: "ministere_department", gloss: "ministry; government department", definition: "administration publique placée sous l’autorité d’un ministre", englishDistractors: nounEnglish, frenchDistractors: ["moulin", "navet", "coussin"] },
  { normalized: "ministre", lemmaKey: "ministre", headword: "ministre", partOfSpeech: "noun", senseKey: "ministre_government_official", gloss: "minister; cabinet official", definition: "membre du gouvernement chargé de diriger un département public", englishDistractors: nounEnglish, frenchDistractors: ["moulin", "navet", "coussin"] },
  { normalized: "minute", lemmaKey: "minute", headword: "minute", partOfSpeech: "noun", senseKey: "minute_moment", gloss: "minute; brief moment", definition: "courte durée ou moment précis", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "mission", lemmaKey: "mission", headword: "mission", partOfSpeech: "noun", senseKey: "mission_assignment", gloss: "mission; assignment", definition: "charge confiée à une personne en vue d’un objectif précis", englishDistractors: nounEnglish, frenchDistractors: ["vacances", "uniforme", "silence"] },
  { normalized: "moderne", lemmaKey: "moderne", headword: "moderne", partOfSpeech: "adjective", senseKey: "moderne_present_age", gloss: "modern", definition: "qui appartient à l’époque actuelle ou récente", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "mœurs", lemmaKey: "moeurs", headword: "mœurs", partOfSpeech: "noun", senseKey: "moeurs_customs", gloss: "customs; morals", definition: "habitudes, pratiques et règles morales d’un groupe ou d’une époque", englishDistractors: ["lanterns", "pumpkins", "suitcases"], frenchDistractors: ["lanternes", "citrouilles", "valises"] },
];
