import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a balcony","a cherry","a compass"];
const nF:[string,string,string]=["balcon","cerise","boussole"];
const aE:[string,string,string]=["wooden","minty","hexagonal"];
const aF:[string,string,string]=["boisé","mentholé","hexagonal"];
const vE:[string,string,string]=["to crochet","to skate","to hum"];
const vF:[string,string,string]=["crocheter","patiner","fredonner"];

export const zolaVocabularyBatch16: ZolaVocabularySpec[] = [
 {normalized:"dès",lemmaKey:"des",headword:"dès",partOfSpeech:"preposition",senseKey:"des_from",gloss:"from; as soon as",definition:"marque un point de départ immédiat dans le temps",englishDistractors:["beneath","beside","despite"],frenchDistractors:["sous","auprès de","malgré"]},
 {normalized:"désastre",lemmaKey:"desastre",headword:"désastre",partOfSpeech:"noun",senseKey:"desastre_disaster",gloss:"disaster",definition:"événement qui cause de très graves dommages",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"désastres",lemmaKey:"desastre",headword:"désastre",partOfSpeech:"noun",senseKey:"desastre_disaster",gloss:"disaster",quizMeaning:"disasters",definition:"événement qui cause de très graves dommages",englishDistractors:["balconies","cherries","compasses"],frenchDistractors:["balcons","cerises","boussoles"]},
 {normalized:"déserts",lemmaKey:"desert",headword:"désert",partOfSpeech:"adjective",senseKey:"desert_deserted",gloss:"deserted; empty",definition:"qui est vide et sans présence humaine",englishDistractors:aE,frenchDistractors:["boisés","mentholés","hexagonaux"]},
 {normalized:"désespérance",lemmaKey:"desesperance",headword:"désespérance",partOfSpeech:"noun",senseKey:"desesperance_despair",gloss:"despair",definition:"état de profond désespoir",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"désespère",lemmaKey:"desesperer",headword:"désespérer",partOfSpeech:"verb",senseKey:"desesperer_lose_hope",gloss:"to despair",quizMeaning:"despair",definition:"perdre tout espoir de voir réussir quelque chose",englishDistractors:["crochet","skate","hum"],frenchDistractors:["crochète","patine","fredonne"]},
 {normalized:"désespérée",lemmaKey:"desespere",headword:"désespéré",partOfSpeech:"adjective",senseKey:"desespere_desperate",gloss:"desperate",definition:"qui manifeste la perte de tout espoir",englishDistractors:aE,frenchDistractors:["boisée","mentholée","hexagonale"]},
 {normalized:"déshonore",lemmaKey:"deshonorer",headword:"déshonorer",partOfSpeech:"verb",senseKey:"deshonorer_disgrace",gloss:"to dishonor; disgrace",quizMeaning:"dishonors; disgraces",definition:"faire perdre l’honneur ou la considération",englishDistractors:["crochets","skates","hums"],frenchDistractors:["crochète","patine","fredonne"]},
 {normalized:"désiré",lemmaKey:"desirer",headword:"désirer",partOfSpeech:"verb",senseKey:"desirer_want",gloss:"to desire; want",quizMeaning:"desired",definition:"souhaiter obtenir ou voir se produire quelque chose",englishDistractors:["crocheted","skated","hummed"],frenchDistractors:["crocheté","patiné","fredonné"]},
 {normalized:"désormais",lemmaKey:"desormais",headword:"désormais",partOfSpeech:"adverb",senseKey:"desormais_henceforth",gloss:"henceforth; from now on",definition:"à partir du moment présent ou du moment considéré",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"détails",lemmaKey:"detail",headword:"détail",partOfSpeech:"noun",senseKey:"detail_particular",gloss:"detail",quizMeaning:"details",definition:"élément particulier d’un ensemble",englishDistractors:["balconies","cherries","compasses"],frenchDistractors:["balcons","cerises","boussoles"]},
 {normalized:"détresse",lemmaKey:"detresse",headword:"détresse",partOfSpeech:"noun",senseKey:"detresse_distress",gloss:"distress",definition:"angoisse profonde causée par une situation douloureuse",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"dettes",lemmaKey:"dette",headword:"dette",partOfSpeech:"noun",senseKey:"dette_debt",gloss:"debt",quizMeaning:"debts",definition:"somme ou obligation que l’on doit à quelqu’un",englishDistractors:["balconies","cherries","compasses"],frenchDistractors:["balcons","cerises","boussoles"]},
 {normalized:"devait",lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"was to; had to",definition:"exprimer une obligation ou un événement attendu",englishDistractors:["crocheted","skated","hummed"],frenchDistractors:["crochetait","patinait","fredonnait"]},
 {normalized:"devant",lemmaKey:"devant",headword:"devant",partOfSpeech:"preposition",senseKey:"devant_before",gloss:"before; in front of",definition:"en présence de ou dans la partie située en avant",englishDistractors:["beneath","beside","despite"],frenchDistractors:["sous","auprès de","malgré"]},
 {normalized:"devenir",lemmaKey:"devenir",headword:"devenir",partOfSpeech:"verb",senseKey:"devenir_become",gloss:"to become",definition:"passer d’un état à un autre",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"devenu",lemmaKey:"devenir",headword:"devenir",partOfSpeech:"verb",senseKey:"devenir_become",gloss:"to become",quizMeaning:"became; become",definition:"passer d’un état à un autre",englishDistractors:["crocheted","skated","hummed"],frenchDistractors:["crocheté","patiné","fredonné"]},
 {normalized:"devient",lemmaKey:"devenir",headword:"devenir",partOfSpeech:"verb",senseKey:"devenir_become",gloss:"to become",quizMeaning:"becomes",definition:"passer d’un état à un autre",englishDistractors:["crochets","skates","hums"],frenchDistractors:["crochète","patine","fredonne"]},
 {normalized:"devoir",candidateIds:["tok_ed8699221ad9d8b501d420d5"],lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"to have to",definition:"exprimer une obligation ou un événement attendu",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"devoir",candidateIds:["tok_3180e264c94976963d94e0a8","tok_73fdeaabdc5b2fa4fe11ef8b","tok_71c5712088327672380a23b0","tok_548673760ec60bb3a2a616b2","tok_842261fe3f95f53e7ea080e6"],lemmaKey:"devoir_noun",headword:"devoir",partOfSpeech:"noun",senseKey:"devoir_duty",gloss:"duty",definition:"obligation morale ou responsabilité que l’on doit accomplir",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"devons",lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"must",definition:"exprimer une obligation ou un événement attendu",englishDistractors:["crochet","skate","hum"],frenchDistractors:["crochetons","patinons","fredonnons"]},
 {normalized:"dévoré",lemmaKey:"devorer",headword:"dévorer",partOfSpeech:"verb",senseKey:"devorer_consume",gloss:"to devour; consume",quizMeaning:"devoured; consumed",definition:"manger ou détruire avec une grande intensité",englishDistractors:["crocheted","skated","hummed"],frenchDistractors:["crocheté","patiné","fredonné"]},
 {normalized:"dévotement",lemmaKey:"devotement",headword:"dévotement",partOfSpeech:"adverb",senseKey:"devotement_devoutly",gloss:"devoutly",definition:"avec une ferveur religieuse ou une soumission excessive",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"devrait",lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"should",definition:"exprimer une obligation ou un événement attendu",englishDistractors:["would crochet","would skate","would hum"],frenchDistractors:["crochèterait","patinerait","fredonnerait"]},
 {normalized:"diabolique",lemmaKey:"diabolique",headword:"diabolique",partOfSpeech:"adjective",senseKey:"diabolique_evil",gloss:"diabolical; evil",definition:"d’une méchanceté extrême, digne du diable",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"dicter",lemmaKey:"dicter",headword:"dicter",partOfSpeech:"verb",senseKey:"dicter_dictate",gloss:"to dictate",definition:"prononcer un texte pour qu’une autre personne l’écrive",englishDistractors:vE,frenchDistractors:vF},
];
