import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a windmill", "a radish", "a pillow"];
const nounFrench: [string, string, string] = ["un moulin", "un radis", "un oreiller"];
const adjectiveEnglish: [string, string, string] = ["spotted", "honey-scented", "cubical"];
const adjectiveFrench: [string, string, string] = ["tacheté", "parfumé au miel", "cubique"];

export const zolaVocabularyBatch29: ZolaVocabularySpec[] = [
  { normalized: "judiciaire", lemmaKey: "judiciaire", headword: "judiciaire", partOfSpeech: "adjective", senseKey: "judiciaire_court", gloss: "judicial; legal", definition: "qui appartient à la justice, aux tribunaux ou à leur activité", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "jugé", lemmaKey: "juger", headword: "juger", partOfSpeech: "verb", senseKey: "juger_decide", gloss: "to judge; adjudicate", quizMeaning: "judged; adjudicated", definition: "examiner une affaire et prononcer une décision ou une appréciation", englishDistractors: ["painted", "swam", "snored"], frenchDistractors: ["peint", "nagé", "ronflé"] },
  { normalized: "jugée", lemmaKey: "juger", headword: "juger", partOfSpeech: "verb", senseKey: "juger_decide", gloss: "to judge; adjudicate", quizMeaning: "judged; adjudicated", definition: "examiner une affaire et prononcer une décision ou une appréciation", englishDistractors: ["painted", "swam", "snored"], frenchDistractors: ["peinte", "nagée", "ronflée"] },
  { normalized: "jugement", lemmaKey: "jugement", headword: "jugement", partOfSpeech: "noun", senseKey: "jugement_discernment", gloss: "judgment; discernment", definition: "faculté d’apprécier correctement les faits et de former une opinion", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "juger", lemmaKey: "juger", headword: "juger", partOfSpeech: "verb", senseKey: "juger_decide", gloss: "to judge; adjudicate", definition: "examiner une affaire et prononcer une décision ou une appréciation", englishDistractors: ["to paint", "to swim", "to snore"], frenchDistractors: ["peindre", "nager", "ronfler"] },
  { normalized: "juges", lemmaKey: "juge", headword: "juge", partOfSpeech: "noun", senseKey: "juge_magistrate", gloss: "judge; magistrate", quizMeaning: "judges; magistrates", definition: "personne chargée de rendre des décisions de justice", englishDistractors: ["windmills", "radishes", "pillows"], frenchDistractors: ["moulins", "radis", "oreillers"] },
  { normalized: "juif", lemmaKey: "juif", headword: "juif", partOfSpeech: "noun", senseKey: "juif_jewish_person", gloss: "Jewish person; Jew", definition: "personne appartenant au peuple juif ou à la religion juive", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "juifs", lemmaKey: "juif", headword: "juif", partOfSpeech: "noun", senseKey: "juif_jewish_person", gloss: "Jewish person; Jew", quizMeaning: "Jewish people; Jews", definition: "personne appartenant au peuple juif ou à la religion juive", englishDistractors: ["windmills", "radishes", "pillows"], frenchDistractors: ["moulins", "radis", "oreillers"] },
  { normalized: "juillet", lemmaKey: "juillet", headword: "juillet", partOfSpeech: "noun", senseKey: "juillet_month", gloss: "July", definition: "septième mois de l’année", englishDistractors: ["pillows", "windmills", "radishes"], frenchDistractors: ["oreillers", "moulins", "radis"] },
  { normalized: "juridique", lemmaKey: "juridique", headword: "juridique", partOfSpeech: "adjective", senseKey: "juridique_law", gloss: "legal; juridical", definition: "qui concerne le droit ou les règles de la loi", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "jusqu’", lemmaKey: "jusqua", headword: "jusqu’à", partOfSpeech: "preposition", senseKey: "jusqua_limit", gloss: "until; up to; as far as", definition: "marque la limite atteinte dans le temps, l’espace ou le degré", englishDistractors: ["beneath", "despite", "beside"], frenchDistractors: ["sous", "malgré", "auprès de"] },
  { normalized: "juste", lemmaKey: "juste", headword: "juste", partOfSpeech: "adjective", senseKey: "juste_fair_rightful", gloss: "just; fair; rightful", definition: "conforme à la justice, au droit ou à ce qui est mérité", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "justement", lemmaKey: "justement", headword: "justement", partOfSpeech: "adverb", senseKey: "justement_precisely", gloss: "precisely; exactly", definition: "précisément au point ou pour la raison dont il est question", englishDistractors: ["quietly", "overhead", "annually"], frenchDistractors: ["silencieusement", "au-dessus", "annuellement"] },
  { normalized: "justes", lemmaKey: "juste", headword: "juste", partOfSpeech: "adjective", senseKey: "juste_fair_rightful", gloss: "just; fair; rightful", definition: "conforme à la justice, au droit ou à ce qui est mérité", englishDistractors: adjectiveEnglish, frenchDistractors: ["tachetées", "parfumées au miel", "cubiques"] },
  { normalized: "justice", lemmaKey: "justice", headword: "justice", partOfSpeech: "noun", senseKey: "justice_fairness_system", gloss: "justice; fairness", definition: "principe qui consiste à reconnaître les droits de chacun, ou institution chargée de l’appliquer", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "justiciers", lemmaKey: "justicier", headword: "justicier", partOfSpeech: "noun", senseKey: "justicier_defender", gloss: "champion of justice", quizMeaning: "champions of justice", definition: "personne qui lutte pour faire triompher la justice", englishDistractors: ["windmills", "radishes", "pillows"], frenchDistractors: ["moulins", "radis", "oreillers"] },
  { normalized: "justifier", lemmaKey: "justifier", headword: "justifier", partOfSpeech: "verb", senseKey: "justifier_defend", gloss: "to justify; defend", definition: "présenter comme légitime ou fondé par des raisons ou des preuves", englishDistractors: ["to paint", "to swim", "to snore"], frenchDistractors: ["peindre", "nager", "ronfler"] },
  { normalized: "là", lemmaKey: "la_adverb", headword: "là", partOfSpeech: "adverb", senseKey: "la_there", gloss: "there; at that point", definition: "dans ce lieu ou à ce point de la situation évoquée", englishDistractors: ["quietly", "overhead", "annually"], frenchDistractors: ["silencieusement", "au-dessus", "annuellement"] },
  { normalized: "là-bas", lemmaKey: "la_bas", headword: "là-bas", partOfSpeech: "adverb", senseKey: "la_bas_over_there", gloss: "over there", definition: "dans un lieu éloigné de la personne qui parle", englishDistractors: ["quietly", "overhead", "annually"], frenchDistractors: ["silencieusement", "au-dessus", "annuellement"] },
  { normalized: "là-dedans", lemmaKey: "la_dedans", headword: "là-dedans", partOfSpeech: "adverb", senseKey: "la_dedans_in_there", gloss: "in there; in that situation", definition: "à l’intérieur de ce lieu ou de cette situation", englishDistractors: ["quietly", "overhead", "annually"], frenchDistractors: ["silencieusement", "au-dessus", "annuellement"] },
  { normalized: "laborieux", lemmaKey: "laborieux", headword: "laborieux", partOfSpeech: "adjective", senseKey: "laborieux_hardworking", gloss: "hardworking; industrious", definition: "qui travaille avec application et constance", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "lâchant", lemmaKey: "lacher", headword: "lâcher", partOfSpeech: "verb", senseKey: "lacher_release", gloss: "to release; let out", quizMeaning: "releasing; letting out", definition: "cesser de retenir et laisser sortir ou divulguer", englishDistractors: ["painting", "swimming", "snoring"], frenchDistractors: ["peignant", "nageant", "ronflant"] },
  { normalized: "laissé", lemmaKey: "laisser", headword: "laisser", partOfSpeech: "verb", senseKey: "laisser_allow", gloss: "to let; allow", quizMeaning: "let; allowed", definition: "ne pas empêcher une action ou permettre qu’elle se produise", englishDistractors: ["painted", "swam", "snored"], frenchDistractors: ["peint", "nagé", "ronflé"] },
  { normalized: "laisser", lemmaKey: "laisser", headword: "laisser", partOfSpeech: "verb", senseKey: "laisser_allow", gloss: "to let; allow", definition: "ne pas empêcher une action ou permettre qu’elle se produise", englishDistractors: ["to paint", "to swim", "to snore"], frenchDistractors: ["peindre", "nager", "ronfler"] },
];
