import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a kettle","an orchard","a sandal"];
const nF:[string,string,string]=["bouilloire","verger","sandale"];
const aE:[string,string,string]=["wooden","lemon-scented","rectangular"];
const aF:[string,string,string]=["boisé","citronné","rectangulaire"];
const vE:[string,string,string]=["to braid","to paddle","to sneeze"];
const vF:[string,string,string]=["tresser","pagayer","éternuer"];

export const zolaVocabularyBatch18: ZolaVocabularySpec[] = [
 {normalized:"doute",candidateIds:["tok_08fc2bd3bcc72fe38ee8d4f0","tok_323b3b60c19228deb4c9edcb","tok_fc4a4cac019748a7ff2a73e6","tok_cb070a368046b7a1edeced1a"],lemmaKey:"doute_noun",headword:"doute",partOfSpeech:"noun",senseKey:"doute_uncertainty",gloss:"doubt; uncertainty",definition:"incertitude sur la vérité ou la réalité de quelque chose",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"doute",candidateIds:["tok_60ed05b0cadb6f9390ba5ecf","tok_0b8e561224d08e43022d934a"],lemmaKey:"se_douter",headword:"se douter",partOfSpeech:"verb",senseKey:"se_douter_suspect",gloss:"to suspect; imagine",quizMeaning:"suspect; imagine",definition:"pressentir ou supposer l’existence de quelque chose",englishDistractors:["braid","paddle","sneeze"],frenchDistractors:["tresse","pagaie","éternue"]},
 {normalized:"doutes",lemmaKey:"doute_noun",headword:"doute",partOfSpeech:"noun",senseKey:"doute_uncertainty",gloss:"doubt; uncertainty",quizMeaning:"doubts",definition:"incertitude sur la vérité ou la réalité de quelque chose",englishDistractors:["kettles","orchards","sandals"],frenchDistractors:["bouilloires","vergers","sandales"]},
 {normalized:"droit",candidateIds:["tok_a006b6e8d069d7ec89f71dbd","tok_2e274aab80a29d221a3bd221"],lemmaKey:"droit_noun",headword:"droit",partOfSpeech:"noun",senseKey:"droit_law",gloss:"law; justice",definition:"ensemble des règles juridiques ou principe de justice",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"droit",candidateIds:["tok_ea72e2d55ebe75b82233950d"],lemmaKey:"droit_noun",headword:"droit",partOfSpeech:"noun",senseKey:"droit_entitlement",gloss:"right; entitlement",definition:"faculté légitime d’exiger ou d’obtenir quelque chose",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"droits",lemmaKey:"droit_noun",headword:"droit",partOfSpeech:"noun",senseKey:"droit_entitlement",gloss:"right; entitlement",quizMeaning:"rights",definition:"faculté légitime d’exiger ou d’obtenir quelque chose",englishDistractors:["kettles","orchards","sandals"],frenchDistractors:["bouilloires","vergers","sandales"]},
 {normalized:"dû",lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"had to",definition:"exprimer une obligation ou un événement attendu",englishDistractors:["braided","paddled","sneezed"],frenchDistractors:["tressé","pagayé","éternué"]},
 {normalized:"duel",lemmaKey:"duel",headword:"duel",partOfSpeech:"noun",senseKey:"duel_conflict",gloss:"duel; confrontation",definition:"affrontement direct entre deux adversaires",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"durèrent",lemmaKey:"durer",headword:"durer",partOfSpeech:"verb",senseKey:"durer_last",gloss:"to last",quizMeaning:"lasted",definition:"se prolonger pendant une certaine période",englishDistractors:["braided","paddled","sneezed"],frenchDistractors:["tressèrent","pagayèrent","éternuèrent"]},
 {normalized:"dut",lemmaKey:"devoir_verb",headword:"devoir",partOfSpeech:"verb",senseKey:"devoir_obligation",gloss:"must; to have to",quizMeaning:"must have; had to",definition:"exprimer une obligation ou un événement attendu",englishDistractors:["braided","paddled","sneezed"],frenchDistractors:["tressa","pagaya","éternua"]},
 {normalized:"éclata",lemmaKey:"eclater",headword:"éclater",partOfSpeech:"verb",senseKey:"eclater_burst",gloss:"to burst; break out",quizMeaning:"burst; broke out",definition:"se produire soudainement avec violence",englishDistractors:["braided","paddled","sneezed"],frenchDistractors:["tressa","pagaya","éternua"]},
 {normalized:"éclatante",lemmaKey:"eclatant",headword:"éclatant",partOfSpeech:"adjective",senseKey:"eclatant_obvious",gloss:"striking; manifest",definition:"qui se manifeste avec une évidence ou une intensité remarquable",englishDistractors:aE,frenchDistractors:["boisée","citronnée","rectangulaire"]},
 {normalized:"éclate",lemmaKey:"eclater",headword:"éclater",partOfSpeech:"verb",senseKey:"eclater_burst",gloss:"to burst; break out",quizMeaning:"bursts; breaks out",definition:"se produire soudainement avec violence",englishDistractors:["braids","paddles","sneezes"],frenchDistractors:["tresse","pagaie","éternue"]},
 {normalized:"éclater",lemmaKey:"eclater",headword:"éclater",partOfSpeech:"verb",senseKey:"eclater_burst",gloss:"to burst; break out",definition:"se produire soudainement avec violence",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"écrira",lemmaKey:"ecrire",headword:"écrire",partOfSpeech:"verb",senseKey:"ecrire_write",gloss:"to write",quizMeaning:"will write",definition:"tracer ou composer un texte",englishDistractors:["will braid","will paddle","will sneeze"],frenchDistractors:["tressera","pagayera","éternuera"]},
 {normalized:"écrites",lemmaKey:"ecrire",headword:"écrire",partOfSpeech:"verb",senseKey:"ecrire_write",gloss:"to write",quizMeaning:"written",definition:"tracer ou composer un texte",englishDistractors:["braided","paddled","sneezed"],frenchDistractors:["tressées","pagayées","éternuées"]},
 {normalized:"écriture",lemmaKey:"ecriture",headword:"écriture",partOfSpeech:"noun",senseKey:"ecriture_handwriting",gloss:"writing; handwriting",definition:"manière ou résultat de tracer des caractères",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"écritures",lemmaKey:"ecriture",headword:"écriture",partOfSpeech:"noun",senseKey:"ecriture_handwriting",gloss:"writing; handwriting",quizMeaning:"writings; handwriting samples",definition:"manière ou résultat de tracer des caractères",englishDistractors:["kettles","orchards","sandals"],frenchDistractors:["bouilloires","vergers","sandales"]},
 {normalized:"écroulement",lemmaKey:"ecroulement",headword:"écroulement",partOfSpeech:"noun",senseKey:"ecroulement_collapse",gloss:"collapse",definition:"chute ou destruction soudaine d’un ensemble",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"effroyable",lemmaKey:"effroyable",headword:"effroyable",partOfSpeech:"adjective",senseKey:"effroyable_appalling",gloss:"appalling; dreadful",definition:"qui provoque une très grande frayeur ou indignation",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"également",lemmaKey:"egalement",headword:"également",partOfSpeech:"adverb",senseKey:"egalement_also",gloss:"also; likewise",definition:"de la même manière ou en plus de ce qui précède",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"égarer",lemmaKey:"egarer",headword:"égarer",partOfSpeech:"verb",senseKey:"egarer_mislead",gloss:"to mislead",definition:"conduire quelqu’un loin de la vérité ou de la bonne direction",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"elle-même",lemmaKey:"elle_meme",headword:"elle-même",partOfSpeech:"pronoun",senseKey:"elle_meme_herself",gloss:"herself",definition:"forme renforcée du pronom elle désignant la même personne ou chose",englishDistractors:["himself","ourselves","themselves"],frenchDistractors:["lui-même","nous-mêmes","eux-mêmes"]},
 {normalized:"éloigna",lemmaKey:"eloigner",headword:"éloigner",partOfSpeech:"verb",senseKey:"eloigner_send_away",gloss:"to move away; send away",quizMeaning:"sent away",definition:"mettre ou envoyer à une grande distance",englishDistractors:["braided","paddled","sneezed"],frenchDistractors:["tressa","pagaya","éternua"]},
 {normalized:"émoi",lemmaKey:"emoi",headword:"émoi",partOfSpeech:"noun",senseKey:"emoi_agitation",gloss:"agitation; alarm",definition:"vive émotion mêlée d’inquiétude",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"émotion",lemmaKey:"emotion",headword:"émotion",partOfSpeech:"noun",senseKey:"emotion_feeling",gloss:"emotion",definition:"réaction affective vive provoquée par un événement",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"empêcher",lemmaKey:"empecher",headword:"empêcher",partOfSpeech:"verb",senseKey:"empecher_prevent",gloss:"to prevent",definition:"faire obstacle à une action ou à un événement",englishDistractors:vE,frenchDistractors:vF},
];
