import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a chimney","a pebble","a violin"];
const nF:[string,string,string]=["cheminée","caillou","violon"];
const aE:[string,string,string]=["salty","circular","sleepy"];
const aF:[string,string,string]=["salé","circulaire","somnolent"];
const vE:[string,string,string]=["to embroider","to float","to sneeze"];
const vF:[string,string,string]=["broder","flotter","éternuer"];

export const zolaVocabularyBatch12: ZolaVocabularySpec[] = [
 {normalized:"condamnant",lemmaKey:"condamner",headword:"condamner",partOfSpeech:"verb",senseKey:"condamner_sentence",gloss:"to condemn; sentence",quizMeaning:"condemning",definition:"déclarer quelqu’un coupable et le punir par un jugement",englishDistractors:["embroidering","floating","sneezing"],frenchDistractors:["brodant","flottant","éternuant"]},
 {normalized:"conduire",lemmaKey:"conduire",headword:"conduire",partOfSpeech:"verb",senseKey:"conduire_lead",gloss:"to lead; conduct",definition:"mener quelqu’un ou quelque chose vers un lieu ou un résultat",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"conduit",lemmaKey:"conduire",headword:"conduire",partOfSpeech:"verb",senseKey:"conduire_lead",gloss:"to lead; conduct",quizMeaning:"led; conducted",definition:"mener quelqu’un ou quelque chose vers un lieu ou un résultat",englishDistractors:["embroidered","floated","sneezed"],frenchDistractors:["brodé","flotté","éternué"]},
 {normalized:"confiante",lemmaKey:"confiant",headword:"confiant",partOfSpeech:"adjective",senseKey:"confiant_trusting",gloss:"confident; trusting",definition:"qui éprouve de la confiance",englishDistractors:aE,frenchDistractors:["salée","circulaire","somnolente"]},
 {normalized:"confondre",lemmaKey:"confondre",headword:"confondre",partOfSpeech:"verb",senseKey:"confondre_expose",gloss:"to expose; confound",definition:"démontrer la faute ou l’erreur de quelqu’un",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"connais",lemmaKey:"connaitre",headword:"connaître",partOfSpeech:"verb",senseKey:"connaitre_know",gloss:"to know",quizMeaning:"know",definition:"avoir connaissance de quelqu’un ou de quelque chose",englishDistractors:["embroider","float","sneeze"],frenchDistractors:["brode","flotte","éternue"]},
 {normalized:"connaît",lemmaKey:"connaitre",headword:"connaître",partOfSpeech:"verb",senseKey:"connaitre_know",gloss:"to know",quizMeaning:"knows",definition:"avoir connaissance de quelqu’un ou de quelque chose",englishDistractors:["embroiders","floats","sneezes"],frenchDistractors:["brode","flotte","éternue"]},
 {normalized:"connaîtra",lemmaKey:"connaitre",headword:"connaître",partOfSpeech:"verb",senseKey:"connaitre_know",gloss:"to know",quizMeaning:"will know",definition:"avoir connaissance de quelqu’un ou de quelque chose",englishDistractors:["will embroider","will float","will sneeze"],frenchDistractors:["brodera","flottera","éternuera"]},
 {normalized:"connue",lemmaKey:"connaitre",headword:"connaître",partOfSpeech:"verb",senseKey:"connaitre_know",gloss:"to know",quizMeaning:"known",definition:"avoir connaissance de quelqu’un ou de quelque chose",englishDistractors:["embroidered","floated","sneezed"],frenchDistractors:["brodée","flottée","éternuée"]},
 {normalized:"conquis",lemmaKey:"conquérir",headword:"conquérir",partOfSpeech:"verb",senseKey:"conquerir_win",gloss:"to win; conquer",quizMeaning:"won; conquered",definition:"gagner par un effort ou s’emparer de quelque chose",englishDistractors:["embroidered","floated","sneezed"],frenchDistractors:["brodé","flotté","éternué"]},
 {normalized:"conscience",lemmaKey:"conscience",headword:"conscience",partOfSpeech:"noun",senseKey:"conscience_moral_awareness",gloss:"conscience; awareness",definition:"faculté de juger moralement ses actes ou d’en avoir connaissance",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"consciences",lemmaKey:"conscience",headword:"conscience",partOfSpeech:"noun",senseKey:"conscience_moral_awareness",gloss:"conscience; awareness",quizMeaning:"consciences",definition:"faculté de juger moralement ses actes ou d’en avoir connaissance",englishDistractors:["chimneys","pebbles","violins"],frenchDistractors:["cheminées","cailloux","violons"]},
 {normalized:"conseil",lemmaKey:"conseil",headword:"conseil",partOfSpeech:"noun",senseKey:"conseil_council",gloss:"council",definition:"assemblée chargée de délibérer ou de juger",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"conseils",lemmaKey:"conseil",headword:"conseil",partOfSpeech:"noun",senseKey:"conseil_council",gloss:"council",quizMeaning:"councils",definition:"assemblée chargée de délibérer ou de juger",englishDistractors:["chimneys","pebbles","violins"],frenchDistractors:["cheminées","cailloux","violons"]},
 {normalized:"constatation",lemmaKey:"constatation",headword:"constatation",partOfSpeech:"noun",senseKey:"constatation_finding",gloss:"finding; observation",definition:"fait établi après examen",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"continuel",lemmaKey:"continuel",headword:"continuel",partOfSpeech:"adjective",senseKey:"continuel_constant",gloss:"continual; constant",definition:"qui se répète ou dure sans interruption",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"contraire",lemmaKey:"contraire",headword:"contraire",partOfSpeech:"noun",senseKey:"contraire_opposite",gloss:"opposite; contrary",definition:"ce qui s’oppose entièrement à autre chose",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"contre",lemmaKey:"contre",headword:"contre",partOfSpeech:"preposition",senseKey:"contre_against",gloss:"against",definition:"marque l’opposition ou le contact opposé",englishDistractors:["beneath","during","beside"],frenchDistractors:["sous","pendant","auprès de"]},
 {normalized:"convaincre",lemmaKey:"convaincre",headword:"convaincre",partOfSpeech:"verb",senseKey:"convaincre_persuade",gloss:"to convince",definition:"amener quelqu’un à reconnaître une vérité ou une faute",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"convaincu",lemmaKey:"convaincre",headword:"convaincre",partOfSpeech:"verb",senseKey:"convaincre_persuade",gloss:"to convince",quizMeaning:"convinced",definition:"amener quelqu’un à reconnaître une vérité ou une faute",englishDistractors:["embroidered","floated","sneezed"],frenchDistractors:["brodé","flotté","éternué"]},
 {normalized:"converse",lemmaKey:"converser",headword:"converser",partOfSpeech:"verb",senseKey:"converser_talk",gloss:"to converse",quizMeaning:"converses",definition:"s’entretenir par la parole avec quelqu’un",englishDistractors:["embroiders","floats","sneezes"],frenchDistractors:["brode","flotte","éternue"]},
 {normalized:"conviction",lemmaKey:"conviction",headword:"conviction",partOfSpeech:"noun",senseKey:"conviction_belief",gloss:"conviction; firm belief",definition:"certitude fortement établie dans l’esprit",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"convoqué",lemmaKey:"convoquer",headword:"convoquer",partOfSpeech:"verb",senseKey:"convoquer_summon",gloss:"to summon",quizMeaning:"summoned",definition:"appeler officiellement quelqu’un à se présenter",englishDistractors:["embroidered","floated","sneezed"],frenchDistractors:["brodé","flotté","éternué"]},
 {normalized:"coquins",lemmaKey:"coquin",headword:"coquin",partOfSpeech:"noun",senseKey:"coquin_scoundrel",gloss:"scoundrel",quizMeaning:"scoundrels",definition:"personne malhonnête ou sans scrupules",englishDistractors:["chimneys","pebbles","violins"],frenchDistractors:["cheminées","cailloux","violons"]},
 {normalized:"corps",lemmaKey:"corps",headword:"corps",partOfSpeech:"noun",senseKey:"corps_group",gloss:"body; corps",definition:"ensemble organisé de personnes appartenant à une même institution",englishDistractors:nE,frenchDistractors:nF},
];
