import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a staircase","a pear","a trumpet"];
const nF:[string,string,string]=["escalier","poire","trompette"];
const aE:[string,string,string]=["striped","spherical","fragrant"];
const aF:[string,string,string]=["rayé","sphérique","parfumé"];
const vE:[string,string,string]=["to knit","to swim","to whistle"];
const vF:[string,string,string]=["tricoter","nager","siffler"];

export const zolaVocabularyBatch13: ZolaVocabularySpec[] = [
 {normalized:"correspondance",lemmaKey:"correspondance",headword:"correspondance",partOfSpeech:"noun",senseKey:"correspondance_letters",gloss:"correspondence",definition:"échange suivi de lettres ou de messages",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"côté",lemmaKey:"cote",headword:"côté",partOfSpeech:"noun",senseKey:"cote_side",gloss:"side",definition:"partie située à droite ou à gauche, ou point de vue particulier",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"cour",lemmaKey:"cour",headword:"cour",partOfSpeech:"noun",senseKey:"cour_tribunal",gloss:"court",definition:"juridiction devant laquelle une affaire est jugée",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"couronnera",lemmaKey:"couronner",headword:"couronner",partOfSpeech:"verb",senseKey:"couronner_culminate",gloss:"to crown; culminate",quizMeaning:"will crown; will culminate",definition:"achever glorieusement ou constituer l’aboutissement de quelque chose",englishDistractors:["will knit","will swim","will whistle"],frenchDistractors:["tricotera","nagera","sifflera"]},
 {normalized:"court",lemmaKey:"courir",headword:"courir",partOfSpeech:"verb",senseKey:"courir_run",gloss:"to run",quizMeaning:"runs",definition:"se déplacer rapidement en courant",englishDistractors:["knits","swims","whistles"],frenchDistractors:["tricote","nage","siffle"]},
 {normalized:"couvert",lemmaKey:"couvrir",headword:"couvrir",partOfSpeech:"verb",senseKey:"couvrir_conceal",gloss:"to cover up; protect",quizMeaning:"covered up; protected",definition:"dissimuler une faute ou protéger une personne mise en cause",englishDistractors:["knitted","swam","whistled"],frenchDistractors:["tricoté","nagé","sifflé"]},
 {normalized:"couvrir",candidateIds:["tok_da0872b13f83fbf858902649"],lemmaKey:"couvrir",headword:"couvrir",partOfSpeech:"verb",senseKey:"couvrir_conceal",gloss:"to cover up; protect",definition:"dissimuler une faute ou protéger une personne mise en cause",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"couvrir",candidateIds:["tok_db15c8661b96e61557b08992"],lemmaKey:"couvrir",headword:"couvrir",partOfSpeech:"verb",senseKey:"couvrir_coat",gloss:"to cover; coat",definition:"mettre une matière sur toute la surface de quelque chose",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"crainte",lemmaKey:"crainte",headword:"crainte",partOfSpeech:"noun",senseKey:"crainte_fear",gloss:"fear",definition:"sentiment d’inquiétude devant un danger possible",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"cri",lemmaKey:"cri",headword:"cri",partOfSpeech:"noun",senseKey:"cri_cry",gloss:"cry; outcry",definition:"parole ou son lancé avec force pour exprimer un sentiment",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"crie",lemmaKey:"crier",headword:"crier",partOfSpeech:"verb",senseKey:"crier_proclaim",gloss:"to cry out; proclaim",quizMeaning:"cries out; proclaims",definition:"exprimer ou proclamer quelque chose avec force",englishDistractors:["knits","swims","whistles"],frenchDistractors:["tricote","nage","siffle"]},
 {normalized:"crierai",lemmaKey:"crier",headword:"crier",partOfSpeech:"verb",senseKey:"crier_proclaim",gloss:"to cry out; proclaim",quizMeaning:"will cry out; will proclaim",definition:"exprimer ou proclamer quelque chose avec force",englishDistractors:["will knit","will swim","will whistle"],frenchDistractors:["tricoterai","nagerai","sifflerai"]},
 {normalized:"crime",lemmaKey:"crime",headword:"crime",partOfSpeech:"noun",senseKey:"crime_offense",gloss:"crime; offense",definition:"acte très grave contraire à la loi ou à la morale",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"crimes",lemmaKey:"crime",headword:"crime",partOfSpeech:"noun",senseKey:"crime_offense",gloss:"crime; offense",quizMeaning:"crimes; offenses",definition:"acte très grave contraire à la loi ou à la morale",englishDistractors:["staircases","pears","trumpets"],frenchDistractors:["escaliers","poires","trompettes"]},
 {normalized:"criminel",lemmaKey:"criminel",headword:"criminel",partOfSpeech:"adjective",senseKey:"criminel_criminal",gloss:"criminal",definition:"qui constitue un crime ou s’y rapporte",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"croira",lemmaKey:"croire",headword:"croire",partOfSpeech:"verb",senseKey:"croire_believe",gloss:"to believe",quizMeaning:"will believe",definition:"tenir quelque chose pour vrai",englishDistractors:["will knit","will swim","will whistle"],frenchDistractors:["tricotera","nagera","sifflera"]},
 {normalized:"croire",lemmaKey:"croire",headword:"croire",partOfSpeech:"verb",senseKey:"croire_believe",gloss:"to believe",definition:"tenir quelque chose pour vrai",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"crois",lemmaKey:"croire",headword:"croire",partOfSpeech:"verb",senseKey:"croire_believe",gloss:"to believe",quizMeaning:"believe",definition:"tenir quelque chose pour vrai",englishDistractors:["knit","swim","whistle"],frenchDistractors:["tricote","nage","siffle"]},
 {normalized:"croulent",lemmaKey:"crouler",headword:"crouler",partOfSpeech:"verb",senseKey:"crouler_collapse",gloss:"to collapse",quizMeaning:"collapse",definition:"s’effondrer sous un poids ou sous une pression",englishDistractors:["knit","swim","whistle"],frenchDistractors:["tricotent","nagent","sifflent"]},
 {normalized:"croyait",lemmaKey:"croire",headword:"croire",partOfSpeech:"verb",senseKey:"croire_believe",gloss:"to believe",quizMeaning:"believed",definition:"tenir quelque chose pour vrai",englishDistractors:["knitted","swam","whistled"],frenchDistractors:["tricotait","nageait","sifflait"]},
 {normalized:"cru",lemmaKey:"croire",headword:"croire",partOfSpeech:"verb",senseKey:"croire_believe",gloss:"to believe",quizMeaning:"believed",definition:"tenir quelque chose pour vrai",englishDistractors:["knitted","swam","whistled"],frenchDistractors:["tricoté","nagé","sifflé"]},
 {normalized:"cruellement",lemmaKey:"cruellement",headword:"cruellement",partOfSpeech:"adverb",senseKey:"cruellement_cruelly",gloss:"cruelly",definition:"d’une manière qui fait souffrir sans pitié",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"culpabilité",lemmaKey:"culpabilite",headword:"culpabilité",partOfSpeech:"noun",senseKey:"culpabilite_guilt",gloss:"guilt",definition:"état d’une personne reconnue ou tenue pour coupable",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"cynique",lemmaKey:"cynique",headword:"cynique",partOfSpeech:"adjective",senseKey:"cynique_shameless",gloss:"cynical; shameless",definition:"qui affiche un mépris provocant des règles morales",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"dame",lemmaKey:"dame",headword:"dame",partOfSpeech:"noun",senseKey:"dame_woman",gloss:"lady; woman",definition:"femme adulte désignée avec une nuance de respect",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"dangereuses",lemmaKey:"dangereux",headword:"dangereux",partOfSpeech:"adjective",senseKey:"dangereux_dangerous",gloss:"dangerous",definition:"qui peut causer un dommage ou présenter un péril",englishDistractors:aE,frenchDistractors:["rayées","sphériques","parfumées"]},
];
