import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a mirror","a pineapple","a wheelbarrow"];
const nF:[string,string,string]=["miroir","ananas","brouette"];
const aE:[string,string,string]=["striped","cinnamon-scented","conical"];
const aF:[string,string,string]=["rayé","parfumé à la cannelle","conique"];
const vE:[string,string,string]=["to knit","to paddle","to yawn"];
const vF:[string,string,string]=["tricoter","pagayer","bâiller"];

export const zolaVocabularyBatch22: ZolaVocabularySpec[] = [
 {normalized:"extravagant",lemmaKey:"extravagant",headword:"extravagant",partOfSpeech:"adjective",senseKey:"extravagant_outlandish",gloss:"extravagant; outlandish",definition:"qui dépasse fortement la mesure ou la vraisemblance",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"fabriqué",lemmaKey:"fabriquer",headword:"fabriquer",partOfSpeech:"verb",senseKey:"fabriquer_make",gloss:"to make; fabricate",quizMeaning:"made; fabricated",definition:"produire quelque chose, parfois artificiellement ou frauduleusement",englishDistractors:["knitted","paddled","yawned"],frenchDistractors:["tricoté","pagayé","bâillé"]},
 {normalized:"façon",lemmaKey:"facon",headword:"façon",partOfSpeech:"noun",senseKey:"facon_manner",gloss:"way; manner",definition:"manière dont une action se déroule ou est accomplie",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"faiblesse",lemmaKey:"faiblesse",headword:"faiblesse",partOfSpeech:"noun",senseKey:"faiblesse_weakness",gloss:"weakness",definition:"manque de force, de courage ou de fermeté",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"fameux",lemmaKey:"fameux",headword:"fameux",partOfSpeech:"adjective",senseKey:"fameux_well_known",gloss:"famous; notorious",definition:"largement connu, parfois avec une nuance critique ou ironique",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"famille",lemmaKey:"famille",headword:"famille",partOfSpeech:"noun",senseKey:"famille_family",gloss:"family",definition:"groupe de personnes liées par la parenté ou présenté comme tel",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"farouches",lemmaKey:"farouche",headword:"farouche",partOfSpeech:"adjective",senseKey:"farouche_harsh",gloss:"fierce; harsh",definition:"d’une dureté ou d’une violence extrême",englishDistractors:aE,frenchDistractors:["rayés","parfumés à la cannelle","coniques"]},
 {normalized:"faussaire",lemmaKey:"faussaire",headword:"faussaire",partOfSpeech:"noun",senseKey:"faussaire_forger",gloss:"forger",definition:"personne qui fabrique ou altère frauduleusement un document",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"faute",lemmaKey:"faute",headword:"faute",partOfSpeech:"noun",senseKey:"faute_wrongdoing",gloss:"fault; wrongdoing",definition:"action contraire à une règle, à un devoir ou à la vérité",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"fautes",lemmaKey:"faute",headword:"faute",partOfSpeech:"noun",senseKey:"faute_wrongdoing",gloss:"fault; wrongdoing",quizMeaning:"faults; wrongdoings",definition:"action contraire à une règle, à un devoir ou à la vérité",englishDistractors:["mirrors","pineapples","wheelbarrows"],frenchDistractors:["miroirs","ananas","brouettes"]},
 {normalized:"femme",lemmaKey:"femme",headword:"femme",partOfSpeech:"noun",senseKey:"femme_woman",gloss:"woman; wife",definition:"personne adulte de sexe féminin, ou épouse selon le contexte",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"femmes",lemmaKey:"femme",headword:"femme",partOfSpeech:"noun",senseKey:"femme_woman",gloss:"woman; wife",quizMeaning:"women; wives",definition:"personne adulte de sexe féminin, ou épouse selon le contexte",englishDistractors:["mirrors","pineapples","wheelbarrows"],frenchDistractors:["miroirs","ananas","brouettes"]},
 {normalized:"ferment",lemmaKey:"fermer",headword:"fermer",partOfSpeech:"verb",senseKey:"fermer_close",gloss:"to close; shut",quizMeaning:"close; shut",definition:"mettre fin à une ouverture ou empêcher le passage",englishDistractors:["knit","paddle","yawn"],frenchDistractors:["tricotent","pagayent","bâillent"]},
 {normalized:"fertile",lemmaKey:"fertile",headword:"fertile",partOfSpeech:"adjective",senseKey:"fertile_productive",gloss:"fertile; productive",definition:"qui produit abondamment, au propre ou par l’imagination",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"fête",lemmaKey:"fete",headword:"fête",partOfSpeech:"noun",senseKey:"fete_celebration",gloss:"celebration; festival",definition:"manifestation organisée pour célébrer un événement",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"feu",lemmaKey:"feu",headword:"feu",partOfSpeech:"noun",senseKey:"feu_battle",gloss:"fire; battle",definition:"combat armé, par référence au feu des armes",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"fini",lemmaKey:"finir",headword:"finir",partOfSpeech:"verb",senseKey:"finir_end",gloss:"to finish; end",quizMeaning:"finished; over",definition:"arriver ou faire arriver à son terme",englishDistractors:["knitted","paddled","yawned"],frenchDistractors:["tricoté","pagayé","bâillé"]},
 {normalized:"finira",lemmaKey:"finir",headword:"finir",partOfSpeech:"verb",senseKey:"finir_end",gloss:"to finish; end",quizMeaning:"will finish; will end",definition:"arriver ou faire arriver à son terme",englishDistractors:["will knit","will paddle","will yawn"],frenchDistractors:["tricotera","pagayera","bâillera"]},
 {normalized:"finissent",lemmaKey:"finir",headword:"finir",partOfSpeech:"verb",senseKey:"finir_end",gloss:"to finish; end",quizMeaning:"finish; end up",definition:"arriver ou faire arriver à son terme",englishDistractors:["knit","paddle","yawn"],frenchDistractors:["tricotent","pagayent","bâillent"]},
 {normalized:"flammes",lemmaKey:"flamme",headword:"flamme",partOfSpeech:"noun",senseKey:"flamme_fire",gloss:"flame",quizMeaning:"flames",definition:"partie visible et lumineuse d’un feu",englishDistractors:["mirrors","pineapples","wheelbarrows"],frenchDistractors:["miroirs","ananas","brouettes"]},
 {normalized:"flot",lemmaKey:"flot",headword:"flot",partOfSpeech:"noun",senseKey:"flot_stream",gloss:"flood; stream",definition:"masse ou courant abondant qui se répand",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"fois",lemmaKey:"fois",headword:"fois",partOfSpeech:"noun",senseKey:"fois_occurrence",gloss:"time; occasion",definition:"occurrence d’un événement ou répétition d’une action",englishDistractors:["mirrors","pineapples","wheelbarrows"],frenchDistractors:["miroirs","ananas","brouettes"]},
 {normalized:"folles",lemmaKey:"fou",headword:"fou",partOfSpeech:"adjective",senseKey:"fou_mad",gloss:"mad; irrational",definition:"qui manque entièrement de raison ou de mesure",englishDistractors:aE,frenchDistractors:["rayées","parfumées à la cannelle","coniques"]},
 {normalized:"fonctions",lemmaKey:"fonction",headword:"fonction",partOfSpeech:"noun",senseKey:"fonction_duties",gloss:"function; official duty",quizMeaning:"functions; official duties",definition:"rôle ou charge exercé dans une organisation",englishDistractors:["mirrors","pineapples","wheelbarrows"],frenchDistractors:["miroirs","ananas","brouettes"]},
 {normalized:"fond",lemmaKey:"fond",headword:"fond",partOfSpeech:"noun",senseKey:"fond_core",gloss:"bottom; heart of the matter",definition:"partie la plus profonde ou essentielle d’une chose",englishDistractors:nE,frenchDistractors:nF},
];
