import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch11: Record<string, EditorialQuizSet> = {
  "affaire:affaire_matter": {
    early: "Cette affaire concerne la fermeture de l’école et mobilise tous les parents.", englishChoices: ["matter", "vacation", "decoration", "weather"],
    intermediate: "La mairie examine cette _____ de permis de construire depuis deux mois.", frenchChoices: ["affaire", "promenade", "peinture", "saison"],
    advanced: "L’affaire de la fermeture de la bibliothèque sera discutée mardi. Les élus étudient le budget, les lecteurs signent une pétition et la réunion commence à dix heures.",
    prompt: "Quel mot désigne la question dont les élus s’occupent ?", advancedChoices: ["affaire", "budget", "pétition", "réunion"],
  },
  "autres:autre_adjective": {
    early: "Paul choisit deux pommes rouges ; les autres fruits restent dans le panier.", englishChoices: ["other", "same", "all", "no"],
    intermediate: "Ces trois élèves partent tôt ; les _____ élèves restent jusqu’à midi.", frenchChoices: ["autres", "mêmes", "seuls", "premiers"],
    advanced: "Léa garde les livres de cuisine ; les autres livres iront à la bibliothèque. Paul range les cahiers, Nina ferme le carton et Marc écrit une étiquette.",
    prompt: "Quel mot distingue les livres restants de ceux de cuisine ?", advancedChoices: ["autres", "cuisine", "cahiers", "carton"],
  },
  "beau:beau_beautiful": {
    early: "Le jardin est beau au printemps, quand les fleurs couvrent les allées.", englishChoices: ["beautiful", "ugly", "empty", "dangerous"],
    intermediate: "Devant ce _____ paysage de montagne, les visiteurs s’arrêtent pour l’admirer.", frenchChoices: ["beau", "laid", "terne", "sinistre"],
    advanced: "Le beau jardin de Nina attire les promeneurs : ses roses sont en fleurs et les allées sont soignées. La clôture est vieille, mais le portail fonctionne.",
    prompt: "Quel mot exprime la beauté du jardin ?", advancedChoices: ["beau", "vieille", "soignées", "portail"],
  },
  "belle:beau_beautiful": {
    early: "Cette belle chanson émeut le public dès les premières notes.", englishChoices: ["beautiful", "ugly", "silent", "broken"],
    intermediate: "La mélodie plaît à tout le monde : quelle _____ chanson !", frenchChoices: ["belle", "laide", "fausse", "banale"],
    advanced: "La belle vue depuis la colline émerveille Paul : on aperçoit la rivière et les champs. Le sentier est étroit, la clôture est basse et le ciel reste gris.",
    prompt: "Quel mot qualifie la vue qui émerveille Paul ?", advancedChoices: ["belle", "étroit", "basse", "gris"],
  },
  "bien:bien_well": {
    early: "Nina connaît bien le chemin : elle y passe chaque matin.", englishChoices: ["well", "poorly", "rarely", "tomorrow"],
    intermediate: "Paul a répété sa leçon plusieurs fois ; maintenant il la connaît _____.", frenchChoices: ["bien", "mal", "peu", "à peine"],
    advanced: "Léa comprend bien les instructions et répare la lampe sans aide. Paul hésite encore, Nina consulte le manuel et Marc cherche une pièce.",
    prompt: "Quel mot indique que Léa comprend correctement les instructions ?", advancedChoices: ["bien", "encore", "manuel", "pièce"],
  },
  "bon:bon_good": {
    early: "Ce médecin est bon : il écoute ses patients et les soigne avec attention.", englishChoices: ["good", "careless", "hostile", "inept"],
    intermediate: "Ce boulanger prépare du pain délicieux : c’est un _____ artisan.", frenchChoices: ["bon", "médiocre", "maladroit", "négligent"],
    advanced: "Paul est un bon professeur : il explique clairement et prend le temps de répondre. Sa classe est petite, son bureau est ancien et la porte reste ouverte.",
    prompt: "Quel mot qualifie favorablement les qualités de Paul comme professeur ?", advancedChoices: ["bon", "petite", "ancien", "ouverte"],
  },
  "civique:civique_civic": {
    early: "Le devoir civique de voter concerne chaque citoyen.", englishChoices: ["civic", "private", "military", "commercial"],
    intermediate: "Voter aux élections relève de la responsabilité _____ de chaque citoyen.", frenchChoices: ["civique", "commerciale", "domestique", "militaire"],
    advanced: "Une association civique encourage les habitants à participer aux décisions de la ville. Une entreprise commerciale vend des journaux et une école organise un débat.",
    prompt: "Quel mot rattache l’association à la participation des citoyens ?", advancedChoices: ["civique", "commerciale", "journaux", "débat"],
  },
  "commandant:commandant_officer": {
    early: "Le commandant donne ses ordres aux soldats avant l’exercice.", englishChoices: ["commanding officer", "recruit", "judge", "witness"],
    intermediate: "L’officier qui dirige le bataillon demande à ses troupes de se rassembler : c’est le _____.", frenchChoices: ["commandant", "recrue", "témoin", "médecin"],
    advanced: "Le commandant dirige les soldats depuis le camp. Une recrue apporte une carte, le médecin examine un blessé et le cuisinier prépare le repas.",
    prompt: "Quel mot désigne l’officier qui donne les ordres ?", advancedChoices: ["commandant", "recrue", "médecin", "cuisinier"],
  },
  "communications:communication_exchange": {
    early: "Après l’orage, les communications entre les deux villages reprennent par téléphone.", englishChoices: ["communications", "buildings", "holidays", "vehicles"],
    intermediate: "La panne a interrompu les appels et les messages : les _____ sont coupées.", frenchChoices: ["communications", "vacances", "récoltes", "lumières"],
    advanced: "Les communications entre les deux îles passent maintenant par radio. Un bateau transporte les colis, le phare indique la côte et les pêcheurs attendent la météo.",
    prompt: "Quel mot désigne les échanges d’informations entre les îles ?", advancedChoices: ["communications", "bateau", "phare", "météo"],
  },
  "complaisant:complaisant_indulgent": {
    early: "Le critique complaisant évite de signaler les erreurs de son ami.", englishChoices: ["overly indulgent", "severe", "impartial", "hostile"],
    intermediate: "Par amitié, ce juge se montre trop _____ avec l’accusé et minimise sa faute.", frenchChoices: ["complaisant", "sévère", "impartial", "exigeant"],
    advanced: "Le responsable complaisant excuse toutes les absences de son ami sans demander de justification. Une collègue exigeante réclame les documents et le directeur vérifie les horaires.",
    prompt: "Quel mot indique que le responsable cherche à plaire en étant trop indulgent ?", advancedChoices: ["complaisant", "exigeante", "documents", "horaires"],
  },
  "complets:complet_complete": {
    early: "Les dossiers complets contiennent tous les formulaires et les signatures requises.", englishChoices: ["complete", "incomplete", "empty", "lost"],
    intermediate: "Chaque document et chaque signature figurent dans ces dossiers : ils sont _____.", frenchChoices: ["complets", "incomplets", "vides", "perdus"],
    advanced: "Les dossiers complets de Nina contiennent toutes les pièces demandées. Ceux de Paul sont incomplets ; un agent les classe et le greffier vérifie les dates.",
    prompt: "Quel mot indique que rien ne manque aux dossiers de Nina ?", advancedChoices: ["complets", "incomplets", "agent", "greffier"],
  },
  "complication:complication_difficulty": {
    early: "Une nouvelle complication retarde les travaux : la route est maintenant fermée.", englishChoices: ["complication", "solution", "shortcut", "celebration"],
    intermediate: "Le fournisseur annule sa livraison et ajoute ainsi une _____ au projet déjà difficile.", frenchChoices: ["complication", "solution", "facilité", "récompense"],
    advanced: "La fermeture du pont ajoute une complication au trajet des élèves. Le bus fait un détour, les parents préviennent l’école et le chauffeur consulte une carte.",
    prompt: "Quel mot désigne une difficulté supplémentaire pour le trajet ?", advancedChoices: ["complication", "détour", "chauffeur", "carte"],
  },
  "complice:complice_accomplice": {
    early: "Le cambrioleur a un complice qui surveille la rue pendant le vol.", englishChoices: ["accomplice", "victim", "witness", "guard"],
    intermediate: "Il a aidé son ami à voler la caisse ; il était son _____ dans ce vol.", frenchChoices: ["complice", "adversaire", "témoin", "gardien"],
    advanced: "Le complice de Luc a coupé l’électricité pendant que Luc entrait dans la boutique. Un voisin a vu la scène, le gardien est arrivé et la propriétaire a appelé la police.",
    prompt: "Quel mot désigne la personne qui a participé au vol avec Luc ?", advancedChoices: ["complice", "voisin", "gardien", "propriétaire"],
  },
  "complices:complice_accomplice": {
    early: "Les complices du voleur l’ont aidé à entrer dans le magasin fermé.", englishChoices: ["accomplices", "victims", "witnesses", "guards"],
    intermediate: "Trois personnes ont organisé le vol ensemble : elles sont _____ de ce crime.", frenchChoices: ["complices", "victimes", "témoins", "gardiennes"],
    advanced: "Les complices de Marc ont caché les objets volés pendant qu’il quittait le magasin. Un témoin a prévenu la police, puis les propriétaires ont vérifié leurs stocks.",
    prompt: "Quel mot désigne les personnes qui ont aidé Marc à voler ?", advancedChoices: ["complices", "témoin", "propriétaires", "police"],
  },
  "compliqué:complique_complex": {
    early: "Ce problème est compliqué : il faut résoudre plusieurs étapes liées entre elles.", englishChoices: ["complicated", "simple", "finished", "obvious"],
    intermediate: "Avec ses nombreuses exceptions, ce règlement est trop _____ pour les débutants.", frenchChoices: ["compliqué", "simple", "clair", "facile"],
    advanced: "Le mécanisme compliqué de l’horloge comprend de nombreuses pièces difficiles à régler. Son boîtier est léger, son cadran est blanc et sa vitre est propre.",
    prompt: "Quel mot indique que le mécanisme présente plusieurs difficultés ?", advancedChoices: ["compliqué", "léger", "blanc", "propre"],
  },
  "complot:complot_conspiracy": {
    early: "Les conspirateurs préparent en secret un complot contre le maire.", englishChoices: ["conspiracy", "agreement", "celebration", "accident"],
    intermediate: "Ils se réunissent en cachette pour renverser le conseil : leur _____ reste secret.", frenchChoices: ["complot", "fête", "accident", "promenade"],
    advanced: "Le complot contre le président a été préparé en secret par quatre hommes. Une lettre en révèle le projet, le gardien prévient la police et le ministre annule la réunion.",
    prompt: "Quel mot désigne le projet secret dirigé contre le président ?", advancedChoices: ["complot", "lettre", "police", "réunion"],
  },
  "comprend:comprendre_understand": {
    early: "Léa comprend la consigne et résout l’exercice sans aide.", englishChoices: ["understands", "forgets", "changes", "rejects"],
    intermediate: "Après une explication claire, Paul _____ enfin pourquoi la machine s’arrête.", frenchChoices: ["comprend", "ignore", "oublie", "conteste"],
    advanced: "Nina comprend le plan après que Luc lui a expliqué les symboles. Paul dessine une carte, Marie ferme la boîte et Léa examine les notes.",
    prompt: "Quel mot indique que Nina saisit le sens du plan ?", advancedChoices: ["comprend", "dessine", "ferme", "examine"],
  },
  "comprenez:comprendre_understand": {
    early: "Comprenez-vous cette règle après l’exemple donné par la professeure ?", englishChoices: ["understand", "forget", "change", "reject"],
    intermediate: "_____ bien ma question : je vous demande la date, pas le lieu.", frenchChoices: ["Comprenez", "Oubliez", "Changez", "Ignorez"],
    advanced: "Comprenez cette consigne avant de commencer l’expérience. Notez les étapes, ouvrez le manuel et vérifiez le matériel avec votre partenaire.",
    prompt: "Quel mot demande aux élèves de saisir le sens de la consigne ?", advancedChoices: ["Comprenez", "Notez", "ouvrez", "vérifiez"],
  },
  "compromettant:compromettre_incriminate": {
    early: "Ce message compromettant révèle que le directeur connaissait le projet illégal.", englishChoices: ["incriminating", "exculpatory", "irrelevant", "reassuring"],
    intermediate: "La lettre montre son implication dans la fraude : c’est un document _____ pour lui.", frenchChoices: ["compromettant", "innocentant", "anodin", "rassurant"],
    advanced: "Un courriel compromettant relie le responsable à la fraude et risque de nuire à sa défense. L’avocat examine le dossier, tandis que le témoin apporte une photographie.",
    prompt: "Quel mot qualifie le courriel qui met le responsable en cause ?", advancedChoices: ["compromettant", "avocat", "dossier", "photographie"],
  },
  "compromis:compromettre_incriminate": {
    early: "Son nom apparaît sur les faux reçus : il est compromis dans cette fraude.", englishChoices: ["implicated", "cleared", "protected", "rewarded"],
    intermediate: "Les preuves le relient à la fraude ; son associé est lui aussi _____ dans l’affaire.", frenchChoices: ["compromis", "innocenté", "blanchi", "protégé"],
    advanced: "Le trésorier est compromis par les faux reçus signés de sa main. Son avocat demande une expertise, le juge consulte les comptes et une journaliste attend dehors.",
    prompt: "Quel mot indique que les reçus mettent le trésorier en cause ?", advancedChoices: ["compromis", "avocat", "expertise", "comptes"],
  },
  "compte:compte_account": {
    early: "Le compte des billets vendus donne un total de cent vingt.", englishChoices: ["count", "letter", "journey", "witness"],
    intermediate: "Après avoir additionné les entrées, Paul vérifie son _____ : il a vendu trente billets.", frenchChoices: ["compte", "voyage", "courrier", "témoignage"],
    advanced: "Le compte de Nina indique qu’elle a ramassé trente pommes. Son panier est plein, Paul note le résultat sur un papier et Léa lave les fruits.",
    prompt: "Quel mot désigne le résultat du dénombrement des pommes ?", advancedChoices: ["compte", "panier", "papier", "fruits"],
  },
  "compter:compter_count": {
    early: "Pour connaître le nombre de chaises, Léa va les compter une par une.", englishChoices: ["to count", "to hide", "to carry", "to repair"],
    intermediate: "Avant de commander les billets, il faut _____ les personnes présentes.", frenchChoices: ["compter", "cacher", "écarter", "ignorer"],
    advanced: "Paul veut compter les trente livres sur l’étagère pour vérifier le total. Nina range les cahiers, Luc nettoie la table et Marie apporte un carton.",
    prompt: "Quel verbe signifie dénombrer les livres un par un ?", advancedChoices: ["compter", "range", "nettoie", "apporte"],
  },
  "conclure:conclure_conclude": {
    early: "Après avoir étudié toutes les preuves, le juge peut conclure que le témoin dit vrai.", englishChoices: ["to conclude", "to interrupt", "to conceal", "to repeat"],
    intermediate: "Après l’examen des chiffres, nous pouvons _____ que ce plan coûte trop cher.", frenchChoices: ["conclure", "ignorer", "dissimuler", "contester"],
    advanced: "Après avoir comparé les résultats, Léa peut conclure que la nouvelle méthode fonctionne. Paul classe les notes, Nina ferme la salle et Marc informe la directrice.",
    prompt: "Quel verbe exprime la conclusion tirée par Léa des résultats ?", advancedChoices: ["conclure", "classe", "ferme", "informe"],
  },
  "condamnation:condamnation_sentence": {
    early: "La condamnation de Marc pour vol comprend une peine de deux ans de prison.", englishChoices: ["conviction", "acquittal", "testimony", "invitation"],
    intermediate: "Le tribunal le déclare coupable et prononce sa _____ pour le vol.", frenchChoices: ["condamnation", "libération", "récompense", "invitation"],
    advanced: "La condamnation de Luc pour fraude entraîne une peine de prison. Son avocat lit le jugement, le témoin quitte la salle et la famille attend dehors.",
    prompt: "Quel mot désigne la décision déclarant Luc coupable et le punissant ?", advancedChoices: ["condamnation", "avocat", "témoin", "famille"],
  },
  "condamné:condamner_sentence": {
    early: "Après le procès, le tribunal a condamné Paul à une amende pour fraude.", englishChoices: ["sentenced", "acquitted", "invited", "praised"],
    intermediate: "Après l’avoir reconnu coupable, le juge l’a _____ à payer une amende.", frenchChoices: ["condamné", "acquitté", "invité", "félicité"],
    advanced: "Le tribunal a condamné Marc à une peine de prison après avoir établi sa culpabilité. Son avocat prépare un recours, et le greffier remet le jugement.",
    prompt: "Quel mot indique que le tribunal a prononcé une peine contre Marc ?", advancedChoices: ["condamné", "prépare", "remet", "jugement"],
  },
};
