import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEn: [string, string, string] = ["a staircase", "a teapot", "a meadow"];
const nounFr: [string, string, string] = ["escalier", "théière", "pré"];
const verbEn: [string, string, string] = ["to knit", "to bloom", "to skate"];
const verbFr: [string, string, string] = ["tricoter", "fleurir", "patiner"];
const adjectiveEn: [string, string, string] = ["striped", "wooden", "mint-flavored"];
const adjectiveFr: [string, string, string] = ["rayé", "boisé", "mentholé"];

export const zolaVocabularyBatch02: ZolaVocabularySpec[] = [
  { normalized:"accommoder", lemmaKey:"accommoder", headword:"accommoder", partOfSpeech:"verb", senseKey:"accommoder_tolerate", gloss:"to reconcile oneself; tolerate", definition:"accepter ou tolérer une situation", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"accomplis", lemmaKey:"accomplir", headword:"accomplir", partOfSpeech:"verb", senseKey:"accomplir_perform", gloss:"I perform; carry out", definition:"je réalise ou exécute", englishDistractors:["I knit","I bloom","I skate"], frenchDistractors:["je tricote","je fleuris","je patine"] },
  { normalized:"accord", lemmaKey:"accord", headword:"accord", partOfSpeech:"noun", senseKey:"accord_agreement", gloss:"agreement", definition:"entente ou conformité d’opinions", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"accueil", lemmaKey:"accueil", headword:"accueil", partOfSpeech:"noun", senseKey:"accueil_reception", gloss:"welcome; reception", definition:"manière de recevoir quelqu’un", englishDistractors:nounEn, frenchDistractors:["escalier","fauteuil","jardin"] },
  { normalized:"accusation", lemmaKey:"accusation", headword:"accusation", partOfSpeech:"noun", senseKey:"accusation_charge", gloss:"accusation; charge", definition:"mise en cause officielle d’une personne", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"accusations", lemmaKey:"accusation", headword:"accusation", partOfSpeech:"noun", senseKey:"accusation_charge", gloss:"accusation; charge", quizMeaning:"accusations; charges", definition:"mise en cause officielle d’une personne", englishDistractors:["staircases","teapots","meadows"], frenchDistractors:["escaliers","théières","prés"] },
  { normalized:"accuse", lemmaKey:"accuser", headword:"accuser", partOfSpeech:"verb", senseKey:"accuser_charge", gloss:"to accuse", quizMeaning:"I accuse", definition:"désigner comme responsable d’une faute ou d’un crime", englishDistractors:["I knit","I bloom","I skate"], frenchDistractors:["je tricote","je fleuris","je patine"] },
  { normalized:"accuser", lemmaKey:"accuser", headword:"accuser", partOfSpeech:"verb", senseKey:"accuser_charge", gloss:"to accuse", definition:"désigner comme responsable d’une faute ou d’un crime", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"accusé", candidateIds:["tok_fced63529f84cf739d2de371","tok_e7590d4aa719107228b59cdb"], lemmaKey:"accuse_noun", headword:"accusé", partOfSpeech:"noun", senseKey:"accuse_defendant", gloss:"the accused; defendant", definition:"personne poursuivie devant la justice", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"accusé", candidateIds:["tok_420e33f7b4544eb502b8699a"], lemmaKey:"accuser", headword:"accuser", partOfSpeech:"verb", senseKey:"accuser_charge", gloss:"to accuse", quizMeaning:"accused", definition:"désigner comme responsable d’une faute ou d’un crime", englishDistractors:["knitted","bloomed","skated"], frenchDistractors:["tricoté","fleuri","patiné"] },
  { normalized:"achèvent", lemmaKey:"achever", headword:"achever", partOfSpeech:"verb", senseKey:"achever_complete", gloss:"complete; finish", definition:"mènent à son terme", englishDistractors:["knit","bloom","skate"], frenchDistractors:["tricotent","fleurissent","patinent"] },
  { normalized:"acquitter", lemmaKey:"acquitter", headword:"acquitter", partOfSpeech:"verb", senseKey:"acquitter_acquit", gloss:"to acquit", definition:"déclarer non coupable", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"acte", candidateIds:["tok_ec5618fba352212fb7ef72f7","tok_f27a7dbf9961c6aa6138b0d6","tok_33577a44ea790e4ad84a79f7"], lemmaKey:"acte", headword:"acte", partOfSpeech:"noun", senseKey:"acte_document", gloss:"document; legal instrument", definition:"document constatant officiellement quelque chose", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"acte", candidateIds:["tok_1938279e97c21f46dd30ddff"], lemmaKey:"acte", headword:"acte", partOfSpeech:"noun", senseKey:"acte_deed", gloss:"act; deed", definition:"action accomplie volontairement", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"actes", lemmaKey:"acte", headword:"acte", partOfSpeech:"noun", senseKey:"acte_deed", gloss:"act; deed", quizMeaning:"acts; actions", definition:"action accomplie volontairement", englishDistractors:["staircases","teapots","meadows"], frenchDistractors:["escaliers","théières","prés"] },
  { normalized:"adjurant", lemmaKey:"adjurer", headword:"adjurer", partOfSpeech:"verb", senseKey:"adjurer_implore", gloss:"imploring; urging solemnly", definition:"suppliant avec insistance", englishDistractors:["knitting","blooming","skating"], frenchDistractors:["tricotant","fleurissant","patinant"] },
  { normalized:"adressée", lemmaKey:"adresser", headword:"adresser", partOfSpeech:"verb", senseKey:"adresser_send", gloss:"addressed; sent", definition:"envoyée ou destinée à quelqu’un", englishDistractors:["knitted","bloomed","skated"], frenchDistractors:["tricotée","fleurie","patinée"] },
  { normalized:"affirme", lemmaKey:"affirmer", headword:"affirmer", partOfSpeech:"verb", senseKey:"affirmer_state", gloss:"to assert; state", quizMeaning:"asserts; states", definition:"énoncer comme certain", englishDistractors:["knits","blooms","skates"], frenchDistractors:["tricote","fleurit","patine"] },
  { normalized:"affirmer", lemmaKey:"affirmer", headword:"affirmer", partOfSpeech:"verb", senseKey:"affirmer_state", gloss:"to assert; state", definition:"énoncer comme certain", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"affolé", lemmaKey:"affoler", headword:"affoler", partOfSpeech:"adjective", senseKey:"affole_panicked", gloss:"panicked; distraught", definition:"mis dans un état de peur désordonnée", englishDistractors:adjectiveEn, frenchDistractors:adjectiveFr },
  { normalized:"affreuse", lemmaKey:"affreux", headword:"affreux", partOfSpeech:"adjective", senseKey:"affreux_horrible", gloss:"horrible; dreadful", definition:"qui inspire l’horreur", englishDistractors:adjectiveEn, frenchDistractors:["rayée","boisée","mentholée"] },
  { normalized:"agent", lemmaKey:"agent", headword:"agent", partOfSpeech:"noun", senseKey:"agent_representative", gloss:"agent; representative", definition:"personne chargée d’agir pour une puissance", englishDistractors:nounEn, frenchDistractors:["escalier","fauteuil","jardin"] },
  { normalized:"aggraver", lemmaKey:"aggraver", headword:"aggraver", partOfSpeech:"verb", senseKey:"aggraver_worsen", gloss:"to worsen; aggravate", definition:"rendre plus grave", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"agi", lemmaKey:"agir", headword:"agir", partOfSpeech:"verb", senseKey:"agir_act", gloss:"to act", quizMeaning:"acted", definition:"accomplir une action", englishDistractors:["knitted","bloomed","skated"], frenchDistractors:["tricoté","fleuri","patiné"] },
  { normalized:"agir", lemmaKey:"agir", headword:"agir", partOfSpeech:"verb", senseKey:"s_agir_concern", gloss:"to be a matter of; concern", definition:"être question de quelque chose", englishDistractors:verbEn, frenchDistractors:verbFr },
];
