import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch17: Record<string, EditorialQuizSet> = {
  "diffamation:diffamation_defamation": {
    early: "Accuser faussement la médecin de vol constitue une diffamation qui nuit à sa réputation.", englishChoices: ["defamation", "praise", "apology", "permission"],
    intermediate: "Cette accusation mensongère salit sa réputation : elle porte plainte pour _____.", frenchChoices: ["diffamation", "félicitation", "autorisation", "récompense"],
    advanced: "La diffamation répandue contre Nina l’accuse à tort de fraude et abîme sa réputation. Paul rassemble les preuves, Léa interroge un témoin et Marc contacte un avocat.",
    prompt: "Quel mot désigne l’accusation mensongère qui porte atteinte à Nina ?", advancedChoices: ["diffamation", "preuves", "témoin", "avocat"],
  },
  "dignité:dignite_worth": {
    early: "Même humiliée publiquement, Léa conserve sa dignité et exige le respect.", englishChoices: ["dignity", "wealth", "strength", "rank"],
    intermediate: "Le prisonnier demande à être traité avec respect pour préserver sa _____.", frenchChoices: ["dignité", "fortune", "force", "fonction"],
    advanced: "Nina défend sa dignité lorsqu’elle refuse les insultes et réclame d’être traitée avec respect. Paul ferme la porte, Léa lit une lettre et Marc attend dehors.",
    prompt: "Quel mot désigne le respect dû à Nina en tant que personne ?", advancedChoices: ["dignité", "insultes", "lettre", "dehors"],
  },
  "dilapidations:dilapidation_misappropriation": {
    early: "Les dilapidations du trésorier comprennent des dépenses privées payées avec l’argent public.", englishChoices: ["misappropriations", "savings", "donations", "refunds"],
    intermediate: "Le rapport révèle plusieurs _____ : des fonds publics ont été détournés et gaspillés.", frenchChoices: ["dilapidations", "économies", "recettes", "restitutions"],
    advanced: "Les dilapidations reprochées au directeur ont vidé la caisse par des achats personnels et inutiles. Nina examine les comptes, Paul classe les factures et Léa avertit le conseil.",
    prompt: "Quel mot désigne les détournements et gaspillages des fonds confiés ?", advancedChoices: ["dilapidations", "comptes", "factures", "conseil"],
  },
  "dirai:dire_say": {
    early: "Demain, je dirai la vérité au juge devant tous les témoins.", englishChoices: ["will say", "will hide", "will write", "will forget"],
    intermediate: "À la réunion de demain, je _____ clairement ce que j’ai vu.", frenchChoices: ["dirai", "cacherai", "oublierai", "nierai"],
    advanced: "Je dirai mon avis au conseil lorsque la présidente me donnera la parole. Nina prendra des notes, Paul ouvrira la séance et Léa préparera le dossier.",
    prompt: "Quel mot annonce que j’exprimerai mon avis par la parole ?", advancedChoices: ["dirai", "prendra", "ouvrira", "préparera"],
  },
  "dire:dire_say": {
    early: "Paul veut dire la vérité à son ami sans rien lui cacher.", englishChoices: ["to say", "to conceal", "to draw", "to forget"],
    intermediate: "Pouvez-vous _____ votre nom à voix haute pour que je l’écrive ?", frenchChoices: ["dire", "cacher", "dessiner", "oublier"],
    advanced: "Nina souhaite dire ce qu’elle a vu au policier. Paul ouvre le dossier, Léa ferme la fenêtre et Marc consulte une carte.",
    prompt: "Quel verbe signifie exprimer son témoignage par la parole ?", advancedChoices: ["dire", "ouvre", "ferme", "consulte"],
  },
  "directeur:directeur_head": {
    early: "Le directeur de l’école organise le travail des professeurs et du personnel.", englishChoices: ["director", "student", "visitor", "customer"],
    intermediate: "La personne qui dirige le musée et son personnel en est le _____.", frenchChoices: ["directeur", "visiteur", "client", "gardien"],
    advanced: "Le directeur de l’usine décide des horaires et supervise tous les services. Nina travaille aux comptes, Paul garde l’entrée et Léa accueille les clients.",
    prompt: "Quel mot désigne la personne qui dirige l’usine ?", advancedChoices: ["directeur", "services", "entrée", "clients"],
  },
  "disait:dire_say": {
    early: "Pendant l’entretien, Paul disait qu’il avait vu la voiture partir.", englishChoices: ["was saying", "was hiding", "was writing", "was forgetting"],
    intermediate: "Hier encore, Nina _____ que le magasin fermerait lundi.", frenchChoices: ["disait", "cachait", "oubliait", "niait"],
    advanced: "Léa disait la vérité lorsqu’elle racontait avoir trouvé la lettre. Paul classait les dossiers, Nina fermait la porte et Marc regardait l’horloge.",
    prompt: "Quel mot indique que Léa exprimait son récit par la parole ?", advancedChoices: ["disait", "classait", "fermait", "regardait"],
  },
  "discipline:discipline_obedience": {
    early: "La discipline militaire exige que chaque soldat obéisse aux ordres.", englishChoices: ["discipline", "freedom", "disorder", "reward"],
    intermediate: "Le règlement impose une stricte _____ aux membres de l’unité.", frenchChoices: ["discipline", "liberté", "confusion", "récompense"],
    advanced: "La discipline du régiment oblige les soldats à respecter les horaires et les ordres. Le commandant inspecte les rangs, Nina note les absences et Paul ferme la grille.",
    prompt: "Quel mot désigne la règle d’obéissance imposée aux soldats ?", advancedChoices: ["discipline", "commandant", "absences", "grille"],
  },
  "discute:discuter_question": {
    early: "L’avocat discute la valeur du témoignage et en conteste la fiabilité.", englishChoices: ["questions", "accepts", "conceals", "repeats"],
    intermediate: "Devant le tribunal, la défense _____ cette preuve et affirme qu’elle n’est pas fiable.", frenchChoices: ["discute", "accepte", "cache", "répète"],
    advanced: "Nina discute la conclusion du rapport en montrant que les chiffres sont incomplets. Paul relit les tableaux, Léa cherche les factures et Marc ouvre le dossier.",
    prompt: "Quel mot indique que Nina examine et conteste la conclusion ?", advancedChoices: ["discute", "relit", "cherche", "ouvre"],
  },
  "disgrâce:disgrace_disfavor": {
    early: "Après avoir trahi le roi, le ministre tombe en disgrâce et perd sa faveur.", englishChoices: ["disfavor", "promotion", "admiration", "reward"],
    intermediate: "Autrefois apprécié du dirigeant, il tombe en _____ après son mensonge.", frenchChoices: ["disgrâce", "faveur", "admiration", "gloire"],
    advanced: "La disgrâce du conseiller commence lorsque la reine cesse de lui faire confiance et l’écarte de la cour. Nina lit la décision, Paul ferme le palais et Léa prépare une voiture.",
    prompt: "Quel mot désigne la perte de la faveur accordée au conseiller ?", advancedChoices: ["disgrâce", "décision", "palais", "voiture"],
  },
  "disparaissaient:disparaitre_vanish": {
    early: "Dans le brouillard, les montagnes disparaissaient peu à peu de la vue.", englishChoices: ["were disappearing", "were appearing", "were growing", "were shining"],
    intermediate: "À mesure que la nuit tombait, les derniers détails du paysage _____ dans l’obscurité.", frenchChoices: ["disparaissaient", "apparaissaient", "grandissaient", "brillaient"],
    advanced: "Les maisons disparaissaient derrière l’épais brouillard et cessaient d’être visibles. Nina ralentissait la voiture, Paul regardait la carte et Léa allumait les phares.",
    prompt: "Quel mot indique que les maisons n’étaient progressivement plus visibles ?", advancedChoices: ["disparaissaient", "ralentissait", "regardait", "allumait"],
  },
  "disparaît:disparaitre_vanish": {
    early: "Le bateau disparaît derrière l’île et n’est bientôt plus visible.", englishChoices: ["disappears", "appears", "approaches", "stops"],
    intermediate: "Quand le soleil se couche, sa lumière _____ peu à peu.", frenchChoices: ["disparaît", "apparaît", "augmente", "reste"],
    advanced: "La route disparaît sous la neige et devient impossible à voir. Nina ferme les volets, Paul range la pelle et Léa prépare du thé.",
    prompt: "Quel mot indique que la route cesse d’être visible ?", advancedChoices: ["disparaît", "ferme", "range", "prépare"],
  },
  "doigt:doigt_finger": {
    early: "Paul montre la direction avec son doigt posé au bout de sa main.", englishChoices: ["finger", "elbow", "knee", "shoulder"],
    intermediate: "Elle porte une bague au _____ de la main gauche.", frenchChoices: ["doigt", "coude", "genou", "épaule"],
    advanced: "Nina s’est coupé le doigt en préparant les légumes. Paul apporte un bandage, Léa lave le couteau et Marc ferme la boîte.",
    prompt: "Quel mot désigne la partie articulée de la main blessée par Nina ?", advancedChoices: ["doigt", "bandage", "couteau", "boîte"],
  },
  "doit:devoir_obligation": {
    early: "Chaque visiteur doit présenter son billet avant d’entrer.", englishChoices: ["must", "may", "wants to", "refuses to"],
    intermediate: "Pour respecter le règlement, Paul _____ porter un casque.", frenchChoices: ["doit", "peut", "veut", "refuse"],
    advanced: "Nina doit envoyer le formulaire aujourd’hui parce que la date limite est ce soir. Paul imprime une copie, Léa vérifie l’adresse et Marc ouvre le guichet.",
    prompt: "Quel mot exprime l’obligation imposée à Nina ?", advancedChoices: ["doit", "imprime", "vérifie", "ouvre"],
  },
  "doivent:devoir_obligation": {
    early: "Les cyclistes doivent porter un casque sur cette piste.", englishChoices: ["must", "may", "want to", "refuse to"],
    intermediate: "Selon la consigne, les élèves _____ rendre leur travail vendredi.", frenchChoices: ["doivent", "peuvent", "veulent", "refusent"],
    advanced: "Les employés doivent fermer les fenêtres avant de quitter le bureau. Nina range les dossiers, Paul éteint les lampes et Léa vérifie la porte.",
    prompt: "Quel mot exprime l’obligation des employés ?", advancedChoices: ["doivent", "range", "éteint", "vérifie"],
  },
  "donc:donc_therefore": {
    early: "La route est fermée ; nous devons donc prendre un autre chemin.", englishChoices: ["therefore", "however", "meanwhile", "perhaps"],
    intermediate: "Il pleut fortement ; la sortie est _____ annulée.", frenchChoices: ["donc", "pourtant", "peut-être", "cependant"],
    advanced: "Le train ne circule pas ; Nina prendra donc le bus en conséquence. Paul attend pourtant sur le quai, Léa téléphone pendant ce temps et Marc cherche un taxi.",
    prompt: "Quel mot introduit la conséquence de l’arrêt du train ?", advancedChoices: ["donc", "pourtant", "pendant", "taxi"],
  },
  "donne:donner_give": {
    early: "Nina donne une pomme à Paul, qui la prend dans sa main.", englishChoices: ["gives", "takes", "hides", "buys"],
    intermediate: "Chaque matin, le facteur _____ le courrier au gardien.", frenchChoices: ["donne", "prend", "cache", "achète"],
    advanced: "Léa donne les clés à Nina pour qu’elle ouvre la maison. Paul porte les sacs, Marc ferme la voiture et Luc regarde la carte.",
    prompt: "Quel mot indique que Léa remet les clés à Nina ?", advancedChoices: ["donne", "porte", "ferme", "regarde"],
  },
  "donner:donner_give": {
    early: "Paul souhaite donner ses anciens livres à la bibliothèque.", englishChoices: ["to give", "to take", "to hide", "to sell"],
    intermediate: "Pour aider l’école, Nina va _____ trente cahiers aux élèves.", frenchChoices: ["donner", "prendre", "cacher", "vendre"],
    advanced: "Marc veut donner son vélo à son frère pour son anniversaire. Nina prépare un ruban, Paul ferme le garage et Léa écrit une carte.",
    prompt: "Quel verbe signifie remettre gratuitement le vélo à son frère ?", advancedChoices: ["donner", "prépare", "ferme", "écrit"],
  },
  "donnera:donner_give": {
    early: "Demain, le professeur donnera les résultats à chaque élève.", englishChoices: ["will give", "will take", "will hide", "will sell"],
    intermediate: "À la fin du concours, le maire _____ un prix au gagnant.", frenchChoices: ["donnera", "prendra", "cachera", "vendra"],
    advanced: "Nina donnera le dossier à Paul lorsqu’il arrivera au bureau. Léa ouvrira la porte, Marc rangera les livres et Luc préparera du café.",
    prompt: "Quel mot indique que Nina remettra le dossier à Paul ?", advancedChoices: ["donnera", "ouvrira", "rangera", "préparera"],
  },
  "donneront:donner_give": {
    early: "Les bénévoles donneront des couvertures aux familles demain.", englishChoices: ["will give", "will take", "will hide", "will sell"],
    intermediate: "À la cérémonie, les organisateurs _____ un livre à chaque enfant.", frenchChoices: ["donneront", "prendront", "cacheront", "vendront"],
    advanced: "Les voisins donneront des meubles à la famille après l’incendie. Nina apportera des vêtements, Paul réparera la porte et Léa préparera le repas.",
    prompt: "Quel mot indique que les voisins remettront gratuitement les meubles ?", advancedChoices: ["donneront", "apportera", "réparera", "préparera"],
  },
  "donnez:donner_give": {
    early: "Donnez votre billet au contrôleur lorsqu’il vous le demande.", englishChoices: ["give", "take", "hide", "buy"],
    intermediate: "_____ ce formulaire au secrétaire avant de partir, s’il vous plaît.", frenchChoices: ["Donnez", "Prenez", "Cachez", "Achetez"],
    advanced: "Donnez la lettre à Nina dès son arrivée. Fermez ensuite la porte, ouvrez le dossier et rangez les autres documents.",
    prompt: "Quel mot demande de remettre la lettre à Nina ?", advancedChoices: ["Donnez", "Fermez", "ouvrez", "rangez"],
  },
  "dont:dont_whose_of_which": {
    early: "Voici le livre dont Paul parle, c’est-à-dire le livre au sujet duquel il s’exprime.", englishChoices: ["of which", "who", "where", "when"],
    intermediate: "La collègue _____ je connais le frère travaille à la mairie.", frenchChoices: ["dont", "qui", "où", "quand"],
    advanced: "Nina retrouve la lettre dont elle avait besoin pour compléter son dossier. Paul demande qui vient, Léa indique où attendre et Marc précise quand partir.",
    prompt: "Quel mot remplace ici le complément introduit par « de » dans « avoir besoin de la lettre » ?", advancedChoices: ["dont", "qui", "où", "quand"],
  },
  "dorment:dormir_sleep": {
    early: "Les enfants dorment dans leur lit depuis neuf heures.", englishChoices: ["sleep", "work", "eat", "sing"],
    intermediate: "Il est minuit et les bébés _____ paisiblement dans leur chambre.", frenchChoices: ["dorment", "travaillent", "mangent", "chantent"],
    advanced: "Les voyageurs dorment dans le train de nuit, les yeux fermés. Nina lit un livre, Paul regarde le paysage et Léa prépare du café.",
    prompt: "Quel mot indique que les voyageurs sont dans l’état naturel de repos ?", advancedChoices: ["dorment", "lit", "regarde", "prépare"],
  },
  "dossier:dossier_case_file": {
    early: "L’avocat rassemble les témoignages et les preuves dans un même dossier.", englishChoices: ["case file", "envelope", "newspaper", "suitcase"],
    intermediate: "Tous les documents de l’affaire sont réunis dans ce _____.", frenchChoices: ["dossier", "journal", "bagage", "roman"],
    advanced: "Le dossier de l’affaire contient les dépositions, les photographies et les rapports de police. Nina ouvre l’armoire, Paul lit une lettre et Léa attend le juge.",
    prompt: "Quel mot désigne l’ensemble des documents réunis sur l’affaire ?", advancedChoices: ["dossier", "photographies", "rapports", "lettre"],
  },
  "double:double_twofold": {
    early: "La porte possède une double serrure, avec deux mécanismes distincts.", englishChoices: ["double", "single", "broken", "hidden"],
    intermediate: "Cette mission a un _____ objectif : réparer le pont et former les ouvriers.", frenchChoices: ["double", "unique", "simple", "seul"],
    advanced: "Le projet poursuit un double but : réduire le bruit et améliorer la sécurité. Nina mesure les sons, Paul vérifie les portes et Léa rédige le rapport.",
    prompt: "Quel mot indique que le projet comporte deux objectifs ?", advancedChoices: ["double", "bruit", "sécurité", "rapport"],
  },
};
