import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch16: Record<string, EditorialQuizSet> = {
  "dès:des_from": {
    early: "Dès huit heures, la bibliothèque ouvre ses portes.", englishChoices: ["from", "until", "before", "during"],
    intermediate: "_____ son arrivée, Nina commence à préparer la salle.", frenchChoices: ["dès", "avant", "pendant", "malgré"],
    advanced: "La boulangerie vend du pain dès six heures, au premier moment de son ouverture. Paul arrive avant midi, Nina travaille pendant la matinée et Luc reste jusqu’au soir.",
    prompt: "Quel mot marque le point de départ immédiat des ventes ?", advancedChoices: ["dès", "avant", "pendant", "jusqu’au"],
  },
  "désastre:desastre_disaster": {
    early: "L’inondation est un désastre qui a détruit cent maisons.", englishChoices: ["disaster", "celebration", "improvement", "routine"],
    intermediate: "Le séisme a détruit la ville et fait des milliers de victimes : quel _____ !", frenchChoices: ["désastre", "succès", "plaisir", "progrès"],
    advanced: "Le désastre a laissé le village sous l’eau et détruit toutes les routes. Les pompiers évacuent les habitants, Nina distribue des couvertures et Paul appelle les secours.",
    prompt: "Quel mot désigne l’événement qui a causé ces graves dommages ?", advancedChoices: ["désastre", "village", "routes", "secours"],
  },
  "désastres:desastre_disaster": {
    early: "Les deux séismes furent des désastres qui détruisirent plusieurs villes.", englishChoices: ["disasters", "celebrations", "improvements", "routines"],
    intermediate: "Ces incendies ont ravagé deux régions : ce sont de véritables _____.", frenchChoices: ["désastres", "succès", "plaisirs", "progrès"],
    advanced: "Les désastres successifs ont détruit les récoltes puis emporté le pont. Les habitants reconstruisent les maisons, Nina soigne les blessés et Paul dégage la route.",
    prompt: "Quel mot désigne les événements ayant causé de très graves dommages ?", advancedChoices: ["désastres", "récoltes", "pont", "maisons"],
  },
  "déserts:desert_deserted": {
    early: "À minuit, les quais déserts ne comptent plus aucun voyageur.", englishChoices: ["deserted", "crowded", "noisy", "welcoming"],
    intermediate: "Après l’évacuation, les villages sont _____ : plus personne n’y habite.", frenchChoices: ["déserts", "peuplés", "animés", "bondés"],
    advanced: "Les couloirs déserts de l’école sont vides pendant les vacances. Les salles sont fermées, les bureaux restent propres et le jardinier travaille dehors.",
    prompt: "Quel mot indique qu’aucune personne ne se trouve dans les couloirs ?", advancedChoices: ["déserts", "fermées", "propres", "dehors"],
  },
  "désespérance:desesperance_despair": {
    early: "Après des mois sans nouvelle, la famille sombre dans la désespérance.", englishChoices: ["despair", "confidence", "joy", "relief"],
    intermediate: "Persuadé que tout secours est impossible, il tombe dans une profonde _____.", frenchChoices: ["désespérance", "confiance", "joie", "sérénité"],
    advanced: "La désespérance gagne Paul lorsqu’il pense que son frère ne reviendra jamais. Nina cherche encore des renseignements, Léa écrit aux autorités et Marc attend près du téléphone.",
    prompt: "Quel mot désigne la perte profonde de tout espoir chez Paul ?", advancedChoices: ["désespérance", "renseignements", "autorités", "téléphone"],
  },
  "désespère:desesperer_lose_hope": {
    early: "Après dix refus, Paul désespère de trouver un logement.", englishChoices: ["despairs", "rejoices", "persists confidently", "celebrates"],
    intermediate: "Sans aucune réponse depuis des mois, Nina _____ de revoir son dossier accepté.", frenchChoices: ["désespère", "se réjouit", "triomphe", "espère"],
    advanced: "Léa désespère de retrouver son chien après des semaines de recherches inutiles. Paul imprime encore des affiches, Nina appelle les refuges et Marc parcourt le quartier.",
    prompt: "Quel mot indique que Léa perd tout espoir de retrouver son chien ?", advancedChoices: ["désespère", "imprime", "appelle", "parcourt"],
  },
  "désespérée:desespere_desperate": {
    early: "Après l’échec de toutes les recherches, la famille désespérée ne sait plus vers qui se tourner.", englishChoices: ["desperate", "confident", "cheerful", "indifferent"],
    intermediate: "N’ayant plus aucun espoir de secours, elle paraît _____.", frenchChoices: ["désespérée", "confiante", "joyeuse", "indifférente"],
    advanced: "Nina, désespérée après des mois sans nouvelle, éclate en sanglots. Paul consulte les dossiers, Léa ferme la fenêtre et Marc apporte une chaise.",
    prompt: "Quel mot qualifie Nina comme ayant perdu tout espoir ?", advancedChoices: ["désespérée", "dossiers", "fenêtre", "chaise"],
  },
  "déshonore:deshonorer_disgrace": {
    early: "En trahissant ses collègues pour de l’argent, il déshonore son équipe.", englishChoices: ["disgraces", "honors", "protects", "rewards"],
    intermediate: "Son mensonge public _____ toute sa famille en lui faisant perdre le respect du village.", frenchChoices: ["déshonore", "honore", "protège", "récompense"],
    advanced: "Le directeur déshonore sa fonction lorsqu’il accepte secrètement de l’argent. Nina révèle les reçus, Paul informe le conseil et Léa ferme le bureau.",
    prompt: "Quel mot indique qu’il fait perdre sa considération à sa fonction ?", advancedChoices: ["déshonore", "révèle", "informe", "ferme"],
  },
  "désiré:desirer_want": {
    early: "Après des années d’efforts, Paul obtient enfin le poste désiré.", englishChoices: ["desired", "refused", "forgotten", "unexpected"],
    intermediate: "Elle a longtemps souhaité cette promotion et obtient enfin le poste _____.", frenchChoices: ["désiré", "refusé", "oublié", "imposé"],
    advanced: "Le résultat désiré par Nina est une réduction du bruit dans sa rue. Paul mesure les niveaux sonores, Léa consulte les voisins et Marc rédige un rapport.",
    prompt: "Quel mot indique que Nina souhaitait obtenir ce résultat ?", advancedChoices: ["désiré", "mesure", "consulte", "rédige"],
  },
  "désormais:desormais_henceforth": {
    early: "Le pont est réparé ; désormais, les bus peuvent de nouveau le traverser.", englishChoices: ["from now on", "previously", "rarely", "elsewhere"],
    intermediate: "La nouvelle règle entre en vigueur aujourd’hui ; _____, chacun devra présenter sa carte.", frenchChoices: ["désormais", "autrefois", "rarement", "ailleurs"],
    advanced: "Désormais, Nina travaillera le matin au lieu du soir : ce nouvel horaire commence aujourd’hui. Paul viendra demain, Léa travaillait autrefois ici et Marc attend dehors.",
    prompt: "Quel mot signifie « à partir de maintenant » ?", advancedChoices: ["désormais", "demain", "autrefois", "dehors"],
  },
  "détails:detail_particular": {
    early: "Le rapport donne tous les détails de l’accident, notamment l’heure et le lieu.", englishChoices: ["details", "summaries", "titles", "questions"],
    intermediate: "Explique-moi les _____ précis du voyage : l’heure, l’adresse et le prix.", frenchChoices: ["détails", "résumés", "titres", "silences"],
    advanced: "Les détails du contrat précisent la date, le montant et les obligations de chacun. Nina lit le titre, Paul ferme le dossier et Léa appelle l’avocat.",
    prompt: "Quel mot regroupe les éléments particuliers du contrat ?", advancedChoices: ["détails", "titre", "dossier", "avocat"],
  },
  "détresse:detresse_distress": {
    early: "Perdue seule dans la montagne, Nina appelle les secours dans une grande détresse.", englishChoices: ["distress", "delight", "calm", "confidence"],
    intermediate: "Sans abri après l’incendie, la famille exprime sa profonde _____.", frenchChoices: ["détresse", "joie", "sérénité", "confiance"],
    advanced: "La détresse de Paul est profonde depuis qu’un incendie a détruit sa maison. Nina lui trouve un abri, Léa apporte des vêtements et Marc prépare un repas.",
    prompt: "Quel mot désigne l’angoisse profonde de Paul dans cette situation douloureuse ?", advancedChoices: ["détresse", "abri", "vêtements", "repas"],
  },
  "dettes:dette_debt": {
    early: "Paul doit encore mille euros à la banque : ses dettes augmentent.", englishChoices: ["debts", "savings", "gifts", "wages"],
    intermediate: "Elle doit rembourser plusieurs sommes à ses créanciers : ses _____ sont lourdes.", frenchChoices: ["dettes", "économies", "récompenses", "salaires"],
    advanced: "Les dettes de Marc comprennent un prêt bancaire et trois factures impayées. Nina vérifie ses économies, Paul classe les reçus et Léa prépare le budget.",
    prompt: "Quel mot désigne les sommes que Marc doit encore payer ?", advancedChoices: ["dettes", "économies", "reçus", "budget"],
  },
  "devait:devoir_obligation": {
    early: "Pour respecter le contrat, Paul devait remettre le dossier avant lundi.", englishChoices: ["had to", "wanted to", "managed to", "refused to"],
    intermediate: "Selon les règles, elle _____ présenter sa carte avant d’entrer.", frenchChoices: ["devait", "voulait", "pouvait", "refusait"],
    advanced: "Nina devait terminer le rapport vendredi parce que son contrat l’y obligeait. Paul classait les lettres, Léa ouvrait le bureau et Marc attendait la réponse.",
    prompt: "Quel mot exprime l’obligation imposée à Nina ?", advancedChoices: ["devait", "classait", "ouvrait", "attendait"],
  },
  "devant:devant_before": {
    early: "Le témoin parle devant le juge, en sa présence.", englishChoices: ["before", "behind", "under", "beside"],
    intermediate: "Les manifestants se rassemblent _____ la mairie, juste en face de l’entrée.", frenchChoices: ["devant", "derrière", "sous", "dans"],
    advanced: "Paul attend devant la gare, face à l’entrée principale. Nina se tient derrière le bâtiment, Léa passe sous le pont et Marc travaille dans le café.",
    prompt: "Quel mot situe Paul en face de l’entrée de la gare ?", advancedChoices: ["devant", "derrière", "sous", "dans"],
  },
  "devenir:devenir_become": {
    early: "Après sa formation, Léa souhaite devenir médecin.", englishChoices: ["to become", "to remain", "to leave", "to forget"],
    intermediate: "Avec le froid, l’eau va _____ solide et former de la glace.", frenchChoices: ["devenir", "rester", "quitter", "oublier"],
    advanced: "Paul veut devenir professeur après ses études et passer ainsi d’étudiant à enseignant. Nina cherche un emploi, Léa prépare le dîner et Marc ferme la fenêtre.",
    prompt: "Quel verbe exprime le passage de Paul à un nouvel état professionnel ?", advancedChoices: ["devenir", "cherche", "prépare", "ferme"],
  },
  "devenu:devenir_become": {
    early: "Après dix ans de pratique, Paul est devenu un excellent cuisinier.", englishChoices: ["became", "remained", "left", "forgot"],
    intermediate: "Avec les années, ce petit village est _____ une grande ville.", frenchChoices: ["devenu", "resté", "quitté", "oublié"],
    advanced: "L’ancien atelier est devenu une bibliothèque après les travaux. Nina classe les livres, Paul nettoie les tables et Léa ouvre les fenêtres.",
    prompt: "Quel mot indique que l’atelier s’est transformé en bibliothèque ?", advancedChoices: ["devenu", "classe", "nettoie", "ouvre"],
  },
  "devient:devenir_become": {
    early: "Quand la température baisse, l’eau devient solide.", englishChoices: ["becomes", "remains", "leaves", "disappears"],
    intermediate: "À force de pluie, le chemin _____ boueux et difficile à traverser.", frenchChoices: ["devient", "reste", "quitte", "disparaît"],
    advanced: "Le ciel devient sombre à l’approche de l’orage, passant du bleu au gris. Nina ferme les volets, Paul rentre le vélo et Léa appelle les enfants.",
    prompt: "Quel mot indique le changement d’état du ciel ?", advancedChoices: ["devient", "ferme", "rentre", "appelle"],
  },
  "devoir:devoir_obligation": {
    early: "Pour entrer, chaque visiteur va devoir présenter son billet.", englishChoices: ["to have to", "to want to", "to be able to", "to refuse to"],
    intermediate: "À cause de cette règle, Paul va _____ porter un casque sur le chantier.", frenchChoices: ["devoir", "vouloir", "pouvoir", "refuser"],
    advanced: "Nina va devoir remettre le dossier avant midi, car le règlement l’exige. Paul prépare les copies, Léa ouvre le guichet et Marc vérifie l’adresse.",
    prompt: "Quel verbe exprime l’obligation imposée à Nina ?", advancedChoices: ["devoir", "prépare", "ouvre", "vérifie"],
  },
  "devoir:devoir_duty": {
    early: "Aider les personnes en danger est un devoir moral.", englishChoices: ["duty", "reward", "privilege", "hobby"],
    intermediate: "Comme médecin, soigner les blessés est son _____ professionnel.", frenchChoices: ["devoir", "loisir", "cadeau", "privilège"],
    advanced: "Le devoir de Paul comme sauveteur est de porter secours aux nageurs en danger. Nina surveille la plage, Léa range le matériel et Marc ferme le poste.",
    prompt: "Quel mot désigne l’obligation morale et professionnelle de Paul ?", advancedChoices: ["devoir", "plage", "matériel", "poste"],
  },
  "devons:devoir_obligation": {
    early: "Nous devons porter un casque, car le règlement l’exige.", englishChoices: ["must", "want to", "can", "refuse to"],
    intermediate: "Pour respecter la date limite, nous _____ envoyer le dossier aujourd’hui.", frenchChoices: ["devons", "voulons", "pouvons", "refusons"],
    advanced: "Nous devons quitter la salle à dix-huit heures, selon le règlement. Paul range les chaises, Nina ferme les fenêtres et Léa vérifie les lumières.",
    prompt: "Quel mot exprime notre obligation de partir ?", advancedChoices: ["devons", "range", "ferme", "vérifie"],
  },
  "dévoré:devorer_consume": {
    early: "Le feu a dévoré la forêt et détruit tous les arbres sur son passage.", englishChoices: ["consumed", "protected", "watered", "repaired"],
    intermediate: "Affamé, le chien a _____ tout son repas en quelques secondes.", frenchChoices: ["dévoré", "protégé", "laissé", "préparé"],
    advanced: "L’incendie a dévoré le vieux hangar en moins d’une heure. Les pompiers ont protégé la maison, Nina a fermé la route et Paul a appelé les secours.",
    prompt: "Quel mot indique que le feu a détruit le hangar avec intensité ?", advancedChoices: ["dévoré", "protégé", "fermé", "appelé"],
  },
  "dévotement:devotement_devoutly": {
    early: "Chaque matin, elle prie dévotement avec une profonde ferveur religieuse.", englishChoices: ["devoutly", "mockingly", "carelessly", "indifferently"],
    intermediate: "Le fidèle s’agenouille et prie _____ devant l’autel.", frenchChoices: ["dévotement", "ironiquement", "négligemment", "indifféremment"],
    advanced: "Nina prie dévotement dans la chapelle, avec recueillement et ferveur. Paul attend dehors, Léa lit un livre et Marc regarde l’horloge.",
    prompt: "Quel mot qualifie la manière fervente et religieuse de prier ?", advancedChoices: ["dévotement", "dehors", "livre", "horloge"],
  },
  "devrait:devoir_obligation": {
    early: "Pour éviter une amende, Paul devrait payer avant vendredi.", englishChoices: ["should", "would like to", "could", "would refuse to"],
    intermediate: "Selon le médecin, Nina _____ se reposer pendant quelques jours.", frenchChoices: ["devrait", "voudrait", "pourrait", "refuserait"],
    advanced: "Léa devrait porter un casque sur le chantier pour respecter les règles de sécurité. Paul vérifie les outils, Nina ouvre le portail et Marc consulte le plan.",
    prompt: "Quel mot exprime ce que les règles imposent normalement à Léa ?", advancedChoices: ["devrait", "vérifie", "ouvre", "consulte"],
  },
  "diabolique:diabolique_evil": {
    early: "Le criminel imagine un plan diabolique pour faire souffrir des innocents.", englishChoices: ["diabolical", "kind", "harmless", "generous"],
    intermediate: "Ce projet conçu pour nuire volontairement à des familles est _____.", frenchChoices: ["diabolique", "bienveillant", "inoffensif", "généreux"],
    advanced: "Le plan diabolique du dirigeant vise à ruiner volontairement ses adversaires et leurs familles. Nina révèle les documents, Paul avertit la presse et Léa appelle un avocat.",
    prompt: "Quel mot qualifie la méchanceté extrême du plan ?", advancedChoices: ["diabolique", "documents", "presse", "avocat"],
  },
  "dicter:dicter_dictate": {
    early: "La professeure va dicter une phrase que les élèves devront écrire mot à mot.", englishChoices: ["to dictate", "to erase", "to translate", "to memorize"],
    intermediate: "Parlez lentement pour _____ l’adresse pendant que je l’écris.", frenchChoices: ["dicter", "effacer", "traduire", "mémoriser"],
    advanced: "Nina va dicter la lettre à Paul, qui l’écrira exactement sous sa parole. Léa ouvre l’enveloppe, Marc cherche un timbre et Luc ferme la fenêtre.",
    prompt: "Quel verbe signifie prononcer le texte pour que Paul l’écrive ?", advancedChoices: ["dicter", "ouvre", "cherche", "ferme"],
  },
};
