import type { ZolaVocabularySpec } from "./zola-authoring.js";

type Kind = "noun" | "adjective" | "verb" | "adverb" | "determiner" | "pronoun";

const make = (
  normalized: string,
  lemmaKey: string,
  candidateIds: readonly string[],
  partOfSpeech: Kind,
  senseKey: string,
  headword: string,
  gloss: string,
  definition: string,
  englishDistractors: [string, string, string],
  frenchDistractors: [string, string, string],
  existingLemmaId?: string,
  existingSenseId?: string,
): ZolaVocabularySpec => {
  const spec: ZolaVocabularySpec = {
    normalized,
    candidateIds,
    lemmaKey,
    headword,
    partOfSpeech,
    senseKey,
    gloss,
    quizMeaning: gloss,
    definition,
    englishDistractors,
    frenchDistractors,
  };
  if (existingLemmaId !== undefined) spec.existingLemmaId = existingLemmaId;
  if (existingSenseId !== undefined) spec.existingSenseId = existingSenseId;
  return spec;
};

export const zolaVocabularyBatch46: ZolaVocabularySpec[] = [
  make(
    "rendu",
    "rendre",
    ["tok_81f84d278e150e54886d4fe8"],
    "verb",
    "rendre_judgment",
    "rendre",
    "rendered; issued",
    "participe passé de rendre, dans l’expression rendre une sentence",
    ["hidden", "forgotten", "refused"],
    ["caché", "oublié", "refusé"],
  ),
  make(
    "rendu",
    "rendre",
    ["tok_91d2d036cd0904fe469c69ad", "tok_3486ccdbc9c2e83a28604ae5"],
    "verb",
    "rendre_become",
    "rendre",
    "become; made oneself",
    "participe passé pronominal de se rendre, indiquant le fait de devenir complice ou coupable",
    ["remained", "appeared", "returned"],
    ["resté", "paru", "revenu"],
  ),
  make(
    "romans-feuilletons",
    "roman-feuilleton",
    ["tok_0609b39f9191fcf2e81f0ede", "tok_d8f6de7ce9c25b45937e9aa2"],
    "noun",
    "roman_feuilleton_serials",
    "roman-feuilleton",
    "serial novels",
    "romans publiés par épisodes dans les journaux",
    ["legal proceedings", "military orders", "private letters"],
    ["procès", "ordres militaires", "lettres privées"],
  ),
  make(
    "visage",
    "visage",
    ["tok_0c39f47d164bbd339ed6140c", "tok_50e058e18d99d8739baac3d0"],
    "noun",
    "visage_face",
    "visage",
    "face",
    "partie antérieure de la tête humaine, ou expression visible de cette personne",
    ["body", "name", "voice"],
    ["corps", "nom", "voix"],
  ),
  make(
    "surprendre",
    "surprendre",
    ["tok_1a51ce6e13958aa103ac5c4c", "tok_8d3328bbb3bf386e584cb1e2"],
    "verb",
    "surprendre_catch_unawares",
    "surprendre",
    "surprise; catch unawares",
    "prendre quelqu’un au dépourvu ou découvrir quelqu’un dans une action secrète",
    ["to defend", "to accuse", "to recognize"],
    ["défendre", "accuser", "reconnaître"],
  ),
  make(
    "quelque",
    "quelque",
    ["tok_0adc192121679c5c963fa746", "tok_165c9e15bc54bcd0d78c432b"],
    "determiner",
    "quelque_indefinite",
    "quelque",
    "some; a certain",
    "détermine un nom en indiquant une quantité ou une personne indéterminée",
    ["each", "no", "many"],
    ["maint", "certain", "tel"],
  ),
  make(
    "renseignements",
    "renseignement",
    ["tok_0367795cc1ac1525881feb6f", "tok_f7037295880851d6d0bb8cf1"],
    "noun",
    "renseignement_information",
    "renseignement",
    "information; intelligence",
    "informations recueillies au sujet d’une affaire ou d’une personne",
    ["celebrations", "punishments", "buildings"],
    ["célébrations", "châtiments", "bâtiments"],
  ),
  make(
    "tombe",
    "tomber",
    ["tok_0eea5ee78c2bf042dfe2cb7a", "tok_3e01e2ca0ee86c8885801a54"],
    "verb",
    "tomber_primary",
    "tomber",
    "falls",
    "forme du présent de tomber, indiquant une chute ou une dégradation",
    ["rises", "waits", "shines"],
    ["monte", "attend", "brille"],
    "lem_tomber",
    "sns_tomber_primary",
  ),
  make(
    "seule",
    "seul",
    ["tok_49d119b7761250df2388e96f", "tok_987ca7498158e2d3ffad593d"],
    "adjective",
    "seul_only",
    "seul",
    "only; single",
    "qui est unique ou isolé, sans autre élément du même type",
    ["large", "ancient", "secret"],
    ["grande", "ancienne", "secrète"],
  ),
  make(
    "trahison",
    "trahison",
    ["tok_34b1b035f075c90c2868b42b", "tok_38372f4361d37a85be2e630a"],
    "noun",
    "trahison_betrayal",
    "trahison",
    "betrayal; treason",
    "fait de trahir une personne, un groupe ou son pays",
    ["alliance", "acquittal", "celebration"],
    ["alliance", "acquittement", "célébration"],
  ),
  make(
    "secrets",
    "secret_noun",
    ["tok_1956ac243b8d2982d64486f0", "tok_5e0e4eb61b4e7d7482b0f21f"],
    "noun",
    "secret_noun",
    "secret_adjective",
    "secrets",
    "informations tenues cachées et connues de peu de personnes",
    ["public statements", "open doors", "ordinary duties"],
    ["déclarations publiques", "portes ouvertes", "devoirs ordinaires"],
  ),
  make(
    "sortir",
    "sortir",
    ["tok_3382e1bb0678cd9c50d46687"],
    "verb",
    "sortir_emerge",
    "sortir",
    "emerge; come out",
    "venir au-dehors ou apparaître à partir d’un lieu ou d’une situation",
    ["to enter", "to sleep", "to disappear"],
    ["entrer", "dormir", "disparaître"],
  ),
  make(
    "sortir",
    "sortir",
    ["tok_b8e2f0fc662eecb68dbe26ab"],
    "verb",
    "sortir_leave",
    "sortir",
    "get out; leave",
    "quitter un lieu ou en faire sortir quelqu’un",
    ["to remain", "to close", "to hide"],
    ["rester", "fermer", "cacher"],
  ),
  make(
    "vrai",
    "vrai",
    ["tok_fca32b4db98f5e70c095d67d", "tok_237a00842bfb2d70ccbe150c"],
    "adjective",
    "vrai_true",
    "vrai",
    "true; real",
    "conforme à la réalité ou à la vérité",
    ["false", "ancient", "distant"],
    ["faux", "ancien", "lointain"],
  ),
  make(
    "responsabilité",
    "responsabilite",
    ["tok_401b32ac86e50095619a3de9", "tok_206db9a05931d7a7b654eec2"],
    "noun",
    "responsabilite_accountability",
    "responsabilité",
    "responsibility; accountability",
    "obligation de répondre d’un acte, d’une faute ou d’une mission",
    ["innocence", "authority", "fortune"],
    ["innocence", "autorité", "fortune"],
  ),
  make(
    "sottise",
    "sottise",
    ["tok_3fbce26358f7242b6c6257b5", "tok_d8e4d8c17b1a021e6b8e529d"],
    "noun",
    "sottise_foolishness",
    "sottise",
    "foolishness; silly act",
    "parole ou action déraisonnable et dépourvue de bon sens",
    ["wisdom", "calm", "justice"],
    ["sagesse", "calme", "justice"],
  ),
  make(
    "voici",
    "voici",
    ["tok_5db0b12a96275a918eecd863", "tok_779121383cfedf7322ce7261"],
    "adverb",
    "voici_presentative",
    "voici",
    "here is; behold",
    "présente vivement une personne, une chose ou une durée",
    ["perhaps", "therefore", "elsewhere"],
    ["peut-être", "ainsi", "ailleurs"],
  ),
  make(
    "stupeur",
    "stupeur",
    ["tok_916addd8755e0997a910d96d", "tok_2bb2e1c93107c8e36b6b39f5"],
    "noun",
    "stupeur_shock",
    "stupeur",
    "stupor; astonishment",
    "état de saisissement qui laisse momentanément sans réaction",
    ["laughter", "patience", "certainty"],
    ["rire", "patience", "certitude"],
  ),
  make(
    "publique",
    "public",
    ["tok_72d7f20b5752fbc03c812e9a", "tok_0cd7dec9409fb391a135a7ab"],
    "adjective",
    "public_accessible",
    "public",
    "public; open to society",
    "qui concerne la collectivité ou est connu de tous",
    ["private", "military", "ancient"],
    ["privée", "militaire", "ancienne"],
  ),
  make(
    "remords",
    "remords",
    ["tok_0a8faba3b7cf4c77026925f0", "tok_c4906cf641eb25eae2f099cb"],
    "noun",
    "remords_regret",
    "remords",
    "remorse",
    "regret douloureux d’avoir commis une faute",
    ["pride", "silence", "happiness"],
    ["fierté", "silence", "bonheur"],
  ),
  make(
    "suffit",
    "suffire",
    ["tok_9876035f91b6e43816ea2800", "tok_686bef0f7be20eb66f1f0f42"],
    "verb",
    "suffire_present",
    "suffire",
    "is enough; suffices",
    "forme du présent de suffire, indiquant qu’une chose est assez efficace ou importante",
    ["permits", "begins", "fails"],
    ["permet", "commence", "échoue"],
  ),
  make(
    "sait",
    "savoir",
    ["tok_28f5ed3b22d1a3bfec3cefa6", "tok_7fc74c959e9861bf8e905cbb"],
    "verb",
    "savoir_present",
    "savoir",
    "knows",
    "forme du présent de savoir, indiquant qu’une personne possède une connaissance",
    ["sees", "believes", "ignores"],
    ["voit", "croit", "ignore"],
    "lem_savoir",
  ),
  make(
    "trouvé",
    "trouver",
    ["tok_ddcfe41e235391172206ff84", "tok_b09ccb5266d56e8823f02ba8"],
    "verb",
    "trouver_past",
    "trouver",
    "found",
    "participe passé de trouver, indiquant qu’une personne ou une chose a été découverte",
    ["lost", "hidden", "forgotten"],
    ["perdu", "caché", "oublié"],
  ),
  make(
    "trouble",
    "troubler",
    ["tok_b5ab2af71664b97eeb6f5704", "tok_ad1fd9459d7217270d1018af"],
    "verb",
    "troubler_reflexive",
    "troubler",
    "become disturbed",
    "forme pronominale de troubler, indiquant une agitation ou une perte de calme",
    ["calms", "laughs", "waits"],
    ["se calme", "rit", "attend"],
  ),
  make(
    "témoignages",
    "témoignage",
    ["tok_7ce0da5b93af084bccabd316", "tok_b321d2eee80345d50e98b34a"],
    "noun",
    "temoignage_evidence",
    "témoignage",
    "testimonies; evidence",
    "déclarations de personnes qui rapportent ce qu’elles ont vu ou savent",
    ["accusations", "orders", "celebrations"],
    ["accusations", "ordres", "célébrations"],
  ),
  make(
    "seconde",
    "second",
    ["tok_c61098d169ca2b7408cdb724", "tok_59a4144e7a6f4cb31beb46ac"],
    "adjective",
    "second_ordinal_feminine",
    "second",
    "second; occurring again",
    "qui vient après le premier ou qui se produit une nouvelle fois",
    ["first", "final", "different"],
    ["première", "finale", "différente"],
  ),
  make(
    "restait",
    "rester",
    ["tok_c51e0e913e3e0053a367bb73", "tok_8211df167ba0f8cdf5c91093"],
    "verb",
    "rester_imperfect",
    "rester",
    "remained; was left",
    "forme de l’imparfait de rester, indiquant la permanence ou ce qui subsistait",
    ["departed", "changed", "disappeared"],
    ["partait", "changeait", "disparaissait"],
  ),
  make(
    "secrète",
    "secret",
    ["tok_ce04d4e16c9bf85d057d578a", "tok_a41388a2dd219ffc7a1566ce"],
    "adjective",
    "secret_adjective",
    "secret",
    "secret; concealed",
    "qui est tenu caché et n’est pas destiné à être révélé",
    ["public", "visible", "distant"],
    ["publique", "visible", "lointaine"],
  ),
  make(
    "puissance",
    "puissance",
    ["tok_f46af6958da2fd6d6c8e7810", "tok_68b4846939bc1300e9e7e2b5"],
    "noun",
    "puissance_power",
    "puissance",
    "power; might",
    "force ou autorité dont dispose une personne, une institution ou un État",
    ["weakness", "silence", "distance"],
    ["faiblesse", "silence", "distance"],
  ),
  make(
    "trop",
    "trop",
    ["tok_44a19dc6d40a950ec24477e4", "tok_83e69821b092647f91a41b19"],
    "adverb",
    "trop_excess",
    "trop",
    "too; excessively",
    "marque un degré qui dépasse la mesure convenable",
    ["quite", "hardly", "suddenly"],
    ["assez", "peu", "soudainement"],
  ),
  make(
    "situation",
    "situation",
    ["tok_b5804edcb06d1d276a15a714", "tok_9f3fe8d1ccc4d682010d9b10"],
    "noun",
    "situation_circumstance",
    "situation",
    "situation; circumstances",
    "état ou ensemble de circonstances dans lesquels se trouve une personne ou une affaire",
    ["solution", "journey", "language"],
    ["solution", "voyage", "langue"],
  ),
  make(
    "victime",
    "victime",
    ["tok_998ce488a5ee451d3f68f375", "tok_4277e2b0f1b68b46a2015fcc"],
    "noun",
    "victime_sufferer",
    "victime",
    "victim",
    "personne qui subit un dommage, une injustice ou une persécution",
    ["judge", "author", "witness"],
    ["juge", "auteur", "témoin"],
  ),
  make(
    "succédé",
    "succéder",
    ["tok_05da670f26f78cb5e02bfa1e", "tok_3e61d9984640c4d2f2586f49"],
    "verb",
    "succeder_replace",
    "succéder",
    "succeeded; replaced",
    "participe passé de succéder, indiquant qu’une personne a pris la place d’une autre",
    ["preceded", "ignored", "followed"],
    ["précédé", "ignoré", "suivi"],
  ),
  make(
    "tant",
    "tant",
    ["tok_a65db44e3dc54b571b1325a4", "tok_1357425b14818ef7e56f1223"],
    "adverb",
    "tant_degree",
    "tant",
    "so much; so greatly",
    "marque une grande quantité ou une grande intensité",
    ["slightly", "never", "silently"],
    ["légèrement", "jamais", "silencieusement"],
  ),
  make(
    "terrible",
    "terrible",
    ["tok_c328b92ad5e4aab6d6626218", "tok_000d03ea465160b578c6ecb7"],
    "adjective",
    "terrible_frightening",
    "terrible",
    "terrible; dreadful",
    "qui inspire une grande peur ou annonce un malheur",
    ["peaceful", "ordinary", "brilliant"],
    ["paisible", "ordinaire", "brillant"],
  ),
  make(
    "public",
    "public",
    ["tok_b13e74e2a250b7fe3cedfe0c", "tok_4a902fd847811428179c37a8"],
    "adjective",
    "public_accessible",
    "public",
    "public; open to society",
    "qui concerne la collectivité ou est connu de tous",
    ["private", "military", "ancient"],
    ["privé", "militaire", "ancien"],
  ),
  make(
    "sûrement",
    "sûrement",
    ["tok_d0d1d122975e89fb1c7bf928", "tok_bab15039bd4a2e9bdd68d7d3"],
    "adverb",
    "surement_certainty",
    "sûrement",
    "surely; certainly",
    "d’une manière tenue pour certaine ou très probable",
    ["quietly", "suddenly", "elsewhere"],
    ["calmement", "soudainement", "ailleurs"],
  ),
  make(
    "sauver",
    "sauver",
    ["tok_732b4bec5890d6f71d50f5a6", "tok_23e71658eebb6568d04860cc"],
    "verb",
    "sauver_protect",
    "sauver",
    "save; rescue",
    "mettre quelqu’un ou quelque chose à l’abri d’un danger ou d’une perte",
    ["to abandon", "to accuse", "to conceal"],
    ["abandonner", "accuser", "cacher"],
  ),
  make(
    "toujours",
    "toujours",
    ["tok_0163e9c2dee5ba712204b604", "tok_683cd80ba18d3e7ee451d528"],
    "adverb",
    "toujours_always",
    "toujours",
    "always; continually",
    "à tout moment ou de façon constante",
    ["elsewhere", "together", "suddenly"],
    ["ailleurs", "ensemble", "soudainement"],
  ),
  make(
    "veut",
    "vouloir",
    ["tok_1d878fe8bad958cd884c1392", "tok_f077aa413a423129489453a2"],
    "verb",
    "vouloir_present_third",
    "vouloir",
    "wants",
    "forme du présent de vouloir exprimant la volonté d’une personne",
    ["can", "must", "believes"],
    ["peut", "doit", "croit"],
  ),
  make(
    "lui-même",
    "lui-même",
    ["tok_054851edd26c17df9b3a1ad1", "tok_66545b7f7d8744694842a626"],
    "pronoun",
    "lui_meme_emphatic",
    "lui-même",
    "himself; itself",
    "pronom tonique qui insiste sur l’identité de la personne ou de la chose",
    ["herself", "themselves", "someone else"],
    ["elle-même", "eux-mêmes", "quelqu’un d’autre"],
  ),
  make(
    "reconnaître",
    "reconnaître",
    ["tok_b565b3251f3373ce258ef839", "tok_c2c8417808267ac2d37dec83"],
    "verb",
    "reconnaitre_acknowledge",
    "reconnaître",
    "recognize; acknowledge",
    "admettre la réalité, l’identité ou la validité de quelqu’un ou de quelque chose",
    ["to deny", "to hide", "to forget"],
    ["nier", "cacher", "oublier"],
  ),
  make(
    "prendre",
    "prendre",
    ["tok_78a390c5ed8d1b6731656706"],
    "verb",
    "prendre_trick",
    "prendre",
    "be taken in; be caught",
    "être trompé ou pris dans une machination",
    ["to escape", "to forgive", "to illuminate"],
    ["s’échapper", "pardonner", "éclairer"],
    "lem_prendre",
    "sns_prendre_primary",
  ),
  make(
    "prendre",
    "prendre",
    ["tok_771a0c6012c82d2fe312b65d"],
    "verb",
    "prendre_charge",
    "prendre",
    "take charge of; take up",
    "s’occuper activement d’une affaire ou l’assumer",
    ["to abandon", "to conceal", "to postpone"],
    ["abandonner", "cacher", "reporter"],
    "lem_prendre",
  ),
];
