import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a teapot", "a staircase", "a violin"];
const nounFrench: [string, string, string] = ["une théière", "un escalier", "un violon"];
const adjectiveEnglish: [string, string, string] = ["striped", "mint-flavored", "triangular"];
const adjectiveFrench: [string, string, string] = ["rayé", "aromatisé à la menthe", "triangulaire"];
const verbEnglish: [string, string, string] = ["to embroider", "to whistle", "to float"];
const verbFrench: [string, string, string] = ["broder", "siffler", "flotter"];

export const zolaVocabularyBatch24: ZolaVocabularySpec[] = [
  { normalized: "faits", lemmaKey: "fait_noun", headword: "fait", partOfSpeech: "noun", senseKey: "fait_event", gloss: "fact; event", quizMeaning: "facts; events", definition: "événement réel ou élément établi", englishDistractors: ["teapots", "staircases", "violins"], frenchDistractors: ["théières", "escaliers", "violons"] },
  { normalized: "force", lemmaKey: "force", headword: "force", partOfSpeech: "noun", senseKey: "force_power", gloss: "strength; force", definition: "puissance physique, morale ou dynamique capable de produire un effet", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "forcément", lemmaKey: "forcement", headword: "forcément", partOfSpeech: "adverb", senseKey: "forcement_necessarily", gloss: "necessarily; inevitably", definition: "d’une manière nécessaire ou inévitable", englishDistractors: ["silently", "upstairs", "yesterday"], frenchDistractors: ["silencieusement", "à l’étage", "hier"] },
  { normalized: "formel", lemmaKey: "formel", headword: "formel", partOfSpeech: "adjective", senseKey: "formel_explicit", gloss: "formal; categorical", definition: "exprimé d’une manière nette, précise et sans réserve", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "formelles", lemmaKey: "formel", headword: "formel", partOfSpeech: "adjective", senseKey: "formel_explicit", gloss: "formal; categorical", quizMeaning: "formal; categorical", definition: "exprimé d’une manière nette, précise et sans réserve", englishDistractors: ["striped", "mint-flavored", "triangular"], frenchDistractors: ["rayées", "aromatisées à la menthe", "triangulaires"] },
  { normalized: "fort", candidateIds: ["tok_c568b181a202f673035c0dfd"], lemmaKey: "fort", headword: "fort", partOfSpeech: "adjective", senseKey: "fort_confident", gloss: "confident; certain", definition: "assuré de pouvoir accomplir ce que l’on affirme", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "fort", candidateIds: ["tok_5422c91eab3081c6a7844294"], lemmaKey: "fort", headword: "fort", partOfSpeech: "adjective", senseKey: "fort_powerful", gloss: "strong; powerful", definition: "qui possède une grande puissance ou autorité", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "fortune", lemmaKey: "fortune", headword: "fortune", partOfSpeech: "noun", senseKey: "fortune_wealth", gloss: "fortune; wealth", definition: "ensemble des biens et des ressources d’une personne", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "fouillait", lemmaKey: "fouiller", headword: "fouiller", partOfSpeech: "verb", senseKey: "fouiller_investigate", gloss: "to search; investigate", quizMeaning: "was searching; was investigating", definition: "examiner avec soin afin de découvrir quelque chose", englishDistractors: ["was embroidering", "was whistling", "was floating"], frenchDistractors: ["brodait", "sifflait", "flottait"] },
  { normalized: "frais", lemmaKey: "frais", headword: "frais", partOfSpeech: "adjective", senseKey: "frais_new", gloss: "fresh; newly arrived", definition: "qui vient d’arriver et n’est pas encore mêlé aux événements", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "français", lemmaKey: "francais", headword: "français", partOfSpeech: "adjective", senseKey: "francais_of_france", gloss: "French", definition: "qui appartient ou se rapporte à la France", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "française", lemmaKey: "francais", headword: "français", partOfSpeech: "adjective", senseKey: "francais_of_france", gloss: "French", definition: "qui appartient ou se rapporte à la France", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayée", "aromatisée à la menthe", "triangulaire"] },
  { normalized: "frappe", lemmaKey: "frapper", headword: "frapper", partOfSpeech: "verb", senseKey: "frapper_strike", gloss: "to strike; attack", quizMeaning: "strikes; attacks", definition: "porter une atteinte violente ou infliger un coup", englishDistractors: ["embroiders", "whistles", "floats"], frenchDistractors: ["brode", "siffle", "flotte"] },
  { normalized: "frappée", lemmaKey: "frapper", headword: "frapper", partOfSpeech: "verb", senseKey: "frapper_strike", gloss: "to strike; attack", quizMeaning: "struck; overwhelmed", definition: "porter une atteinte violente ou infliger un coup", englishDistractors: ["embroidered", "whistled", "floated"], frenchDistractors: ["brodée", "sifflée", "flottée"] },
  { normalized: "frauduleux", lemmaKey: "frauduleux", headword: "frauduleux", partOfSpeech: "adjective", senseKey: "frauduleux_deceptive", gloss: "fraudulent; deceitful", definition: "entaché de fraude ou destiné à tromper", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "fripouille", lemmaKey: "fripouille", headword: "fripouille", partOfSpeech: "noun", senseKey: "fripouille_scoundrels", gloss: "scoundrel; rabble", definition: "personne malhonnête ou ensemble de gens méprisables", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "frontière", lemmaKey: "frontiere", headword: "frontière", partOfSpeech: "noun", senseKey: "frontiere_border", gloss: "border; frontier", definition: "limite séparant deux États ou territoires", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "fuite", lemmaKey: "fuite", headword: "fuite", partOfSpeech: "noun", senseKey: "fuite_escape", gloss: "flight; escape", definition: "action de s’échapper ou de se soustraire au danger", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "fuites", lemmaKey: "fuite", headword: "fuite", partOfSpeech: "noun", senseKey: "fuite_leak", gloss: "leak; disclosure", quizMeaning: "leaks; disclosures", definition: "divulgation clandestine d’informations ou de documents", englishDistractors: ["teapots", "staircases", "violins"], frenchDistractors: ["théières", "escaliers", "violons"] },
  { normalized: "fumeux", lemmaKey: "fumeux", headword: "fumeux", partOfSpeech: "adjective", senseKey: "fumeux_confused", gloss: "hazy; muddled", definition: "dont les idées sont obscures, confuses ou extravagantes", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "fût", lemmaKey: "etre", existingLemmaId: "lem_etre", existingSenseId: "sns_etre_primary", headword: "être", partOfSpeech: "verb", senseKey: "etre_primary", gloss: "to be", quizMeaning: "were; was", definition: "avoir une existence ou se trouver dans un état", englishDistractors: ["embroidered", "whistled", "floated"], frenchDistractors: ["brodât", "sifflât", "flottât"] },
  { normalized: "galonnés", lemmaKey: "galonne", headword: "galonné", partOfSpeech: "noun", senseKey: "galonne_officers", gloss: "uniformed officers", definition: "militaires portant des galons, considérés comme un groupe", englishDistractors: ["teapots", "staircases", "violins"], frenchDistractors: ["théières", "escaliers", "violons"] },
  { normalized: "garde", lemmaKey: "garde", headword: "garde", partOfSpeech: "noun", senseKey: "garde_official", gloss: "keeper; custodian", definition: "personne chargée officiellement de conserver ou de protéger quelque chose", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "gardé", lemmaKey: "garder", headword: "garder", partOfSpeech: "verb", senseKey: "garder_keep", gloss: "to keep; retain", quizMeaning: "kept; withheld", definition: "conserver quelque chose sans le communiquer ou le céder", englishDistractors: ["embroidered", "whistled", "floated"], frenchDistractors: ["brodé", "sifflé", "flotté"] },
  { normalized: "général", lemmaKey: "general_noun", headword: "général", partOfSpeech: "noun", senseKey: "general_military_rank", gloss: "general", definition: "officier appartenant aux grades les plus élevés de l’armée", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "générale", lemmaKey: "general_adjective", headword: "général", partOfSpeech: "adjective", senseKey: "general_whole", gloss: "general; widespread", definition: "qui concerne l’ensemble ou s’étend à la totalité", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayée", "aromatisée à la menthe", "triangulaire"] },
  { normalized: "généraux", lemmaKey: "general_noun", headword: "général", partOfSpeech: "noun", senseKey: "general_military_rank", gloss: "general", quizMeaning: "generals", definition: "officier appartenant aux grades les plus élevés de l’armée", englishDistractors: ["teapots", "staircases", "violins"], frenchDistractors: ["théières", "escaliers", "violons"] },
  { normalized: "généreuse", lemmaKey: "genereux", headword: "généreux", partOfSpeech: "adjective", senseKey: "genereux_noble", gloss: "generous; noble", definition: "qui manifeste de la grandeur d’âme et agit avec noblesse", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayée", "aromatisée à la menthe", "triangulaire"] },
];
