import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a telescope", "a turnip", "a suitcase"];
const nounFrench: [string, string, string] = ["télescope", "navet", "coussin"];
const feminineNounFrench: [string, string, string] = ["lanterne", "citrouille", "valise"];
const adjectiveEnglish: [string, string, string] = ["plaid", "orange-scented", "spherical"];
const adjectiveFrench: [string, string, string] = ["écossais", "parfumé à l’orange", "sphérique"];

export const zolaVocabularyBatch33: ZolaVocabularySpec[] = [
  { normalized: "moins", candidateIds: ["tok_bcc56a0a2f8e673040a1c91f"], lemmaKey: "moins_adverb", headword: "moins", partOfSpeech: "adverb", senseKey: "moins_nevertheless", gloss: "nevertheless; still", definition: "dans « ne… pas moins », indique qu’un fait demeure vrai malgré ce qui précède", englishDistractors: ["personally", "officially", "mechanically"], frenchDistractors: ["personnellement", "officiellement", "mécaniquement"] },
  { normalized: "moins", candidateIds: ["tok_88f6861f6d395d17e1e3ceb3"], lemmaKey: "moins_adverb", headword: "moins", partOfSpeech: "adverb", senseKey: "moins_at_all", gloss: "at all; in the least", definition: "dans « le moins du monde », renforce une négation en excluant le plus petit degré", englishDistractors: ["telescope", "turnip", "suitcase"], frenchDistractors: ["télescope", "navet", "valise"] },
  { normalized: "moins", candidateIds: ["tok_d10e5f46ef8d5a58652570f4"], lemmaKey: "moins_adverb", headword: "moins", partOfSpeech: "adverb", senseKey: "moins_at_least", gloss: "at least", definition: "indique une limite minimale ou une restriction apportée à l’affirmation", englishDistractors: ["edge", "attic", "springtime"], frenchDistractors: ["bord", "grenier", "printemps"] },
  { normalized: "moins", candidateIds: ["tok_cb77c6203a2a7d3e4fb7ea62"], lemmaKey: "a_moins_que", headword: "à moins que", partOfSpeech: "conjunction", senseKey: "a_moins_que_unless", gloss: "unless", definition: "introduit la seule condition qui empêcherait le fait principal", englishDistractors: ["as", "now", "hardly"], frenchDistractors: ["mesure", "présent", "peine"] },
  { normalized: "mois", lemmaKey: "mois", headword: "mois", partOfSpeech: "noun", senseKey: "mois_month", gloss: "month", quizMeaning: "months", definition: "chacune des douze divisions principales de l’année", englishDistractors: ["turnips", "suitcases", "telescopes"], frenchDistractors: ["navets", "valises", "télescopes"] },
  { normalized: "moment", lemmaKey: "moment", headword: "moment", partOfSpeech: "noun", senseKey: "moment_point_in_time", gloss: "moment; point in time", definition: "court espace de temps ou instant précis", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "monde", candidateIds: ["tok_648b84c972a53c43adaaa59b"], lemmaKey: "monde", headword: "monde", partOfSpeech: "noun", senseKey: "monde_world_public", gloss: "world; public", definition: "ensemble des êtres humains ou société considérée dans son étendue", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "monde", candidateIds: ["tok_e0f01edbbee34b07105c3f1e"], lemmaKey: "monde", headword: "monde", partOfSpeech: "noun", senseKey: "monde_emphasis", gloss: "at all; whatsoever", definition: "dans une expression négative, sert à renforcer complètement la négation", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "monstrueuse", lemmaKey: "monstrueux", headword: "monstrueux", partOfSpeech: "adjective", senseKey: "monstrueux_outrageous", gloss: "monstrous; outrageous", definition: "qui dépasse toute mesure par son caractère horrible ou révoltant", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaise", "parfumée à l’orange", "sphérique"] },
  { normalized: "monstrueuses", lemmaKey: "monstrueux", headword: "monstrueux", partOfSpeech: "adjective", senseKey: "monstrueux_outrageous", gloss: "monstrous; outrageous", definition: "qui dépasse toute mesure par son caractère horrible ou révoltant", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaises", "parfumées à l’orange", "sphériques"] },
  { normalized: "montre", lemmaKey: "montrer", headword: "montrer", partOfSpeech: "verb", senseKey: "montrer_show", gloss: "to show; demonstrate", quizMeaning: "shows; demonstrates", definition: "faire voir ou rendre évident", englishDistractors: ["knits", "dives", "snores"], frenchDistractors: ["tricote", "plonge", "ronfle"] },
  { normalized: "montrent", lemmaKey: "montrer", headword: "montrer", partOfSpeech: "verb", senseKey: "montrer_show", gloss: "to show; demonstrate", quizMeaning: "show; demonstrate", definition: "faire voir ou rendre évident", englishDistractors: ["knit", "dive", "snore"], frenchDistractors: ["tricotent", "plongent", "ronflent"] },
  { normalized: "monument", lemmaKey: "monument", headword: "monument", partOfSpeech: "noun", senseKey: "monument_enduring_example", gloss: "monument; enduring example", definition: "œuvre ou témoignage durable qui conserve la mémoire de quelque chose", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "morales", lemmaKey: "moral", headword: "moral", partOfSpeech: "adjective", senseKey: "moral_nonmaterial", gloss: "moral; circumstantial", definition: "qui concerne la conduite, la conscience ou une conviction non matérielle", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaises", "parfumées à l’orange", "sphériques"] },
  { normalized: "mort", candidateIds: ["tok_786699d478a7cbe7ada8e19f", "tok_349d1ed227c4c876967779b0"], lemmaKey: "mort_adjective", headword: "mort", partOfSpeech: "adjective", senseKey: "mort_dead", gloss: "dead", definition: "qui a cessé de vivre", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "mort", candidateIds: ["tok_f72331d70b1d865915ea55b0", "tok_e08184b38223313e7f04fb36"], lemmaKey: "mort_noun", headword: "mort", partOfSpeech: "noun", senseKey: "mort_death", gloss: "death", definition: "cessation définitive de la vie", englishDistractors: nounEnglish, frenchDistractors: feminineNounFrench },
  { normalized: "motif", lemmaKey: "motif", headword: "motif", partOfSpeech: "noun", senseKey: "motif_reason", gloss: "reason; motive", definition: "raison qui explique ou justifie une action", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "motifs", lemmaKey: "motif", headword: "motif", partOfSpeech: "noun", senseKey: "motif_reason", gloss: "reason; motive", quizMeaning: "reasons; motives", definition: "raison qui explique ou justifie une action", englishDistractors: ["telescopes", "turnips", "suitcases"], frenchDistractors: ["télescopes", "navets", "valises"] },
  { normalized: "mourra", lemmaKey: "mourir", headword: "mourir", partOfSpeech: "verb", senseKey: "mourir_die", gloss: "to die", quizMeaning: "will die", definition: "cesser de vivre ou disparaître sous l’effet d’un mal", englishDistractors: ["will knit", "will dive", "will snore"], frenchDistractors: ["tricotera", "plongera", "ronflera"] },
  { normalized: "moyen", lemmaKey: "moyen", headword: "moyen", partOfSpeech: "noun", senseKey: "moyen_method", gloss: "means; method", definition: "procédé ou ressource employé pour atteindre un but", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "moyens", lemmaKey: "moyen", headword: "moyen", partOfSpeech: "noun", senseKey: "moyen_method", gloss: "means; method", quizMeaning: "means; methods", definition: "procédé ou ressource employé pour atteindre un but", englishDistractors: ["telescopes", "turnips", "suitcases"], frenchDistractors: ["télescopes", "navets", "valises"] },
  { normalized: "mystère", lemmaKey: "mystere", headword: "mystère", partOfSpeech: "noun", senseKey: "mystere_secrecy", gloss: "mystery; secrecy", definition: "ce qui reste caché, inexplicable ou tenu secret", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "mystérieuse", lemmaKey: "mysterieux", headword: "mystérieux", partOfSpeech: "adjective", senseKey: "mysterieux_mysterious", gloss: "mysterious; unknown", definition: "dont l’identité, la nature ou les intentions restent cachées", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaise", "parfumée à l’orange", "sphérique"] },
  { normalized: "mystérieuses", lemmaKey: "mysterieux", headword: "mystérieux", partOfSpeech: "adjective", senseKey: "mysterieux_mysterious", gloss: "mysterious; unknown", definition: "dont l’identité, la nature ou les intentions restent cachées", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaises", "parfumées à l’orange", "sphériques"] },
  { normalized: "n’ont", lemmaKey: "avoir", existingLemmaId: "lem_avoir", existingSenseId: "sns_avoir_primary", headword: "avoir", partOfSpeech: "verb", senseKey: "avoir_primary", gloss: "to have", quizMeaning: "have not; did not", definition: "posséder ou former un temps composé avec un participe passé", englishDistractors: ["the turnips have", "the suitcases have", "the telescopes have"], frenchDistractors: ["les navets ont", "les valises ont", "les télescopes ont"] },
  { normalized: "naïve", lemmaKey: "naif", headword: "naïf", partOfSpeech: "adjective", senseKey: "naif_unsophisticated", gloss: "naive; unsophisticated", definition: "qui manque d’expérience, de méfiance ou de subtilité", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaise", "parfumée à l’orange", "sphérique"] },
  { normalized: "naïvetés", lemmaKey: "naivete", headword: "naïveté", partOfSpeech: "noun", senseKey: "naivete_simplemindedness", gloss: "naivety; simplemindedness", quizMeaning: "naive features; absurd simplicities", definition: "manifestation d’un manque de subtilité ou de vraisemblance", englishDistractors: ["telescopes", "turnips", "suitcases"], frenchDistractors: ["télescopes", "navets", "valises"] },
  { normalized: "nation", lemmaKey: "nation", headword: "nation", partOfSpeech: "noun", senseKey: "nation_people_state", gloss: "nation; people", definition: "communauté politique et humaine constituant un pays", englishDistractors: nounEnglish, frenchDistractors: feminineNounFrench },
  { normalized: "nationale", lemmaKey: "national", headword: "national", partOfSpeech: "adjective", senseKey: "national_of_nation", gloss: "national", definition: "qui appartient à la nation ou concerne le pays entier", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaise", "parfumée à l’orange", "sphérique"] },
  { normalized: "nations", lemmaKey: "nation", headword: "nation", partOfSpeech: "noun", senseKey: "nation_people_state", gloss: "nation; people", quizMeaning: "nations", definition: "communauté politique et humaine constituant un pays", englishDistractors: ["telescopes", "turnips", "suitcases"], frenchDistractors: ["télescopes", "navets", "valises"] },
  { normalized: "naturellement", lemmaKey: "naturellement", headword: "naturellement", partOfSpeech: "adverb", senseKey: "naturellement_naturally", gloss: "naturally; as expected", definition: "d’une manière naturelle ou conforme à ce que l’on pouvait prévoir", englishDistractors: ["slowly", "outside", "tomorrow"], frenchDistractors: ["lentement", "dehors", "demain"] },
  { normalized: "néant", lemmaKey: "neant", headword: "néant", partOfSpeech: "noun", senseKey: "neant_nothingness", gloss: "nothingness; worthlessness", definition: "absence totale de réalité, de valeur ou de contenu", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "née", lemmaKey: "naitre", headword: "naître", partOfSpeech: "verb", senseKey: "naitre_arise", gloss: "to be born; arise", quizMeaning: "was born; arose", definition: "commencer à exister ou apparaître", englishDistractors: ["knitted", "dived", "snored"], frenchDistractors: ["tricotée", "plongée", "ronflée"] },
  { normalized: "néfaste", lemmaKey: "nefaste", headword: "néfaste", partOfSpeech: "adjective", senseKey: "nefaste_harmful", gloss: "harmful; disastrous", definition: "qui produit des effets très mauvais ou funestes", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "nettement", lemmaKey: "nettement", headword: "nettement", partOfSpeech: "adverb", senseKey: "nettement_clearly", gloss: "clearly; distinctly", definition: "d’une manière claire, précise et sans ambiguïté", englishDistractors: ["slowly", "outside", "tomorrow"], frenchDistractors: ["lentement", "dehors", "demain"] },
  { normalized: "nettes", lemmaKey: "net", headword: "net", partOfSpeech: "adjective", senseKey: "net_clear", gloss: "clear; definite", definition: "clairement défini et dépourvu d’ambiguïté", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaises", "parfumées à l’orange", "sphériques"] },
  { normalized: "nid", lemmaKey: "nid", headword: "nid", partOfSpeech: "noun", senseKey: "nid_den", gloss: "nest; den", definition: "abri d’un oiseau, employé ici pour un foyer d’activités nuisibles", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
];
