import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a lantern", "a cabbage", "a staircase"];
const nounFrench: [string, string, string] = ["lanterne", "chou", "escalier"];
const adjectiveEnglish: [string, string, string] = ["striped", "cinnamon-scented", "conical"];
const adjectiveFrench: [string, string, string] = ["rayé", "parfumé à la cannelle", "conique"];

export const zolaVocabularyBatch30: ZolaVocabularySpec[] = [
  { normalized: "langues", lemmaKey: "langue", headword: "langue", partOfSpeech: "noun", senseKey: "langue_language", gloss: "language", quizMeaning: "languages", definition: "système de mots et de règles employé par une communauté pour communiquer", englishDistractors: ["lanterns", "cabbages", "staircases"], frenchDistractors: ["lanternes", "choux", "escaliers"] },
  { normalized: "lanterne", lemmaKey: "lanterne", headword: "lanterne", partOfSpeech: "noun", senseKey: "lanterne_lamp", gloss: "lantern", definition: "appareil portatif qui protège et diffuse une source de lumière", englishDistractors: ["a suitcase", "a cabbage", "a staircase"], frenchDistractors: ["valise", "chou", "escalier"] },
  { normalized: "laquelle", lemmaKey: "lequel", headword: "lequel", partOfSpeech: "pronoun", senseKey: "lequel_which", gloss: "which; whom", definition: "pronom relatif ou interrogatif qui reprend une personne ou une chose déjà désignée", englishDistractors: ["a lantern", "a cabbage", "a staircase"], frenchDistractors: ["une lanterne", "un chou", "un escalier"] },
  { normalized: "légitime", candidateIds: ["tok_ec9d6ab5b7c6a471325d1e70"], lemmaKey: "legitimer", headword: "légitimer", partOfSpeech: "verb", senseKey: "legitimer_justify", gloss: "to legitimize; justify", quizMeaning: "legitimizes; justifies", definition: "donner un caractère légitime ou fournir une justification", englishDistractors: ["knits", "dives", "snores"], frenchDistractors: ["tricote", "plonge", "ronfle"] },
  { normalized: "légitime", candidateIds: ["tok_d73b07ac84e9d9d7a48b1aa7"], lemmaKey: "legitime", headword: "légitime", partOfSpeech: "adjective", senseKey: "legitime_justified", gloss: "legitimate; justified", definition: "conforme au droit, à la justice ou à une raison valable", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "lequel", lemmaKey: "lequel", headword: "lequel", partOfSpeech: "pronoun", senseKey: "lequel_which", gloss: "which; whom", definition: "pronom relatif ou interrogatif qui reprend une personne ou une chose déjà désignée", englishDistractors: ["a lantern", "a cabbage", "a staircase"], frenchDistractors: ["un moulin", "un navet", "un oreiller"] },
  { normalized: "lèse-humanité", lemmaKey: "lese_humanite", headword: "lèse-humanité", partOfSpeech: "noun", senseKey: "lese_humanite_offense", gloss: "crime against humanity", definition: "atteinte extrêmement grave portée à l’humanité", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "lèse-justice", lemmaKey: "lese_justice", headword: "lèse-justice", partOfSpeech: "noun", senseKey: "lese_justice_offense", gloss: "crime against justice", definition: "atteinte extrêmement grave portée à la justice", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "lesquels", lemmaKey: "lequel", headword: "lequel", partOfSpeech: "pronoun", senseKey: "lequel_which", gloss: "which; whom", definition: "pronom relatif ou interrogatif qui reprend une personne ou une chose déjà désignée", englishDistractors: ["lanterns", "cabbages", "staircases"], frenchDistractors: ["moulins", "navets", "oreillers"] },
  { normalized: "lettre", lemmaKey: "lettre", headword: "lettre", partOfSpeech: "noun", senseKey: "lettre_message", gloss: "letter; written message", definition: "message écrit adressé à une personne", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "lettre-télégramme", lemmaKey: "lettre_telegramme", headword: "lettre-télégramme", partOfSpeech: "noun", senseKey: "lettre_telegramme_message", gloss: "letter-telegram; telegram card", definition: "communication écrite brève transmise sous une forme proche du télégramme", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "lettres", lemmaKey: "lettre", headword: "lettre", partOfSpeech: "noun", senseKey: "lettre_message", gloss: "letter; written message", quizMeaning: "letters; written messages", definition: "message écrit adressé à une personne", englishDistractors: ["lanterns", "cabbages", "staircases"], frenchDistractors: ["lanternes", "choux", "escaliers"] },
  { normalized: "lèverait", lemmaKey: "lever", headword: "se lever", partOfSpeech: "verb", senseKey: "lever_rise", gloss: "to rise; stand up", quizMeaning: "would rise; would mobilize", definition: "se mettre debout ou entrer activement en action", englishDistractors: ["would knit", "would dive", "would snore"], frenchDistractors: ["tricoterait", "plongerait", "ronflerait"] },
  { normalized: "libérale", lemmaKey: "liberal", headword: "libéral", partOfSpeech: "adjective", senseKey: "liberal_freedom", gloss: "liberal; freedom-supporting", definition: "favorable aux libertés civiles et politiques", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayée", "parfumée à la cannelle", "conique"] },
  { normalized: "liberté", lemmaKey: "liberte", headword: "liberté", partOfSpeech: "noun", senseKey: "liberte_freedom", gloss: "freedom; liberty", definition: "possibilité d’agir, de penser et de s’exprimer sans contrainte injuste", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "libres", lemmaKey: "libre", headword: "libre", partOfSpeech: "adjective", senseKey: "libre_free", gloss: "free", definition: "qui jouit de la liberté et n’est pas soumis à une domination", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayées", "parfumées à la cannelle", "coniques"] },
  { normalized: "lieu", lemmaKey: "avoir_lieu", headword: "avoir lieu", partOfSpeech: "expression", senseKey: "avoir_lieu_happen", gloss: "to take place; happen", definition: "se produire ou se dérouler à un moment ou dans un cadre donné", englishDistractors: ["to knit", "to dive", "to snore"], frenchDistractors: ["faim", "peur", "raison"] },
  { normalized: "lieutenant-colonel", lemmaKey: "lieutenant_colonel", headword: "lieutenant-colonel", partOfSpeech: "noun", senseKey: "lieutenant_colonel_rank", gloss: "lieutenant colonel", definition: "grade militaire situé entre commandant et colonel", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "lire", lemmaKey: "lire", headword: "lire", partOfSpeech: "verb", senseKey: "lire_read", gloss: "to read", definition: "prendre connaissance d’un texte écrit", englishDistractors: ["to knit", "to dive", "to snore"], frenchDistractors: ["tricoter", "plonger", "ronfler"] },
  { normalized: "livrer", lemmaKey: "livrer", headword: "livrer", partOfSpeech: "verb", senseKey: "livrer_hand_over", gloss: "to hand over; expose", definition: "remettre à autrui ou abandonner à un pouvoir ou à un danger", englishDistractors: ["to knit", "to dive", "to snore"], frenchDistractors: ["tricoter", "plonger", "ronfler"] },
  { normalized: "livrés", lemmaKey: "livrer", headword: "livrer", partOfSpeech: "verb", senseKey: "livrer_hand_over", gloss: "to hand over; expose", quizMeaning: "handed over; disclosed", definition: "remettre à autrui ou abandonner à un pouvoir ou à un danger", englishDistractors: ["knitted", "dived", "snored"], frenchDistractors: ["tricotés", "plongés", "ronflés"] },
  { normalized: "loi", lemmaKey: "loi", headword: "loi", partOfSpeech: "noun", senseKey: "loi_law", gloss: "law; statute", definition: "règle obligatoire adoptée par l’autorité publique", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "loin", lemmaKey: "loin", headword: "loin", partOfSpeech: "adverb", senseKey: "loin_far", gloss: "far; far away", definition: "à une grande distance dans l’espace ou au sens figuré", englishDistractors: ["quietly", "indoors", "yearly"], frenchDistractors: ["silencieusement", "à l’intérieur", "annuellement"] },
  { normalized: "long", lemmaKey: "long", headword: "long", partOfSpeech: "adjective", senseKey: "long_extended", gloss: "long; extended", quizMeaning: "throughout; all along", definition: "qui s’étend sur une grande distance ou durée", englishDistractors: adjectiveEnglish, frenchDistractors: ["large", "vert", "carré"] },
  { normalized: "longue", lemmaKey: "long", headword: "long", partOfSpeech: "adjective", senseKey: "long_extended", gloss: "long; extended", definition: "qui s’étend sur une grande distance ou durée", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayée", "parfumée à la cannelle", "conique"] },
  { normalized: "lors", lemmaKey: "lors", headword: "lors", partOfSpeech: "adverb", senseKey: "lors_then", gloss: "then; at that time", definition: "à ce moment-là, généralement dans une locution temporelle", englishDistractors: ["quietly", "indoors", "yearly"], frenchDistractors: ["silencieusement", "à l’intérieur", "annuellement"] },
  { normalized: "lorsqu’", lemmaKey: "lorsque", headword: "lorsque", partOfSpeech: "conjunction", senseKey: "lorsque_when", gloss: "when", definition: "introduit une proposition indiquant le moment où un fait se produit", englishDistractors: ["although", "because", "unless"], frenchDistractors: ["quoique", "parce que", "à moins que"] },
  { normalized: "loyale", lemmaKey: "loyal", headword: "loyal", partOfSpeech: "adjective", senseKey: "loyal_faithful", gloss: "loyal; honorable", definition: "qui agit avec fidélité, droiture et honnêteté", englishDistractors: adjectiveEnglish, frenchDistractors: ["rayée", "parfumée à la cannelle", "conique"] },
  { normalized: "lu", lemmaKey: "lire", headword: "lire", partOfSpeech: "verb", senseKey: "lire_read", gloss: "to read", quizMeaning: "read", definition: "prendre connaissance d’un texte écrit", englishDistractors: ["knitted", "dived", "snored"], frenchDistractors: ["tricoté", "plongé", "ronflé"] },
  { normalized: "luire", lemmaKey: "luire", headword: "luire", partOfSpeech: "verb", senseKey: "luire_shine", gloss: "to shine; gleam", definition: "émettre ou réfléchir de la lumière", englishDistractors: ["to knit", "to dive", "to snore"], frenchDistractors: ["tricoter", "plonger", "ronfler"] },
  { normalized: "lumière", candidateIds: ["tok_4e98f2518e4c21cfb8303f9a"], lemmaKey: "lumiere", headword: "lumière", partOfSpeech: "noun", senseKey: "lumiere_physical", gloss: "light; illumination", definition: "rayonnement visible qui permet de voir les objets", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "lumière", candidateIds: ["tok_b4919e0c06fe898e97b6d3f3", "tok_53537577fd21cda9a8a6bb5a"], lemmaKey: "lumiere", headword: "lumière", partOfSpeech: "noun", senseKey: "lumiere_truth", gloss: "light; revealed truth", definition: "vérité rendue visible et capable de dissiper l’erreur", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
];
