import type { ZolaVocabularySpec } from "./zola-authoring.js";

type Kind = "noun" | "adjective" | "verb" | "adverb" | "determiner";

const make = (
  normalized: string,
  lemmaKey: string,
  candidateIds: readonly string[],
  partOfSpeech: Kind,
  senseKey: string,
  headword: string,
  gloss: string,
  definition: string,
  englishDistractors: [string, string, string],
  frenchDistractors: [string, string, string],
  existingLemmaId?: string,
  existingSenseId?: string,
): ZolaVocabularySpec => ({
  normalized,
  lemmaKey,
  candidateIds,
  partOfSpeech,
  senseKey,
  headword,
  gloss,
  quizMeaning: gloss,
  definition,
  englishDistractors,
  frenchDistractors,
  ...(existingLemmaId ? { existingLemmaId } : {}),
  ...(existingSenseId ? { existingSenseId } : {}),
});

export const zolaVocabularyBatch48: ZolaVocabularySpec[] = [
  make("taches", "tache", ["tok_c3d0c48e65da98258320f257"], "noun", "tache_stain", "tache", "stain; blemish", "marque qui souille une surface ou porte atteinte à une réputation", ["honors", "songs", "victories"], ["honneurs", "chants", "victoires"], "lem_zola_tache", "sns_zola_tache_stain"),
  make("sorti", "sortir", ["tok_bd2efc7b4f571552cf49723b"], "verb", "sortir_emerge", "sortir", "emerge; come out", "venir au-dehors ou apparaître à partir d’un lieu ou d’une situation", ["entered", "slept", "vanished"], ["entré", "dormi", "disparu"], "lem_zola_sortir", "sns_zola_sortir_emerge"),
  make("sain", "sain", ["tok_7f7f3434f7f9b9814438d2a1"], "adjective", "sain_unharmed", "sain", "safe; unharmed", "qui n’a subi ni dommage ni atteinte", ["wounded", "hidden", "guilty"], ["blessé", "caché", "coupable"]),
  make("sauf", "sauf", ["tok_ea8f0cb4c3e4e435936d241c"], "adjective", "sauf_safe", "sauf", "safe; unharmed", "qui est hors de danger ou excepté d’un ensemble", ["endangered", "included", "silent"], ["menacé", "inclus", "silencieux"]),
  make("russe", "russe", ["tok_9f4572b09c6af61f9bf6ead0"], "adjective", "russe_russian", "russe", "Russian", "qui se rapporte à la Russie ou à ses habitants", ["French", "German", "Spanish"], ["français", "allemand", "espagnol"]),
  make("solennel", "solennel", ["tok_43b08f9d6736ea42dec283ca"], "adjective", "solennel_formal", "solennel", "solemn; formal", "qui est accompli avec une gravité officielle", ["casual", "secret", "playful"], ["familier", "secret", "enjoué"]),
  make("règne", "regne", ["tok_477ae32c538996a3437ec959"], "noun", "regne_rule", "règne", "reign; rule", "période ou exercice de l’autorité d’un souverain", ["exile", "silence", "trial"], ["exil", "silence", "procès"]),
  make("soufflet", "soufflet", ["tok_afd4707e902f9fe5a17b3259"], "noun", "soufflet_insult", "soufflet", "slap; affront", "offense humiliante comparée à un coup porté au visage", ["compliment", "reward", "apology"], ["compliment", "récompense", "excuse"]),
  make("tel", "tel", ["tok_550a0764f664f7281940d010"], "adjective", "tel_primary", "tel", "such; a certain", "adjectif indiquant une ressemblance ou une qualité déterminée", ["none", "whose", "how many"], ["aucun", "dont", "combien"], "lem_tel", "sns_tel_primary"),
  make("social", "social", ["tok_d0d2ad3ad4cfcfbc5d15835a"], "adjective", "social_society", "social", "social", "qui concerne la société et les relations entre ses membres", ["private", "musical", "wooden"], ["privé", "musical", "en bois"]),
  make("régulièrement", "regulier", ["tok_c14c213ac16004ec96921d88"], "adverb", "regulier_regularly", "régulièrement", "regularly; properly", "d’une manière régulière ou conforme aux règles", ["rarely", "secretly", "accidentally"], ["rarement", "secrètement", "accidentellement"]),
  make("saisie", "saisir", ["tok_f414033a47c2994fa42b0c9b"], "verb", "saisir_referred", "saisir", "seized; referred to", "qui a été officiellement saisie d’une affaire et doit en connaître", ["ignored", "released", "forgotten"], ["ignorée", "relâchée", "oubliée"], "lem_saisir"),
  make("seraient", "etre", ["tok_f21ab7514c763f3b8eb153c3"], "verb", "etre_conditional", "être", "would be", "forme conditionnelle de être exprimant une éventualité", ["will have", "would leave", "must go"], ["auront", "partiraient", "doivent partir"], "lem_etre", "sns_etre_primary"),
  make("spectre", "spectre", ["tok_9084a89c31b09c8f52a12113"], "noun", "spectre_ghost", "spectre", "specter; ghost", "apparition d’un mort ou image obsédante d’une menace", ["witness", "letter", "victory"], ["témoin", "lettre", "victoire"]),
  make("tortures", "torture", ["tok_831511c55dc24c79916a3465"], "noun", "torture_suffering", "torture", "tortures; torment", "souffrances physiques ou morales infligées à quelqu’un", ["comforts", "celebrations", "pardons"], ["réconforts", "célébrations", "pardons"]),
  make("suis", "etre", ["tok_53b437090f9dba9affd16c58"], "verb", "etre_present", "être", "am; am convinced", "forme du présent de être à la première personne du singulier", ["was", "will be", "has"], ["étais", "serai", "a"], "lem_etre", "sns_etre_primary"),
  make("tourbe", "tourbe", ["tok_1d5eeda857fd95509c40fb07"], "noun", "tourbe_rabble", "tourbe", "rabble; vile crowd", "foule méprisable et malfaisante", ["council", "family", "jury"], ["conseil", "famille", "jury"]),
  make("volés", "voler", ["tok_668c7ab3e248b6b1f47db48c"], "verb", "voler_stolen", "voler", "stolen", "participe passé de voler, pris ou dérobé sans autorisation", ["returned", "sealed", "published"], ["rendus", "scellés", "publiés"]),
  make("rêva", "rever", ["tok_fb0144ef57c6e83e01563003"], "verb", "rever_dream", "rêver", "dreamed", "forme du passé de rêver, imaginer ou souhaiter en songe", ["calculated", "forgot", "proved"], ["calcula", "oublia", "prouva"]),
  make("revêtue", "revetir", ["tok_4ea1c29107c30cbd486e0e1d"], "verb", "revetir_covered", "revêtir", "covered; lined", "participe passé de revêtir, entièrement couverte d’une matière", ["emptied", "opened", "broken"], ["vidée", "ouverte", "brisée"]),
  make("représente", "representer", ["tok_76d095787b65fa6264b76c2b"], "verb", "representer_depict", "représenter", "represents; depicts", "montre ou décrit quelqu’un ou quelque chose", ["conceals", "erases", "abandons"], ["dissimule", "efface", "abandonne"]),
  make("sourde", "sourd", ["tok_408662269d308d96b7793245"], "adjective", "sourd_muted", "sourd", "muted; dim", "qui ne laisse pas passer le son ou la lumière, comme dans lanterne sourde", ["bright", "noisy", "transparent"], ["brillante", "bruyante", "transparente"]),
  make("voulant", "vouloir", ["tok_1587e1990cf6644e802cf357"], "verb", "vouloir_present", "vouloir", "wanting", "participe présent de vouloir, exprimant une volonté", ["forgetting", "denying", "sleeping"], ["oubliant", "niant", "dormant"], "lem_zola_vouloir", "sns_zola_vouloir_present"),
  make("réveil", "reveil", ["tok_6583fff8b6da21f3a0d56aa0"], "noun", "reveil_awakening", "réveil", "awakening; waking", "moment où l’on cesse de dormir et reprend conscience", ["silence", "departure", "punishment"], ["silence", "départ", "punition"]),
  { ...make("trouvera", "trouver", ["tok_8a53d87a18799880ef99ffd8"], "verb", "trouver_discover", "trouver", "to find; discover", "découvrir ou constater quelque chose après l’avoir cherché", ["will lose", "will hide", "will forget"], ["perdra", "cachera", "oubliera"], "lem_zola_trouver"), quizMeaning: "will find" },
  make("simplement", "simplement", ["tok_9cd98dcb8bf14333228adaaf"], "adverb", "simplement_plainly", "simplement", "simply; plainly", "d’une manière simple, sans complication ni détour", ["secretly", "violently", "rarely"], ["secrètement", "violemment", "rarement"]),
  make("recherché", "rechercher", ["tok_808dd884a511c3303ce71874"], "verb", "rechercher_sought", "rechercher", "sought; searched for", "participe passé de rechercher, activement cherché", ["ignored", "abandoned", "hidden"], ["ignoré", "abandonné", "caché"]),
  make("superficiel", "superficiel", ["tok_7616a9268ef1e1a91b947d75"], "adjective", "superficiel_shallow", "superficiel", "superficial; shallow", "qui ne va pas au fond des choses", ["thorough", "honest", "ancient"], ["approfondi", "honnête", "ancien"]),
  make("troupe", "troupe", ["tok_776ffac4f5a1a2fc8730d86a"], "noun", "troupe_group", "troupe", "group; troop", "groupe organisé de personnes, notamment une unité ou une compagnie", ["individual", "letter", "verdict"], ["individu", "lettre", "verdict"]),
  make("veuille", "vouloir", ["tok_f24f549fdd9d7b28edbe72fc"], "verb", "vouloir_subjunctive", "vouloir", "may want; be willing", "forme du subjonctif de vouloir exprimant une volonté éventuelle", ["must refuse", "has forgotten", "is sleeping"], ["doive refuser", "ait oublié", "dorme"]),
  make("refaire", "refaire", ["tok_9ac7f2d18a18fbd97d23c7c5"], "verb", "refaire_repeat", "refaire", "redo; do again", "faire de nouveau ou recommencer", ["finish", "erase", "hide"], ["finir", "effacer", "cacher"]),
  make("scène", "scene", ["tok_0135557e73fbe55ae4e48292"], "noun", "scene_event", "scène", "scene; episode", "partie d’un récit ou événement présenté comme un spectacle", ["silence", "footnote", "verdict"], ["silence", "note", "verdict"]),
  make("soupçon", "soupcon", ["tok_167f0b77aaf9bab1c4b1e01b"], "noun", "soupcon_suspicion", "soupçon", "suspicion; hint", "doute ou indice qui fait penser à une faute", ["certainty", "pardon", "celebration"], ["certitude", "pardon", "célébration"]),
  make("semble", "sembler", ["tok_9227c6618a2a96d4f5827240"], "verb", "sembler_primary", "sembler", "seems; appears", "paraître avoir une qualité ou être dans un état", ["proves", "vanishes", "denies"], ["prouve", "disparaît", "nie"], "lem_sembler", "sns_sembler_primary"),
  make("sous-chef", "sous_chef", ["tok_6c981bcb8d09e0ae294d58ec"], "noun", "sous_chef_deputy", "sous-chef", "deputy chief", "personne placée sous l’autorité d’un chef et chargée de le seconder", ["sovereign", "prisoner", "messenger"], ["souverain", "prisonnier", "messager"]),
  make("spiritisme", "spiritisme", ["tok_60d0c9050160e0dd64f4126e"], "noun", "spiritisme", "spiritisme", "spiritism", "doctrine ou pratique prétendant communiquer avec les esprits", ["jurisprudence", "agriculture", "athletics"], ["jurisprudence", "agriculture", "athlétisme"]),
  make("soumis", "soumettre", ["tok_dc7b456987719cd469b12575"], "verb", "soumettre_submitted", "soumettre", "submitted; subjected", "participe passé de soumettre, placé sous une autorité ou présenté à un examen", ["freed", "hidden", "acquitted"], ["libéré", "caché", "acquitté"]),
  make("torturante", "torturant", ["tok_f3088212482105cf1f0e7976"], "adjective", "torturant_painful", "torturant", "tormenting; painful", "qui fait souffrir moralement ou physiquement", ["soothing", "comic", "ordinary"], ["apaisant", "comique", "ordinaire"]),
  make("secret", "secret", ["tok_2d5af7474e3da35872ddb2ad"], "adjective", "secret_adjective", "secret", "secret; concealed", "qui est tenu caché et n’est pas destiné à être révélé", ["public", "obvious", "official"], ["public", "évident", "officiel"], "lem_zola_secret", "sns_zola_secret_adjective"),
  make("terrorise", "terroriser", ["tok_57616901106767d9fbd06d15"], "verb", "terroriser_present", "terroriser", "terrorizes; frightens", "inspire une grande peur à quelqu’un", ["comforts", "encourages", "amuses"], ["rassure", "encourage", "amuse"]),
  make("vulgaire", "vulgaire", ["tok_55fff6eccc0193fa1a22277e"], "adjective", "vulgaire_common", "vulgaire", "vulgar; common", "qui manque de distinction ou appartient au langage ordinaire", ["refined", "sacred", "legal"], ["raffiné", "sacré", "juridique"]),
  { ...make("trouvaient", "trouver", ["tok_1a13da5726537c13e44b9a2b"], "verb", "trouver_state", "trouver", "to be; find oneself", "dans se trouver, être ou se situer dans un état ou un lieu", ["were proving", "were explaining", "were concealing"], ["prouvaient", "expliquaient", "dissimulaient"], "lem_zola_trouver"), quizMeaning: "were; were found" },
  make("valeur", "valeur", ["tok_a8dbbc024c132e3861e922ee"], "noun", "valeur_worth", "valeur", "value; worth", "importance ou mérite attribué à une chose ou à une action", ["weight", "silence", "color"], ["poids", "silence", "couleur"]),
  make("voudrais", "vouloir", ["tok_0a5dbaae42b0c913ef9b868f"], "verb", "vouloir_conditional", "vouloir", "would like", "forme conditionnelle de vouloir exprimant un souhait poli", ["would refuse", "would forget", "would sleep"], ["refuserais", "oublierais", "dormirais"], "lem_zola_vouloir"),
  make("toucher", "toucher", ["tok_5020024ea827cdc2b8da2959"], "verb", "toucher_primary", "toucher", "to touch; affect", "entrer en contact avec ou atteindre moralement", ["to avoid", "to conceal", "to release"], ["éviter", "dissimuler", "relâcher"], "lem_toucher", "sns_toucher_primary"),
  make("religieuses", "religieux", ["tok_f1033b8a7307699190055510"], "adjective", "religieux_faith", "religieux", "religious", "qui concerne la religion ou la foi", ["military", "scientific", "judicial"], ["militaire", "scientifique", "judiciaire"]),
  make("silence", "silence", ["tok_e9e9f610c2f050ec01abe13e"], "noun", "silence_absence_sound", "silence", "silence", "absence de bruit ou de parole", ["uproar", "speech", "movement"], ["tumulte", "discours", "mouvement"]),
  make("terribles", "terrible", ["tok_81c14d1c8bbf3ef053bdc708"], "adjective", "terrible_frightening", "terrible", "terrible; dreadful", "qui inspire une grande peur ou annonce un malheur", ["comforting", "ordinary", "comic"], ["rassurant", "ordinaire", "comique"], "lem_zola_terrible", "sns_zola_terrible_frightening"),
  make("trahisons", "trahison", ["tok_ee03a90c7486078d083d55bf"], "noun", "trahison_betrayal", "trahison", "betrayal; treason", "fait de trahir une personne, un groupe ou son pays", ["alliances", "acquittals", "welcomes"], ["alliances", "acquittements", "accueils"], "lem_zola_trahison", "sns_zola_trahison_betrayal"),
  make("sévère", "severe", ["tok_2b193f750d71e444860329fa"], "adjective", "severe_strict", "sévère", "severe; strict", "qui manifeste une grande rigueur ou une dureté de jugement", ["lenient", "cheerful", "uncertain"], ["indulgent", "joyeux", "incertain"]),
  make("voudra", "vouloir", ["tok_7224ba162de122eb8fe27172"], "verb", "vouloir_future", "vouloir", "will want", "forme du futur de vouloir exprimant une volonté", ["will refuse", "will forget", "will sleep"], ["refusera", "oubliera", "dormira"], "lem_zola_vouloir", "sns_zola_vouloir_present"),
  make("reste", "rester", ["tok_bb1a4a0b903ef6d2cbd71746"], "verb", "rester_present", "rester", "remains; stays", "demeurer dans un lieu ou un état", ["leaves", "changes", "vanishes"], ["part", "change", "disparaît"], "lem_zola_rester"),
  make("rocher", "rocher", ["tok_1968453bc45a084cf7c711b2"], "noun", "rocher_cliff", "rocher", "rock; cliff", "masse de pierre naturelle, souvent élevée ou isolée", ["river", "letter", "forest"], ["rivière", "lettre", "forêt"]),
  make("soigneusement", "soigneusement", ["tok_5c9a53f408a0adf534cd7ea8"], "adverb", "soigneusement_carefully", "soigneusement", "carefully; meticulously", "avec beaucoup de soin et d’attention", ["carelessly", "publicly", "suddenly"], ["négligemment", "publiquement", "soudainement"]),
  make("saugrenu", "saugrenu", ["tok_21622c29e611bbeeb1977a77"], "adjective", "saugrenu_absurd", "saugrenu", "absurd; bizarre", "qui paraît étrange, invraisemblable ou dépourvu de bon sens", ["credible", "solemn", "ordinary"], ["crédible", "solennel", "ordinaire"]),
  make("saugrenus", "saugrenu", ["tok_45557c87032663f4d2f0a08f"], "adjective", "saugrenu_absurd", "saugrenu", "absurd; bizarre", "qui paraît étrange, invraisemblable ou dépourvu de bon sens", ["credible", "solemn", "ordinary"], ["crédibles", "solennels", "ordinaires"]),
  make("saugrenues", "saugrenu", ["tok_2debf361172a10ca3d20fdaa"], "adjective", "saugrenu_absurd", "saugrenu", "absurd; bizarre", "qui paraît étrange, invraisemblable ou dépourvu de bon sens", ["credible", "solemn", "ordinary"], ["crédibles", "solennelles", "ordinaires"]),
  make("rédaction", "redaction", ["tok_ea77c3bf4bd2b8babca328b4"], "noun", "redaction_wording", "rédaction", "wording; drafting", "manière dont un texte est écrit ou travail de le composer", ["translation", "silence", "verdict"], ["traduction", "silence", "verdict"]),
  make("vide", "vide", ["tok_9340552f9589e2582ed4e356"], "noun", "vide_void", "vide", "void; emptiness", "absence de contenu, de réalité ou de résultat", ["fullness", "evidence", "victory"], ["plénitude", "preuve", "victoire"]),
  { ...make("trouvons", "trouver", ["tok_508a3b2a767a5312ffa60c61"], "verb", "trouver_discover", "trouver", "to find; discover", "découvrir ou constater quelque chose après l’avoir cherché", ["lose", "hide", "forget"], ["perdons", "cachons", "oublions"], "lem_zola_trouver", "sns_zola_trouver_discover"), quizMeaning: "find" },
  make("sens", "sens", ["tok_62381dd3879fdb86c714883f"], "noun", "sens_direction", "sens", "direction; sense", "orientation ou ligne de conduite dans laquelle une action s’effectue", ["height", "silence", "color"], ["hauteur", "silence", "couleur"]),
];
