import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a cushion","a lighthouse","a radish"];
const nF:[string,string,string]=["coussin","phare","radis"];
const aE:[string,string,string]=["metallic","sleepy","turquoise"];
const aF:[string,string,string]=["métallique","somnolent","turquoise"];
const vE:[string,string,string]=["to fold","to juggle","to row"];
const vF:[string,string,string]=["plier","jongler","ramer"];

export const zolaVocabularyBatch15: ZolaVocabularySpec[] = [
 {normalized:"dans",lemmaKey:"dans",headword:"dans",partOfSpeech:"preposition",senseKey:"dans_in",gloss:"in; within",definition:"marque l’intérieur d’un lieu, d’un temps ou d’une situation",englishDistractors:["beneath","beside","during"],frenchDistractors:["sous","auprès de","pendant"]},
 {normalized:"dégradation",lemmaKey:"degradation",headword:"dégradation",partOfSpeech:"noun",senseKey:"degradation_demotion",gloss:"degradation; demotion",definition:"action d’abaisser publiquement quelqu’un dans son rang ou sa dignité",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"dehors",lemmaKey:"dehors",headword:"dehors",partOfSpeech:"adverb",senseKey:"dehors_outside",gloss:"outside",definition:"hors d’un lieu, d’un groupe ou d’une limite",englishDistractors:["slowly","tomorrow","clockwise"],frenchDistractors:["lentement","demain","dans le sens horaire"]},
 {normalized:"déjà",lemmaKey:"deja",headword:"déjà",partOfSpeech:"adverb",senseKey:"deja_already",gloss:"already",definition:"avant le moment considéré",englishDistractors:["slowly","upstairs","clockwise"],frenchDistractors:["lentement","à l’étage","dans le sens horaire"]},
 {normalized:"délais",lemmaKey:"delai",headword:"délai",partOfSpeech:"noun",senseKey:"delai_delay",gloss:"delay; time limit",quizMeaning:"delays",definition:"temps accordé ou écoulé avant une action",englishDistractors:["cushions","lighthouses","radishes"],frenchDistractors:["coussins","phares","radis"]},
 {normalized:"délirer",lemmaKey:"delirer",headword:"délirer",partOfSpeech:"verb",senseKey:"delirer_rave",gloss:"to rave; become delirious",definition:"perdre le contrôle de son jugement et tenir des propos déraisonnables",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"délits",lemmaKey:"delit",headword:"délit",partOfSpeech:"noun",senseKey:"delit_offense",gloss:"offense",quizMeaning:"offenses",definition:"infraction punie par la loi",englishDistractors:["cushions","lighthouses","radishes"],frenchDistractors:["coussins","phares","radis"]},
 {normalized:"demain",lemmaKey:"demain",headword:"demain",partOfSpeech:"adverb",senseKey:"demain_tomorrow",gloss:"tomorrow",definition:"le jour qui suit celui où l’on parle",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"demande",lemmaKey:"demande_noun",headword:"demande",partOfSpeech:"noun",senseKey:"demande_request",gloss:"request; application",definition:"action de solliciter officiellement quelque chose",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"demandé",lemmaKey:"demander",headword:"demander",partOfSpeech:"verb",senseKey:"demander_ask",gloss:"to ask",quizMeaning:"asked; wondered",definition:"poser une question ou chercher à savoir",englishDistractors:["folded","juggled","rowed"],frenchDistractors:["plié","jonglé","ramé"]},
 {normalized:"démence",lemmaKey:"demence",headword:"démence",partOfSpeech:"noun",senseKey:"demence_madness",gloss:"madness",definition:"état de dérèglement profond de la raison",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"démentes",lemmaKey:"dement",headword:"dément",partOfSpeech:"adjective",senseKey:"dement_mad",gloss:"mad; insane",definition:"qui manifeste un profond dérèglement de la raison",englishDistractors:aE,frenchDistractors:["métalliques","somnolentes","turquoises"]},
 {normalized:"démenti",lemmaKey:"dementi",headword:"démenti",partOfSpeech:"noun",senseKey:"dementi_denial",gloss:"denial; contradiction",definition:"déclaration ou fait qui contredit formellement une affirmation",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"démesurée",lemmaKey:"demesure",headword:"démesuré",partOfSpeech:"adjective",senseKey:"demesure_excessive",gloss:"excessive; disproportionate",definition:"qui dépasse toute mesure raisonnable",englishDistractors:aE,frenchDistractors:["métallique","somnolente","turquoise"]},
 {normalized:"démontre",lemmaKey:"demontrer",headword:"démontrer",partOfSpeech:"verb",senseKey:"demontrer_prove",gloss:"to demonstrate; prove",quizMeaning:"demonstrates; proves",definition:"établir la vérité de quelque chose par un raisonnement ou des preuves",englishDistractors:["folds","juggles","rows"],frenchDistractors:["plie","jongle","rame"]},
 {normalized:"démontré",lemmaKey:"demontrer",headword:"démontrer",partOfSpeech:"verb",senseKey:"demontrer_prove",gloss:"to demonstrate; prove",quizMeaning:"demonstrated; proved",definition:"établir la vérité de quelque chose par un raisonnement ou des preuves",englishDistractors:["folded","juggled","rowed"],frenchDistractors:["plié","jonglé","ramé"]},
 {normalized:"déni",lemmaKey:"deni",headword:"déni",partOfSpeech:"noun",senseKey:"deni_denial",gloss:"denial",definition:"refus de reconnaître ou d’accorder ce qui est dû",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"dénonça",lemmaKey:"denoncer",headword:"dénoncer",partOfSpeech:"verb",senseKey:"denoncer_report",gloss:"to denounce; report",quizMeaning:"denounced; reported",definition:"signaler publiquement ou à une autorité une personne ou un fait répréhensible",englishDistractors:["folded","juggled","rowed"],frenchDistractors:["plia","jongla","rama"]},
 {normalized:"dénoncé",lemmaKey:"denoncer",headword:"dénoncer",partOfSpeech:"verb",senseKey:"denoncer_report",gloss:"to denounce; report",quizMeaning:"denounced; reported",definition:"signaler publiquement ou à une autorité une personne ou un fait répréhensible",englishDistractors:["folded","juggled","rowed"],frenchDistractors:["plié","jonglé","ramé"]},
 {normalized:"dénoncerai",lemmaKey:"denoncer",headword:"dénoncer",partOfSpeech:"verb",senseKey:"denoncer_report",gloss:"to denounce; report",quizMeaning:"will denounce; will report",definition:"signaler publiquement ou à une autorité une personne ou un fait répréhensible",englishDistractors:["will fold","will juggle","will row"],frenchDistractors:["plierai","jonglerai","ramerai"]},
 {normalized:"dénouement",lemmaKey:"denouement",headword:"dénouement",partOfSpeech:"noun",senseKey:"denouement_outcome",gloss:"outcome; ending",definition:"événement final qui résout ou achève une affaire",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"déposer",lemmaKey:"deposer",headword:"déposer",partOfSpeech:"verb",senseKey:"deposer_submit",gloss:"to submit; lodge",definition:"remettre officiellement une demande ou un document",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"depuis",lemmaKey:"depuis",headword:"depuis",partOfSpeech:"preposition",senseKey:"depuis_since",gloss:"since; for",definition:"marque le point de départ ou la durée d’une action jusqu’au moment considéré",englishDistractors:["beneath","beside","despite"],frenchDistractors:["sous","auprès de","malgré"]},
 {normalized:"dérangée",lemmaKey:"deranger",headword:"déranger",partOfSpeech:"verb",senseKey:"deranger_go_out_of_way",gloss:"to inconvenience; go out of one’s way",quizMeaning:"went out of her way",definition:"quitter ses habitudes ou se donner de la peine pour agir",englishDistractors:["folded","juggled","rowed"],frenchDistractors:["pliée","jonglée","ramée"]},
 {normalized:"dernier",lemmaKey:"dernier",headword:"dernier",partOfSpeech:"adjective",senseKey:"dernier_latter",gloss:"last; latter",definition:"qui vient après tous les autres ou désigne le second de deux éléments",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"derrière",lemmaKey:"derriere",headword:"derrière",partOfSpeech:"preposition",senseKey:"derriere_behind",gloss:"behind",definition:"à l’arrière de quelqu’un ou de quelque chose, au propre ou au figuré",englishDistractors:["beneath","during","beside"],frenchDistractors:["sous","pendant","auprès de"]},
];
