import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a telescope", "a pumpkin", "a hammock"];
const nounFrench: [string, string, string] = ["un télescope", "une citrouille", "un hamac"];
const adjectiveEnglish: [string, string, string] = ["polka-dotted", "lemon-scented", "cylindrical"];
const adjectiveFrench: [string, string, string] = ["à pois", "parfumé au citron", "cylindrique"];

export const zolaVocabularyBatch26: ZolaVocabularySpec[] = [
  { normalized: "hommes", lemmaKey: "homme", existingLemmaId: "lem_zola_homme", existingSenseId: "sns_zola_homme_man_human", headword: "homme", partOfSpeech: "noun", senseKey: "homme_man_human", gloss: "man; human being", quizMeaning: "men; human beings", definition: "être humain, ou personne adulte de sexe masculin selon le contexte", englishDistractors: ["telescopes", "pumpkins", "hammocks"], frenchDistractors: ["télescopes", "citrouilles", "hamacs"] },
  { normalized: "honnête", lemmaKey: "honnete", headword: "honnête", partOfSpeech: "adjective", senseKey: "honnete_upright", gloss: "honest; upright", definition: "qui agit avec droiture, loyauté et probité", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "honnêtes", lemmaKey: "honnete", headword: "honnête", partOfSpeech: "adjective", senseKey: "honnete_upright", gloss: "honest; upright", definition: "qui agit avec droiture, loyauté et probité", englishDistractors: adjectiveEnglish, frenchDistractors: ["à pois", "parfumés au citron", "cylindriques"] },
  { normalized: "honorent", lemmaKey: "honorer", headword: "honorer", partOfSpeech: "verb", senseKey: "honorer_bring_honor", gloss: "to honor; do credit to", quizMeaning: "honor; do credit to", definition: "témoigner de l’estime ou faire ressortir la dignité de quelqu’un", englishDistractors: ["fold", "row", "hiccup"], frenchDistractors: ["plient", "rament", "hoquettent"] },
  { normalized: "honorer", lemmaKey: "honorer", headword: "honorer", partOfSpeech: "verb", senseKey: "honorer_bring_honor", gloss: "to honor; do credit to", definition: "témoigner de l’estime ou faire ressortir la dignité de quelqu’un", englishDistractors: ["to fold", "to row", "to hiccup"], frenchDistractors: ["plier", "ramer", "hoqueter"] },
  { normalized: "honteuse", lemmaKey: "honteux", headword: "honteux", partOfSpeech: "adjective", senseKey: "honteux_shameful", gloss: "shameful; disgraceful", definition: "qui provoque la honte ou mérite une sévère réprobation", englishDistractors: adjectiveEnglish, frenchDistractors: ["à pois", "parfumée au citron", "cylindrique"] },
  { normalized: "huis", lemmaKey: "huis", headword: "huis", partOfSpeech: "noun", senseKey: "huis_door", gloss: "door; closed-door setting", definition: "mot ancien pour une porte, conservé dans l’expression « huis clos »", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "humain", lemmaKey: "humain", headword: "humain", partOfSpeech: "adjective", senseKey: "humain_human", gloss: "human", definition: "qui appartient à l’être humain ou concerne l’humanité", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "humaine", lemmaKey: "humain", headword: "humain", partOfSpeech: "adjective", senseKey: "humain_human", gloss: "human", definition: "qui appartient à l’être humain ou concerne l’humanité", englishDistractors: adjectiveEnglish, frenchDistractors: ["à pois", "parfumée au citron", "cylindrique"] },
  { normalized: "humanité", lemmaKey: "humanite", headword: "humanité", partOfSpeech: "noun", senseKey: "humanite_humankind", gloss: "humanity; humankind", definition: "ensemble des êtres humains, considéré comme une communauté", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "humbles", lemmaKey: "humble", headword: "humble", partOfSpeech: "adjective", senseKey: "humble_lowly", gloss: "humble; lowly", definition: "de condition modeste ou dépourvu de pouvoir social", englishDistractors: adjectiveEnglish, frenchDistractors: ["à pois", "parfumés au citron", "cylindriques"] },
  { normalized: "hurlait", lemmaKey: "hurler", headword: "hurler", partOfSpeech: "verb", senseKey: "hurler_shout", gloss: "to howl; shout", quizMeaning: "was howling; was shouting", definition: "crier d’une voix très forte et prolongée", englishDistractors: ["was folding", "was rowing", "was hiccupping"], frenchDistractors: ["pliait", "ramait", "hoquetait"] },
  { normalized: "hypnotise", lemmaKey: "hypnotiser", headword: "hypnotiser", partOfSpeech: "verb", senseKey: "hypnotiser_control", gloss: "to hypnotize; mesmerize", quizMeaning: "hypnotizes; mesmerizes", definition: "placer sous une influence qui fascine et prive de discernement", englishDistractors: ["folds", "rows", "hiccups"], frenchDistractors: ["plie", "rame", "hoquette"] },
  { normalized: "ici", lemmaKey: "ici", headword: "ici", partOfSpeech: "adverb", senseKey: "ici_here", gloss: "here; at this point", definition: "dans ce lieu, ce passage ou cette situation précise", englishDistractors: ["silently", "upstairs", "tomorrow"], frenchDistractors: ["silencieusement", "à l’étage", "demain"] },
  { normalized: "idée", lemmaKey: "idee", headword: "idée", partOfSpeech: "noun", senseKey: "idee_conception", gloss: "idea; conception", definition: "représentation ou conception formée par l’esprit", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "ignoble", lemmaKey: "ignoble", headword: "ignoble", partOfSpeech: "adjective", senseKey: "ignoble_vile", gloss: "vile; disgraceful", definition: "qui inspire un profond mépris par sa bassesse morale", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "ignore", lemmaKey: "ignorer", headword: "ignorer", partOfSpeech: "verb", senseKey: "ignorer_not_know", gloss: "not to know; be unaware of", quizMeaning: "am unaware of", definition: "ne pas connaître ou ne pas avoir conscience de quelque chose", englishDistractors: ["fold", "row", "hiccup"], frenchDistractors: ["plie", "rame", "hoquette"] },
  { normalized: "ignorez", lemmaKey: "ignorer", headword: "ignorer", partOfSpeech: "verb", senseKey: "ignorer_not_know", gloss: "not to know; be unaware of", quizMeaning: "are unaware of", definition: "ne pas connaître ou ne pas avoir conscience de quelque chose", englishDistractors: ["fold", "row", "hiccup"], frenchDistractors: ["pliez", "ramez", "hoquetez"] },
  { normalized: "ignorons", lemmaKey: "ignorer", headword: "ignorer", partOfSpeech: "verb", senseKey: "ignorer_not_know", gloss: "not to know; be unaware of", quizMeaning: "do not know; are unaware of", definition: "ne pas connaître ou ne pas avoir conscience de quelque chose", englishDistractors: ["fold", "row", "hiccup"], frenchDistractors: ["plions", "ramons", "hoquetons"] },
  { normalized: "île", lemmaKey: "ile", headword: "île", partOfSpeech: "noun", senseKey: "ile_island", gloss: "island", definition: "étendue de terre entièrement entourée d’eau", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "illégalité", lemmaKey: "illegalite", headword: "illégalité", partOfSpeech: "noun", senseKey: "illegalite_unlawfulness", gloss: "illegality; unlawful act", definition: "caractère ou acte contraire à la loi", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "ils", lemmaKey: "ils", headword: "ils", partOfSpeech: "pronoun", senseKey: "ils_they", gloss: "they", definition: "pronom personnel désignant plusieurs personnes ou éléments déjà mentionnés", englishDistractors: ["the telescopes", "the pumpkins", "the hammocks"], frenchDistractors: ["les télescopes", "les citrouilles", "les hamacs"] },
  { normalized: "imagina", lemmaKey: "imaginer", headword: "imaginer", partOfSpeech: "verb", senseKey: "imaginer_devise", gloss: "to imagine; devise", quizMeaning: "imagined; devised", definition: "concevoir dans son esprit ou inventer un procédé", englishDistractors: ["folded", "rowed", "hiccupped"], frenchDistractors: ["plia", "rama", "hoqueta"] },
  { normalized: "imaginables", lemmaKey: "imaginable", headword: "imaginable", partOfSpeech: "adjective", senseKey: "imaginable_conceivable", gloss: "imaginable; conceivable", definition: "que l’esprit peut concevoir ou supposer", englishDistractors: adjectiveEnglish, frenchDistractors: ["à pois", "parfumés au citron", "cylindriques"] },
  { normalized: "imagination", lemmaKey: "imagination", headword: "imagination", partOfSpeech: "noun", senseKey: "imagination_fancy", gloss: "imagination; fancy", definition: "faculté de former des représentations ou d’inventer des idées", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "imaginations", lemmaKey: "imagination", headword: "imagination", partOfSpeech: "noun", senseKey: "imagination_fancy", gloss: "imagination; fancy", quizMeaning: "imaginations; fantasies", definition: "faculté de former des représentations ou d’inventer des idées", englishDistractors: ["telescopes", "pumpkins", "hammocks"], frenchDistractors: ["télescopes", "citrouilles", "hamacs"] },
];
