import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch04: Record<string, EditorialQuizSet> = {
  "anonymes:anonyme_unsigned": {
    early: "Deux lettres anonymes arrivent sans nom d’auteur.", englishChoices: ["anonymous", "signed", "identified", "attributed"],
    intermediate: "Ces lettres sont _____ : leurs auteurs n’ont laissé aucun nom.", frenchChoices: ["anonymes", "signées", "nominatives", "identifiées"],
    advanced: "Deux lettres anonymes arrivent sans nom d’auteur. Les autres courriers sont signés, les billets sont datés et les formulaires sont officiels.",
    prompt: "Quel mot qualifie les lettres dont les auteurs sont inconnus ?", advancedChoices: ["anonymes", "signés", "datés", "officiels"],
  },
  "ans:an_year": {
    early: "Léa a vécu trois ans près de la mer.", englishChoices: ["years", "months", "weeks", "days"],
    intermediate: "De 2020 à 2023, il s’est écoulé trois _____.", frenchChoices: ["ans", "jours", "mois", "siècles"],
    advanced: "Après trois ans de voyage, Nina revient. Paul est parti hier, Léa restera un mois et Luc attend depuis un jour.",
    prompt: "Quel mot désigne ici trois périodes de douze mois ?", advancedChoices: ["ans", "hier", "mois", "jour"],
  },
  "antisémite:antisemite": {
    early: "Un tract antisémite attaque les personnes juives en raison de leur identité.", englishChoices: ["antisemitic", "antiracist", "impartial", "supportive"],
    intermediate: "Ce texte appelle à exclure les Juifs parce qu’ils sont juifs : il est _____.", frenchChoices: ["antisémite", "antiraciste", "solidaire", "impartial"],
    advanced: "Le tract antisémite vise les Juifs en raison de leur identité. Une association antiraciste le dénonce, un journal local relaie la plainte et un voisin lit l’affiche.",
    prompt: "Quel mot qualifie le préjugé hostile aux personnes juives ?", advancedChoices: ["antisémite", "antiraciste", "local", "voisin"],
  },
  "antisémitisme:antisemitisme": {
    early: "Cette association lutte contre l’antisémitisme dans la ville.", englishChoices: ["antisemitism", "friendship", "solidarity", "tolerance"],
    intermediate: "L’association combat l’_____ qui vise les personnes juives.", frenchChoices: ["antisémitisme", "entraide", "amitié", "équité"],
    advanced: "L’antisémitisme vise les personnes juives. Une association organise un débat, distribue des brochures et invite les voisins à refuser ces préjugés.",
    prompt: "Quel mot nomme précisément cette hostilité envers les personnes juives ?", advancedChoices: ["antisémitisme", "association", "brochures", "voisins"],
  },
  "apothéose:apotheose_glorification": {
    early: "Sa victoire finale fut l’apothéose de sa carrière.", englishChoices: ["glorious culmination", "humiliating defeat", "uncertain beginning", "brief pause"],
    intermediate: "Son dernier concert est l’_____ de sa carrière : la salle entière l’acclame longtemps.", frenchChoices: ["apothéose", "échec", "oubli", "interruption"],
    advanced: "Le concert final fut l’apothéose de sa carrière : la foule l’acclama longuement. Le programme était simple, la scène étroite et les billets modestes.",
    prompt: "Quel mot désigne le sommet glorieux de sa carrière ?", advancedChoices: ["apothéose", "programme", "scène", "billets"],
  },
  "apparaissait:apparaitre_seem": {
    early: "De loin, le village apparaissait au milieu de la brume.", englishChoices: ["appeared", "vanished", "collapsed", "grew"],
    intermediate: "À mesure que nous approchions, le phare _____ enfin à travers la brume.", frenchChoices: ["apparaissait", "s’écroulait", "s’éteignait", "s’enfonçait"],
    advanced: "Le phare apparaissait au loin dans la brume. Nina marchait sur la plage, Luc tenait une lampe et Marie écoutait la mer.",
    prompt: "Quel mot indique que le phare devenait visible ?", advancedChoices: ["apparaissait", "marchait", "tenait", "écoutait"],
  },
  "apparaissez:apparaitre_seem": {
    early: "Sur cette photo de classe, vous apparaissez au premier rang.", englishChoices: ["you appear", "you hide", "you vanish", "you leave"],
    intermediate: "Sur cette photo de groupe, vous _____ au premier rang.", frenchChoices: ["apparaissez", "apparais", "apparaît", "apparaissent"],
    advanced: "Vous apparaissez sur la photo, près de Luc. Marie cache son visage, Paul sort de la pièce et Léa regarde l’appareil.",
    prompt: "Quel mot indique que l’interlocuteur est visible sur la photo ?", advancedChoices: ["apparaissez", "cache", "sort", "regarde"],
  },
  "apparaît:apparaitre_seem": {
    early: "Une étoile apparaît dans le ciel quand la nuit tombe.", englishChoices: ["appears", "falls", "dims", "disappears"],
    intermediate: "Après la pluie, un arc-en-ciel _____ et les enfants le découvrent dans le ciel.", frenchChoices: ["apparaît", "disparaît", "tombe", "s’éteint"],
    advanced: "Une étoile apparaît au-dessus du village. Luc ouvre sa fenêtre, Marie observe le ciel et Paul ferme sa lampe.",
    prompt: "Quel mot indique que l’étoile devient visible ?", advancedChoices: ["apparaît", "ouvre", "observe", "ferme"],
  },
  "appartenaient:appartenir_belong": {
    early: "Ces trois musiciens appartenaient au même orchestre.", englishChoices: ["belonged", "opposed", "conducted", "replaced"],
    intermediate: "Tous ces joueurs _____ à la même équipe à cette époque.", frenchChoices: ["appartenaient", "s’opposaient", "arrivaient", "assistaient"],
    advanced: "À cette époque, Nina et Léa appartenaient au même groupe de théâtre. Luc organisait les répétitions, Paul préparait les costumes et Marie réservait la salle.",
    prompt: "Quel mot indique que Nina et Léa faisaient partie du groupe ?", advancedChoices: ["appartenaient", "organisait", "préparait", "réservait"],
  },
  "appelle:appeler_name": {
    early: "Nina appelle son nouveau chat Biscotte.", englishChoices: ["names", "finds", "follows", "feeds"],
    intermediate: "Elle _____ son nouveau chat « Biscotte ».", frenchChoices: ["appelle", "invite", "cherche", "observe"],
    advanced: "Nina appelle son chat Biscotte. Luc cherche son chien, Marie nourrit son lapin et Paul regarde les oiseaux.",
    prompt: "Quel mot indique le nom que Nina donne à son chat ?", advancedChoices: ["appelle", "cherche", "nourrit", "regarde"],
  },
  "applaudira:applaudir_approve": {
    early: "Le public applaudira la chanteuse à la fin du concert.", englishChoices: ["will applaud", "will criticize", "will ignore", "will interrupt"],
    intermediate: "Si elle réussit, la salle l’_____ pour saluer sa performance.", frenchChoices: ["applaudira", "sifflera", "ignorera", "chassera"],
    advanced: "Après le concert, le public applaudira la chanteuse. Nina préparera les fleurs, Paul fermera la salle et Luc écrira une critique.",
    prompt: "Quel mot exprime l’approbation future du public ?", advancedChoices: ["applaudira", "préparera", "fermera", "écrira"],
  },
  "apportée:apporter_bring": {
    early: "La boîte apportée par Nina est posée sur la table.", englishChoices: ["brought", "lost", "broken", "opened"],
    intermediate: "Cette valise, _____ par Luc, est maintenant dans le salon.", frenchChoices: ["apportée", "apporté", "apporter", "apportées"],
    advanced: "La valise apportée par Luc reste près de la porte. Nina porte un manteau, Marie cherche un sac et Paul ferme la fenêtre.",
    prompt: "Quel mot indique que Luc a amené la valise ici ?", advancedChoices: ["apportée", "porte", "cherche", "ferme"],
  },
  "apprenons:apprendre_learn": {
    early: "Nous apprenons aujourd’hui que le musée fermera lundi.", englishChoices: ["we learn", "we conceal", "we forget", "we deny"],
    intermediate: "En lisant l’annonce, nous _____ que le train est annulé.", frenchChoices: ["apprenons", "oublions", "cachons", "nions"],
    advanced: "En lisant l’affiche, nous apprenons que le musée fermera lundi. Luc ferme son livre, Nina cherche ses clés et Paul attend le bus.",
    prompt: "Quel mot signifie que cette information devient connue de nous ?", advancedChoices: ["apprenons", "ferme", "cherche", "attend"],
  },
  "appuyé:s_appuyer_rely": {
    early: "Pour décider, Paul s’est appuyé sur l’avis du médecin.", englishChoices: ["relied", "hesitated", "wandered", "complained"],
    intermediate: "Pour rédiger son rapport, il s’est _____ sur les données vérifiées.", frenchChoices: ["appuyé", "appuyée", "appuyés", "appuyer"],
    advanced: "Pour choisir son traitement, Paul s’est appuyé sur les analyses. Marie a consulté un livre, Luc a écouté un collègue et Nina a rangé ses notes.",
    prompt: "Quel mot indique que Paul a pris les analyses pour soutien ?", advancedChoices: ["appuyé", "consulté", "écouté", "rangé"],
  },
  "après:apres_following": {
    early: "Après le dîner, nous allons nous promener.", englishChoices: ["after", "before", "during", "despite"],
    intermediate: "Nous sortirons _____ le dîner, une fois le repas terminé.", frenchChoices: ["après", "avant", "sous", "vers"],
    advanced: "Après le dîner, Nina lit au salon. Avant le repas, Paul cuisine ; pendant la soirée, Luc joue du piano et Marie attend dehors.",
    prompt: "Quel mot situe la lecture à la suite du dîner ?", advancedChoices: ["après", "Avant", "pendant", "dehors"],
  },
  "arche:arche_sacred_chest": {
    early: "Dans ce récit ancien, l’arche renferme les objets sacrés du peuple.", englishChoices: ["sacred chest", "stone arch", "market stall", "water vessel"],
    intermediate: "Dans le récit ancien, les prêtres transportent l’_____ de l’Alliance.", frenchChoices: ["arche", "armée", "arène", "adresse"],
    advanced: "Dans ce récit, l’arche renferme des objets sacrés. La porte est fermée, le rideau tombe et le jardin est silencieux.",
    prompt: "Quel mot nomme le coffre sacré ?", advancedChoices: ["arche", "porte", "rideau", "jardin"],
  },
  "armé:arme_equipped": {
    early: "Le gardien armé porte un fusil.", englishChoices: ["armed", "unarmed", "asleep", "untrained"],
    intermediate: "Le soldat, _____ d’un fusil, monte la garde.", frenchChoices: ["armé", "désarmé", "fatigué", "rassuré"],
    advanced: "Le gardien armé tient un fusil. Le visiteur est calme, le médecin regarde la porte et la secrétaire porte un dossier.",
    prompt: "Quel mot indique que le gardien est muni d’une arme ?", advancedChoices: ["armé", "calme", "regarde", "porte"],
  },
  "armée:armee_military": {
    early: "L’armée organise les secours après la tempête.", englishChoices: ["army", "hospital", "school", "village"],
    intermediate: "Les soldats de l’_____ avancent ensemble sous les ordres du général.", frenchChoices: ["armée", "école", "entreprise", "famille"],
    advanced: "L’armée avance sous les ordres du général. Un hôpital accueille des blessés, l’école ferme ses portes et le village reste calme.",
    prompt: "Quel mot désigne l’ensemble organisé des soldats ?", advancedChoices: ["armée", "hôpital", "école", "village"],
  },
  "arrachait:arracher_tear": {
    early: "Le vent arrachait les tuiles du toit pendant la tempête.", englishChoices: ["was tearing off", "was repairing", "was painting", "was counting"],
    intermediate: "La tempête _____ les tuiles du toit à chaque rafale ; elles tombaient dans la rue.", frenchChoices: ["arrachait", "réparait", "fixait", "nettoyait"],
    advanced: "Le vent arrachait les tuiles du toit. Paul fermait les volets, Nina regardait la rue et Luc tenait la porte.",
    prompt: "Quel mot indique que le vent enlevait violemment les tuiles ?", advancedChoices: ["arrachait", "fermait", "regardait", "tenait"],
  },
  "arrêtera:arreter_stop": {
    early: "La barrière arrêtera les voitures avant le pont.", englishChoices: ["will stop", "will guide", "will follow", "will count"],
    intermediate: "Si le voyant devient rouge, le conducteur _____ immédiatement la machine.", frenchChoices: ["arrêtera", "accélérera", "oubliera", "lavera"],
    advanced: "La barrière arrêtera les voitures avant le pont. Le gardien ouvrira la porte, l’agent surveillera la route et le mécanicien réparera le signal.",
    prompt: "Quel mot annonce que la barrière empêchera les voitures d’avancer ?", advancedChoices: ["arrêtera", "ouvrira", "surveillera", "réparera"],
  },
  "arrête:arreter_arrest": {
    early: "La police arrête le suspect après le vol.", englishChoices: ["arrests", "releases", "praises", "follows"],
    intermediate: "Après le vol, la police _____ le suspect et le conduit au poste.", frenchChoices: ["arrête", "félicite", "aide", "libère"],
    advanced: "La police arrête le suspect et le conduit au poste. Un témoin raconte les faits, l’avocat ouvre son dossier et la victime rentre chez elle.",
    prompt: "Quel mot indique que la police place le suspect en état d’arrestation ?", advancedChoices: ["arrête", "raconte", "ouvre", "rentre"],
  },
  "arrêts:arret_judgment": {
    early: "Les arrêts de cette cour sont publiés chaque mois.", englishChoices: ["court rulings", "traffic stops", "delays", "breaks"],
    intermediate: "La cour rend plusieurs _____ motivés sur ces affaires.", frenchChoices: ["arrêts", "pauses", "voyages", "retards"],
    advanced: "Les arrêts rendus par la cour sont publiés. Les juges signent les décisions, les dossiers restent au greffe et les témoins rentrent chez eux.",
    prompt: "Quel mot désigne les décisions officielles rendues par la cour ?", advancedChoices: ["arrêts", "juges", "dossiers", "témoins"],
  },
  "articles:article_law": {
    early: "Les articles du code fixent les peines prévues.", englishChoices: ["legal provisions", "news stories", "objects", "opinions"],
    intermediate: "Les _____ 3 et 4 de cette loi fixent les peines prévues.", frenchChoices: ["articles", "contrats", "témoins", "enfants"],
    advanced: "Les articles de cette loi définissent les obligations. Les paragraphes expliquent les exceptions, les juges étudient le texte et les témoins attendent.",
    prompt: "Quel mot désigne les divisions numérotées de la loi ?", advancedChoices: ["articles", "paragraphes", "juges", "témoins"],
  },
  "artillerie:artillerie": {
    early: "Sur la colline, l’artillerie tire avant l’avancée des soldats.", englishChoices: ["artillery", "infantry", "cavalry", "navy"],
    intermediate: "Les soldats préparent les canons ; l’_____ ouvrira le feu depuis la colline.", frenchChoices: ["artillerie", "infanterie", "cavalerie", "marine"],
    advanced: "L’artillerie tire depuis la colline. Les fantassins avancent dans la vallée, les navires restent au port et les blindés traversent le pont.",
    prompt: "Quel mot désigne l’unité qui manie les canons ?", advancedChoices: ["artillerie", "fantassins", "navires", "blindés"],
  },
  "asile:asile_refuge": {
    early: "Le monastère leur offre un asile pendant la guerre.", englishChoices: ["sanctuary", "prison", "workplace", "hospital"],
    intermediate: "Fuyant la violence, ils demandent un _____ où ils seront protégés.", frenchChoices: ["asile", "combat", "danger", "exil"],
    advanced: "Les voyageurs trouvent un asile dans le monastère et y restent en sécurité. Un gardien ferme le portail, des voisins apportent du pain et la route reste dangereuse.",
    prompt: "Quel mot désigne le lieu qui protège les voyageurs ?", advancedChoices: ["asile", "gardien", "voisins", "route"],
  },
};
