import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEn: [string,string,string] = ["a bicycle", "a kettle", "a vineyard"];
const nounFr: [string,string,string] = ["bicyclette", "bouilloire", "vignoble"];
const verbEn: [string,string,string] = ["to crochet", "to dive", "to sneeze"];
const verbFr: [string,string,string] = ["crocheter", "plonger", "éternuer"];
const advEn: [string,string,string] = ["quietly", "upstairs", "clockwise"];
const advFr: [string,string,string] = ["calmement", "à l’étage", "dans le sens horaire"];

export const zolaVocabularyBatch05: ZolaVocabularySpec[] = [
  { normalized:"arrivait", lemmaKey:"arriver", headword:"arriver", partOfSpeech:"verb", senseKey:"arriver_reach", gloss:"to arrive", quizMeaning:"was arriving", definition:"parvenir à un lieu ou à un moment", englishDistractors:["was crocheting","was diving","was sneezing"], frenchDistractors:["crochetait","plongeait","éternuait"] },
  { normalized:"arrivons", lemmaKey:"arriver", headword:"arriver", partOfSpeech:"verb", senseKey:"arriver_come_to", gloss:"to come to; reach", quizMeaning:"we come to", definition:"aborder un point dans un raisonnement", englishDistractors:["we crochet","we dive","we sneeze"], frenchDistractors:["nous crochetons","nous plongeons","nous éternuons"] },
  { normalized:"assertions", lemmaKey:"assertion", headword:"assertion", partOfSpeech:"noun", senseKey:"assertion_claim", gloss:"assertions; claims", definition:"affirmations présentées comme certaines", englishDistractors:["bicycles","kettles","vineyards"], frenchDistractors:["bicyclettes","bouilloires","vignobles"] },
  { normalized:"assez", lemmaKey:"assez", headword:"assez", partOfSpeech:"adverb", senseKey:"assez_enough", gloss:"enough; sufficiently", definition:"dans une mesure suffisante", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"assises", lemmaKey:"assises", headword:"assises", partOfSpeech:"noun", senseKey:"cour_assises", gloss:"criminal court; assize court", definition:"juridiction jugeant les crimes", englishDistractors:["bicycles","kettles","vineyards"], frenchDistractors:["bicyclettes","bouilloires","vignobles"] },
  { normalized:"assistons", lemmaKey:"assister", headword:"assister", partOfSpeech:"verb", senseKey:"assister_witness", gloss:"to witness; attend", quizMeaning:"we witness", definition:"être présent comme témoin", englishDistractors:["we crochet","we dive","we sneeze"], frenchDistractors:["nous crochetons","nous plongeons","nous éternuons"] },
  { normalized:"assurance", lemmaKey:"assurance", headword:"assurance", partOfSpeech:"noun", senseKey:"assurance_expression", gloss:"assurance; expression", definition:"formule affirmant avec certitude un sentiment", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"assurer", lemmaKey:"assurer", headword:"assurer", partOfSpeech:"verb", senseKey:"s_assurer_verify", gloss:"to make sure; verify", definition:"vérifier afin d’acquérir une certitude", englishDistractors:verbEn, frenchDistractors:verbFr },
  { normalized:"atteints", lemmaKey:"atteindre", headword:"atteindre", partOfSpeech:"verb", senseKey:"atteindre_afflict", gloss:"afflicted; affected", definition:"touchés par une maladie", englishDistractors:["crocheted","dived","sneezed"], frenchDistractors:["crochetés","plongés","éternués"] },
  { normalized:"attends", lemmaKey:"attendre", headword:"attendre", partOfSpeech:"verb", senseKey:"attendre_wait", gloss:"to wait", quizMeaning:"I wait", definition:"demeurer jusqu’à ce qu’un événement arrive", englishDistractors:["I crochet","I dive","I sneeze"], frenchDistractors:["je crochète","je plonge","j’éternue"] },
  { normalized:"attendu", lemmaKey:"attendu_adjective", headword:"attendu", partOfSpeech:"adjective", senseKey:"attendu_expected", gloss:"expected", definition:"prévu ou considéré comme devant arriver", englishDistractors:["striped","ceramic","peppery"], frenchDistractors:["rayé","céramique","poivré"] },
  { normalized:"attentivement", lemmaKey:"attentivement", headword:"attentivement", partOfSpeech:"adverb", senseKey:"attentivement", gloss:"attentively; carefully", definition:"avec une attention soutenue", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"attitude", lemmaKey:"attitude", headword:"attitude", partOfSpeech:"noun", senseKey:"attitude_behavior", gloss:"attitude; demeanor", definition:"manière de se comporter", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"aucun", lemmaKey:"aucun", headword:"aucun", partOfSpeech:"determiner", senseKey:"aucun_none", gloss:"no; not any", definition:"pas un seul", englishDistractors:["each","several","both"], frenchDistractors:["chaque","plusieurs","les deux"] },
  { normalized:"audace", lemmaKey:"audace", headword:"audace", partOfSpeech:"noun", senseKey:"audace_boldness", gloss:"boldness; audacity", definition:"courage poussé jusqu’à braver les risques", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"aujourd’hui", lemmaKey:"aujourd_hui", headword:"aujourd’hui", partOfSpeech:"adverb", senseKey:"aujourd_hui_today", gloss:"today; nowadays", definition:"le jour présent ou l’époque présente", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"auprès", lemmaKey:"aupres", headword:"auprès", partOfSpeech:"preposition", senseKey:"aupres_near", gloss:"with; near; in the presence of", definition:"près de quelqu’un ou en s’adressant à lui", englishDistractors:["beneath","despite","across"], frenchDistractors:["sous","malgré","à travers"] },
  { normalized:"auquel", lemmaKey:"auquel", headword:"auquel", partOfSpeech:"relative pronoun", senseKey:"auquel_to_which", gloss:"to which", definition:"pronom relatif contractant à et lequel", englishDistractors:["without whom","beneath which","despite whom"], frenchDistractors:["sans lequel","sous lequel","malgré lequel"] },
  { normalized:"aura", lemmaKey:"avoir", headword:"avoir", partOfSpeech:"verb", senseKey:"avoir_possess_auxiliary", gloss:"to have; auxiliary avoir", quizMeaning:"will have", definition:"posséder ou servir d’auxiliaire", englishDistractors:["will crochet","will dive","will sneeze"], frenchDistractors:["crochètera","plongera","éternuera"] },
  { normalized:"aurait", lemmaKey:"avoir", headword:"avoir", partOfSpeech:"verb", senseKey:"avoir_possess_auxiliary", gloss:"to have; auxiliary avoir", quizMeaning:"would have", definition:"posséder ou servir d’auxiliaire", englishDistractors:["would crochet","would dive","would sneeze"], frenchDistractors:["crochèterait","plongerait","éternuerait"] },
  { normalized:"aussi", candidateIds:["tok_e02ea3bc8478dfc81fb92262","tok_0b79d65efc4eeac1a84d4869","tok_cc2f5ebc25261067bcba61bd","tok_4470d95d933ff590b9bef925","tok_64607c508fe5ec156990e121","tok_23a8b3d53fa496ae81596f90","tok_5ba675ee7a26aa0c3e41940c"], lemmaKey:"aussi", headword:"aussi", partOfSpeech:"adverb", senseKey:"aussi_also", gloss:"also; too", definition:"en plus, également", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"aussi", candidateIds:["tok_0b73e1ec8c786ccdbf0bb9d3"], lemmaKey:"aussi", headword:"aussi", partOfSpeech:"adverb", senseKey:"aussi_therefore", gloss:"therefore; consequently", definition:"introduit une conséquence", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"autant", lemmaKey:"autant", headword:"autant", partOfSpeech:"adverb", senseKey:"d_autant_plus", gloss:"all the more", definition:"dans une mesure d’autant plus grande", englishDistractors:advEn, frenchDistractors:advFr },
  { normalized:"auteur", lemmaKey:"auteur", headword:"auteur", partOfSpeech:"noun", senseKey:"auteur_originator", gloss:"author; originator", definition:"personne qui a produit un écrit ou un acte", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"autorité", lemmaKey:"autorite", headword:"autorité", partOfSpeech:"noun", senseKey:"autorite_power", gloss:"authority", definition:"pouvoir reconnu de décider ou d’imposer", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"auxquelles", lemmaKey:"auquel", headword:"auquel", partOfSpeech:"relative pronoun", senseKey:"auquel_to_which", gloss:"to which", definition:"pronom relatif contractant à et lequel", englishDistractors:["without which","beneath which","despite which"], frenchDistractors:["sans lesquelles","sous lesquelles","malgré lesquelles"] },
];
