import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch03: Record<string, EditorialQuizSet> = {
  "agissait:s_agir_concern": {
    early: "Il s’agissait d’une simple erreur de date, et non d’une fraude.", englishChoices: ["was a matter of", "was going away", "was arriving", "was sleeping"],
    intermediate: "À cette époque, il s’_____ d’une erreur de date, et non d’une fraude.", frenchChoices: ["agissait", "agissent", "agira", "agissant"],
    advanced: "Il s’agissait d’une erreur de date. Luc examinait le registre, Marie comptait les pages et Paul cherchait le bon dossier.",
    prompt: "Quel mot, après « s’ », indique de quoi il était question ?", advancedChoices: ["agissait", "examinait", "comptait", "cherchait"],
  },
  "agissait:agir_act": {
    early: "Tandis que tout le monde attendait, Léa agissait déjà.", englishChoices: ["was acting", "was hesitating", "was sleeping", "was complaining"],
    intermediate: "Pendant que les autres hésitaient, Léa _____ pour protéger l’enfant.", frenchChoices: ["agissait", "dormait", "oubliait", "tombait"],
    advanced: "Léa agissait vite pour mettre l’enfant à l’abri. Paul hésitait, Marie attendait les secours et Luc regardait la route.",
    prompt: "Quel mot indique que Léa passait à l’action ?", advancedChoices: ["agissait", "hésitait", "attendait", "regardait"],
  },
  "agit:s_agir_concern": {
    early: "Il s’agit d’un colis pour Marie, pas d’une lettre.", englishChoices: ["is a matter of", "is walking", "is working", "is disappearing"],
    intermediate: "Il ne s’_____ pas d’un cadeau : c’est un prêt.", frenchChoices: ["agit", "agissent", "agissant", "agi"],
    advanced: "Il s’agit d’un prêt, pas d’un cadeau. Léa apporte le livre, Marc attend dans le jardin et Nina prépare un reçu.",
    prompt: "Quel mot, après « s’ », indique ici ce dont on parle ?", advancedChoices: ["agit", "apporte", "attend", "prépare"],
  },
  "agité:agiter_stir": {
    early: "La nouvelle a agité tout le quartier : chacun en parle avec inquiétude.", englishChoices: ["stirred up", "calmed", "emptied", "reassured"],
    intermediate: "Cette annonce a _____ la foule, qui s’est mise à crier de colère.", frenchChoices: ["agité", "calmé", "endormi", "rassuré"],
    advanced: "La rumeur a agité le quartier : les voisins discutent avec colère. Le gardien a fermé la grille, un enfant a rangé son vélo et le boulanger a ouvert sa boutique.",
    prompt: "Quel mot indique que la rumeur a troublé le quartier ?", advancedChoices: ["agité", "fermé", "rangé", "ouvert"],
  },
  "agréer:agreer_accept": {
    early: "Après examen, le comité décide d’agréer le projet.", englishChoices: ["to approve", "to reject", "to delay", "to hide"],
    intermediate: "Le comité accepte le dossier et décide de l’_____ officiellement.", frenchChoices: ["agréer", "écarter", "refuser", "ignorer"],
    advanced: "Après examen, le comité va agréer la demande. Son président veut signer la décision, le secrétaire doit classer le dossier et Luc préfère attendre.",
    prompt: "Quel verbe signifie accepter officiellement la demande ?", advancedChoices: ["agréer", "signer", "classer", "attendre"],
  },
  "ah:ah_emotion": {
    early: "Ah ! Je comprends enfin pourquoi la porte était fermée !", englishChoices: ["Ah!", "Splash!", "Tick-tock!", "Woof!"],
    intermediate: "En découvrant la solution, Léa s’exclame joyeusement : « _____ ! Je comprends enfin ! »", frenchChoices: ["Ah", "Aïe", "Chut", "Plouf"],
    advanced: "Ah ! Je comprends enfin la réponse. Léa dit « chut » aux enfants, Marie téléphone à son frère et le chien aboie dehors.",
    prompt: "Quel mot exprime la soudaine prise de conscience du locuteur ?", advancedChoices: ["Ah", "chut", "téléphone", "aboie"],
  },
  "ai:avoir_possess_auxiliary": {
    early: "J’ai deux frères et une sœur.", englishChoices: ["have", "want", "need", "know"],
    intermediate: "J’_____ un livre dans mon sac.", frenchChoices: ["ai", "as", "a", "ont"],
    advanced: "J’ai un vieux vélo. Tu as un casque, Léa possède un panier et Luc cherche sa clé.",
    prompt: "Quel mot indique que je possède le vélo ?", advancedChoices: ["ai", "as", "possède", "cherche"],
  },
  "ailleurs:ailleurs_elsewhere": {
    early: "Le livre n’est pas ici ; Paul va chercher ailleurs.", englishChoices: ["elsewhere", "nearby", "inside", "earlier"],
    intermediate: "Le livre n’est pas dans cette maison ; cherche _____, dans un autre bâtiment.", frenchChoices: ["ailleurs", "ici", "dedans", "dessus"],
    advanced: "Ce cahier n’est pas ici ; il faut chercher ailleurs. Luc regarde dans la chambre, Marie monte au grenier et Paul attend près de la porte.",
    prompt: "Quel mot indique un autre lieu que celui-ci ?", advancedChoices: ["ailleurs", "chambre", "grenier", "porte"],
  },
  "aiment:aimer_love": {
    early: "Les enfants aiment leur grand-mère et lui rendent visite.", englishChoices: ["they love", "they avoid", "they fear", "they forget"],
    intermediate: "Les enfants _____ leurs grands-parents et les serrent dans leurs bras.", frenchChoices: ["aiment", "détestent", "ignorent", "oublient"],
    advanced: "Les enfants aiment leur grand-mère et lui écrivent souvent. Marc prépare le dîner, Nina raconte une histoire et Luc ferme la fenêtre.",
    prompt: "Quel mot exprime l’affection des enfants ?", advancedChoices: ["aiment", "prépare", "raconte", "ferme"],
  },
  "aimions:aimer_love": {
    early: "Quand nous étions petits, nous aimions les longues promenades.", englishChoices: ["we loved", "we feared", "we forgot", "we refused"],
    intermediate: "Quand nous étions petits, nous _____ les promenades et les attendions avec impatience.", frenchChoices: ["aimions", "détestions", "oubliions", "ignorions"],
    advanced: "Nous aimions rendre visite à notre tante chaque été. Paul détestait les longs trajets, Léa oubliait parfois son chapeau et Marc préférait rester chez lui.",
    prompt: "Quel mot exprime l’affection que nous éprouvions ?", advancedChoices: ["aimions", "détestait", "oubliait", "préférait"],
  },
  "ait:avoir_possess_auxiliary": {
    early: "Il faut que Léa ait son billet avant le départ.", englishChoices: ["have", "lose", "borrow", "read"],
    intermediate: "Il faut qu’elle _____ son passeport pour voyager.", frenchChoices: ["ait", "a", "as", "ont"],
    advanced: "Il faut que Léa ait son billet avant le départ. Paul présente sa carte, Luc ouvre sa valise et Nina cherche sa place.",
    prompt: "Quel mot exprime ici la possession nécessaire du billet ?", advancedChoices: ["ait", "présente", "ouvre", "cherche"],
  },
  "allaient:aller_imminent": {
    early: "Les enfants allaient sortir quand la pluie a commencé.", englishChoices: ["were going to", "had already", "refused to", "were unable to"],
    intermediate: "Les enfants _____ sortir quand la pluie a commencé.", frenchChoices: ["allaient", "allait", "allions", "allez"],
    advanced: "Les enfants allaient sortir quand la pluie a commencé. Marie fermait la fenêtre, Paul cherchait un parapluie et le chien dormait.",
    prompt: "Quel mot annonce une sortie imminente avant la pluie ?", advancedChoices: ["allaient", "fermait", "cherchait", "dormait"],
  },
  "allais:aller_imminent": {
    early: "J’allais ouvrir la porte quand tu as sonné.", englishChoices: ["was going to", "had forgotten to", "refused to", "had finished"],
    intermediate: "J’_____ partir quand le téléphone a sonné.", frenchChoices: ["allais", "allait", "allaient", "allions"],
    advanced: "J’allais dormir quand le téléphone a sonné. Tu lisais un livre, Luc cherchait ses lunettes et Léa fermait la fenêtre.",
    prompt: "Quel mot marque l’action que je m’apprêtais à faire ?", advancedChoices: ["allais", "lisais", "cherchait", "fermait"],
  },
  "allait:aller_imminent": {
    early: "Luc allait partir quand Marie est arrivée.", englishChoices: ["was going to", "had already", "refused to", "had forgotten to"],
    intermediate: "Paul _____ partir quand la pluie a commencé.", frenchChoices: ["allait", "allais", "allaient", "allions"],
    advanced: "Luc allait partir quand sa sœur est arrivée. Marie préparait le repas, Paul attendait le bus et Léa téléphonait à un ami.",
    prompt: "Quel mot annonce le départ imminent de Luc ?", advancedChoices: ["allait", "préparait", "attendait", "téléphonait"],
  },
  "allemand:allemand_german": {
    early: "Ce journal allemand arrive chaque matin de Berlin.", englishChoices: ["German", "Italian", "French", "Spanish"],
    intermediate: "Ce journal officiel du gouvernement d’Allemagne est _____.", frenchChoices: ["allemand", "italien", "français", "espagnol"],
    advanced: "Un journal allemand arrive de Berlin. Un livre italien vient de Rome, un magazine français de Paris et une revue espagnole de Madrid.",
    prompt: "Quel mot qualifie le journal venu de Berlin ?", advancedChoices: ["allemand", "italien", "français", "espagnole"],
  },
  "alliance:alliance_union": {
    early: "Les deux villes forment une alliance pour protéger la rivière.", englishChoices: ["alliance", "rivalry", "separation", "defeat"],
    intermediate: "Les deux pays promettent de s’entraider et signent une _____ commune.", frenchChoices: ["alliance", "querelle", "séparation", "défaite"],
    advanced: "Une alliance unit les deux pays pour protéger la rivière. Une dispute avait retardé leur accord, la frontière reste ouverte et le pont sera réparé.",
    prompt: "Quel mot désigne l’union entre les deux pays ?", advancedChoices: ["alliance", "dispute", "frontière", "pont"],
  },
  "alors:alors_then": {
    early: "La réunion s’est terminée ; alors nous sommes allés déjeuner.", englishChoices: ["then", "nearby", "quietly", "outside"],
    intermediate: "La réunion se terminera à midi ; _____, nous irons déjeuner après avoir quitté la salle.", frenchChoices: ["alors", "avant", "près", "dedans"],
    advanced: "La réunion se termine ; alors nous partons déjeuner. Luc reste ici, Marie arrive bientôt et Paul attend dehors.",
    prompt: "Quel mot indique ce qui se passe après la réunion ?", advancedChoices: ["alors", "ici", "bientôt", "dehors"],
  },
  "amasse:amasser_accumulate": {
    early: "Chaque semaine, Léa amasse des pièces dans un bocal.", englishChoices: ["accumulates", "spends", "loses", "borrows"],
    intermediate: "Jour après jour, il _____ des centaines de vieux livres en un énorme tas.", frenchChoices: ["amasse", "disperse", "prête", "vend"],
    advanced: "Nina amasse des pièces dans un bocal et le remplit peu à peu. Luc dépense son argent, Marie trie des lettres et Paul prête des livres.",
    prompt: "Quel mot indique que Nina réunit progressivement une grande quantité ?", advancedChoices: ["amasse", "dépense", "trie", "prête"],
  },
  "âme:ame_inner_self": {
    early: "Cette musique touche l’âme de Marie.", englishChoices: ["soul", "skin", "voice", "house"],
    intermediate: "Cette musique émeut Léa jusqu’au fond de l’_____.", frenchChoices: ["âme", "oreille", "histoire", "habitude"],
    advanced: "La musique touche l’âme de Marie. Son visage change, sa voix tremble et ses yeux brillent.",
    prompt: "Quel mot désigne la vie intérieure et sensible de Marie ?", advancedChoices: ["âme", "visage", "voix", "yeux"],
  },
  "amener:amener_bring": {
    early: "Je vais amener Luc à la gare en voiture.", englishChoices: ["to bring", "to leave", "to forget", "to follow"],
    intermediate: "Peux-tu _____ ta sœur à l’école ? Elle ne connaît pas le chemin.", frenchChoices: ["amener", "amenez", "amené", "amenait"],
    advanced: "Je vais amener Luc à la gare. Marie préfère rester ici, Paul cherche les billets et Nina attend sur le quai.",
    prompt: "Quel mot signifie conduire Luc jusqu’à la gare ?", advancedChoices: ["amener", "rester", "cherche", "attend"],
  },
  "ameutent:ameuter_stir_up": {
    early: "Les rumeurs ameutent les habitants contre le maire.", englishChoices: ["stir up", "calm", "scatter", "reassure"],
    intermediate: "En répétant ces mensonges, les meneurs _____ la foule contre leur voisin.", frenchChoices: ["ameutent", "calment", "dispersent", "éloignent"],
    advanced: "Ces rumeurs ameutent les voisins contre le maire. Luc calme sa sœur, Marie disperse les curieux et Paul ferme la porte.",
    prompt: "Quel mot indique que les rumeurs soulèvent les voisins contre quelqu’un ?", advancedChoices: ["ameutent", "calme", "disperse", "ferme"],
  },
  "amicale:amical_friendly": {
    early: "Nina adresse une lettre amicale à ses anciens voisins.", englishChoices: ["friendly", "hostile", "cold", "formal"],
    intermediate: "Elle envoie une carte _____ pour prendre des nouvelles de son amie.", frenchChoices: ["amicale", "hostile", "froide", "méchante"],
    advanced: "La lettre amicale de Nina réjouit son amie. La réponse est brève, la boîte est vide et l’enveloppe reste ouverte.",
    prompt: "Quel mot qualifie la lettre inspirée par l’amitié ?", advancedChoices: ["amicale", "brève", "vide", "ouverte"],
  },
  "amoncelait:amonceler_gather": {
    early: "Pendant la tempête, la neige s’amoncelait devant la porte.", englishChoices: ["was piling up", "was melting", "was disappearing", "was blowing away"],
    intermediate: "Heure après heure, la neige s’_____ en tas devant la maison.", frenchChoices: ["amoncelait", "évaporait", "éloignait", "éparpillait"],
    advanced: "La neige s’amoncelait près de la porte. Sur le toit, elle fondait, le vent soufflait dans la rue et la pluie tombait au loin.",
    prompt: "Quel mot indique que la neige s’accumulait en tas ?", advancedChoices: ["amoncelait", "fondait", "soufflait", "tombait"],
  },
  "an:an_year": {
    early: "Mon petit frère a un an aujourd’hui.", englishChoices: ["year", "month", "week", "day"],
    intermediate: "De janvier à décembre, il s’écoule un _____.", frenchChoices: ["an", "jour", "mois", "siècle"],
    advanced: "Après un an de voyage, Léa revient au village. Son frère est parti hier, son cousin restera un mois et leur amie attend depuis un jour.",
    prompt: "Quel mot désigne une période de douze mois ?", advancedChoices: ["an", "hier", "mois", "jour"],
  },
  "angoisse:angoisse_anguish": {
    early: "Sans nouvelles de son enfant, Léa ressent une profonde angoisse.", englishChoices: ["anguish", "joy", "pride", "relief"],
    intermediate: "Sans nouvelles de son enfant disparu, elle éprouve une vive _____.", frenchChoices: ["angoisse", "joie", "fierté", "satisfaction"],
    advanced: "L’angoisse de Léa grandit pendant qu’elle attend des nouvelles de son enfant. Son frère garde espoir, sa sœur exprime sa colère et leur mère montre de la fatigue.",
    prompt: "Quel mot désigne l’inquiétude profonde de Léa ?", advancedChoices: ["angoisse", "espoir", "colère", "fatigue"],
  },
  "anonyme:anonyme_unsigned": {
    early: "Cette lettre anonyme ne porte aucun nom d’auteur.", englishChoices: ["anonymous", "signed", "public", "dated"],
    intermediate: "La lettre est _____ : son auteur n’a laissé ni nom ni signature.", frenchChoices: ["anonyme", "signée", "nominative", "identifiée"],
    advanced: "Une lettre anonyme arrive sans nom d’auteur. Le courrier signé par Paul est sur la table, le message daté de lundi est accroché et le billet officiel est dans un tiroir.",
    prompt: "Quel mot qualifie la lettre dont on ignore l’auteur ?", advancedChoices: ["anonyme", "signé", "daté", "officiel"],
  },
};
