import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch18: Record<string, EditorialQuizSet> = {
  "doute:doute_uncertainty": {
    early: "Un doute subsiste sur l’heure du départ, car deux horaires différents sont affichés.", englishChoices: ["doubt", "certainty", "proof", "agreement"],
    intermediate: "Les témoignages se contredisent et laissent un _____ sur ce qui s’est passé.", frenchChoices: ["doute", "certitude", "accord", "fait"],
    advanced: "Le doute de Nina vient des deux réponses contradictoires qu’elle a reçues. Paul vérifie la date, Léa ouvre le courrier et Marc consulte le directeur.",
    prompt: "Quel mot désigne l’incertitude de Nina sur la vérité ?", advancedChoices: ["doute", "date", "courrier", "directeur"],
  },
  "doute:se_douter_suspect": {
    early: "Paul se doute que Nina prépare une surprise, car elle cache un paquet.", englishChoices: ["suspects", "proves", "forgets", "denies"],
    intermediate: "En voyant les cadeaux cachés, Léa se _____ qu’une fête se prépare.", frenchChoices: ["doute", "convainc", "souvient", "réjouit"],
    advanced: "Marc se doute que ses amis organisent une fête parce qu’ils lui cachent leurs préparatifs. Nina ferme une boîte, Paul range les rubans et Léa prépare un gâteau.",
    prompt: "Quel mot indique que Marc pressent l’existence de la fête ?", advancedChoices: ["doute", "ferme", "range", "prépare"],
  },
  "doutes:doute_uncertainty": {
    early: "Les contradictions du récit font naître des doutes chez les enquêteurs.", englishChoices: ["doubts", "certainties", "proofs", "agreements"],
    intermediate: "Faute de preuves claires, les jurés conservent plusieurs _____ sur sa culpabilité.", frenchChoices: ["doutes", "certitudes", "accords", "réponses"],
    advanced: "Les doutes de Paul persistent parce que les deux témoins donnent des versions opposées. Nina relit les déclarations, Léa classe les photos et Marc appelle le juge.",
    prompt: "Quel mot désigne les incertitudes de Paul ?", advancedChoices: ["doutes", "témoins", "déclarations", "photos"],
  },
  "droit:droit_law": {
    early: "Le droit interdit de condamner une personne sans procès équitable.", englishChoices: ["law", "custom", "rumor", "opinion"],
    intermediate: "Cet avocat étudie le _____ pour connaître les règles juridiques applicables.", frenchChoices: ["droit", "bruit", "hasard", "goût"],
    advanced: "Le droit protège chaque accusé en exigeant un procès équitable. Le juge lit le dossier, Nina attend son avocat et Paul ferme la salle.",
    prompt: "Quel mot désigne l’ensemble des règles juridiques qui protège l’accusé ?", advancedChoices: ["droit", "juge", "dossier", "avocat"],
  },
  "droit:droit_entitlement": {
    early: "Chaque salarié a droit à un jour de repos hebdomadaire.", englishChoices: ["right", "ban", "gift", "habit"],
    intermediate: "La loi lui reconnaît le _____ de consulter son dossier.", frenchChoices: ["droit", "refus", "cadeau", "souhait"],
    advanced: "Nina possède le droit de demander une copie du document, et l’administration doit la lui fournir. Paul ouvre le bureau, Léa prépare le courrier et Marc attend dehors.",
    prompt: "Quel mot désigne la faculté légitime accordée à Nina ?", advancedChoices: ["droit", "document", "courrier", "bureau"],
  },
  "droits:droit_entitlement": {
    early: "La loi garantit aux locataires des droits, notamment celui de vivre dans un logement sûr.", englishChoices: ["rights", "prohibitions", "gifts", "habits"],
    intermediate: "Les citoyens défendent leurs _____ à voter et à s’exprimer librement.", frenchChoices: ["droits", "interdictions", "cadeaux", "loisirs"],
    advanced: "Les droits des salariés comprennent le repos et la sécurité au travail. Nina consulte le règlement, Paul ferme l’atelier et Léa prépare la réunion.",
    prompt: "Quel mot désigne les facultés légitimes garanties aux salariés ?", advancedChoices: ["droits", "repos", "règlement", "réunion"],
  },
  "dû:devoir_obligation": {
    early: "À cause de la panne, Paul a dû rentrer à pied.", englishChoices: ["had to", "wanted to", "managed to", "refused to"],
    intermediate: "La route étant fermée, Nina a _____ faire un long détour.", frenchChoices: ["dû", "voulu", "pu", "refusé"],
    advanced: "Léa a dû présenter son passeport parce que le règlement l’exigeait. Paul a porté les valises, Nina a lu les billets et Marc a appelé un taxi.",
    prompt: "Quel mot exprime l’obligation imposée à Léa ?", advancedChoices: ["dû", "porté", "lu", "appelé"],
  },
  "duel:duel_conflict": {
    early: "Le débat devient un duel verbal entre les deux candidats opposés.", englishChoices: ["duel", "alliance", "celebration", "journey"],
    intermediate: "Les deux champions s’affrontent directement dans un _____ décisif.", frenchChoices: ["duel", "accord", "repos", "voyage"],
    advanced: "Le duel oppose directement Nina et Paul lors de la finale d’échecs. Léa note les coups, Marc surveille l’horloge et le public garde le silence.",
    prompt: "Quel mot désigne l’affrontement direct entre Nina et Paul ?", advancedChoices: ["duel", "finale", "horloge", "public"],
  },
  "durèrent:durer_last": {
    early: "Les négociations durèrent trois semaines avant la signature de l’accord.", englishChoices: ["lasted", "began", "stopped", "failed"],
    intermediate: "Les travaux _____ deux ans, de 1890 à 1892.", frenchChoices: ["durèrent", "commencèrent", "cessèrent", "échouèrent"],
    advanced: "Les débats durèrent toute la nuit et ne prirent fin qu’au lever du soleil. Nina nota les décisions, Paul ferma les fenêtres et Léa prépara du café.",
    prompt: "Quel mot indique que les débats se prolongèrent pendant toute la nuit ?", advancedChoices: ["durèrent", "nota", "ferma", "prépara"],
  },
  "dut:devoir_obligation": {
    early: "Après la fermeture du pont, Paul dut prendre un autre chemin.", englishChoices: ["had to", "wanted to", "managed to", "refused to"],
    intermediate: "Faute de train, Nina _____ rentrer à pied ce soir-là.", frenchChoices: ["dut", "voulut", "put", "refusa"],
    advanced: "Marc dut remettre son dossier avant midi parce que la date limite expirait. Nina ouvrit le guichet, Paul vérifia les signatures et Léa rangea les copies.",
    prompt: "Quel mot exprime l’obligation imposée à Marc ?", advancedChoices: ["dut", "ouvrit", "vérifia", "rangea"],
  },
  "éclata:eclater_burst": {
    early: "Une violente dispute éclata soudainement au milieu de la réunion.", englishChoices: ["broke out", "ended", "faded", "continued calmly"],
    intermediate: "Sans avertissement, un incendie _____ dans l’entrepôt pendant la nuit.", frenchChoices: ["éclata", "cessa", "faiblit", "diminua"],
    advanced: "Un orage éclata soudain au-dessus du village et secoua les fenêtres. Nina ferma les volets, Paul rentra le vélo et Léa appela les enfants.",
    prompt: "Quel mot indique que l’orage se produisit soudainement avec violence ?", advancedChoices: ["éclata", "ferma", "rentra", "appela"],
  },
  "éclatante:eclatant_obvious": {
    early: "La vidéo constitue une preuve éclatante de son innocence.", englishChoices: ["striking", "uncertain", "hidden", "weak"],
    intermediate: "Tous les chiffres concordent : la réussite de cette méthode est _____.", frenchChoices: ["éclatante", "douteuse", "cachée", "faible"],
    advanced: "La réussite éclatante de Nina est évidente : elle obtient le meilleur résultat de toute l’école. Paul lit les notes, Léa ferme la salle et Marc range les cahiers.",
    prompt: "Quel mot souligne le caractère manifeste et remarquable de la réussite ?", advancedChoices: ["éclatante", "évidente", "notes", "cahiers"],
  },
  "éclate:eclater_burst": {
    early: "Une dispute éclate soudainement entre les deux voisins.", englishChoices: ["breaks out", "ends", "fades", "calms down"],
    intermediate: "Quand la foule apprend la nouvelle, une protestation _____ sur la place.", frenchChoices: ["éclate", "cesse", "faiblit", "disparaît"],
    advanced: "Un incendie éclate brusquement dans l’atelier et les ouvriers courent vers la sortie. Nina appelle les pompiers, Paul ferme le gaz et Léa ouvre le portail.",
    prompt: "Quel mot indique que l’incendie se produit soudainement ?", advancedChoices: ["éclate", "appelle", "ferme", "ouvre"],
  },
  "éclater:eclater_burst": {
    early: "La tension monte et une dispute risque d’éclater pendant la réunion.", englishChoices: ["to break out", "to end", "to fade", "to calm down"],
    intermediate: "À cause des étincelles, un incendie pourrait _____ dans l’atelier.", frenchChoices: ["éclater", "cesser", "faiblir", "disparaître"],
    advanced: "Une protestation pourrait éclater si le conseil ferme l’école sans consulter les parents. Nina prépare une pétition, Paul lit le règlement et Léa ouvre la salle.",
    prompt: "Quel verbe signifie se produire soudainement avec force ?", advancedChoices: ["éclater", "prépare", "lit", "ouvre"],
  },
  "écrira:ecrire_write": {
    early: "Demain, Nina écrira une lettre au maire pour expliquer sa demande.", englishChoices: ["will write", "will erase", "will read", "will hide"],
    intermediate: "Après la réunion, Paul _____ le compte rendu dans son cahier.", frenchChoices: ["écrira", "effacera", "lira", "cachera"],
    advanced: "Léa écrira le rapport demain en réunissant ses notes dans un texte clair. Nina classera les dossiers, Paul fermera le bureau et Marc lira le journal.",
    prompt: "Quel mot indique que Léa composera le rapport ?", advancedChoices: ["écrira", "classera", "fermera", "lira"],
  },
  "écrites:ecrire_write": {
    early: "Les lettres écrites par Paul sont rangées dans cette boîte.", englishChoices: ["written", "erased", "spoken", "hidden"],
    intermediate: "Les consignes _____ au tableau restent visibles pendant le cours.", frenchChoices: ["écrites", "effacées", "prononcées", "cachées"],
    advanced: "Les déclarations écrites par Nina figurent dans le dossier sous forme de trois pages signées. Paul ouvre l’enveloppe, Léa lit le titre et Marc ferme l’armoire.",
    prompt: "Quel mot indique que les déclarations ont été mises par écrit ?", advancedChoices: ["écrites", "signées", "titre", "armoire"],
  },
  "écriture:ecriture_handwriting": {
    early: "L’écriture de Nina est reconnaissable à ses grandes lettres inclinées.", englishChoices: ["handwriting", "voice", "signature stamp", "drawing"],
    intermediate: "Grâce à la forme particulière des lettres, Paul reconnaît l’_____ de son frère.", frenchChoices: ["écriture", "voix", "photographie", "peinture"],
    advanced: "L’écriture de Léa se distingue par des lettres hautes et très serrées. Nina examine la signature, Paul lit le texte et Marc range le papier.",
    prompt: "Quel mot désigne la manière dont Léa trace les caractères ?", advancedChoices: ["écriture", "signature", "texte", "papier"],
  },
  "écritures:ecriture_handwriting": {
    early: "L’experte compare les écritures de trois lettres pour savoir si la même main les a tracées.", englishChoices: ["handwriting samples", "voices", "drawings", "photographs"],
    intermediate: "Les formes des lettres diffèrent ; l’experte compare donc les _____.", frenchChoices: ["écritures", "voix", "images", "photographies"],
    advanced: "Les écritures des deux documents présentent des lettres formées de façons différentes. Nina compare les signatures, Paul photographie les pages et Léa classe les enveloppes.",
    prompt: "Quel mot désigne les différentes manières de tracer les caractères ?", advancedChoices: ["écritures", "signatures", "pages", "enveloppes"],
  },
  "écroulement:ecroulement_collapse": {
    early: "L’écroulement du vieux mur a couvert la route de pierres.", englishChoices: ["collapse", "construction", "repair", "painting"],
    intermediate: "La chute soudaine du toit provoque l’_____ du bâtiment entier.", frenchChoices: ["écroulement", "édification", "réparation", "peinture"],
    advanced: "L’écroulement du pont entraîne sa chute complète dans la rivière. Nina ferme la route, Paul avertit les secours et Léa consulte une carte.",
    prompt: "Quel mot désigne la destruction soudaine du pont ?", advancedChoices: ["écroulement", "rivière", "route", "carte"],
  },
  "effroyable:effroyable_appalling": {
    early: "L’effroyable accident a terrifié tous les témoins.", englishChoices: ["dreadful", "pleasant", "minor", "reassuring"],
    intermediate: "Le récit de ce massacre est _____ et provoque une profonde indignation.", frenchChoices: ["effroyable", "agréable", "banal", "rassurant"],
    advanced: "La nouvelle effroyable de l’incendie qui a détruit l’hôpital bouleverse la ville. Nina appelle les secours, Paul aide les blessés et Léa cherche les familles.",
    prompt: "Quel mot qualifie la nouvelle qui provoque une immense frayeur ?", advancedChoices: ["effroyable", "ville", "blessés", "familles"],
  },
  "également:egalement_also": {
    early: "Nina parle espagnol et connaît également l’italien.", englishChoices: ["also", "never", "instead", "rarely"],
    intermediate: "Paul joue du piano ; il pratique _____ le violon.", frenchChoices: ["également", "jamais", "plutôt", "rarement"],
    advanced: "Léa étudie le droit et apprend également l’histoire, en plus de sa matière principale. Nina lit un roman, Paul ferme la porte et Marc prépare du café.",
    prompt: "Quel mot ajoute l’histoire à ce que Léa étudie déjà ?", advancedChoices: ["également", "droit", "roman", "café"],
  },
  "égarer:egarer_mislead": {
    early: "Le faux panneau risque d’égarer les randonneurs loin du bon chemin.", englishChoices: ["to mislead", "to guide", "to inform", "to reassure"],
    intermediate: "Avec ses indications mensongères, il cherche à _____ les enquêteurs.", frenchChoices: ["égarer", "guider", "informer", "rassurer"],
    advanced: "Le témoin essaie d’égarer la police en donnant une fausse adresse. Nina vérifie la carte, Paul examine les faits et Léa ouvre le dossier.",
    prompt: "Quel verbe signifie conduire la police loin de la vérité ?", advancedChoices: ["égarer", "vérifie", "examine", "ouvre"],
  },
  "elle-même:elle_meme_herself": {
    early: "Nina a réparé elle-même son vélo, sans demander d’aide.", englishChoices: ["herself", "himself", "ourselves", "themselves"],
    intermediate: "Léa a cousu _____ cette robe, sans l’aide de personne.", frenchChoices: ["elle-même", "lui-même", "nous-mêmes", "eux-mêmes"],
    advanced: "Marie a construit elle-même la table, sans que personne d’autre ne travaille à sa place. Paul peint la chaise, Nina ouvre la fenêtre et Luc range les outils.",
    prompt: "Quel mot insiste sur le fait que Marie a personnellement construit la table ?", advancedChoices: ["elle-même", "personne", "chaise", "outils"],
  },
  "éloigna:eloigner_send_away": {
    early: "Le directeur éloigna l’employé du bureau en l’envoyant dans une autre ville.", englishChoices: ["sent away", "welcomed", "approached", "retained"],
    intermediate: "Pour le tenir loin de la capitale, le ministre l’_____ dans un poste isolé.", frenchChoices: ["éloigna", "accueillit", "approcha", "retint"],
    advanced: "Le commandant éloigna Paul du régiment en l’envoyant à cent kilomètres. Nina lut l’ordre, Léa ferma le bureau et Marc prépara la voiture.",
    prompt: "Quel mot indique que le commandant envoya Paul à grande distance ?", advancedChoices: ["éloigna", "lut", "ferma", "prépara"],
  },
  "émoi:emoi_agitation": {
    early: "L’annonce soudaine de l’évacuation provoque un grand émoi dans le village.", englishChoices: ["alarm", "calm", "boredom", "indifference"],
    intermediate: "La disparition de l’enfant suscite un vif _____ parmi les voisins inquiets.", frenchChoices: ["émoi", "calme", "ennui", "repos"],
    advanced: "Un vif émoi gagne les passagers lorsqu’une fumée noire sort du moteur. Nina appelle le conducteur, Paul ouvre une fenêtre et Léa cherche la sortie.",
    prompt: "Quel mot désigne l’agitation inquiète des passagers ?", advancedChoices: ["émoi", "moteur", "fenêtre", "sortie"],
  },
  "émotion:emotion_feeling": {
    early: "En retrouvant son frère, Nina ressent une vive émotion et se met à pleurer.", englishChoices: ["emotion", "calculation", "habit", "silence"],
    intermediate: "La musique provoque une forte _____ chez les spectateurs, qui essuient leurs larmes.", frenchChoices: ["émotion", "habitude", "mesure", "indifférence"],
    advanced: "L’émotion de Paul est visible lorsqu’il retrouve sa fille après dix ans : sa voix tremble. Nina ferme la porte, Léa apporte une chaise et Marc regarde la photographie.",
    prompt: "Quel mot désigne la réaction affective vive de Paul ?", advancedChoices: ["émotion", "voix", "chaise", "photographie"],
  },
  "empêcher:empecher_prevent": {
    early: "Une barrière doit empêcher les voitures d’entrer dans la rue.", englishChoices: ["to prevent", "to allow", "to encourage", "to invite"],
    intermediate: "Fermez la porte pour _____ le chien de sortir.", frenchChoices: ["empêcher", "permettre", "encourager", "inviter"],
    advanced: "Nina veut empêcher la fermeture de l’école en présentant une pétition au conseil. Paul rassemble les signatures, Léa prépare les documents et Marc ouvre la salle.",
    prompt: "Quel verbe signifie faire obstacle à la fermeture de l’école ?", advancedChoices: ["empêcher", "rassemble", "prépare", "ouvre"],
  },
};
