import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a telescope", "a turnip", "a cushion"];
const nounFrench: [string, string, string] = ["télescope", "navet", "coussin"];
const adjectiveEnglish: [string, string, string] = ["spotted", "vanilla-scented", "triangular"];
const adjectiveFrench: [string, string, string] = ["tacheté", "parfumé à la vanille", "triangulaire"];

export const zolaVocabularyBatch34: ZolaVocabularySpec[] = [
  { normalized: "nie", lemmaKey: "nier", headword: "nier", partOfSpeech: "verb", senseKey: "nier_deny", gloss: "to deny; reject", quizMeaning: "deny; reject", definition: "déclarer qu’un fait ou une affirmation n’est pas vrai", englishDistractors: ["knit", "paddle", "sneeze"], frenchDistractors: ["tricote", "pagaie", "éternue"] },
  { normalized: "nom", candidateIds: ["tok_7fc9b8098396811f0d76935d"], lemmaKey: "nom", headword: "nom", partOfSpeech: "noun", senseKey: "nom_name_reputation", gloss: "name; reputation", definition: "désignation d’une personne, considérée aussi comme porteuse de sa réputation", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "nom", candidateIds: ["tok_badbf8713ff143481ff449cd", "tok_c9f632e6f924b508e1ff1e8b"], lemmaKey: "nom", headword: "nom", partOfSpeech: "noun", senseKey: "nom_on_behalf", gloss: "name; on behalf of", definition: "dans « au nom de », indique l’autorité, la cause ou la personne au titre de laquelle on agit", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "nos", lemmaKey: "notre", headword: "notre", partOfSpeech: "determiner", senseKey: "notre_our", gloss: "our", definition: "déterminant possessif indiquant que plusieurs éléments appartiennent au groupe qui parle", englishDistractors: ["seven", "twelve", "a thousand"], frenchDistractors: ["sept", "douze", "mille"] },
  { normalized: "nous", lemmaKey: "nous", headword: "nous", partOfSpeech: "pronoun", senseKey: "nous_we_us", gloss: "we; us", definition: "pronom personnel représentant la personne qui parle avec une ou plusieurs autres", englishDistractors: ["me", "you", "himself"], frenchDistractors: ["me", "te", "se"] },
  { normalized: "nuit", lemmaKey: "nuit", headword: "nuit", partOfSpeech: "noun", senseKey: "nuit_night", gloss: "night; nighttime", definition: "période d’obscurité comprise entre le soir et le matin", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "nuits", lemmaKey: "nuit", headword: "nuit", partOfSpeech: "noun", senseKey: "nuit_night", gloss: "night; nighttime", quizMeaning: "nights", definition: "période d’obscurité comprise entre le soir et le matin", englishDistractors: ["telescopes", "turnips", "cushions"], frenchDistractors: ["télescopes", "navets", "coussins"] },
  { normalized: "o", lemmaKey: "o_interjection", headword: "ô", partOfSpeech: "interjection", senseKey: "o_invocation", gloss: "O; oh", definition: "interjection employée pour invoquer ou apostropher solennellement", englishDistractors: ["alas", "bravo", "hush"], frenchDistractors: ["hélas", "bravo", "chut"] },
  { normalized: "obéissance", lemmaKey: "obeissance", headword: "obéissance", partOfSpeech: "noun", senseKey: "obeissance_obedience", gloss: "obedience", definition: "fait de se soumettre à une autorité ou d’exécuter un ordre", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "obligés", lemmaKey: "obliger", headword: "obliger", partOfSpeech: "verb", senseKey: "obliger_compel", gloss: "to oblige; compel", quizMeaning: "obliged; compelled", definition: "contraindre quelqu’un à accomplir une action", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricotés", "pagayés", "éternués"] },
  { normalized: "obscurcies", lemmaKey: "obscurcir", headword: "obscurcir", partOfSpeech: "verb", senseKey: "obscurcir_darkened", gloss: "to darken; obscure", quizMeaning: "darkened; obscured", definition: "rendre moins clair, moins visible ou moins compréhensible", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricotées", "pagayées", "éternuées"] },
  { normalized: "obstination", lemmaKey: "obstination", headword: "obstination", partOfSpeech: "noun", senseKey: "obstination_stubbornness", gloss: "stubbornness; persistence", definition: "volonté tenace de maintenir une conduite ou une opinion", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "occultisme", lemmaKey: "occultisme", headword: "occultisme", partOfSpeech: "noun", senseKey: "occultisme_occultism", gloss: "occultism", definition: "ensemble de croyances et de pratiques prétendant accéder à des forces cachées", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "occupe", lemmaKey: "occuper", headword: "s’occuper", partOfSpeech: "verb", senseKey: "occuper_concern_oneself", gloss: "to concern oneself; engage in", quizMeaning: "concerns himself; engages in", definition: "consacrer son attention ou son activité à quelque chose", englishDistractors: ["knits", "paddles", "sneezes"], frenchDistractors: ["tricote", "pagaie", "éternue"] },
  { normalized: "odieux", lemmaKey: "odieux", headword: "odieux", partOfSpeech: "adjective", senseKey: "odieux_hateful", gloss: "hateful; odious", definition: "qui mérite une forte haine ou inspire un profond dégoût moral", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "œuf", lemmaKey: "oeuf", headword: "œuf", partOfSpeech: "noun", senseKey: "oeuf_origin", gloss: "egg; germ", definition: "œuf, employé figurément pour désigner l’origine d’un développement futur", englishDistractors: nounEnglish, frenchDistractors: ["avion", "orage", "escalier"] },
  { normalized: "œuvre", lemmaKey: "oeuvre", headword: "œuvre", partOfSpeech: "noun", senseKey: "oeuvre_work_deed", gloss: "work; deed", definition: "résultat d’une action ou entreprise accomplie par une personne", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "œuvres", lemmaKey: "oeuvre", headword: "œuvre", partOfSpeech: "noun", senseKey: "oeuvre_work_deed", gloss: "work; deed", quizMeaning: "works; deeds", definition: "résultat d’une action ou entreprise accomplie par une personne", englishDistractors: ["telescopes", "turnips", "cushions"], frenchDistractors: ["télescopes", "navets", "coussins"] },
  { normalized: "officier", lemmaKey: "officier_noun", headword: "officier", partOfSpeech: "noun", senseKey: "officier_military", gloss: "military officer", definition: "membre des forces armées titulaire d’un grade de commandement", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "officiers", lemmaKey: "officier_noun", headword: "officier", partOfSpeech: "noun", senseKey: "officier_military", gloss: "military officer", quizMeaning: "military officers", definition: "membre des forces armées titulaire d’un grade de commandement", englishDistractors: ["telescopes", "turnips", "cushions"], frenchDistractors: ["télescopes", "navets", "coussins"] },
  { normalized: "ombre", lemmaKey: "ombre", headword: "ombre", partOfSpeech: "noun", senseKey: "ombre_secrecy", gloss: "shadow; secrecy", definition: "absence de lumière, employée aussi pour désigner ce qui reste caché", englishDistractors: nounEnglish, frenchDistractors: ["avion", "orage", "escalier"] },
  { normalized: "ont", lemmaKey: "avoir", existingLemmaId: "lem_avoir", existingSenseId: "sns_avoir_primary", headword: "avoir", partOfSpeech: "verb", senseKey: "avoir_primary", gloss: "to have", quizMeaning: "have", definition: "posséder ou former un temps composé avec un participe passé", englishDistractors: ["have vertically", "have musically", "have geometrically"], frenchDistractors: ["ont verticalement", "ont musicalement", "ont géométriquement"] },
  { normalized: "opinion", lemmaKey: "opinion", headword: "opinion", partOfSpeech: "noun", senseKey: "opinion_view_public", gloss: "opinion; public sentiment", definition: "jugement partagé ou manière de penser d’une personne ou du public", englishDistractors: nounEnglish, frenchDistractors: ["avion", "orage", "escalier"] },
  { normalized: "or", lemmaKey: "or_conjunction", headword: "or", partOfSpeech: "conjunction", senseKey: "or_now_yet", gloss: "now; yet", definition: "introduit un fait nouveau qui sert d’objection ou de transition dans un raisonnement", englishDistractors: ["tomorrow", "outside", "silently"], frenchDistractors: ["demain", "dehors", "silencieusement"] },
  { normalized: "orage", lemmaKey: "orage", headword: "orage", partOfSpeech: "noun", senseKey: "orage_storm_crisis", gloss: "storm; crisis", definition: "perturbation atmosphérique violente, employée aussi pour une crise imminente", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "ordre", candidateIds: ["tok_9b896cc0f9fe1b4edb1e3849", "tok_b8c00d8212f71566d74a8bde"], lemmaKey: "ordre", headword: "ordre", partOfSpeech: "noun", senseKey: "ordre_command", gloss: "order; command", definition: "instruction donnée par une autorité et destinée à être exécutée", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "ordre", candidateIds: ["tok_95c0d71fc97cc149592c0dd8"], lemmaKey: "ordre", headword: "ordre", partOfSpeech: "noun", senseKey: "ordre_sequence", gloss: "order; sequence", definition: "disposition successive ou classement selon un principe", englishDistractors: nounEnglish, frenchDistractors: ["avion", "orage", "escalier"] },
  { normalized: "origine", lemmaKey: "origine", headword: "origine", partOfSpeech: "noun", senseKey: "origine_source", gloss: "origin; source", definition: "point de départ, provenance ou commencement d’une personne ou d’une chose", englishDistractors: nounEnglish, frenchDistractors: ["avion", "orage", "escalier"] },
];
