import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a kettle", "a ladder", "a pear"];
const nounFrench: [string, string, string] = ["une bouilloire", "une échelle", "une poire"];
const adjectiveEnglish: [string, string, string] = ["striped", "lavender-scented", "octagonal"];
const adjectiveFrench: [string, string, string] = ["rayé", "parfumé à la lavande", "octogonal"];

export const zolaVocabularyBatch28: ZolaVocabularySpec[] = [
  { normalized: "innocence", lemmaKey: "innocence", headword: "innocence", partOfSpeech: "noun", senseKey: "innocence_not_guilty", gloss: "innocence", definition: "état d’une personne qui n’a pas commis la faute ou le crime reproché", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "innocent", lemmaKey: "innocent", headword: "innocent", partOfSpeech: "adjective", senseKey: "innocent_not_guilty", gloss: "innocent; not guilty", definition: "qui n’a pas commis la faute ou le crime reproché", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "innocenter", lemmaKey: "innocenter", headword: "innocenter", partOfSpeech: "verb", senseKey: "innocenter_clear", gloss: "to clear; exonerate", definition: "faire reconnaître quelqu’un comme innocent d’une accusation", englishDistractors: ["to knit", "to sail", "to sneeze"], frenchDistractors: ["tricoter", "naviguer", "éternuer"] },
  { normalized: "inquiètent", lemmaKey: "inquieter", headword: "s’inquiéter", partOfSpeech: "verb", senseKey: "inquieter_worry", gloss: "to worry; become concerned", quizMeaning: "worry; become concerned", definition: "éprouver de l’inquiétude ou craindre une difficulté", englishDistractors: ["knit", "sail", "sneeze"], frenchDistractors: ["tricotent", "naviguent", "éternuent"] },
  { normalized: "inquisition", lemmaKey: "inquisition", headword: "inquisition", partOfSpeech: "noun", senseKey: "inquisition_oppressive_inquiry", gloss: "inquisition; oppressive investigation", definition: "enquête oppressive menée avec une sévérité arbitraire", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "insistait", lemmaKey: "insister", headword: "insister", partOfSpeech: "verb", senseKey: "insister_persist", gloss: "to insist; persist", quizMeaning: "was insisting; persisted", definition: "maintenir fermement une demande ou une affirmation", englishDistractors: ["was knitting", "was sailing", "was sneezing"], frenchDistractors: ["tricotait", "naviguait", "éternuait"] },
  { normalized: "insiste", lemmaKey: "insister", headword: "insister", partOfSpeech: "verb", senseKey: "insister_persist", gloss: "to insist; persist", quizMeaning: "insist; persist", definition: "maintenir fermement une demande ou une affirmation", englishDistractors: ["knit", "sail", "sneeze"], frenchDistractors: ["tricote", "navigue", "éternue"] },
  { normalized: "insolemment", lemmaKey: "insolemment", headword: "insolemment", partOfSpeech: "adverb", senseKey: "insolemment_brazenly", gloss: "insolently; brazenly", definition: "d’une manière effrontée qui manifeste un manque de respect", englishDistractors: ["quietly", "outside", "monthly"], frenchDistractors: ["silencieusement", "dehors", "chaque mois"] },
  { normalized: "instruction", lemmaKey: "instruction_noun", headword: "instruction", partOfSpeech: "noun", senseKey: "instruction_investigation", gloss: "judicial investigation; inquiry", definition: "phase d’une procédure judiciaire consacrée à l’examen des faits", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "instruire", lemmaKey: "instruire", headword: "instruire", partOfSpeech: "verb", senseKey: "instruire_investigate", gloss: "to investigate; prepare a case", definition: "examiner judiciairement une affaire ou préparer un procès", englishDistractors: ["to knit", "to sail", "to sneeze"], frenchDistractors: ["tricoter", "naviguer", "éternuer"] },
  { normalized: "instruisaient", lemmaKey: "instruire", headword: "instruire", partOfSpeech: "verb", senseKey: "instruire_investigate", gloss: "to investigate; prepare a case", quizMeaning: "were preparing; were investigating", definition: "examiner judiciairement une affaire ou préparer un procès", englishDistractors: ["were knitting", "were sailing", "were sneezing"], frenchDistractors: ["tricotaient", "naviguaient", "éternuaient"] },
  { normalized: "intelligence", lemmaKey: "intelligence", headword: "intelligence", partOfSpeech: "noun", senseKey: "intelligence_mental_ability", gloss: "intelligence; mental ability", definition: "faculté de comprendre, de raisonner et de juger", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "intéressant", lemmaKey: "interesser", headword: "intéresser", partOfSpeech: "verb", senseKey: "interesser_concern", gloss: "to concern; affect", quizMeaning: "concerning; affecting", definition: "avoir un rapport direct avec quelque chose ou le concerner", englishDistractors: ["knitting", "sailing", "sneezing"], frenchDistractors: ["tricotant", "naviguant", "éternuant"] },
  { normalized: "intérêt", lemmaKey: "interet", headword: "intérêt", partOfSpeech: "noun", senseKey: "interet_advantage", gloss: "interest; advantage", definition: "ce qui importe ou procure un avantage à une personne ou un groupe", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "interpellation", lemmaKey: "interpellation", headword: "interpellation", partOfSpeech: "noun", senseKey: "interpellation_parliamentary", gloss: "parliamentary questioning; interpellation", definition: "demande officielle d’explications adressée au gouvernement dans une assemblée", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "interrogatoires", lemmaKey: "interrogatoire", headword: "interrogatoire", partOfSpeech: "noun", senseKey: "interrogatoire_questioning", gloss: "questioning; interrogation", quizMeaning: "interrogations; examinations", definition: "ensemble de questions posées officiellement à une personne", englishDistractors: ["kettles", "ladders", "pears"], frenchDistractors: ["bouilloires", "échelles", "poires"] },
  { normalized: "intolérance", lemmaKey: "intolerance", headword: "intolérance", partOfSpeech: "noun", senseKey: "intolerance_bigotry", gloss: "intolerance; bigotry", definition: "refus d’admettre des opinions, croyances ou personnes différentes", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "intrigues", lemmaKey: "intrigue", headword: "intrigue", partOfSpeech: "noun", senseKey: "intrigue_plot", gloss: "intrigue; plot", quizMeaning: "intrigues; plots", definition: "manœuvre secrète et compliquée destinée à obtenir un résultat", englishDistractors: ["kettles", "ladders", "pears"], frenchDistractors: ["bouilloires", "échelles", "poires"] },
  { normalized: "introduire", lemmaKey: "introduire", headword: "introduire", partOfSpeech: "verb", senseKey: "introduire_admit", gloss: "to introduce; admit", definition: "faire entrer une personne dans un lieu ou auprès de quelqu’un", englishDistractors: ["to knit", "to sail", "to sneeze"], frenchDistractors: ["tricoter", "naviguer", "éternuer"] },
  { normalized: "introduit", lemmaKey: "introduire", headword: "introduire", partOfSpeech: "verb", senseKey: "introduire_admit", gloss: "to introduce; admit", quizMeaning: "introduced; admitted", definition: "faire entrer une personne dans un lieu ou auprès de quelqu’un", englishDistractors: ["knitted", "sailed", "sneezed"], frenchDistractors: ["tricoté", "navigué", "éternué"] },
  { normalized: "inventé", lemmaKey: "inventer", headword: "inventer", partOfSpeech: "verb", senseKey: "inventer_fabricate", gloss: "to invent; fabricate", quizMeaning: "invented; fabricated", definition: "créer par l’imagination, parfois sans fondement réel", englishDistractors: ["knitted", "sailed", "sneezed"], frenchDistractors: ["tricoté", "navigué", "éternué"] },
  { normalized: "invisible", lemmaKey: "invisible", headword: "invisible", partOfSpeech: "adjective", senseKey: "invisible_unseen", gloss: "invisible; unseen", definition: "qui ne peut être vu ou demeure caché au regard", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "irrésistible", lemmaKey: "irresistible", headword: "irrésistible", partOfSpeech: "adjective", senseKey: "irresistible_unstoppable", gloss: "irresistible; unstoppable", definition: "auquel rien ne peut résister ou faire obstacle", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "jamais", lemmaKey: "jamais", headword: "jamais", partOfSpeech: "adverb", senseKey: "jamais_ever_never", gloss: "ever; never", definition: "à aucun moment, ou à quelque moment que ce soit selon la construction", englishDistractors: ["quietly", "outside", "monthly"], frenchDistractors: ["silencieusement", "dehors", "chaque mois"] },
  { normalized: "jésuitière", lemmaKey: "jesuitiere", headword: "jésuitière", partOfSpeech: "noun", senseKey: "jesuitiere_jesuit_den", gloss: "Jesuit stronghold; Jesuit den", definition: "terme polémique désignant un milieu dominé par l’influence des jésuites", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "jeter", lemmaKey: "jeter", headword: "jeter", partOfSpeech: "verb", senseKey: "jeter_cast", gloss: "to throw; cast", definition: "lancer, projeter ou répandre quelque chose avec force", englishDistractors: ["to knit", "to sail", "to sneeze"], frenchDistractors: ["tricoter", "naviguer", "éternuer"] },
  { normalized: "joli", lemmaKey: "joli", headword: "joli", partOfSpeech: "adjective", senseKey: "joli_fine_ironic", gloss: "fine; amusing", definition: "plaisant ou remarquable, avec ici une nuance ironique", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "joue", lemmaKey: "joue", headword: "joue", partOfSpeech: "noun", senseKey: "joue_cheek", gloss: "cheek", definition: "partie latérale du visage située entre le nez, l’oreille et la mâchoire", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "jour", candidateIds: ["tok_604a58509d503069c17f1e38", "tok_535f9a38e026829b0c29bafc", "tok_458a2e86a8d12a3d5ad573d0", "tok_90f4efd3bdf60b422a771e28", "tok_453f2a3eabcb958663b1beac", "tok_c8f3f0f6c5ffb0de9304cb64"], lemmaKey: "jour", headword: "jour", partOfSpeech: "noun", senseKey: "jour_day", gloss: "day; occasion", definition: "période de vingt-quatre heures ou moment déterminé où survient un événement", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "jour", candidateIds: ["tok_740007c45d2a6a933a70f00e", "tok_1e8efe95cf1b5cc4b6ee1562", "tok_a018d6205e1066d0807e03bb"], lemmaKey: "jour", headword: "jour", partOfSpeech: "noun", senseKey: "jour_light_exposure", gloss: "daylight; public exposure", definition: "lumière du jour ou pleine révélation au regard du public", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
];
