import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a telescope", "a turnip", "a cushion"];
const nounFrench: [string, string, string] = ["télescope", "navet", "coussin"];
const adjectiveEnglish: [string, string, string] = ["spotted", "mint-scented", "hexagonal"];
const adjectiveFrench: [string, string, string] = ["tacheté", "parfumé à la menthe", "hexagonal"];

export const zolaVocabularyBatch35: ZolaVocabularySpec[] = [
  { normalized: "osa", lemmaKey: "oser", headword: "oser", partOfSpeech: "verb", senseKey: "oser_dare", gloss: "to dare; venture", quizMeaning: "dared", definition: "avoir l’audace de faire quelque chose malgré le risque ou la difficulté", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricoté", "pagayé", "éternué"] },
  { normalized: "ose", lemmaKey: "oser", headword: "oser", partOfSpeech: "verb", senseKey: "oser_dare", gloss: "to dare; venture", quizMeaning: "dare", definition: "avoir l’audace de faire quelque chose malgré le risque ou la difficulté", englishDistractors: ["knit", "paddle", "sneeze"], frenchDistractors: ["tricote", "pagaie", "éternue"] },
  { normalized: "osé", lemmaKey: "oser", headword: "oser", partOfSpeech: "verb", senseKey: "oser_dare", gloss: "to dare; venture", quizMeaning: "dared", definition: "avoir l’audace de faire quelque chose malgré le risque ou la difficulté", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricoté", "pagayé", "éternué"] },
  { normalized: "oser", lemmaKey: "oser", headword: "oser", partOfSpeech: "verb", senseKey: "oser_dare", gloss: "to dare; venture", definition: "avoir l’audace de faire quelque chose malgré le risque ou la difficulté", englishDistractors: ["to knit", "to paddle", "to sneeze"], frenchDistractors: ["tricoter", "pagayer", "éternuer"] },
  { normalized: "osera", lemmaKey: "oser", headword: "oser", partOfSpeech: "verb", senseKey: "oser_dare", gloss: "to dare; venture", quizMeaning: "will dare", definition: "avoir l’audace de faire quelque chose malgré le risque ou la difficulté", englishDistractors: ["will knit", "will paddle", "will sneeze"], frenchDistractors: ["tricotera", "pagayera", "éternuera"] },
  { normalized: "oserai", lemmaKey: "oser", headword: "oser", partOfSpeech: "verb", senseKey: "oser_dare", gloss: "to dare; venture", quizMeaning: "will dare", definition: "avoir l’audace de faire quelque chose malgré le risque ou la difficulté", englishDistractors: ["will knit", "will paddle", "will sneeze"], frenchDistractors: ["tricotera", "pagayera", "éternuera"] },
  { normalized: "oui", lemmaKey: "oui", headword: "oui", partOfSpeech: "interjection", senseKey: "oui_yes", gloss: "yes; indeed", definition: "réponse affirmative ou marque d’adhésion", englishDistractors: ["alas", "perhaps", "hush"], frenchDistractors: ["hélas", "peut-être", "chut"] },
  { normalized: "ourdit", lemmaKey: "ourdir", headword: "ourdir", partOfSpeech: "verb", senseKey: "ourdir_plot", gloss: "to plot; scheme", quizMeaning: "plots; schemes", definition: "préparer secrètement une action nuisible ou compliquée", englishDistractors: ["knits", "paddles", "sneezes"], frenchDistractors: ["tricote", "pagaie", "éternue"] },
  { normalized: "outrageante", lemmaKey: "outrageant", headword: "outrageant", partOfSpeech: "adjective", senseKey: "outrageant_offensive", gloss: "outrageous; offensive", definition: "qui blesse gravement la dignité ou choque par son injustice", englishDistractors: adjectiveEnglish, frenchDistractors: ["tachetée", "parfumée à la menthe", "hexagonale"] },
  { normalized: "outre", lemmaKey: "en_outre", headword: "en outre", partOfSpeech: "adverb", senseKey: "en_outre_moreover", gloss: "moreover; in addition", definition: "ajoute un élément supplémentaire au raisonnement", englishDistractors: ["tomorrow", "outside", "silently"], frenchDistractors: ["demain", "dehors", "silencieusement"] },
  { normalized: "ouvert", lemmaKey: "ouvrir", headword: "ouvrir", partOfSpeech: "verb", senseKey: "ouvrir_begin", gloss: "to open; begin", quizMeaning: "opened", definition: "faire passer d’un état fermé à un état accessible ou commencer une activité", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricoté", "pagayé", "éternué"] },
  { normalized: "ouvrier", lemmaKey: "ouvrier", headword: "ouvrier", partOfSpeech: "noun", senseKey: "ouvrier_worker", gloss: "worker; craftsman", definition: "personne qui travaille manuellement ou participe activement à une œuvre", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "ouvrir", lemmaKey: "ouvrir", headword: "ouvrir", partOfSpeech: "verb", senseKey: "ouvrir_begin", gloss: "to open; begin", definition: "faire passer d’un état fermé à un état accessible ou commencer une activité", englishDistractors: ["to knit", "to paddle", "to sneeze"], frenchDistractors: ["tricoter", "pagayer", "éternuer"] },
  { normalized: "pages", lemmaKey: "page", headword: "page", partOfSpeech: "noun", senseKey: "page_written_page", gloss: "page; written section", quizMeaning: "pages", definition: "feuille ou section d’un ouvrage écrit", englishDistractors: ["telescopes", "turnips", "cushions"], frenchDistractors: ["télescopes", "navets", "coussins"] },
  { normalized: "papier", lemmaKey: "papier", headword: "papier", partOfSpeech: "noun", senseKey: "papier_document", gloss: "paper; document", definition: "feuille destinée à l’écriture ou document écrit", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "papiers", lemmaKey: "papier", headword: "papier", partOfSpeech: "noun", senseKey: "papier_document", gloss: "paper; document", quizMeaning: "papers; documents", definition: "feuille destinée à l’écriture ou document écrit", englishDistractors: ["telescopes", "turnips", "cushions"], frenchDistractors: ["télescopes", "navets", "coussins"] },
  { normalized: "paquet", lemmaKey: "paquet", headword: "paquet", partOfSpeech: "noun", senseKey: "paquet_bundle", gloss: "bundle; packet", definition: "ensemble d’objets ou d’informations réunis en un seul groupe", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "parages", lemmaKey: "parage", headword: "parages", partOfSpeech: "noun", senseKey: "parage_vicinity", gloss: "vicinity; surrounding area", definition: "région ou environs d’un lieu", englishDistractors: ["telescopes", "turnips", "cushions"], frenchDistractors: ["télescopes", "navets", "coussins"] },
  { normalized: "paraît", lemmaKey: "paraitre", headword: "paraître", partOfSpeech: "verb", senseKey: "paraitre_appear", gloss: "to appear; seem", quizMeaning: "appears; seems", definition: "se montrer ou donner une impression déterminée", englishDistractors: ["knits", "paddles", "sneezes"], frenchDistractors: ["tricote", "pagaie", "éternue"] },
  { normalized: "paralysie", lemmaKey: "paralysie", headword: "paralysie", partOfSpeech: "noun", senseKey: "paralysie_paralysis", gloss: "paralysis", definition: "privation ou forte diminution de la capacité de mouvement", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "parce", lemmaKey: "parce_que", headword: "parce que", partOfSpeech: "conjunction", senseKey: "parce_que_because", gloss: "because", definition: "introduit la cause ou la raison d’un fait", englishDistractors: ["although", "unless", "while"], frenchDistractors: ["quoique", "à moins que", "pendant que"] },
  { normalized: "parfois", lemmaKey: "parfois", headword: "parfois", partOfSpeech: "adverb", senseKey: "parfois_sometimes", gloss: "sometimes", definition: "à certains moments, mais pas toujours", englishDistractors: ["tomorrow", "outside", "silently"], frenchDistractors: ["demain", "dehors", "silencieusement"] },
  { normalized: "parlait", lemmaKey: "parler", headword: "parler", partOfSpeech: "verb", senseKey: "parler_speak", gloss: "to speak; talk", quizMeaning: "was speaking; was talking", definition: "exprimer une pensée par la parole ou traiter d’un sujet", englishDistractors: ["was knitting", "was paddling", "was sneezing"], frenchDistractors: ["tricotait", "pagayait", "éternuait"] },
  { normalized: "parle", lemmaKey: "parler", headword: "parler", partOfSpeech: "verb", senseKey: "parler_speak", gloss: "to speak; talk", quizMeaning: "speaks; talks", definition: "exprimer une pensée par la parole ou traiter d’un sujet", englishDistractors: ["knits", "paddles", "sneezes"], frenchDistractors: ["tricote", "pagaie", "éternue"] },
  { normalized: "parlé", lemmaKey: "parler", headword: "parler", partOfSpeech: "verb", senseKey: "parler_speak", gloss: "to speak; talk", quizMeaning: "spoken; talked about", definition: "exprimer une pensée par la parole ou traiter d’un sujet", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricoté", "pagayé", "éternué"] },
  { normalized: "parler", lemmaKey: "parler", headword: "parler", partOfSpeech: "verb", senseKey: "parler_speak", gloss: "to speak; talk", definition: "exprimer une pensée par la parole ou traiter d’un sujet", englishDistractors: ["to knit", "to paddle", "to sneeze"], frenchDistractors: ["tricoter", "pagayer", "éternuer"] },
  { normalized: "part", candidateIds: ["tok_3057c936fc9af0eaf52c69d9"], lemmaKey: "part", headword: "part", partOfSpeech: "noun", senseKey: "part_behalf", gloss: "part; behalf", definition: "rôle ou côté attribué à une personne dans une situation", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "part", candidateIds: ["tok_a0494505fda78be2360ffed8", "tok_459a19723e94180b4f12a17b"], lemmaKey: "part", headword: "part", partOfSpeech: "noun", senseKey: "part_side", gloss: "part; side", definition: "côté ou aspect d’un ensemble considéré séparément", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "partialité", lemmaKey: "partialite", headword: "partialité", partOfSpeech: "noun", senseKey: "partialite_bias", gloss: "partiality; bias", definition: "absence d’impartialité et préférence injuste pour un camp", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "particulièrement", lemmaKey: "particulierement", headword: "particulièrement", partOfSpeech: "adverb", senseKey: "particulierement_especially", gloss: "particularly; especially", definition: "d’une manière spéciale ou plus que les autres éléments", englishDistractors: ["tomorrow", "outside", "silently"], frenchDistractors: ["demain", "dehors", "silencieusement"] },
  { normalized: "partie", lemmaKey: "partie", headword: "partie", partOfSpeech: "noun", senseKey: "partie_portion", gloss: "part; portion", quizMeaning: "part; partly", definition: "portion d’un ensemble, employée dans « en partie » pour indiquer une réalisation incomplète", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "passait", lemmaKey: "passer", headword: "passer", partOfSpeech: "verb", senseKey: "passer_elapse_happen", gloss: "to pass; happen", quizMeaning: "was happening", definition: "se dérouler, arriver ou s’écouler dans le temps", englishDistractors: ["was knitting", "was paddling", "was sneezing"], frenchDistractors: ["tricotait", "pagayait", "éternuait"] },
  { normalized: "passée", lemmaKey: "passer", headword: "passer", partOfSpeech: "verb", senseKey: "passer_elapse_happen", gloss: "to pass; happen", quizMeaning: "passed; elapsed", definition: "se dérouler, arriver ou s’écouler dans le temps", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricotée", "pagayée", "éternuée"] },
  { normalized: "passés", lemmaKey: "passer", headword: "passer", partOfSpeech: "verb", senseKey: "passer_elapse_happen", gloss: "to pass; happen", quizMeaning: "passed; elapsed", definition: "se dérouler, arriver ou s’écouler dans le temps", englishDistractors: ["knitted", "paddled", "sneezed"], frenchDistractors: ["tricotés", "pagayés", "éternués"] },
];
