import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a chimney","a melon","a violin"];
const nF:[string,string,string]=["cheminée","melon","violon"];
const aE:[string,string,string]=["woolen","vanilla-scented","cylindrical"];
const aF:[string,string,string]=["laineux","parfumé à la vanille","cylindrique"];
const vE:[string,string,string]=["to crochet","to ski","to whistle"];
const vF:[string,string,string]=["crocheter","skier","siffler"];

export const zolaVocabularyBatch21: ZolaVocabularySpec[] = [
 {normalized:"eut",lemmaKey:"avoir",headword:"avoir",partOfSpeech:"verb",senseKey:"avoir_possess_auxiliary",gloss:"to have; auxiliary avoir",quizMeaning:"had",definition:"posséder ou servir d’auxiliaire",englishDistractors:["crocheted","skied","whistled"],frenchDistractors:["crocheta","skia","siffla"]},
 {normalized:"eux",lemmaKey:"eux",headword:"eux",partOfSpeech:"pronoun",senseKey:"eux_them",gloss:"them",definition:"pronom personnel masculin pluriel employé avec insistance ou après une préposition",englishDistractors:["herself","ourselves","itself"],frenchDistractors:["elle","nous","lui"]},
 {normalized:"eux-mêmes",lemmaKey:"eux",headword:"eux",partOfSpeech:"pronoun",senseKey:"eux_them",gloss:"them",quizMeaning:"themselves",definition:"pronom personnel masculin pluriel employé avec insistance ou après une préposition",englishDistractors:["herself","ourselves","itself"],frenchDistractors:["elle-même","nous-mêmes","lui-même"]},
 {normalized:"évidemment",lemmaKey:"evidemment",headword:"évidemment",partOfSpeech:"adverb",senseKey:"evidemment_obviously",gloss:"obviously; clearly",definition:"d’une manière qui paraît certaine et manifeste",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"examen",lemmaKey:"examen",headword:"examen",partOfSpeech:"noun",senseKey:"examen_examination",gloss:"examination; review",definition:"étude attentive destinée à vérifier ou comprendre quelque chose",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"examinait",lemmaKey:"examiner",headword:"examiner",partOfSpeech:"verb",senseKey:"examiner_inspect",gloss:"to examine; inspect",quizMeaning:"was examining",definition:"observer ou étudier avec attention",englishDistractors:["was crocheting","was skiing","was whistling"],frenchDistractors:["crochetait","skiait","sifflait"]},
 {normalized:"exaspérer",lemmaKey:"exasperer",headword:"exaspérer",partOfSpeech:"verb",senseKey:"exasperer_inflame",gloss:"to exasperate; inflame",definition:"porter un sentiment ou une opposition à un degré extrême",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"excuse",lemmaKey:"excuse",headword:"excuse",partOfSpeech:"noun",senseKey:"excuse_justification",gloss:"excuse; justification",definition:"raison avancée pour atténuer ou justifier une faute",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"exercice",lemmaKey:"exercice",headword:"exercice",partOfSpeech:"noun",senseKey:"exercice_performance",gloss:"exercise; performance",definition:"action d’accomplir effectivement une fonction ou un pouvoir",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"exigé",lemmaKey:"exiger",headword:"exiger",partOfSpeech:"verb",senseKey:"exiger_require",gloss:"to require; demand",quizMeaning:"required; demanded",definition:"réclamer quelque chose comme nécessaire ou obligatoire",englishDistractors:["crocheted","skied","whistled"],frenchDistractors:["crocheté","skié","sifflé"]},
 {normalized:"exigeant",lemmaKey:"exigeant",headword:"exigeant",partOfSpeech:"adjective",senseKey:"exigeant_demanding",gloss:"demanding",definition:"qui réclame beaucoup ou impose des conditions difficiles",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"existence",lemmaKey:"existence",headword:"existence",partOfSpeech:"noun",senseKey:"existence_fact",gloss:"existence",definition:"fait d’exister ou d’être réellement présent",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"exister",lemmaKey:"exister",headword:"exister",partOfSpeech:"verb",senseKey:"exister_be_present",gloss:"to exist",definition:"avoir une réalité ou être présent",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"expédients",lemmaKey:"expedient",headword:"expédient",partOfSpeech:"noun",senseKey:"expedient_makeshift",gloss:"expedient; makeshift",quizMeaning:"expedients; makeshifts",definition:"moyen provisoire ou habile employé pour sortir d’une difficulté",englishDistractors:["chimneys","melons","violins"],frenchDistractors:["cheminées","melons","violons"]},
 {normalized:"expériences",lemmaKey:"experience",headword:"expérience",partOfSpeech:"noun",senseKey:"experience_trial",gloss:"experiment; ordeal",quizMeaning:"experiments; ordeals",definition:"épreuve ou essai destiné à observer un résultat",englishDistractors:["chimneys","melons","violins"],frenchDistractors:["cheminées","melons","violons"]},
 {normalized:"experts",lemmaKey:"expert",headword:"expert",partOfSpeech:"noun",senseKey:"expert_specialist",gloss:"expert; specialist",quizMeaning:"experts; specialists",definition:"personne chargée de donner un avis technique spécialisé",englishDistractors:["chimneys","melons","violins"],frenchDistractors:["cheminées","melons","violons"]},
 {normalized:"expiation",lemmaKey:"expiation",headword:"expiation",partOfSpeech:"noun",senseKey:"expiation_atonement",gloss:"atonement; punishment",definition:"souffrance ou peine par laquelle une faute est réparée",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"expie",lemmaKey:"expier",headword:"expier",partOfSpeech:"verb",senseKey:"expier_atone",gloss:"to atone; pay the penalty",quizMeaning:"atones; pays the penalty",definition:"subir une peine pour réparer une faute",englishDistractors:["crochets","skis","whistles"],frenchDistractors:["crochète","skie","siffle"]},
 {normalized:"expliquent",lemmaKey:"expliquer",headword:"expliquer",partOfSpeech:"verb",senseKey:"expliquer_make_clear",gloss:"to explain",quizMeaning:"explain",definition:"rendre une chose compréhensible en exposant ses causes",englishDistractors:["crochet","ski","whistle"],frenchDistractors:["crochètent","skient","sifflent"]},
 {normalized:"expliquer",lemmaKey:"expliquer",headword:"expliquer",partOfSpeech:"verb",senseKey:"expliquer_make_clear",gloss:"to explain",definition:"rendre une chose compréhensible en exposant ses causes",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"exploiter",lemmaKey:"exploiter",headword:"exploiter",partOfSpeech:"verb",senseKey:"exploiter_use",gloss:"to exploit; make use of",definition:"tirer parti de quelque chose à son avantage",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"explosion",lemmaKey:"explosion",headword:"explosion",partOfSpeech:"noun",senseKey:"explosion_burst",gloss:"explosion; outburst",definition:"libération soudaine et violente d’une force accumulée",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"expose",lemmaKey:"s_exposer",headword:"s’exposer",partOfSpeech:"verb",senseKey:"s_exposer_risk",gloss:"to expose oneself; take a risk",quizMeaning:"expose myself; take a risk",definition:"se placer volontairement face à un danger ou à une conséquence",englishDistractors:["crochet","ski","whistle"],frenchDistractors:["crochète","skie","siffle"]},
 {normalized:"expulser",lemmaKey:"expulser",headword:"expulser",partOfSpeech:"verb",senseKey:"expulser_remove",gloss:"to expel",definition:"faire sortir quelqu’un d’un lieu ou d’un groupe par autorité",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"extraordinaires",lemmaKey:"extraordinaire",headword:"extraordinaire",partOfSpeech:"adjective",senseKey:"extraordinaire_unusual",gloss:"extraordinary; unusual",definition:"qui sort fortement de l’ordinaire",englishDistractors:aE,frenchDistractors:["laineuses","parfumées à la vanille","cylindriques"]},
];
