import type { ZolaVocabularySpec } from "./zola-authoring.js";

type Entry = Omit<ZolaVocabularySpec, "existingLemmaId" | "existingSenseId"> & {
  existingLemmaId?: string;
  existingSenseId?: string;
};

const make = (entry: Entry): ZolaVocabularySpec => entry;

const noun = (
  normalized: string,
  lemmaKey: string,
  candidateIds: readonly string[],
  senseKey: string,
  headword: string,
  gloss: string,
  definition: string,
  englishDistractors: [string, string, string],
  frenchDistractors: [string, string, string],
  existingLemmaId?: string,
  existingSenseId?: string,
): ZolaVocabularySpec => make({ normalized, candidateIds, lemmaKey, senseKey, headword, partOfSpeech: "noun", gloss, quizMeaning: gloss, definition, englishDistractors, frenchDistractors, ...(existingLemmaId ? { existingLemmaId } : {}), ...(existingSenseId ? { existingSenseId } : {}) });

const verb = (
  normalized: string,
  lemmaKey: string,
  candidateIds: readonly string[],
  senseKey: string,
  headword: string,
  gloss: string,
  definition: string,
  englishDistractors: [string, string, string],
  frenchDistractors: [string, string, string],
  existingLemmaId?: string,
  existingSenseId?: string,
): ZolaVocabularySpec => make({ normalized, candidateIds, lemmaKey, senseKey, headword, partOfSpeech: "verb", gloss, quizMeaning: gloss, definition, englishDistractors, frenchDistractors, ...(existingLemmaId ? { existingLemmaId } : {}), ...(existingSenseId ? { existingSenseId } : {}) });

const adjective = (
  normalized: string,
  lemmaKey: string,
  candidateIds: readonly string[],
  senseKey: string,
  headword: string,
  gloss: string,
  definition: string,
  englishDistractors: [string, string, string],
  frenchDistractors: [string, string, string],
  existingLemmaId?: string,
  existingSenseId?: string,
): ZolaVocabularySpec => make({ normalized, candidateIds, lemmaKey, senseKey, headword, partOfSpeech: "adjective", gloss, quizMeaning: gloss, definition, englishDistractors, frenchDistractors, ...(existingLemmaId ? { existingLemmaId } : {}), ...(existingSenseId ? { existingSenseId } : {}) });

const adverb = (
  normalized: string,
  lemmaKey: string,
  candidateIds: readonly string[],
  senseKey: string,
  headword: string,
  gloss: string,
  definition: string,
  englishDistractors: [string, string, string],
  frenchDistractors: [string, string, string],
  existingLemmaId?: string,
  existingSenseId?: string,
): ZolaVocabularySpec => make({ normalized, candidateIds, lemmaKey, senseKey, headword, partOfSpeech: "adverb", gloss, quizMeaning: gloss, definition, englishDistractors, frenchDistractors, ...(existingLemmaId ? { existingLemmaId } : {}), ...(existingSenseId ? { existingSenseId } : {}) });

const determiner = (
  normalized: string,
  candidateIds: readonly string[],
  senseKey: string,
  headword: string,
  gloss: string,
  definition: string,
  englishDistractors: [string, string, string],
  frenchDistractors: [string, string, string],
  lemmaKey: string,
  existingLemmaId?: string,
  existingSenseId?: string,
): ZolaVocabularySpec => make({ normalized, candidateIds, lemmaKey, senseKey, headword, partOfSpeech: "determiner", gloss, quizMeaning: gloss, definition, englishDistractors, frenchDistractors, ...(existingLemmaId ? { existingLemmaId } : {}), ...(existingSenseId ? { existingSenseId } : {}) });

export const zolaVocabularyBatch47: ZolaVocabularySpec[] = [
  determiner("quelle", ["tok_e76179c8f11e8837ecb1c240", "tok_e4aec40da990b699619aaf6f", "tok_b2ddf0d7e0fd29d54bbaa6c8", "tok_609b9ea5354b1996e72f1307"], "quel_primary", "quel", "which; what", "déterminant interrogatif ou exclamatif qui précise un nom", ["whose", "how many", "where"], ["dont", "combien", "où"], "quel", "lem_quel", "sns_quel_primary"),
  determiner("quel", ["tok_e291ddc11ccf3caf6993b22b", "tok_d215edbc087f7330d441f064", "tok_915d613d0a63e64fa4cb0cf6", "tok_174b63df4d0d75ac6de05eca"], "quel_primary", "quel", "which; what", "déterminant interrogatif ou exclamatif qui précise un nom", ["whose", "how many", "where"], ["dont", "combien", "où"], "quel", "lem_quel", "sns_quel_primary"),
  determiner("quelles", ["tok_a3ba15f9ef3792d0f11d91a5"], "quel_primary", "quel", "which; what", "déterminant interrogatif ou exclamatif au féminin pluriel", ["whose", "how many", "where"], ["dont", "combien", "où"], "quel", "lem_quel", "sns_quel_primary"),
  determiner("quels", ["tok_5e195443bb6b498c6e126d41"], "quel_primary", "quel", "which; what", "déterminant interrogatif ou exclamatif au masculin pluriel", ["whose", "how many", "where"], ["dont", "combien", "où"], "quel", "lem_quel", "sns_quel_primary"),
  determiner("quelques", ["tok_b28125b910e9d8a976feeb5e"], "quelque_indefinite", "quelque", "some; several", "déterminant qui indique une petite quantité indéterminée", ["each", "no", "every"], ["chaque", "aucun", "tout"], "quelque", "lem_zola_quelque", "sns_zola_quelque_indefinite"),
  { ...noun("plusieurs", "plusieurs", ["tok_fda8976c58a78896daf90498"], "plusieurs_several", "plusieurs", "several; many", "détermine un nom pluriel en indiquant un nombre supérieur à un mais indéterminé", ["one", "neither", "none"], ["un", "ni l’un ni l’autre", "aucun" ]), partOfSpeech: "determiner" },
  { ...verb("tandis", "tandis", ["tok_ed66d09841bbccdcd61460bb", "tok_d2b65ad18f4596dbbeb9436a"], "tandis_whereas", "tandis", "whereas; while", "conjonction qui met en contraste deux actions ou situations simultanées", ["because", "before", "therefore"], ["parce que", "avant que", "donc"]), partOfSpeech: "conjunction" },
  verb("pouvons", "pouvoir", ["tok_8e2f64530ca977230600896d", "tok_93c0a07d075ef413ea05421f"], "pouvoir_present_ability", "pouvoir", "can; are able to", "forme du présent de pouvoir indiquant une capacité ou une possibilité", ["must", "want", "forget"], ["doivent", "veulent", "oublient"], "lem_zola_pouvoir"),
  verb("vu", "voir", ["tok_0b06546b16ff3be296cb4e3f", "tok_3b5c7281741875d73199502a"], "voir_past_participle", "voir", "seen", "participe passé de voir, indiquant qu’une personne ou une chose a été observée", ["heard", "hidden", "forgotten"], ["entendu", "caché", "oublié"], "lem_voir"),
  adjective("scélérate", "scelerat_adjective", ["tok_8b975b5b53f661bf0a2cf7b6", "tok_8489c469e5cbd506ee36980f"], "scelerat_wicked", "scélérat", "wicked; disgraceful", "qui manifeste une malhonnêteté ou une gravité moralement condamnable", ["honest", "ordinary", "peaceful"], ["honnête", "ordinaire", "paisible"]),
  adjective("supérieure", "superieur_adjective", ["tok_5e1649111fca4f84c7157c99", "tok_e824c2d53e6a50faa6d3480d"], "superieur_higher", "supérieur", "superior; higher", "qui est placé plus haut ou considéré comme de rang plus élevé", ["inferior", "equal", "hidden"], ["inférieure", "égale", "cachée"]),
  noun("pouvoir", "pouvoir_noun", ["tok_62f71dc5838b9964ffef6d53", "tok_11ccaa439f4dc39cd7955b3f"], "pouvoir_authority", "pouvoir", "power; authority", "capacité d’agir, d’imposer une décision ou d’exercer une autorité", ["weakness", "silence", "distance"], ["faiblesse", "silence", "distance"]),
  adverb("publiquement", "publiquement", ["tok_d4d748d00415410fb72283a8", "tok_d4073189ba31ec27f1e92d83"], "publiquement_openly", "publiquement", "publicly; openly", "d’une manière visible ou connue de la collectivité", ["secretly", "rarely", "tomorrow"], ["secrètement", "rarement", "demain"]),
  verb("répète", "répéter", ["tok_6195e33a5977e44176847aeb", "tok_51887a59e93a70d9c91c0732"], "repeter_present", "répéter", "repeat; say again", "forme du présent de répéter, indiquant qu’une parole est redite", ["forgets", "hides", "denies"], ["oublie", "cache", "nie"]),
  noun("terre", "terre", ["tok_c659adc1d142026797645a33", "tok_8e9c3aad36af0c23b3041951"], "terre_ground", "terre", "earth; ground", "sol ou planète considérée comme le monde habité", ["sky", "water", "silence"], ["ciel", "eau", "silence"]),
  noun("respect", "respect", ["tok_fab9ab2968c221f448f2f2e9", "tok_bbe2cd5f68cd5079116c025b"], "respect_deference", "respect", "respect; regard", "sentiment de considération envers une personne, une règle ou une valeur", ["contempt", "noise", "fear"], ["mépris", "bruit", "peur"]),
  verb("soit", "etre", ["tok_e645f24c207b00bee74d6d89", "tok_488fa8c3f0246c69a2773253"], "etre_subjunctive", "être", "be", "forme du subjonctif présent de être", ["have", "go", "know"], ["avoir", "aller", "savoir"], "lem_etre"),
  verb("veulent", "vouloir", ["tok_020c77581be4cb996e0a4554", "tok_a88c5c5de6d0271e2c5bd799"], "vouloir_present", "vouloir", "want", "forme du présent de vouloir exprimant une volonté", ["can", "must", "believe"], ["peuvent", "doivent", "croient"], "lem_zola_vouloir", "sns_zola_vouloir_present"),
  { ...verb("puisque", "puisque", ["tok_254ccc50fd72febefdf30f61", "tok_8d0277f9349e725ba86b387a"], "puisque_since", "puisque", "since; as", "introduit une cause considérée comme connue ou évidente", ["although", "before", "unless"], ["bien que", "avant que", "à moins que"], "lem_zola_puisque", "sns_zola_puisque_since"), partOfSpeech: "conjunction" },
  noun("témoin", "temoin", ["tok_08d2ea439f5a23d5d1c046c1", "tok_f90a247329427213bc7f67fa"], "temoin_witness", "témoin", "witness", "personne qui a vu un fait et peut en rendre compte", ["judge", "accused person", "author"], ["juge", "accusé", "auteur"]),
  adjective("telle", "tel", ["tok_7a1e96388ce8bf226a393beb", "tok_1697f96c44ac7d48b8bb1dd1"], "tel_primary", "tel", "such; so great", "adjectif féminin indiquant une qualité ou un degré de cette nature", ["different", "ordinary", "hidden"], ["différente", "ordinaire", "cachée"], "lem_tel", "sns_tel_primary"),

  noun("pièges", "piege", ["tok_828113bcb4460b21d40c252f"], "piege_trap", "piège", "traps; snares", "dispositifs ou manœuvres destinés à surprendre ou tromper quelqu’un", ["escapes", "answers", "celebrations"], ["évasions", "réponses", "célébrations"]),
  noun("plaisir", "plaisir", ["tok_e071eb6c721b873be3907c09"], "plaisir_pleasure", "plaisir", "pleasure; willingness", "satisfaction ou volonté personnelle de faire quelque chose", ["duty", "fear", "silence"], ["devoir", "peur", "silence"]),
  adjective("plein", "plein", ["tok_456ccda398bebd2af7d4307e"], "plein_full", "plein", "full; complete", "qui contient tout ce qu’il peut contenir ou qui est entièrement occupé", ["empty", "narrow", "distant"], ["vide", "étroit", "lointain"], "lem_zola_plein", "sns_zola_plein_full"),
  adverb("plus", "plus", ["tok_931f553c962ec8910a6306e0"], "plus_no_longer", "plus", "no longer; anymore", "dans une phrase négative, indique qu’une action ne se poursuit plus", ["still", "already", "always"], ["encore", "déjà", "toujours"], "lem_plus"),
  noun("poignée", "poignee", ["tok_3c06b9b403ca7d74cbb3bf76"], "poignee_handle", "poignée", "hilt; handle", "partie par laquelle on saisit une arme ou un objet", ["blade", "door", "scabbard"], ["lame", "porte", "fourreau"]),
  noun("police", "police", ["tok_9825948800b7ed5d10352f1f"], "police_force", "police", "police; law enforcement", "organisation chargée de maintenir l’ordre et de rechercher les infractions", ["school", "hospital", "newspaper"], ["école", "hôpital", "journal"]),
  adjective("politique", "politique", ["tok_fb6bf6ef87d6e25723719b79"], "politique_civic", "politique", "political; civic", "qui concerne la conduite des affaires publiques", ["private", "medical", "musical"], ["privé", "médical", "musical"]),
  verb("portant", "porter", ["tok_3dfb89168a0694320a8fa578"], "porter_gerund", "porter", "carrying; bringing", "participe présent de porter, indiquant l’action de porter ou d’entraîner", ["hiding", "forgetting", "refusing"], ["cachant", "oubliant", "refusant"], "lem_porter"),
  noun("positions", "position", ["tok_7f2aa257f17e51e0fced4f3b"], "position_stance", "position", "positions; stances", "manières de se situer ou opinions adoptées dans une affaire", ["questions", "journeys", "secrets"], ["questions", "voyages", "secrets"]),
  adverb("pourquoi", "pourquoi", ["tok_4eecd7386ad9fbc0ae0c2a56"], "pourquoi_reason", "pourquoi", "why", "adverbe qui demande la cause ou la raison", ["when", "where", "how"], ["quand", "où", "comment"]),
  noun("pratiques", "pratique", ["tok_d8836d4772d6d6506708c289"], "pratique_conduct", "pratique", "practices; methods", "manières habituelles d’agir ou procédés employés", ["theories", "silences", "victories"], ["théories", "silences", "victoires"]),
  adjective("préconçue", "preconcu", ["tok_cfa2dd66b2e16258ea90420b"], "preconcu_prejudged", "préconçu", "preconceived", "formé à l’avance sans examen des faits", ["impartial", "recent", "visible"], ["impartiale", "récente", "visible"]),
  noun("préjugés", "prejuge", ["tok_bb055f216eadbd6c6a1a8af1"], "prejuge_bias", "préjugé", "prejudices; biases", "opinions formées avant un examen attentif et souvent défavorables", ["proofs", "agreements", "questions"], ["preuves", "accords", "questions"]),
  verb("prend", "prendre", ["tok_59d5eed49b2d9da4a9dfeea9"], "prendre_acquire", "prendre", "takes; gains", "forme du présent de prendre, indiquant l’acquisition d’une force ou d’un état", ["loses", "hides", "breaks"], ["perd", "cache", "brise"], "lem_prendre"),
  verb("préparer", "preparer", ["tok_58e7173c8c9dc1fe1b3a4785"], "preparer_prepare", "préparer", "prepare", "mettre en ordre ou rendre prêt à l’avance", ["destroy", "forget", "conceal"], ["détruire", "oublier", "dissimuler"]),
  verb("préparez", "preparer", ["tok_739e1d748c38d7076227b1a9"], "preparer_prepare", "préparer", "prepare", "mettre en ordre ou rendre prêt à l’avance", ["destroy", "forget", "conceal"], ["détruisez", "oubliez", "dissimulez"]),
  verb("présider", "presider", ["tok_4eac5674c6b7f9297956ec2e"], "presider_lead", "présider", "preside; chair", "diriger une réunion, une cérémonie ou une institution", ["follow", "hide", "resign"], ["suivre", "cacher", "démissionner"]),
  noun("pression", "pression", ["tok_536108d1f62c63ac952ac878"], "pression_pressure", "pression", "pressure", "force exercée sur quelqu’un pour le pousser à agir", ["freedom", "silence", "distance"], ["liberté", "silence", "distance"]),
  noun("prétexte", "pretexte", ["tok_d07b24c30c10268d414f7a1b"], "pretexte_pretext", "prétexte", "pretext; excuse", "raison invoquée pour dissimuler le véritable motif d’une action", ["proof", "result", "promise"], ["preuve", "résultat", "promesse"]),
  verb("pris", "prendre", ["tok_a4bf6e247939797ae47e4bfb"], "prendre_charge", "prendre", "taken on; assumed", "participe passé de prendre dans l’expression prendre à sa charge", ["abandoned", "hidden", "forgotten"], ["abandonné", "caché", "oublié"], "lem_prendre", "sns_zola_prendre_charge"),
  noun("prisonnier", "prisonnier", ["tok_741b8759fdca156ff80435bc"], "prisonnier_captive", "prisonnier", "prisoner; captive", "personne privée de liberté ou soumise à une contrainte", ["leader", "visitor", "witness"], ["dirigeant", "visiteur", "témoin"]),
  noun("prix", "prix", ["tok_72814a6cd670efe64898a273"], "prix_cost", "prix", "price; cost", "valeur à payer ou sacrifice accepté pour obtenir quelque chose", ["reward", "silence", "distance"], ["récompense", "silence", "distance"]),
  noun("probité", "probite", ["tok_3899933e2b4a0e8593f82524"], "probite_integrity", "probité", "integrity; honesty", "droiture morale et respect scrupuleux de l’honnêteté", ["deceit", "anger", "noise"], ["tromperie", "colère", "bruit"]),
  adjective("prochaine", "prochain", ["tok_1c02fa2172a40a3c36562a70"], "prochain_future", "prochain", "next; forthcoming", "qui doit arriver ou se produire bientôt", ["past", "distant", "hidden"], ["passée", "lointaine", "cachée"]),
  adverb("prochainement", "prochainement", ["tok_69f2a5f0e50a5d22b853afa3"], "prochainement_soon", "prochainement", "soon; shortly", "dans un avenir proche", ["yesterday", "never", "elsewhere"], ["hier", "jamais", "ailleurs"]),
  verb("proclame", "proclamer", ["tok_2c7cb13416f6a0b9e61a04a6"], "proclamer_declare", "proclamer", "proclaim; declare", "annoncer publiquement une affirmation ou une décision", ["hides", "questions", "denies"], ["cache", "questionne", "nie"]),
  verb("proclamer", "proclamer", ["tok_22db65bc3e423fa348ae186e"], "proclamer_declare", "proclamer", "proclaim; declare", "annoncer publiquement une affirmation ou une décision", ["hide", "question", "deny"], ["cacher", "questionner", "nier"]),
  noun("prodige", "prodige", ["tok_f6ce22f03d396e12c45b9c73"], "prodige_wonder", "prodige", "wonder; marvel", "fait extraordinaire qui paraît difficile à expliquer", ["routine", "silence", "mistake"], ["routine", "silence", "erreur"]),
  adjective("prodigieuse", "prodigieux", ["tok_3af191824bef1e121abd44f5"], "prodigieux_extraordinary", "prodigieux", "extraordinary; astounding", "qui est exceptionnel par son ampleur ou son caractère étonnant", ["ordinary", "minor", "hidden"], ["ordinaire", "mineure", "cachée"]),
  verb("produire", "produire", ["tok_741d2a966040800bfb1e73b0"], "produire_present", "produire", "produce; present", "faire apparaître ou présenter un élément, notamment comme preuve", ["destroy", "hide", "borrow"], ["détruire", "cacher", "emprunter"]),
  adjective("profond", "profond", ["tok_5adf28e9228ed1bc589d45d6"], "profond_intense", "profond", "deep; profound", "qui atteint une grande intensité ou une grande profondeur", ["shallow", "brief", "public"], ["superficiel", "bref", "public"]),
  adverb("profondément", "profondement", ["tok_47b8a87cfb65f84e3563f3cb"], "profondement_deeply", "profondément", "deeply", "à un degré intense ou dans une grande profondeur", ["slightly", "openly", "rarely"], ["légèrement", "ouvertement", "rarement"]),
  verb("projeter", "projeter", ["tok_4b1efcda346a0b23e2baa6bf"], "projeter_cast", "projeter", "project; cast", "faire tomber ou diriger une lumière, une image ou un objet", ["absorb", "hide", "forget"], ["absorber", "cacher", "oublier"]),
  verb("promis", "promettre", ["tok_be89c5604e48cda0fc3dafec"], "promettre_past", "promettre", "promised", "participe passé de promettre, s’engager à faire quelque chose", ["refused", "forgotten", "hidden"], ["refusé", "oublié", "caché"]),
  noun("protecteurs", "protecteur", ["tok_8fa574bbe8b11f3835676950"], "protecteur_guardian", "protecteur", "protectors; guardians", "personnes qui défendent ou soutiennent quelqu’un", ["enemies", "judges", "strangers"], ["ennemis", "juges", "étrangers"]),
  noun("protestation", "protestation", ["tok_96087fcbfc5e3f3be7888a4a"], "protestation_objection", "protestation", "protest; objection", "expression publique d’un désaccord ou d’une indignation", ["agreement", "silence", "celebration"], ["accord", "silence", "célébration"]),
  adjective("psychologique", "psychologique", ["tok_1365e69b739b5be764c52c55"], "psychologique_mental", "psychologique", "psychological", "qui concerne la vie intérieure et les réactions de l’esprit", ["physical", "legal", "musical"], ["physique", "juridique", "musical"]),
  verb("publier", "publier", ["tok_3bbf71160f8c978699c26ada"], "publier_release", "publier", "publish; make public", "rendre un texte ou une information accessible au public", ["hide", "destroy", "translate"], ["cacher", "détruire", "traduire"]),
  verb("puis", "pouvoir", ["tok_6a98e90cf542dac32c7df50e"], "pouvoir_present_ability", "pouvoir", "can; am able to", "forme ancienne du présent de pouvoir à la première personne du singulier", ["must", "want", "forget"], ["dois", "veux", "oublie"], "lem_zola_pouvoir", "sns_zola_pouvoir_present_ability"),
  verb("puisse", "pouvoir", ["tok_b51c1b274d7fbd1930d89c04"], "pouvoir_subjunctive", "pouvoir", "may; can", "forme du subjonctif de pouvoir indiquant une possibilité", ["must", "refuse", "sleep"], ["doive", "refuse", "dorme"], "lem_zola_pouvoir"),
  verb("puni", "punir", ["tok_164c0e7b9af532c22ba472fc"], "punir_past", "punir", "punished", "participe passé de punir, frappé d’une peine ou d’une conséquence", ["rewarded", "freed", "ignored"], ["récompensé", "libéré", "ignoré"]),
  verb("punira", "punir", ["tok_581377b6f1110551cd150eda"], "punir_future", "punir", "will punish", "forme du futur de punir", ["will reward", "will free", "will ignore"], ["récompensera", "libérera", "ignorera"]),
  verb("punit", "punir", ["tok_60acceb04eb76c6769150be5"], "punir_present", "punir", "punishes", "forme du présent de punir", ["rewards", "frees", "ignores"], ["récompense", "libère", "ignore"]),
  { ...noun("quatorze", "quatorze", ["tok_29fa77f9855f79e2500e11a8"], "quatorze_number", "quatorze", "fourteen", "nombre entier égal à dix plus quatre", ["twelve", "fifteen", "twenty"], ["douze", "quinze", "vingt"]), partOfSpeech: "numeral" },
  adjective("quinzième", "quinzieme", ["tok_0770c64ddd5fc71179a10380"], "quinzieme_ordinal", "quinzième", "fifteenth", "qui vient immédiatement après le quatorzième", ["fourteenth", "sixteenth", "first"], ["quatorzième", "seizième", "premier"]),
  verb("raconte", "raconter", ["tok_728f1fcef4125b32868f655c"], "raconter_present", "raconter", "tells; recounts", "forme du présent de raconter, rapporter une histoire ou un fait", ["hides", "forgets", "denies"], ["cache", "oublie", "nie"]),
  noun("raison", "raison", ["tok_b74a7d23bc9116ef069bc663"], "raison_primary", "raison", "reason", "motif ou explication d’un fait", ["result", "silence", "mistake"], ["résultat", "silence", "erreur"], "lem_raison", "sns_raison_primary"),
  adjective("raisonné", "raisonne", ["tok_01e8aecb5e8ab99b312403a0"], "raisonne_reasoned", "raisonné", "reasoned; rational", "fondé sur un examen réfléchi et logique", ["random", "secret", "violent"], ["aléatoire", "secret", "violent"]),
  verb("raisonner", "raisonner", ["tok_7e787702b6746249111ac67c"], "raisonner_reason", "raisonner", "reason; reason out", "examiner des faits en suivant un raisonnement logique", ["forget", "shout", "hide"], ["oublier", "crier", "cacher"]),
  noun("rancune", "rancune", ["tok_49055222f25a7ce71dd50176"], "rancune_resentment", "rancune", "resentment; grudge", "hostilité durable née d’une offense ou d’un tort", ["gratitude", "trust", "joy"], ["gratitude", "confiance", "joie"]),
  noun("rapport", "rapport", ["tok_5037fb04bf9909d89033a71c"], "rapport_report", "rapport", "report", "document qui expose des faits ou les résultats d’une enquête", ["fiction", "silence", "weapon"], ["fiction", "silence", "arme"]),
  noun("rapporteur", "rapporteur", ["tok_8d9ccb1661e68aaf7f4d3826"], "rapporteur_reporter", "rapporteur", "reporting judge; rapporteur", "personne chargée de présenter le rapport d’une affaire", ["witness", "prisoner", "messenger"], ["témoin", "prisonnier", "messager"]),
  noun("rapports", "rapport", ["tok_6940383ea359ccb30dff7d01"], "rapport_report", "rapport", "report", "document qui expose des faits ou les résultats d’une enquête", ["fiction", "silence", "weapons"], ["fiction", "silence", "armes"]),
  adjective("rayonnant", "rayonnant", ["tok_412c048ebc4a0c7ecd7858a3"], "rayonnant_glowing", "rayonnant", "radiant; glowing", "qui exprime un éclat ou une joie très visible", ["dull", "hidden", "angry"], ["terne", "caché", "furieux"]),
  noun("réaction", "reaction", ["tok_bb06d8f004790622c855ec45"], "reaction_response", "réaction", "reaction; backlash", "réponse à une action, souvent marquée par une opposition", ["agreement", "silence", "departure"], ["accord", "silence", "départ"]),
];
