import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a compass", "a turnip", "a balcony"];
const nounFrench: [string, string, string] = ["une boussole", "un navet", "un balcon"];
const adjectiveEnglish: [string, string, string] = ["plaid", "coconut-scented", "spherical"];
const adjectiveFrench: [string, string, string] = ["écossais", "parfumé à la noix de coco", "sphérique"];

export const zolaVocabularyBatch27: ZolaVocabularySpec[] = [
  { normalized: "imbécile", lemmaKey: "imbecile", headword: "imbécile", partOfSpeech: "adjective", senseKey: "imbecile_foolish", gloss: "stupid; foolish", definition: "qui manque fortement d’intelligence ou de jugement", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "immonde", lemmaKey: "immonde", headword: "immonde", partOfSpeech: "adjective", senseKey: "immonde_vile", gloss: "filthy; vile", definition: "qui provoque le dégoût par sa saleté ou sa bassesse morale", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "impérissable", lemmaKey: "imperissable", headword: "impérissable", partOfSpeech: "adjective", senseKey: "imperissable_enduring", gloss: "imperishable; enduring", definition: "qui ne peut disparaître et demeure dans le temps", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "impolitiques", lemmaKey: "impolitique", headword: "impolitique", partOfSpeech: "adjective", senseKey: "impolitique_unwise", gloss: "politically unwise; imprudent", definition: "contraire à une conduite politique prudente ou habile", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossais", "parfumés à la noix de coco", "sphériques"] },
  { normalized: "imposer", lemmaKey: "imposer", headword: "imposer", partOfSpeech: "verb", senseKey: "imposer_force", gloss: "to impose; force upon", definition: "faire accepter quelque chose par autorité ou contrainte", englishDistractors: ["to crochet", "to skate", "to yawn"], frenchDistractors: ["crocheter", "patiner", "bâiller"] },
  { normalized: "impossible", lemmaKey: "impossible", headword: "impossible", partOfSpeech: "adjective", senseKey: "impossible_not_possible", gloss: "impossible", definition: "qui ne peut être réalisé ou exister", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "impudent", lemmaKey: "impudent", headword: "impudent", partOfSpeech: "adjective", senseKey: "impudent_shameless", gloss: "shameless; brazen", definition: "qui agit avec une audace insolente et sans honte", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "impudente", lemmaKey: "impudent", headword: "impudent", partOfSpeech: "adjective", senseKey: "impudent_shameless", gloss: "shameless; brazen", definition: "qui agit avec une audace insolente et sans honte", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaise", "parfumée à la noix de coco", "sphérique"] },
  { normalized: "impunément", lemmaKey: "impunement", headword: "impunément", partOfSpeech: "adverb", senseKey: "impunement_without_punishment", gloss: "with impunity; unpunished", definition: "sans subir de punition pour ses actes", englishDistractors: ["quietly", "downstairs", "weekly"], frenchDistractors: ["silencieusement", "en bas", "chaque semaine"] },
  { normalized: "inattaquable", lemmaKey: "inattaquable", headword: "inattaquable", partOfSpeech: "adjective", senseKey: "inattaquable_beyond_challenge", gloss: "unassailable; beyond challenge", definition: "que l’on ne peut attaquer, contester ou remettre en cause", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "inattendue", lemmaKey: "inattendu", headword: "inattendu", partOfSpeech: "adjective", senseKey: "inattendu_unexpected", gloss: "unexpected", definition: "qui survient sans avoir été prévu", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaise", "parfumée à la noix de coco", "sphérique"] },
  { normalized: "incline", lemmaKey: "incliner", headword: "s’incliner", partOfSpeech: "verb", senseKey: "incliner_submit", gloss: "to bow; submit", quizMeaning: "bows; submits", definition: "céder devant une autorité ou accepter sans résister", englishDistractors: ["crochets", "skates", "yawns"], frenchDistractors: ["crochète", "patine", "bâille"] },
  { normalized: "incliner", lemmaKey: "incliner", headword: "s’incliner", partOfSpeech: "verb", senseKey: "incliner_submit", gloss: "to bow; submit", definition: "céder devant une autorité ou accepter sans résister", englishDistractors: ["to crochet", "to skate", "to yawn"], frenchDistractors: ["crocheter", "patiner", "bâiller"] },
  { normalized: "inconnaissable", lemmaKey: "inconnaissable", headword: "inconnaissable", partOfSpeech: "adjective", senseKey: "inconnaissable_unknowable", gloss: "unknowable", definition: "que l’esprit humain ne peut connaître ou comprendre", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "inconscient", lemmaKey: "inconscient", headword: "inconscient", partOfSpeech: "adjective", senseKey: "inconscient_unaware", gloss: "unaware; unwitting", definition: "qui agit sans avoir conscience de la portée de ses actes", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "incurie", lemmaKey: "incurie", headword: "incurie", partOfSpeech: "noun", senseKey: "incurie_negligence", gloss: "negligence; carelessness", definition: "manque de soin, d’attention ou de compétence dans une responsabilité", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "indicibles", lemmaKey: "indicible", headword: "indicible", partOfSpeech: "adjective", senseKey: "indicible_unspeakable", gloss: "unspeakable; indescribable", definition: "que l’on ne peut ou ne veut exprimer par des mots", englishDistractors: adjectiveEnglish, frenchDistractors: ["écossaises", "parfumées à la noix de coco", "sphériques"] },
  { normalized: "indignation", lemmaKey: "indignation", headword: "indignation", partOfSpeech: "noun", senseKey: "indignation_outrage", gloss: "indignation; outrage", definition: "colère provoquée par ce qui paraît injuste ou honteux", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "indignent", lemmaKey: "indigner", headword: "indigner", partOfSpeech: "verb", senseKey: "indigner_outrage", gloss: "to outrage; provoke indignation", quizMeaning: "outrage; provoke indignation", definition: "provoquer une vive colère devant une injustice", englishDistractors: ["crochet", "skate", "yawn"], frenchDistractors: ["crochètent", "patinent", "bâillent"] },
  { normalized: "ineffaçable", lemmaKey: "ineffacable", headword: "ineffaçable", partOfSpeech: "adjective", senseKey: "ineffacable_indelible", gloss: "indelible; unforgettable", definition: "qui ne peut être effacé ou faire disparaître sa trace", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "inévitablement", lemmaKey: "inevitablement", headword: "inévitablement", partOfSpeech: "adverb", senseKey: "inevitablement_inevitably", gloss: "inevitably", definition: "d’une manière que rien ne peut empêcher", englishDistractors: ["quietly", "downstairs", "weekly"], frenchDistractors: ["silencieusement", "en bas", "chaque semaine"] },
  { normalized: "infâme", lemmaKey: "infame", headword: "infâme", partOfSpeech: "adjective", senseKey: "infame_disgraceful", gloss: "infamous; disgraceful", definition: "qui déshonore par une extrême indignité morale", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "infamie", lemmaKey: "infamie", headword: "infamie", partOfSpeech: "noun", senseKey: "infamie_disgrace", gloss: "infamy; disgrace", definition: "déshonneur extrême attaché à une conduite honteuse", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "inférieurs", lemmaKey: "inferieur_noun", headword: "inférieur", partOfSpeech: "noun", senseKey: "inferieur_subordinate", gloss: "subordinate; inferior", quizMeaning: "subordinates", definition: "personne placée sous l’autorité d’une autre dans une hiérarchie", englishDistractors: ["compasses", "turnips", "balconies"], frenchDistractors: ["boussoles", "navets", "balcons"] },
  { normalized: "infirmer", lemmaKey: "infirmer", headword: "infirmer", partOfSpeech: "verb", senseKey: "infirmer_invalidate", gloss: "to invalidate; disprove", definition: "affaiblir, contredire ou priver de validité", englishDistractors: ["to crochet", "to skate", "to yawn"], frenchDistractors: ["crocheter", "patiner", "bâiller"] },
  { normalized: "influences", lemmaKey: "influence", headword: "influence", partOfSpeech: "noun", senseKey: "influence_pressure", gloss: "influence; pressure", quizMeaning: "influences; pressures", definition: "action exercée sur quelqu’un afin d’orienter ses décisions", englishDistractors: ["compasses", "turnips", "balconies"], frenchDistractors: ["boussoles", "navets", "balcons"] },
  { normalized: "inintelligence", lemmaKey: "inintelligence", headword: "inintelligence", partOfSpeech: "noun", senseKey: "inintelligence_lack", gloss: "lack of intelligence; obtuseness", definition: "absence d’intelligence ou incapacité à comprendre correctement", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "inintelligent", lemmaKey: "inintelligent", headword: "inintelligent", partOfSpeech: "adjective", senseKey: "inintelligent_foolish", gloss: "unintelligent; foolish", definition: "qui manque d’intelligence ou de discernement", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "inique", lemmaKey: "inique", headword: "inique", partOfSpeech: "adjective", senseKey: "inique_unjust", gloss: "iniquitous; unjust", definition: "profondément contraire à la justice et à l’équité", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "iniquité", lemmaKey: "iniquite", headword: "iniquité", partOfSpeech: "noun", senseKey: "iniquite_injustice", gloss: "iniquity; injustice", definition: "injustice grave ou acte profondément contraire à l’équité", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "iniquités", lemmaKey: "iniquite", headword: "iniquité", partOfSpeech: "noun", senseKey: "iniquite_injustice", gloss: "iniquity; injustice", quizMeaning: "iniquities; injustices", definition: "injustice grave ou acte profondément contraire à l’équité", englishDistractors: ["compasses", "turnips", "balconies"], frenchDistractors: ["boussoles", "navets", "balcons"] },
];
