import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a teapot","a glacier","a necklace"];
const nF:[string,string,string]=["théière","glacier","collier"];
const aE:[string,string,string]=["woolen","transparent","spicy"];
const aF:[string,string,string]=["laineux","transparent","épicé"];
const vE:[string,string,string]=["to paddle","to sew","to yawn"];
const vF:[string,string,string]=["pagayer","coudre","bâiller"];

export const zolaVocabularyBatch14: ZolaVocabularySpec[] = [
 {normalized:"coup",candidateIds:["tok_7062b74b1f5dbd77c63ae5f0"],lemmaKey:"coup",headword:"coup",partOfSpeech:"noun",senseKey:"coup_sudden_event",gloss:"sudden event",quizMeaning:"suddenly",definition:"événement qui survient brusquement",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"coup",candidateIds:["tok_976ea754492520c8f5bef073"],lemmaKey:"coup",headword:"coup",partOfSpeech:"noun",senseKey:"coup_stroke",gloss:"stroke; blow",definition:"mouvement brusque qui frappe ou agit fortement",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"coup",candidateIds:["tok_10a2a07acf22346c5997debe"],lemmaKey:"coup",headword:"coup",partOfSpeech:"noun",senseKey:"coup_effect",gloss:"effect; force",quizMeaning:"subject to; under the force of",definition:"effet ou autorité auxquels quelqu’un est soumis",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"coupable",candidateIds:["tok_18e77efadd85dcfe664e9c1e","tok_96ed7fc43c052afb114f3c5d","tok_ee3db48703c5135d21088250","tok_85cfd47f071de6de64738bfa","tok_de933e55659349421b2a2f6d","tok_0428ccac923a5e41a5d8ade4"],lemmaKey:"coupable_adj",headword:"coupable",partOfSpeech:"adjective",senseKey:"coupable_adj_guilty",gloss:"guilty",definition:"qui a commis une faute ou un crime",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"coupable",candidateIds:["tok_3dbbf4070e832a42c6c0b039","tok_5ce4015f7fb266ef726ce2df","tok_a34c6d8be3b7fec486e00050"],lemmaKey:"coupable_noun",headword:"coupable",partOfSpeech:"noun",senseKey:"coupable_noun_offender",gloss:"guilty person; offender",definition:"personne qui a commis une faute ou un crime",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"coupables",candidateIds:["tok_c78743f81d33e00e32c412f4"],lemmaKey:"coupable_adj",headword:"coupable",partOfSpeech:"adjective",senseKey:"coupable_adj_guilty",gloss:"guilty",definition:"qui a commis une faute ou un crime",englishDistractors:aE,frenchDistractors:["laineuses","transparentes","épicées"]},
 {normalized:"coupables",candidateIds:["tok_723a6a57ede536fd2ad55d6b","tok_a105c94f3faaaa9d7f538fc2"],lemmaKey:"coupable_noun",headword:"coupable",partOfSpeech:"noun",senseKey:"coupable_noun_offender",gloss:"guilty person; offender",quizMeaning:"guilty people; offenders",definition:"personne qui a commis une faute ou un crime",englishDistractors:["teapots","glaciers","necklaces"],frenchDistractors:["théières","glaciers","colliers"]},
 {normalized:"dates",lemmaKey:"date",headword:"date",partOfSpeech:"noun",senseKey:"date_time_point",gloss:"date",quizMeaning:"dates",definition:"indication précise d’un moment dans le temps",englishDistractors:["teapots","glaciers","necklaces"],frenchDistractors:["théières","glaciers","colliers"]},
 {normalized:"début",lemmaKey:"debut",headword:"début",partOfSpeech:"noun",senseKey:"debut_beginning",gloss:"beginning",definition:"premier moment d’une action ou d’une période",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"décide",lemmaKey:"decider",headword:"décider",partOfSpeech:"verb",senseKey:"decider_determine",gloss:"to decide; determine",quizMeaning:"is decided; is determined",definition:"fixer un choix ou déterminer un résultat",englishDistractors:["paddles","sews","yawns"],frenchDistractors:["pagaie","coud","bâille"]},
 {normalized:"décidément",lemmaKey:"decidement",headword:"décidément",partOfSpeech:"adverb",senseKey:"decidement_decidedly",gloss:"decidedly; definitely",definition:"d’une manière nette qui confirme un jugement",englishDistractors:["quietly","upstairs","clockwise"],frenchDistractors:["calmement","à l’étage","dans le sens horaire"]},
 {normalized:"déclarant",lemmaKey:"declarer",headword:"déclarer",partOfSpeech:"verb",senseKey:"declarer_state",gloss:"to declare; state",quizMeaning:"declaring",definition:"faire connaître quelque chose de façon explicite ou officielle",englishDistractors:["paddling","sewing","yawning"],frenchDistractors:["pagayant","cousant","bâillant"]},
 {normalized:"déclaration",lemmaKey:"declaration",headword:"déclaration",partOfSpeech:"noun",senseKey:"declaration_statement",gloss:"statement; declaration",definition:"paroles par lesquelles on affirme officiellement quelque chose",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"déclare",lemmaKey:"declarer",headword:"déclarer",partOfSpeech:"verb",senseKey:"declarer_state",gloss:"to declare; state",quizMeaning:"declares",definition:"faire connaître quelque chose de façon explicite ou officielle",englishDistractors:["paddles","sews","yawns"],frenchDistractors:["pagaie","coud","bâille"]},
 {normalized:"déclarée",lemmaKey:"declarer",headword:"déclarer",partOfSpeech:"verb",senseKey:"declarer_state",gloss:"to declare; state",quizMeaning:"declared",definition:"faire connaître quelque chose de façon explicite ou officielle",englishDistractors:["paddled","sewn","yawned"],frenchDistractors:["pagayée","cousue","bâillée"]},
 {normalized:"déclarer",lemmaKey:"declarer",headword:"déclarer",partOfSpeech:"verb",senseKey:"declarer_state",gloss:"to declare; state",definition:"faire connaître quelque chose de façon explicite ou officielle",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"décomposition",lemmaKey:"decomposition",headword:"décomposition",partOfSpeech:"noun",senseKey:"decomposition_decay",gloss:"decay; decomposition",definition:"désagrégation progressive d’un ensemble",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"découvert",lemmaKey:"decouvert",headword:"découvert",partOfSpeech:"adjective",senseKey:"decouvert_uncovered",gloss:"uncovered; exposed",definition:"qui n’est pas caché ou protégé",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"défaite",lemmaKey:"defaite",headword:"défaite",partOfSpeech:"noun",senseKey:"defaite_defeat",gloss:"defeat",definition:"échec subi dans une lutte ou un conflit",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"défend",lemmaKey:"defendre",headword:"défendre",partOfSpeech:"verb",senseKey:"defendre_protect",gloss:"to defend; protect",quizMeaning:"defends",definition:"protéger quelqu’un ou quelque chose contre une attaque ou une accusation",englishDistractors:["paddles","sews","yawns"],frenchDistractors:["pagaie","coud","bâille"]},
 {normalized:"défendrait",lemmaKey:"defendre",headword:"défendre",partOfSpeech:"verb",senseKey:"defendre_protect",gloss:"to defend; protect",quizMeaning:"would defend",definition:"protéger quelqu’un ou quelque chose contre une attaque ou une accusation",englishDistractors:["would paddle","would sew","would yawn"],frenchDistractors:["pagayerait","coudrait","bâillerait"]},
 {normalized:"défendre",lemmaKey:"defendre",headword:"défendre",partOfSpeech:"verb",senseKey:"defendre_protect",gloss:"to defend; protect",definition:"protéger quelqu’un ou quelque chose contre une attaque ou une accusation",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"défendu",lemmaKey:"defendre",headword:"défendre",partOfSpeech:"verb",senseKey:"defendre_protect",gloss:"to defend; protect",quizMeaning:"defended",definition:"protéger quelqu’un ou quelque chose contre une attaque ou une accusation",englishDistractors:["paddled","sewn","yawned"],frenchDistractors:["pagayé","cousu","bâillé"]},
 {normalized:"défense",lemmaKey:"defense",headword:"défense",partOfSpeech:"noun",senseKey:"defense_protection",gloss:"defense",definition:"action ou moyens employés pour protéger une personne ou un pays",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"déferait",lemmaKey:"defaire",headword:"défaire",partOfSpeech:"verb",senseKey:"defaire_undo",gloss:"to undo; reverse",quizMeaning:"would undo; would reverse",definition:"annuler ou détruire ce qui a été fait",englishDistractors:["would paddle","would sew","would yawn"],frenchDistractors:["pagayerait","coudrait","bâillerait"]},
 {normalized:"défie",lemmaKey:"defier",headword:"défier",partOfSpeech:"verb",senseKey:"defier_challenge",gloss:"to challenge; defy",quizMeaning:"challenge; defy",definition:"mettre quelqu’un au défi de faire ou de prouver quelque chose",englishDistractors:["paddle","sew","yawn"],frenchDistractors:["pagaie","couds","bâille"]},
];
