import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a windmill", "a turnip", "a cushion"];
const nounFrench: [string, string, string] = ["moulin", "navet", "coussin"];
const adjectiveEnglish: [string, string, string] = ["checkered", "rose-scented", "pyramidal"];
const adjectiveFrench: [string, string, string] = ["à carreaux", "parfumé à la rose", "pyramidal"];

export const zolaVocabularyBatch31: ZolaVocabularySpec[] = [
  { normalized: "m’", lemmaKey: "me_pronoun", headword: "me", partOfSpeech: "pronoun", senseKey: "me_first_person", gloss: "me; myself", definition: "pronom personnel complément représentant la personne qui parle", englishDistractors: ["it", "them", "some of it"], frenchDistractors: ["l’", "les", "en"] },
  { normalized: "machinations", lemmaKey: "machination", headword: "machination", partOfSpeech: "noun", senseKey: "machination_plot", gloss: "scheme; machination", quizMeaning: "schemes; machinations", definition: "manœuvre secrète et compliquée préparée pour nuire", englishDistractors: ["windmills", "turnips", "cushions"], frenchDistractors: ["moulins", "navets", "coussins"] },
  { normalized: "machiné", lemmaKey: "machiner", headword: "machiner", partOfSpeech: "verb", senseKey: "machiner_plot", gloss: "to plot; engineer", quizMeaning: "plotted; engineered", definition: "préparer secrètement une action complexe et nuisible", englishDistractors: ["knitted", "paddled", "yawned"], frenchDistractors: ["tricoté", "pagayé", "bâillé"] },
  { normalized: "madame", lemmaKey: "madame", headword: "madame", partOfSpeech: "noun", senseKey: "madame_title", gloss: "Madam; Mrs.", definition: "titre de civilité employé pour s’adresser à une femme ou parler d’elle", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "magistrat", lemmaKey: "magistrat", headword: "magistrat", partOfSpeech: "noun", senseKey: "magistrat_official", gloss: "magistrate; high official", definition: "personne investie d’une autorité judiciaire ou d’une haute fonction publique", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "mai", lemmaKey: "mai", headword: "mai", partOfSpeech: "noun", senseKey: "mai_month", gloss: "May", definition: "cinquième mois de l’année", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "main", candidateIds: ["tok_e27b3f0ef380783832ea1c5b"], lemmaKey: "main", headword: "main", partOfSpeech: "noun", senseKey: "main_control", gloss: "control; charge", definition: "pouvoir de diriger ou de prendre personnellement en charge", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "main", candidateIds: ["tok_636688889b92f839682f9b7b"], lemmaKey: "main", headword: "main", partOfSpeech: "noun", senseKey: "main_authorship", gloss: "hand; authorship", definition: "manière d’écrire ou trace révélant l’auteur d’un acte", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "mains", lemmaKey: "main", headword: "main", partOfSpeech: "noun", senseKey: "main_possession", gloss: "hand; possession", quizMeaning: "hands; possession", definition: "organe qui saisit, employé aussi pour exprimer la possession ou le pouvoir", englishDistractors: ["windmills", "turnips", "cushions"], frenchDistractors: ["moulins", "navets", "coussins"] },
  { normalized: "mais", lemmaKey: "mais", headword: "mais", partOfSpeech: "conjunction", senseKey: "mais_but", gloss: "but; however", definition: "introduit une opposition, une restriction ou un contraste", englishDistractors: ["tomorrow", "outdoors", "silently"], frenchDistractors: ["demain", "dehors", "silencieusement"] },
  { normalized: "maison", lemmaKey: "maison", headword: "maison", partOfSpeech: "noun", senseKey: "maison_household", gloss: "house; establishment", definition: "bâtiment d’habitation ou organisation considérée comme un même foyer", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "malade", lemmaKey: "malade", headword: "malade", partOfSpeech: "adjective", senseKey: "malade_sick", gloss: "sick; diseased", definition: "atteint d’une maladie ou profondément affecté par un mal", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "maladie", lemmaKey: "maladie", headword: "maladie", partOfSpeech: "noun", senseKey: "maladie_illness", gloss: "illness; disease", definition: "altération de la santé du corps ou de l’esprit", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "malfaisance", lemmaKey: "malfaisance", headword: "malfaisance", partOfSpeech: "noun", senseKey: "malfaisance_harm", gloss: "harmfulness; malevolence", definition: "disposition ou action qui produit volontairement du mal", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "malfaisante", lemmaKey: "malfaisant", headword: "malfaisant", partOfSpeech: "adjective", senseKey: "malfaisant_harmful", gloss: "harmful; malevolent", definition: "qui fait du mal ou exerce une influence nuisible", englishDistractors: adjectiveEnglish, frenchDistractors: ["à carreaux", "parfumée à la rose", "pyramidale"] },
  { normalized: "malheureux", lemmaKey: "malheureux", headword: "malheureux", partOfSpeech: "adjective", senseKey: "malheureux_unfortunate", gloss: "unfortunate; wretched", definition: "qui subit le malheur, inspire la pitié ou se trouve dans une situation pénible", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "manifeste", lemmaKey: "manifeste", headword: "manifeste", partOfSpeech: "adjective", senseKey: "manifeste_obvious", gloss: "obvious; evident", definition: "qui apparaît clairement et ne peut raisonnablement être nié", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "marchait", lemmaKey: "marcher", headword: "marcher", partOfSpeech: "verb", senseKey: "marcher_advance", gloss: "to walk; advance", quizMeaning: "was advancing; moved forward", definition: "avancer progressivement, au propre ou au figuré", englishDistractors: ["was knitting", "was paddling", "was yawning"], frenchDistractors: ["tricotait", "pagayait", "bâillait"] },
  { normalized: "marche", lemmaKey: "marche_noun", headword: "marche", partOfSpeech: "noun", senseKey: "marche_progress", gloss: "movement; progress", definition: "action d’avancer ou progression vers un résultat", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "mari", lemmaKey: "mari", headword: "mari", partOfSpeech: "noun", senseKey: "mari_husband", gloss: "husband", definition: "homme uni à une autre personne par le mariage", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "marquis", lemmaKey: "marquis", headword: "marquis", partOfSpeech: "noun", senseKey: "marquis_title", gloss: "marquis", definition: "titre de noblesse situé entre ceux de duc et de comte", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "masqué", lemmaKey: "masquer", headword: "masquer", partOfSpeech: "verb", senseKey: "masquer_conceal", gloss: "to mask; conceal", quizMeaning: "masked; concealed", definition: "couvrir le visage ou dissimuler l’identité et les intentions", englishDistractors: ["knitted", "paddled", "yawned"], frenchDistractors: ["tricoté", "pagayé", "bâillé"] },
  { normalized: "massacrer", lemmaKey: "massacrer", headword: "massacrer", partOfSpeech: "verb", senseKey: "massacrer_kill", gloss: "to massacre; slaughter", definition: "tuer brutalement une personne ou un grand nombre de personnes", englishDistractors: ["to knit", "to paddle", "to yawn"], frenchDistractors: ["tricoter", "pagayer", "bâiller"] },
  { normalized: "méconnues", lemmaKey: "meconnaitre", headword: "méconnaître", partOfSpeech: "verb", senseKey: "meconnaitre_disregard", gloss: "to disregard; fail to recognize", quizMeaning: "disregarded; unrecognized", definition: "ne pas reconnaître la valeur, les droits ou la réalité de quelque chose", englishDistractors: ["knitted", "paddled", "yawned"], frenchDistractors: ["tricotées", "pagayées", "bâillées"] },
  { normalized: "médical", lemmaKey: "medical", headword: "médical", partOfSpeech: "adjective", senseKey: "medical_medicine", gloss: "medical", definition: "qui concerne la médecine, la santé ou l’examen par un médecin", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "médiocre", lemmaKey: "mediocre", headword: "médiocre", partOfSpeech: "adjective", senseKey: "mediocre_poor", gloss: "mediocre; poor", definition: "qui se situe au-dessous d’un niveau satisfaisant", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
];
