import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch14: Record<string, EditorialQuizSet> = {
  "coup:coup_sudden_event": {
    early: "La démission inattendue du maire a été un coup de théâtre pour tout le village.", englishChoices: ["sudden turn", "daily routine", "careful plan", "old tradition"],
    intermediate: "Son retour imprévu au milieu du procès constitue un _____ de théâtre.", frenchChoices: ["coup", "projet", "récit", "souvenir"],
    advanced: "Un coup de théâtre bouleverse la réunion : le candidat annoncé vainqueur se retire soudain. Léa consulte le programme, Marc ferme la salle et Nina cherche le secrétaire.",
    prompt: "Quel mot, dans l’expression « ... de théâtre », évoque ce retournement soudain ?", advancedChoices: ["coup", "réunion", "programme", "secrétaire"],
  },
  "coup:coup_stroke": {
    early: "Un coup de marteau fend la planche en deux.", englishChoices: ["blow", "whisper", "rest", "gift"],
    intermediate: "D’un seul _____ de marteau, Paul enfonce le clou dans le bois.", frenchChoices: ["coup", "repos", "cadeau", "souhait"],
    advanced: "Le coup de bâton frappe la porte et laisse une marque dans le bois. Nina regarde la poignée, Luc ramasse les outils et Paul apporte une lampe.",
    prompt: "Quel mot désigne le choc soudain du bâton contre la porte ?", advancedChoices: ["coup", "marque", "poignée", "outils"],
  },
  "coup:coup_effect": {
    early: "Sous le coup de la colère, Luc quitte brusquement la salle.", englishChoices: ["force or sway", "physical blow", "compliment", "delay"],
    intermediate: "Encore sous le _____ de l’émotion, elle peine à trouver ses mots.", frenchChoices: ["coup", "repos", "plaisir", "choix"],
    advanced: "Sous le coup de la surprise, Nina reste sans voix après l’annonce. Paul relit la lettre, Léa ouvre la porte et Marc se sert un verre d’eau.",
    prompt: "Quel mot forme avec « sous le » une expression indiquant l’emprise de la surprise ?", advancedChoices: ["coup", "annonce", "lettre", "verre"],
  },
  "coupable:coupable_adj_guilty": {
    early: "Le tribunal déclare Paul coupable du vol après avoir examiné les preuves.", englishChoices: ["guilty", "innocent", "absent", "unaware"],
    intermediate: "Les preuves établissent que Marc a volé la caisse : il est _____ de ce vol.", frenchChoices: ["coupable", "innocent", "étranger", "ignorant"],
    advanced: "La juge déclare Luc coupable après avoir établi qu’il a falsifié le contrat. Son avocat prépare un recours, la secrétaire note le verdict et le témoin quitte la salle.",
    prompt: "Quel mot qualifie Luc comme auteur de la faute jugée ?", advancedChoices: ["coupable", "avocat", "secrétaire", "témoin"],
  },
  "coupable:coupable_noun_offender": {
    early: "La police cherche le coupable qui a pris l’argent dans le tiroir.", englishChoices: ["offender", "victim", "witness", "judge"],
    intermediate: "La caméra montre la personne qui a volé la caisse : le _____ est identifié.", frenchChoices: ["coupable", "témoin", "juge", "gardien"],
    advanced: "Le coupable avoue avoir emporté l’argent du magasin. Un témoin décrit la scène, le juge écoute sa déposition et le gardien retrouve la caisse.",
    prompt: "Quel nom désigne la personne qui a commis le vol ?", advancedChoices: ["coupable", "témoin", "juge", "gardien"],
  },
  "coupables:coupable_adj_guilty": {
    early: "Les deux employés sont coupables de fraude : ils ont signé les faux reçus.", englishChoices: ["guilty", "innocent", "absent", "unaware"],
    intermediate: "Après avoir participé au vol, les deux suspects sont _____ du même délit.", frenchChoices: ["coupables", "innocents", "étrangers", "ignorants"],
    advanced: "Les deux hommes sont coupables d’avoir falsifié les billets, selon les preuves retenues. Leurs avocats lisent les documents, la juge convoque les témoins et la greffière note les réponses.",
    prompt: "Quel mot qualifie les hommes reconnus responsables de la fraude ?", advancedChoices: ["coupables", "avocats", "témoins", "réponses"],
  },
  "coupables:coupable_noun_offender": {
    early: "La police a retrouvé les coupables qui avaient volé les vélos.", englishChoices: ["offenders", "victims", "witnesses", "judges"],
    intermediate: "Les deux personnes qui ont organisé le vol sont les _____ recherchés.", frenchChoices: ["coupables", "victimes", "témoins", "juges"],
    advanced: "Les coupables ont reconnu avoir volé les tableaux du musée. Les gardiens inspectent les salles, les visiteurs attendent dehors et la directrice contacte la police.",
    prompt: "Quel nom désigne les personnes qui ont commis le vol ?", advancedChoices: ["coupables", "gardiens", "visiteurs", "directrice"],
  },
  "dates:date_time_point": {
    early: "Les dates des deux examens sont le 12 et le 19 juin.", englishChoices: ["dates", "places", "prices", "names"],
    intermediate: "Note les _____ des réunions dans ton agenda : mardi et vendredi.", frenchChoices: ["dates", "adresses", "tarifs", "noms"],
    advanced: "Les dates des concerts figurent sur l’affiche : le 3 et le 10 mai. Les prix sont indiqués plus bas, Nina réserve les billets et Paul lit les noms des artistes.",
    prompt: "Quel mot désigne les indications précises de jours pour les concerts ?", advancedChoices: ["dates", "prix", "billets", "noms"],
  },
  "début:debut_beginning": {
    early: "Au début du film, les personnages arrivent dans un village inconnu.", englishChoices: ["beginning", "ending", "pause", "middle"],
    intermediate: "La première scène marque le _____ de la pièce de théâtre.", frenchChoices: ["début", "milieu", "terme", "finale"],
    advanced: "Le début du cours est fixé à neuf heures ; les élèves entrent alors dans la salle. À la fin, Nina ferme les fenêtres et Paul ramasse les cahiers.",
    prompt: "Quel mot désigne le premier moment du cours ?", advancedChoices: ["début", "fin", "fenêtres", "cahiers"],
  },
  "décide:decider_determine": {
    early: "Le conseil décide de fermer le parc après avoir voté.", englishChoices: ["decides", "forgets", "copies", "postpones"],
    intermediate: "Après le vote, la majorité _____ que la réunion aura lieu lundi.", frenchChoices: ["décide", "oublie", "copie", "ignore"],
    advanced: "La directrice décide de prolonger l’ouverture du musée après avoir lu les demandes du public. Nina imprime les horaires, Paul vérifie les portes et Luc accueille les visiteurs.",
    prompt: "Quel mot indique que la directrice fixe le nouveau choix ?", advancedChoices: ["décide", "imprime", "vérifie", "accueille"],
  },
  "décidément:decidement_decidedly": {
    early: "Décidément, ce sentier est trop glissant : trois marcheurs viennent de tomber.", englishChoices: ["definitely", "rarely", "quietly", "elsewhere"],
    intermediate: "_____, après trois annulations successives, ce spectacle porte malheur !", frenchChoices: ["Décidément", "Rarement", "Ailleurs", "Silencieusement"],
    advanced: "Décidément, la route est impraticable : deux véhicules viennent encore de s’y enliser. Nina consulte une carte, Paul appelle un dépanneur et Marc attend près du pont.",
    prompt: "Quel mot renforce le jugement confirmé par ces nouveaux incidents ?", advancedChoices: ["Décidément", "encore", "carte", "pont"],
  },
  "déclarant:declarer_state": {
    early: "En déclarant officiellement la réunion ouverte, le maire invite les participants à entrer.", englishChoices: ["declaring", "concealing", "denying", "forgetting"],
    intermediate: "En _____ publiquement son intention de démissionner, Léa dissipe les rumeurs.", frenchChoices: ["déclarant", "cachant", "niant", "oubliant"],
    advanced: "En déclarant devant tous que le pont rouvrira lundi, la maire annonce une décision officielle. Paul affiche l’horaire, Nina ferme la barrière et Luc note la date.",
    prompt: "Quel mot indique que la maire fait connaître explicitement sa décision ?", advancedChoices: ["déclarant", "affiche", "ferme", "note"],
  },
  "déclaration:declaration_statement": {
    early: "La déclaration du maire annonce officiellement l’ouverture du nouveau parc.", englishChoices: ["statement", "silence", "question", "rumor"],
    intermediate: "Devant les journalistes, sa _____ officielle confirme la date du départ.", frenchChoices: ["déclaration", "question", "rumeur", "hésitation"],
    advanced: "La déclaration du directeur confirme publiquement que l’école restera ouverte. Nina écrit un article, Paul consulte le calendrier et Luc prépare les chaises.",
    prompt: "Quel mot désigne l’annonce publique faite par le directeur ?", advancedChoices: ["déclaration", "article", "calendrier", "chaises"],
  },
  "déclare:declarer_state": {
    early: "Devant les journalistes, la ministre déclare que le musée ouvrira lundi.", englishChoices: ["declares", "hides", "denies", "forgets"],
    intermediate: "Dans son discours, le maire _____ officiellement que la route est ouverte.", frenchChoices: ["déclare", "dissimule", "ignore", "oublie"],
    advanced: "La présidente déclare publiquement que le projet est accepté. Paul rédige le compte rendu, Nina prépare une affiche et Léa ouvre la salle.",
    prompt: "Quel mot indique que la présidente annonce explicitement sa décision ?", advancedChoices: ["déclare", "rédige", "prépare", "ouvre"],
  },
  "déclarée:declarer_state": {
    early: "La réunion est déclarée ouverte après l’annonce officielle de la présidente.", englishChoices: ["declared", "hidden", "denied", "forgotten"],
    intermediate: "Après l’annonce officielle du jury, la gagnante est _____ vainqueure.", frenchChoices: ["déclarée", "cachée", "ignorée", "oubliée"],
    advanced: "La séance est déclarée ouverte lorsque la présidente le dit officiellement. Nina note l’heure, Paul distribue le programme et Luc ferme la porte.",
    prompt: "Quel mot indique que l’ouverture de la séance a été annoncée officiellement ?", advancedChoices: ["déclarée", "présidente", "programme", "porte"],
  },
  "déclarer:declarer_state": {
    early: "Le témoin vient déclarer devant le juge ce qu’il a vu.", englishChoices: ["to state", "to conceal", "to deny", "to forget"],
    intermediate: "Le directeur va _____ publiquement la date d’ouverture du musée.", frenchChoices: ["déclarer", "dissimuler", "oublier", "nier"],
    advanced: "Léa doit déclarer devant le conseil que les travaux sont terminés. Nina apporte les factures, Marc dessine un plan et Paul ferme le dossier.",
    prompt: "Quel verbe signifie faire connaître explicitement le résultat devant le conseil ?", advancedChoices: ["déclarer", "apporte", "dessine", "ferme"],
  },
  "décomposition:decomposition_decay": {
    early: "La décomposition des feuilles mortes transforme peu à peu leur matière dans le sol.", englishChoices: ["decomposition", "construction", "collection", "preservation"],
    intermediate: "L’odeur du fruit pourri révèle sa lente _____ au fond du panier.", frenchChoices: ["décomposition", "conservation", "fabrication", "récolte"],
    advanced: "La décomposition du bois humide a fragilisé la vieille poutre au fil des ans. Nina vérifie le toit, Paul mesure une planche et Marc ouvre la fenêtre.",
    prompt: "Quel mot désigne la désagrégation progressive du bois ?", advancedChoices: ["décomposition", "poutre", "planche", "fenêtre"],
  },
  "découvert:decouvert_uncovered": {
    early: "Le puits découvert reste exposé à la pluie depuis qu’on a retiré son couvercle.", englishChoices: ["uncovered", "sealed", "hidden", "protected"],
    intermediate: "On a retiré le toit de l’abri ; il est maintenant _____ et exposé aux intempéries.", frenchChoices: ["découvert", "couvert", "fermé", "protégé"],
    advanced: "Le bassin découvert n’a plus de toit et reçoit directement la pluie. Un hangar couvert se trouve à côté, Nina ferme la porte et Paul porte une échelle.",
    prompt: "Quel mot indique que le bassin n’est plus protégé par un toit ?", advancedChoices: ["découvert", "couvert", "porte", "échelle"],
  },
  "défaite:defaite_defeat": {
    early: "Après une défaite de trois buts à zéro, l’équipe quitte le stade en silence.", englishChoices: ["defeat", "victory", "draw", "celebration"],
    intermediate: "L’équipe a perdu le match : elle doit accepter sa _____.", frenchChoices: ["défaite", "victoire", "fête", "récompense"],
    advanced: "La défaite de Paul au tournoi met fin à son parcours cette année. Nina remporte la finale, Luc range les raquettes et Marie photographie les joueurs.",
    prompt: "Quel mot désigne l’échec subi par Paul dans la compétition ?", advancedChoices: ["défaite", "finale", "raquettes", "joueurs"],
  },
  "défend:defendre_protect": {
    early: "L’avocate défend son client contre une accusation de vol.", englishChoices: ["defends", "accuses", "abandons", "punishes"],
    intermediate: "L’avocate _____ le prévenu en contestant les preuves présentées contre lui.", frenchChoices: ["défend", "accuse", "abandonne", "punit"],
    advanced: "Nina défend Luc devant le tribunal et présente des faits en sa faveur. Le juge écoute le témoin, Paul consulte le dossier et Léa prend des notes.",
    prompt: "Quel mot indique que Nina protège Luc contre une accusation ?", advancedChoices: ["défend", "écoute", "consulte", "prend"],
  },
  "défendrait:defendre_protect": {
    early: "Si elle disposait des preuves, l’avocate défendrait son client au tribunal.", englishChoices: ["would defend", "would accuse", "would abandon", "would punish"],
    intermediate: "Avec ce témoin, Nina _____ son ami face à cette accusation injuste.", frenchChoices: ["défendrait", "accuserait", "abandonnerait", "punirait"],
    advanced: "Si le procès s’ouvrait demain, Paul défendrait sa sœur en apportant les documents qui l’innocentent. Nina classerait les lettres, Luc fermerait le bureau et Marc attendrait dehors.",
    prompt: "Quel mot indique que Paul protégerait sa sœur de l’accusation ?", advancedChoices: ["défendrait", "classerait", "fermerait", "attendrait"],
  },
  "défendre:defendre_protect": {
    early: "Léa promet de défendre son amie contre une accusation sans preuve.", englishChoices: ["to defend", "to accuse", "to abandon", "to punish"],
    intermediate: "Avec les témoins présents, Paul pourra _____ son frère devant le juge.", frenchChoices: ["défendre", "accuser", "abandonner", "punir"],
    advanced: "L’avocat veut défendre Marc en présentant un alibi vérifié. Nina prépare les documents, Paul ouvre la porte et Luc consulte le calendrier.",
    prompt: "Quel verbe indique que l’avocat cherche à protéger Marc contre l’accusation ?", advancedChoices: ["défendre", "prépare", "ouvre", "consulte"],
  },
  "défendu:defendre_protect": {
    early: "Au procès, Paul a défendu sa sœur en montrant qu’elle était absente ce jour-là.", englishChoices: ["defended", "accused", "abandoned", "punished"],
    intermediate: "Face à l’accusation, Léa a _____ son ami grâce à un témoin fiable.", frenchChoices: ["défendu", "accusé", "abandonné", "puni"],
    advanced: "L’avocate a défendu Nina en produisant une vidéo qui prouve son innocence. Le juge a lu le dossier, Paul a interrogé le témoin et Marc a fermé la salle.",
    prompt: "Quel mot indique que l’avocate a protégé Nina contre l’accusation ?", advancedChoices: ["défendu", "lu", "interrogé", "fermé"],
  },
  "défense:defense_protection": {
    early: "La défense de l’accusé repose sur une vidéo prouvant son absence.", englishChoices: ["defense", "accusation", "sentence", "confession"],
    intermediate: "L’avocate prépare la _____ de son client en rassemblant les preuves de son innocence.", frenchChoices: ["défense", "condamnation", "accusation", "confession"],
    advanced: "La défense de Luc présente un alibi qui le disculpe. Le juge examine les dates, Nina classe les lettres et Paul apporte une photographie.",
    prompt: "Quel mot désigne l’ensemble des moyens employés pour protéger Luc contre l’accusation ?", advancedChoices: ["défense", "juge", "lettres", "photographie"],
  },
  "déferait:defaire_undo": {
    early: "Si l’on tirait sur ce fil, cela déferait toute la couture.", englishChoices: ["would undo", "would strengthen", "would preserve", "would complete"],
    intermediate: "Un tel vote _____ l’accord négocié hier et nous obligerait à recommencer.", frenchChoices: ["déferait", "renforcerait", "maintiendrait", "confirmerait"],
    advanced: "Si Marc retirait ce fil, il déferait les points cousus par Nina. Paul rangerait les aiguilles, Léa fermerait la boîte et Luc apporterait une lampe.",
    prompt: "Quel mot indique que Marc annulerait le travail de couture déjà fait ?", advancedChoices: ["déferait", "rangerait", "fermerait", "apporterait"],
  },
  "défie:defier_challenge": {
    early: "Nina défie Paul de résoudre l’énigme avant midi.", englishChoices: ["challenges", "excuses", "forgets", "thanks"],
    intermediate: "Léa _____ son frère de finir la course avant elle.", frenchChoices: ["défie", "remercie", "excuse", "félicite"],
    advanced: "Marc défie Luc de battre son temps sur le parcours. Nina mesure la distance, Léa prépare la montre et Paul note les résultats.",
    prompt: "Quel mot indique que Marc met Luc au défi de faire mieux ?", advancedChoices: ["défie", "mesure", "prépare", "note"],
  },
};
