import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nE:[string,string,string]=["a basket","a comet","a walnut"];
const nF:[string,string,string]=["panier","comète","noix"];
const aE:[string,string,string]=["wooden","peppermint-flavored","octagonal"];
const aF:[string,string,string]=["boisé","mentholé","octogonal"];
const vE:[string,string,string]=["to quilt","to sail","to wink"];
const vF:[string,string,string]=["matelasser","naviguer","cligner"];

export const zolaVocabularyBatch20: ZolaVocabularySpec[] = [
 {normalized:"empereur",lemmaKey:"empereur",headword:"empereur",partOfSpeech:"noun",senseKey:"empereur_ruler",gloss:"emperor",definition:"souverain qui gouverne un empire",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"empoisonner",lemmaKey:"empoisonner",headword:"empoisonner",partOfSpeech:"verb",senseKey:"empoisonner_poison",gloss:"to poison",definition:"rendre nocif par un poison ou corrompre profondément",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"entretenait",lemmaKey:"entretenir",headword:"entretenir",partOfSpeech:"verb",senseKey:"entretenir_maintain",gloss:"to maintain; carry on",quizMeaning:"maintained; carried on",definition:"faire durer une relation, une activité ou un échange",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassait","naviguait","clignait"]},
 {normalized:"envoyé",lemmaKey:"envoyer",headword:"envoyer",partOfSpeech:"verb",senseKey:"envoyer_send",gloss:"to send",quizMeaning:"sent",definition:"faire partir quelqu’un ou quelque chose vers une destination",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassé","navigué","cligné"]},
 {normalized:"époque",lemmaKey:"epoque",headword:"époque",partOfSpeech:"noun",senseKey:"epoque_period",gloss:"era; period",definition:"période déterminée de l’histoire ou de la vie",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"épouvantable",lemmaKey:"epouvantable",headword:"épouvantable",partOfSpeech:"adjective",senseKey:"epouvantable_horrifying",gloss:"horrifying; dreadful",definition:"qui inspire une peur ou une indignation extrême",englishDistractors:aE,frenchDistractors:aF},
 {normalized:"épouvante",lemmaKey:"s_epouvanter",headword:"s’épouvanter",partOfSpeech:"verb",senseKey:"s_epouvanter_be_horrified",gloss:"to be horrified",quizMeaning:"is horrified",definition:"être saisi d’une peur ou d’une indignation extrême",englishDistractors:["quilts","sails","winks"],frenchDistractors:["matelasse","navigue","cligne"]},
 {normalized:"éprouver",lemmaKey:"eprouver",headword:"éprouver",partOfSpeech:"verb",senseKey:"eprouver_feel",gloss:"to feel; experience",definition:"ressentir un sentiment ou subir une expérience",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"équité",lemmaKey:"equite",headword:"équité",partOfSpeech:"noun",senseKey:"equite_fairness",gloss:"fairness; equity",definition:"justice fondée sur une appréciation impartiale",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"erreur",lemmaKey:"erreur",headword:"erreur",partOfSpeech:"noun",senseKey:"erreur_mistake",gloss:"error; mistake",definition:"jugement ou action contraire à la vérité",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"escroqueries",lemmaKey:"escroquerie",headword:"escroquerie",partOfSpeech:"noun",senseKey:"escroquerie_fraud",gloss:"fraud; swindle",quizMeaning:"frauds; swindles",definition:"action de tromper quelqu’un pour obtenir un avantage",englishDistractors:["baskets","comets","walnuts"],frenchDistractors:["paniers","comètes","noix"]},
 {normalized:"espérer",lemmaKey:"esperer",headword:"espérer",partOfSpeech:"verb",senseKey:"esperer_hope",gloss:"to hope",definition:"attendre avec confiance la réalisation de quelque chose",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"établi",lemmaKey:"etablir",headword:"établir",partOfSpeech:"verb",senseKey:"etablir_establish",gloss:"to establish",quizMeaning:"established",definition:"fixer ou démontrer solidement un fait ou une autorité",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassé","navigué","cligné"]},
 {normalized:"étaient",lemmaKey:"etre",existingLemmaId:"lem_etre",existingSenseId:"sns_etre_primary",headword:"être",partOfSpeech:"verb",senseKey:"etre_be",gloss:"to be",quizMeaning:"were",definition:"exprimer un état ou une identité",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassaient","naviguaient","clignaient"]},
 {normalized:"était",lemmaKey:"etre",existingLemmaId:"lem_etre",existingSenseId:"sns_etre_primary",headword:"être",partOfSpeech:"verb",senseKey:"etre_be",gloss:"to be",quizMeaning:"was",definition:"exprimer un état ou une identité",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassait","naviguait","clignait"]},
 {normalized:"état-major",lemmaKey:"etat_major",headword:"état-major",partOfSpeech:"noun",senseKey:"etat_major_staff",gloss:"general staff; headquarters",definition:"ensemble des officiers qui assistent le commandement militaire",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"été",lemmaKey:"etre",existingLemmaId:"lem_etre",existingSenseId:"sns_etre_primary",headword:"être",partOfSpeech:"verb",senseKey:"etre_be",gloss:"to be",quizMeaning:"been",definition:"exprimer un état ou une identité",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassé","navigué","cligné"]},
 {normalized:"étoile",lemmaKey:"etoile",headword:"étoile",partOfSpeech:"noun",senseKey:"etoile_destiny",gloss:"star; destiny",definition:"astre lumineux, employé figurément pour désigner la destinée",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"étonne",lemmaKey:"etonner",headword:"étonner",partOfSpeech:"verb",senseKey:"etonner_surprise",gloss:"to surprise; astonish",quizMeaning:"surprises; astonishes",definition:"causer une vive surprise",englishDistractors:["quilts","sails","winks"],frenchDistractors:["matelasse","navigue","cligne"]},
 {normalized:"étouffées",lemmaKey:"etouffer",headword:"étouffer",partOfSpeech:"verb",senseKey:"etouffer_suppress",gloss:"to suppress; stifle",quizMeaning:"suppressed; stifled",definition:"empêcher une vérité ou une preuve de se manifester",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassées","naviguées","clignées"]},
 {normalized:"étrangère",lemmaKey:"etranger",headword:"étranger",partOfSpeech:"adjective",senseKey:"etranger_foreign",gloss:"foreign",definition:"qui appartient à un autre pays",englishDistractors:aE,frenchDistractors:["boisée","mentholée","octogonale"]},
 {normalized:"étroites",lemmaKey:"etroit",headword:"étroit",partOfSpeech:"adjective",senseKey:"etroit_strict",gloss:"narrow; strict",definition:"qui laisse très peu de largeur ou de liberté",englishDistractors:aE,frenchDistractors:["boisées","mentholées","octogonales"]},
 {normalized:"étudié",lemmaKey:"etudier",headword:"étudier",partOfSpeech:"verb",senseKey:"etudier_examine",gloss:"to study; examine",quizMeaning:"studied; examined",definition:"examiner attentivement pour comprendre",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassé","navigué","cligné"]},
 {normalized:"étudier",lemmaKey:"etudier",headword:"étudier",partOfSpeech:"verb",senseKey:"etudier_examine",gloss:"to study; examine",definition:"examiner attentivement pour comprendre",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"eu",lemmaKey:"avoir",headword:"avoir",partOfSpeech:"verb",senseKey:"avoir_possess_auxiliary",gloss:"to have; auxiliary avoir",quizMeaning:"had",definition:"posséder ou servir d’auxiliaire",englishDistractors:["quilted","sailed","winked"],frenchDistractors:["matelassé","navigué","cligné"]},
];
