import type { EditorialQuizSet } from "./zola-editorial-quizzes.js";

export const zolaEditorialBatch15: Record<string, EditorialQuizSet> = {
  "dans:dans_in": {
    early: "Le chat dort dans son panier, à l’intérieur de la maison.", englishChoices: ["in", "under", "beside", "during"],
    intermediate: "Pour protéger la lettre de la pluie, Nina la met _____ une enveloppe.", frenchChoices: ["dans", "sous", "devant", "autour de"],
    advanced: "Le dossier se trouve dans l’armoire fermée, à l’intérieur du bureau. Paul attend devant la porte, Nina passe sous l’escalier et Léa travaille près de la fenêtre.",
    prompt: "Quel mot situe le dossier à l’intérieur de l’armoire ?", advancedChoices: ["dans", "devant", "sous", "près"],
  },
  "dégradation:degradation_demotion": {
    early: "Lors de la cérémonie, la dégradation de l’officier lui retire publiquement son grade.", englishChoices: ["demotion", "promotion", "reward", "transfer"],
    intermediate: "On lui retire son rang devant les soldats : cette _____ publique met fin à sa carrière d’officier.", frenchChoices: ["dégradation", "promotion", "récompense", "nomination"],
    advanced: "La dégradation de l’officier a lieu devant le régiment : on lui retire ses insignes. Le commandant lit la décision, les soldats restent immobiles et le secrétaire note la date.",
    prompt: "Quel mot désigne la perte publique du rang de l’officier ?", advancedChoices: ["dégradation", "insignes", "commandant", "date"],
  },
  "dehors:dehors_outside": {
    early: "Les enfants jouent dehors, dans le jardin plutôt que dans la maison.", englishChoices: ["outside", "inside", "upstairs", "tomorrow"],
    intermediate: "La salle est pleine ; les visiteurs restants attendent _____ devant l’entrée.", frenchChoices: ["dehors", "dedans", "à l’étage", "partout"],
    advanced: "Nina attend dehors, sur le trottoir, tandis que Paul lit à l’intérieur du café. Léa ferme la porte et Marc regarde le ciel.",
    prompt: "Quel mot indique que Nina n’est pas à l’intérieur du café ?", advancedChoices: ["dehors", "intérieur", "porte", "ciel"],
  },
  "déjà:deja_already": {
    early: "Quand j’arrive, le train est déjà parti : son départ a eu lieu avant mon arrivée.", englishChoices: ["already", "not yet", "later", "rarely"],
    intermediate: "Il n’est que huit heures, mais Nina a _____ terminé son travail.", frenchChoices: ["déjà", "jamais", "rarement", "ensuite"],
    advanced: "Paul a déjà payé son billet avant d’entrer dans la gare. Nina achète encore le sien, Léa attend son tour et Marc ferme sa valise.",
    prompt: "Quel mot indique que le paiement de Paul a eu lieu avant ce moment ?", advancedChoices: ["déjà", "encore", "tour", "valise"],
  },
  "délais:delai_delay": {
    early: "Les délais de réponse sont de dix jours pour cette demande officielle.", englishChoices: ["time limits", "answers", "addresses", "prices"],
    intermediate: "Pour répondre aux candidatures, le bureau dispose de _____ de deux semaines.", frenchChoices: ["délais", "tarifs", "adresses", "titres"],
    advanced: "Les délais accordés pour remettre les dossiers se terminent vendredi. Nina vérifie les signatures, Paul range les enveloppes et Léa ouvre le bureau.",
    prompt: "Quel mot désigne les périodes de temps accordées avant la remise des dossiers ?", advancedChoices: ["délais", "signatures", "enveloppes", "bureau"],
  },
  "délirer:delirer_rave": {
    early: "Après trois nuits sans sommeil, Paul se met à délirer et raconte des événements imaginaires.", englishChoices: ["to rave", "to concentrate", "to calculate", "to rest"],
    intermediate: "Il tient des propos incohérents et semble _____ au lieu de décrire des faits réels.", frenchChoices: ["délirer", "raisonner", "calculer", "se taire"],
    advanced: "Luc commence à délirer : il prétend que les murs lui parlent et perd le fil de ses phrases. Nina consulte le calendrier, Paul apporte de l’eau et Léa ouvre la fenêtre.",
    prompt: "Quel verbe indique que Luc tient des propos déraisonnables ?", advancedChoices: ["délirer", "consulte", "apporte", "ouvre"],
  },
  "délits:delit_offense": {
    early: "Le tribunal examine deux délits : une fraude et un vol de faible gravité.", englishChoices: ["offenses", "rewards", "invitations", "accidents"],
    intermediate: "La loi punit ces deux infractions : ce sont des _____.", frenchChoices: ["délits", "cadeaux", "accidents", "félicitations"],
    advanced: "Les délits reprochés à Marc sont la fraude et le vol de documents. Nina témoigne devant le juge, Paul apporte un dossier et Léa attend dans le couloir.",
    prompt: "Quel mot désigne les infractions punies par la loi ?", advancedChoices: ["délits", "documents", "dossier", "couloir"],
  },
  "demain:demain_tomorrow": {
    early: "Nous sommes lundi ; la réunion aura lieu demain, mardi.", englishChoices: ["tomorrow", "yesterday", "today", "last week"],
    intermediate: "Aujourd’hui, nous sommes jeudi ; la visite aura lieu _____, vendredi.", frenchChoices: ["demain", "hier", "aujourd’hui", "lundi"],
    advanced: "Demain, mardi, Nina ira au musée ; aujourd’hui, lundi, elle prépare son sac. Paul y est allé hier et Léa partira vendredi.",
    prompt: "Quel mot désigne le jour qui suit aujourd’hui ?", advancedChoices: ["demain", "aujourd’hui", "hier", "vendredi"],
  },
  "demande:demande_request": {
    early: "La demande de permis de Luc a été déposée à la mairie hier.", englishChoices: ["application", "refusal", "receipt", "complaint"],
    intermediate: "Pour obtenir une autorisation, Nina remplit et remet une _____ à la mairie.", frenchChoices: ["demande", "réponse", "plainte", "invitation"],
    advanced: "La demande de permis de Marie arrive au bureau des inscriptions. Paul vérifie les pièces jointes, Nina ouvre le courrier et Luc imprime une copie.",
    prompt: "Quel mot désigne la démarche officielle de Marie pour obtenir un permis ?", advancedChoices: ["demande", "bureau", "courrier", "copie"],
  },
  "demandé:demander_ask": {
    early: "Paul a demandé à quelle heure le train partira.", englishChoices: ["asked", "answered", "forgot", "guessed"],
    intermediate: "Ne connaissant pas l’horaire, Léa a _____ l’heure du départ au guichetier.", frenchChoices: ["demandé", "répondu", "caché", "oublié"],
    advanced: "Nina a demandé à Paul où se trouve la bibliothèque parce qu’elle ne connaît pas la rue. Marc a montré une carte, Léa a fermé sa valise et Luc a ouvert la porte.",
    prompt: "Quel mot indique que Nina a posé une question à Paul ?", advancedChoices: ["demandé", "montré", "fermé", "ouvert"],
  },
  "démence:demence_madness": {
    early: "Dans ce récit fantastique, la démence du roi le pousse à croire que les arbres lui parlent.", englishChoices: ["madness", "wisdom", "patience", "courage"],
    intermediate: "Dans la pièce, le personnage perd tout contact avec la réalité ; sa _____ inquiète les autres.", frenchChoices: ["démence", "sagesse", "patience", "prudence"],
    advanced: "La démence du personnage de théâtre lui fait entendre des voix dans une pièce vide. Le public reste silencieux, la metteuse en scène règle la lumière et Paul lit le programme.",
    prompt: "Quel mot désigne ici le profond dérèglement de la raison du personnage ?", advancedChoices: ["démence", "public", "lumière", "programme"],
  },
  "démentes:dement_mad": {
    early: "Dans le roman, ses idées démentes le poussent à croire que le fleuve lui répond.", englishChoices: ["insane", "reasonable", "ordinary", "calm"],
    intermediate: "Dans cette fiction, leurs croyances _____ leur font prendre les ombres pour des personnes réelles.", frenchChoices: ["démentes", "raisonnables", "prudentes", "réalistes"],
    advanced: "Les croyances démentes des personnages leur font croire qu’une maison vide parle la nuit. Le directeur du théâtre ajuste le décor, Nina lit son rôle et Luc range les costumes.",
    prompt: "Quel mot qualifie des croyances marquées par une profonde perte de raison ?", advancedChoices: ["démentes", "directeur", "décor", "costumes"],
  },
  "démenti:dementi_denial": {
    early: "Le directeur publie un démenti : il nie formellement la rumeur de fermeture.", englishChoices: ["denial", "confirmation", "invitation", "compliment"],
    intermediate: "Après la rumeur, la mairie publie un _____ officiel pour affirmer qu’aucune fermeture n’est prévue.", frenchChoices: ["démenti", "aveu", "accord", "éloge"],
    advanced: "Le démenti du musée contredit la rumeur de sa fermeture : il restera ouvert tout l’été. Nina lit l’affiche, Paul ferme la caisse et Léa accueille les visiteurs.",
    prompt: "Quel mot désigne la déclaration officielle qui contredit la rumeur ?", advancedChoices: ["démenti", "affiche", "caisse", "visiteurs"],
  },
  "démesurée:demesure_excessive": {
    early: "La dépense est démesurée : ce repas coûte autant qu’une année de salaire.", englishChoices: ["excessive", "moderate", "small", "reasonable"],
    intermediate: "Pour un simple goûter, cette facture de mille euros est _____.", frenchChoices: ["démesurée", "modérée", "raisonnable", "minime"],
    advanced: "La somme démesurée réclamée pour réparer une chaise dépasse dix mille euros. La chaise est vieille, la pièce est calme et le devis est signé.",
    prompt: "Quel mot indique que la somme dépasse toute mesure raisonnable ?", advancedChoices: ["démesurée", "vieille", "calme", "signé"],
  },
  "démontre:demontrer_prove": {
    early: "Ce calcul démontre que le pont peut supporter le poids prévu.", englishChoices: ["proves", "hides", "forgets", "denies"],
    intermediate: "À l’aide de mesures précises, l’ingénieure _____ que le mur est solide.", frenchChoices: ["démontre", "cache", "oublie", "nie"],
    advanced: "Le graphique démontre que les ventes ont doublé : les chiffres passent de cent à deux cents. Paul rédige le rapport, Nina vérifie les reçus et Marc ferme le bureau.",
    prompt: "Quel mot indique que le graphique établit le résultat par des chiffres ?", advancedChoices: ["démontre", "rédige", "vérifie", "ferme"],
  },
  "démontré:demontrer_prove": {
    early: "Avec deux expériences, la chercheuse a démontré que l’hypothèse était fausse.", englishChoices: ["proved", "concealed", "forgot", "denied"],
    intermediate: "À l’aide d’un calcul vérifiable, Paul a _____ que le plan est réalisable.", frenchChoices: ["démontré", "caché", "oublié", "nié"],
    advanced: "L’enquête a démontré que la route était fermée ce matin : plusieurs témoins l’ont constaté. Nina a classé les notes, Paul a ouvert la carte et Léa a téléphoné au maire.",
    prompt: "Quel mot indique que l’enquête a établi le fait avec des preuves ?", advancedChoices: ["démontré", "classé", "ouvert", "téléphoné"],
  },
  "déni:deni_denial": {
    early: "Refuser à Paul l’accès au tribunal constitue un déni de justice.", englishChoices: ["denial", "grant", "reward", "agreement"],
    intermediate: "La cour refuse d’examiner ses droits : il dénonce un _____ de justice.", frenchChoices: ["déni", "accès", "don", "accord"],
    advanced: "Le déni de justice empêche Léa d’obtenir l’audience à laquelle elle a droit. Le greffier examine les dossiers, Paul attend son tour et Nina téléphone à son avocat.",
    prompt: "Quel mot désigne le refus d’accorder un droit dû à Léa ?", advancedChoices: ["déni", "audience", "greffier", "avocat"],
  },
  "dénonça:denoncer_report": {
    early: "En 1895, Léa dénonça publiquement la fraude dont elle avait découvert les preuves.", englishChoices: ["reported", "concealed", "approved", "ignored"],
    intermediate: "Hier, le témoin _____ la corruption au juge en présentant ses preuves.", frenchChoices: ["dénonça", "cacha", "approuva", "ignora"],
    advanced: "Devant le conseil, Marc dénonça le vol qu’il avait vu la veille. Nina classa les lettres, Paul ouvrit la séance et Léa nota les noms.",
    prompt: "Quel mot indique que Marc signala le vol à une autorité ?", advancedChoices: ["dénonça", "classa", "ouvrit", "nota"],
  },
  "dénoncé:denoncer_report": {
    early: "Le témoin a dénoncé le vol au juge en donnant les noms des auteurs.", englishChoices: ["reported", "concealed", "approved", "ignored"],
    intermediate: "Après avoir vu la fraude, Nina l’a _____ au directeur et lui a montré les preuves.", frenchChoices: ["dénoncé", "caché", "approuvé", "ignoré"],
    advanced: "Le comptable a dénoncé la fraude à la police après avoir découvert de faux reçus. Nina a classé les dossiers, Paul a fermé la caisse et Luc a ouvert la porte.",
    prompt: "Quel mot indique que le comptable a signalé la fraude aux autorités ?", advancedChoices: ["dénoncé", "classé", "fermé", "ouvert"],
  },
  "dénoncerai:denoncer_report": {
    early: "Si je découvre une fraude, je la dénoncerai demain à la police.", englishChoices: ["will report", "will conceal", "will approve", "will ignore"],
    intermediate: "Si je vois un vol, je le _____ au commissariat dès demain.", frenchChoices: ["dénoncerai", "cacherai", "approuverai", "ignorerai"],
    advanced: "Si les fausses factures sont confirmées, je dénoncerai la fraude au juge. Nina vérifiera les comptes, Paul rangera les documents et Luc attendra la réponse.",
    prompt: "Quel mot indique que je signalerai la fraude à l’autorité ?", advancedChoices: ["dénoncerai", "vérifiera", "rangera", "attendra"],
  },
  "dénouement:denouement_outcome": {
    early: "Le dénouement du roman révèle enfin qui avait volé la lettre.", englishChoices: ["resolution", "beginning", "introduction", "digression"],
    intermediate: "À la fin de l’histoire, le mystère est résolu : voilà le _____.", frenchChoices: ["dénouement", "début", "prologue", "détour"],
    advanced: "Au dénouement de la pièce, le vrai voleur avoue et l’innocent retrouve sa liberté. Le public applaudit, le rideau tombe et la salle se rallume.",
    prompt: "Quel mot désigne la fin qui résout l’intrigue ?", advancedChoices: ["dénouement", "public", "rideau", "salle"],
  },
  "déposer:deposer_submit": {
    early: "Pour obtenir un permis, Léa doit déposer sa demande à la mairie.", englishChoices: ["to submit", "to withdraw", "to destroy", "to conceal"],
    intermediate: "Avant vendredi, il faut _____ le formulaire signé au guichet officiel.", frenchChoices: ["déposer", "détruire", "cacher", "retirer"],
    advanced: "Paul va déposer son dossier de candidature à la mairie avant midi. Nina vérifie les signatures, Marc ouvre le guichet et Léa prend un numéro.",
    prompt: "Quel verbe signifie remettre officiellement le dossier à la mairie ?", advancedChoices: ["déposer", "vérifie", "ouvre", "prend"],
  },
  "depuis:depuis_since": {
    early: "Nina travaille ici depuis lundi ; elle a commencé ce jour-là et continue aujourd’hui.", englishChoices: ["since", "until", "during", "before"],
    intermediate: "Paul habite dans ce village _____ 2018 et n’a jamais déménagé.", frenchChoices: ["depuis", "jusqu’en", "pendant", "avant"],
    advanced: "Léa joue du piano depuis l’enfance et continue chaque semaine. Nina apprend la guitare, Paul chante le dimanche et Marc répare les instruments.",
    prompt: "Quel mot indique le point de départ d’une activité qui continue ?", advancedChoices: ["depuis", "enfance", "dimanche", "instruments"],
  },
  "dérangée:deranger_go_out_of_way": {
    early: "Bien qu’elle soit en congé, Nina s’est dérangée pour apporter les clés à son voisin.", englishChoices: ["went out of her way", "remained indifferent", "refused", "forgot"],
    intermediate: "Alors qu’elle se reposait, Léa s’est _____ pour conduire son amie à la gare.", frenchChoices: ["dérangée", "reposé", "endormie", "absentée"],
    advanced: "Marie s’est dérangée un dimanche pour aider son voisin à déménager. Paul a apporté des cartons, Nina a préparé du café et Luc a ouvert le portail.",
    prompt: "Quel mot indique que Marie s’est donné de la peine en changeant ses habitudes ?", advancedChoices: ["dérangée", "apporté", "préparé", "ouvert"],
  },
  "dernier:dernier_latter": {
    early: "Paul et Marc ont parlé ; ce dernier, Marc, a proposé une autre date.", englishChoices: ["latter", "first", "earlier", "previous"],
    intermediate: "Deux témoins arrivent, Luc puis Paul ; ce _____ prend la parole en second.", frenchChoices: ["dernier", "premier", "précédent", "suivant"],
    advanced: "Nina et Paul examinent le plan ; ce dernier, Paul, découvre une erreur. Luc ferme le dossier, Léa consulte une carte et Marc appelle le directeur.",
    prompt: "Quel mot renvoie à Paul, le second des deux noms mentionnés ?", advancedChoices: ["dernier", "plan", "erreur", "dossier"],
  },
  "derrière:derriere_behind": {
    early: "Le vélo est garé derrière la maison, à l’abri des regards depuis la rue.", englishChoices: ["behind", "in front of", "under", "inside"],
    intermediate: "La voiture est stationnée _____ le bâtiment, du côté opposé à l’entrée.", frenchChoices: ["derrière", "devant", "sous", "dans"],
    advanced: "Le petit jardin se trouve derrière l’école, à l’opposé de l’entrée principale. Nina attend devant la porte, Paul passe sous le préau et Léa entre dans la cour.",
    prompt: "Quel mot situe le jardin à l’arrière de l’école ?", advancedChoices: ["derrière", "devant", "sous", "dans"],
  },
};
