import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEnglish: [string, string, string] = ["a lantern", "a cucumber", "a suitcase"];
const nounFrench: [string, string, string] = ["une lanterne", "un concombre", "une valise"];
const adjectiveEnglish: [string, string, string] = ["checkered", "vanilla-scented", "hexagonal"];
const adjectiveFrench: [string, string, string] = ["à carreaux", "parfumé à la vanille", "hexagonal"];

export const zolaVocabularyBatch25: ZolaVocabularySpec[] = [
  { normalized: "gens", lemmaKey: "gens", headword: "gens", partOfSpeech: "noun", senseKey: "gens_people", gloss: "people", definition: "ensemble indéterminé de personnes", englishDistractors: ["lanterns", "cucumbers", "suitcases"], frenchDistractors: ["lanternes", "concombres", "valises"] },
  { normalized: "gens-là", lemmaKey: "gens", headword: "gens", partOfSpeech: "noun", senseKey: "gens_people", gloss: "people", quizMeaning: "those people", definition: "ensemble indéterminé de personnes", englishDistractors: ["those lanterns", "those cucumbers", "those suitcases"], frenchDistractors: ["ces lanternes-là", "ces concombres-là", "ces valises-là"] },
  { normalized: "glaces", lemmaKey: "glace", headword: "glace", partOfSpeech: "noun", senseKey: "glace_mirror", gloss: "mirror", quizMeaning: "mirrors", definition: "plaque de verre réfléchissante dans laquelle on voit une image", englishDistractors: ["lanterns", "cucumbers", "suitcases"], frenchDistractors: ["lanternes", "concombres", "valises"] },
  { normalized: "gorge", lemmaKey: "gorge", headword: "gorge", partOfSpeech: "noun", senseKey: "gorge_throat", gloss: "throat", definition: "partie antérieure du cou et conduit reliant la bouche aux voies respiratoires", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "gouvernement", lemmaKey: "gouvernement", headword: "gouvernement", partOfSpeech: "noun", senseKey: "gouvernement_government", gloss: "government", definition: "ensemble des personnes et institutions qui dirigent l’État", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "grand", lemmaKey: "grand", headword: "grand", partOfSpeech: "adjective", senseKey: "grand_great", gloss: "great; large", definition: "qui possède une importance, une intensité ou une ampleur considérable", englishDistractors: adjectiveEnglish, frenchDistractors: adjectiveFrench },
  { normalized: "grande", lemmaKey: "grand", headword: "grand", partOfSpeech: "adjective", senseKey: "grand_great", gloss: "great; large", definition: "qui possède une importance, une intensité ou une ampleur considérable", englishDistractors: adjectiveEnglish, frenchDistractors: ["à carreaux", "parfumée à la vanille", "hexagonale"] },
  { normalized: "grandes", lemmaKey: "grand", headword: "grand", partOfSpeech: "adjective", senseKey: "grand_great", gloss: "great; large", definition: "qui possède une importance, une intensité ou une ampleur considérable", englishDistractors: adjectiveEnglish, frenchDistractors: ["à carreaux", "parfumées à la vanille", "hexagonales"] },
  { normalized: "grandir", lemmaKey: "grandir", headword: "grandir", partOfSpeech: "verb", senseKey: "grandir_grow", gloss: "to grow; increase", definition: "devenir plus grand, plus intense ou plus important", englishDistractors: ["to juggle", "to paddle", "to sneeze"], frenchDistractors: ["jongler", "pagayer", "éternuer"] },
  { normalized: "grandit", lemmaKey: "grandir", headword: "grandir", partOfSpeech: "verb", senseKey: "grandir_grow", gloss: "to grow; increase", quizMeaning: "grows; increases", definition: "devenir plus grand, plus intense ou plus important", englishDistractors: ["juggles", "paddles", "sneezes"], frenchDistractors: ["jongle", "pagaie", "éternue"] },
  { normalized: "gratitude", lemmaKey: "gratitude", headword: "gratitude", partOfSpeech: "noun", senseKey: "gratitude_thankfulness", gloss: "gratitude; thankfulness", definition: "sentiment de reconnaissance envers quelqu’un", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "graves", lemmaKey: "grave", headword: "grave", partOfSpeech: "adjective", senseKey: "grave_serious", gloss: "serious; grave", definition: "qui a une grande importance et peut entraîner de lourdes conséquences", englishDistractors: adjectiveEnglish, frenchDistractors: ["à carreaux", "parfumés à la vanille", "hexagonaux"] },
  { normalized: "gros", lemmaKey: "en_gros", headword: "en gros", partOfSpeech: "adverb", senseKey: "en_gros_broadly", gloss: "broadly; in outline", definition: "sans entrer dans les détails, d’une manière générale", englishDistractors: ["silently", "outdoors", "tomorrow"], frenchDistractors: ["silencieusement", "dehors", "demain"] },
  { normalized: "guérie", lemmaKey: "guerir", headword: "guérir", partOfSpeech: "verb", senseKey: "guerir_cure", gloss: "to cure; heal", quizMeaning: "cured; healed", definition: "délivrer d’un mal ou retrouver un état sain", englishDistractors: ["juggled", "paddled", "sneezed"], frenchDistractors: ["jonglée", "pagayée", "éternuée"] },
  { normalized: "guerre", lemmaKey: "guerre", headword: "guerre", partOfSpeech: "noun", senseKey: "guerre_war", gloss: "war; military affairs", definition: "conflit armé ou domaine institutionnel relatif aux affaires militaires", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "haine", lemmaKey: "haine", headword: "haine", partOfSpeech: "noun", senseKey: "haine_hatred", gloss: "hatred; hate", definition: "sentiment violent d’hostilité et de rejet", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "hanté", lemmaKey: "hanter", headword: "hanter", partOfSpeech: "verb", senseKey: "hanter_haunt", gloss: "to haunt; obsess", quizMeaning: "haunted; obsessed", definition: "occuper sans cesse l’esprit ou poursuivre comme une présence inquiétante", englishDistractors: ["juggled", "paddled", "sneezed"], frenchDistractors: ["jonglé", "pagayé", "éternué"] },
  { normalized: "hantées", lemmaKey: "hanter", headword: "hanter", partOfSpeech: "verb", senseKey: "hanter_haunt", gloss: "to haunt; obsess", quizMeaning: "haunted", definition: "occuper sans cesse l’esprit ou poursuivre comme une présence inquiétante", englishDistractors: ["juggled", "paddled", "sneezed"], frenchDistractors: ["jonglées", "pagayées", "éternuées"] },
  { normalized: "hâter", lemmaKey: "hater", headword: "hâter", partOfSpeech: "verb", senseKey: "hater_hasten", gloss: "to hasten; accelerate", definition: "faire arriver plus vite ou accélérer le déroulement", englishDistractors: ["to juggle", "to paddle", "to sneeze"], frenchDistractors: ["jongler", "pagayer", "éternuer"] },
  { normalized: "haut", lemmaKey: "haut_adverb", headword: "haut", partOfSpeech: "adverb", senseKey: "haut_aloud", gloss: "aloud; openly", definition: "d’une voix forte ou d’une manière publiquement perceptible", englishDistractors: ["silently", "outdoors", "tomorrow"], frenchDistractors: ["silencieusement", "dehors", "demain"] },
  { normalized: "haute", lemmaKey: "haut_adjective", headword: "haut", partOfSpeech: "adjective", senseKey: "haut_elevated", gloss: "high; elevated", definition: "qui atteint un degré élevé de valeur ou de dignité", englishDistractors: adjectiveEnglish, frenchDistractors: ["à carreaux", "parfumée à la vanille", "hexagonale"] },
  { normalized: "heure", lemmaKey: "heure", headword: "heure", partOfSpeech: "noun", senseKey: "heure_hour", gloss: "hour", definition: "unité de temps ou moment déterminé dans le déroulement du temps", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "heureuse", lemmaKey: "heureux", headword: "heureux", partOfSpeech: "adjective", senseKey: "heureux_fortunate", gloss: "happy; fortunate", definition: "qui connaît le bonheur ou bénéficie de circonstances favorables", englishDistractors: adjectiveEnglish, frenchDistractors: ["à carreaux", "parfumée à la vanille", "hexagonale"] },
  { normalized: "hiérarchiquement", lemmaKey: "hierarchiquement", headword: "hiérarchiquement", partOfSpeech: "adverb", senseKey: "hierarchiquement_by_rank", gloss: "hierarchically; by rank", definition: "selon l’ordre et les rapports de subordination d’une hiérarchie", englishDistractors: ["silently", "outdoors", "tomorrow"], frenchDistractors: ["silencieusement", "dehors", "demain"] },
  { normalized: "hiérarchiques", lemmaKey: "hierarchique", headword: "hiérarchique", partOfSpeech: "adjective", senseKey: "hierarchique_ranked", gloss: "hierarchical; superior in rank", definition: "relatif à une organisation fondée sur des degrés de subordination", englishDistractors: adjectiveEnglish, frenchDistractors: ["à carreaux", "parfumés à la vanille", "hexagonaux"] },
  { normalized: "histoire", candidateIds: ["tok_f53355a55fc41f3844e4ef1b", "tok_7e53168c930eaf905f406b2f"], lemmaKey: "histoire", headword: "histoire", partOfSpeech: "noun", senseKey: "histoire_historical_record", gloss: "history; historical record", definition: "mémoire collective et récit des événements du passé", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "histoire", candidateIds: ["tok_caad59695777bae1cc3ba601", "tok_144c14f894e12a2b11504851", "tok_f3656dd094b092a2736718fb"], lemmaKey: "histoire", headword: "histoire", partOfSpeech: "noun", senseKey: "histoire_story", gloss: "story; account", definition: "récit ou ensemble d’événements constituant une affaire", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "historique", lemmaKey: "historique_noun", headword: "historique", partOfSpeech: "noun", senseKey: "historique_account", gloss: "history; chronological account", definition: "exposé chronologique des faits et de leur évolution", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
  { normalized: "homme", lemmaKey: "homme", headword: "homme", partOfSpeech: "noun", senseKey: "homme_man_human", gloss: "man; human being", definition: "être humain, ou personne adulte de sexe masculin selon le contexte", englishDistractors: nounEnglish, frenchDistractors: nounFrench },
];
