import type { ZolaVocabularySpec } from "./zola-authoring.js";
const nE:[string,string,string]=["a chimney","a blanket","a plum"];
const nF:[string,string,string]=["cheminée","couverture","prune"];
const vE:[string,string,string]=["to juggle","to sail","to cough"];
const vF:[string,string,string]=["jongler","naviguer","tousser"];
export const zolaVocabularyBatch09: ZolaVocabularySpec[] = [
 {normalized:"cela",lemmaKey:"cela",headword:"cela",partOfSpeech:"pronoun",senseKey:"cela_that",gloss:"that",definition:"pronom désignant ce qui vient d’être mentionné",englishDistractors:["someone","nowhere","several"],frenchDistractors:["quelqu’un","nulle part","plusieurs"]},
 {normalized:"celle",lemmaKey:"celui",existingLemmaId:"lem_celui",existingSenseId:"sns_celui_primary",headword:"celui",partOfSpeech:"pronoun",senseKey:"celui_primary",gloss:"the one",definition:"pronom démonstratif féminin singulier",englishDistractors:["somewhere","nobody","often"],frenchDistractors:["ailleurs","personne","souvent"]},
 {normalized:"celui-là",lemmaKey:"celui",existingLemmaId:"lem_celui",existingSenseId:"sns_celui_primary",headword:"celui",partOfSpeech:"pronoun",senseKey:"celui_primary",gloss:"that one",definition:"pronom démonstratif désignant une personne éloignée",englishDistractors:["somewhere","nobody","often"],frenchDistractors:["ailleurs","personne","souvent"]},
 {normalized:"cet",lemmaKey:"ce",existingLemmaId:"lem_ce",existingSenseId:"sns_ce_primary",headword:"ce",partOfSpeech:"determiner",senseKey:"ce_primary",gloss:"this; that",definition:"déterminant démonstratif masculin devant une voyelle",englishDistractors:["each","my","several"],frenchDistractors:["chaque","mon","plusieurs"]},
 {normalized:"charge",candidateIds:["tok_dcfe30876b4d10e8ffaa6802"],lemmaKey:"charge",headword:"charge",partOfSpeech:"noun",senseKey:"charge_evidence",gloss:"charge; evidence",definition:"élément retenu contre une personne accusée",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"charge",candidateIds:["tok_ad0ed432306eb04bc7e28bbd"],lemmaKey:"charge",headword:"charge",partOfSpeech:"noun",senseKey:"charge_burden",gloss:"responsibility; burden",definition:"responsabilité assumée par quelqu’un",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"chargé",candidateIds:["tok_7594275591f0755c823a8e44"],lemmaKey:"charger",headword:"charger",partOfSpeech:"verb",senseKey:"charger_assign",gloss:"to task; entrust",quizMeaning:"tasked; entrusted",definition:"confier une mission à quelqu’un",englishDistractors:["juggled","sailed","coughed"],frenchDistractors:["jonglé","navigué","toussé"]},
 {normalized:"chargé",candidateIds:["tok_0fcad22636e919133ad4fafd"],lemmaKey:"charger",headword:"charger",partOfSpeech:"verb",senseKey:"charger_accuse",gloss:"to accuse; incriminate",quizMeaning:"accused; incriminated",definition:"mettre gravement en cause",englishDistractors:["juggled","sailed","coughed"],frenchDistractors:["jonglé","navigué","toussé"]},
 {normalized:"chargeant",lemmaKey:"charger",headword:"charger",partOfSpeech:"verb",senseKey:"charger_assign",gloss:"to task; entrust",quizMeaning:"tasking; assigning",definition:"confier une mission à quelqu’un",englishDistractors:["juggling","sailing","coughing"],frenchDistractors:["jonglant","naviguant","toussant"]},
 {normalized:"charger",lemmaKey:"charger",headword:"charger",partOfSpeech:"verb",senseKey:"charger_accuse",gloss:"to accuse; incriminate",definition:"mettre gravement en cause",englishDistractors:vE,frenchDistractors:vF},
 {normalized:"chef",lemmaKey:"chef",headword:"chef",partOfSpeech:"noun",senseKey:"chef_leader",gloss:"chief; leader",definition:"personne qui dirige",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"chefs",candidateIds:["tok_f4c9d89465c05c8adab4e400"],lemmaKey:"chef",headword:"chef",partOfSpeech:"noun",senseKey:"chef_count",gloss:"counts; grounds",definition:"points distincts d’une accusation",englishDistractors:["chimneys","blankets","plums"],frenchDistractors:["cheminées","couvertures","prunes"]},
 {normalized:"chefs",candidateIds:["tok_b8678e10e4043843fd567110"],lemmaKey:"chef",headword:"chef",partOfSpeech:"noun",senseKey:"chef_leader",gloss:"chief; leader",quizMeaning:"chiefs; leaders",definition:"personne qui dirige",englishDistractors:["chimneys","blankets","plums"],frenchDistractors:["cheminées","couvertures","prunes"]},
 {normalized:"cher",lemmaKey:"cher",headword:"cher",partOfSpeech:"adjective",senseKey:"cher_expensive",gloss:"expensive; dearly",definition:"à un prix élevé",englishDistractors:["purple","square","peppery"],frenchDistractors:["violet","carré","poivré"]},
 {normalized:"cherchait",lemmaKey:"chercher",headword:"chercher",partOfSpeech:"verb",senseKey:"chercher_seek",gloss:"to seek; look for",quizMeaning:"was looking for",definition:"tenter de trouver",englishDistractors:["was juggling","was sailing","was coughing"],frenchDistractors:["jonglait","naviguait","toussait"]},
 {normalized:"cherche",lemmaKey:"chercher",headword:"chercher",partOfSpeech:"verb",senseKey:"chercher_seek",gloss:"to seek; look for",quizMeaning:"looks for",definition:"tenter de trouver",englishDistractors:["juggles","sails","coughs"],frenchDistractors:["jongle","navigue","tousse"]},
 {normalized:"cherchent",lemmaKey:"chercher",headword:"chercher",partOfSpeech:"verb",senseKey:"chercher_seek",gloss:"to seek; look for",quizMeaning:"look for",definition:"tenter de trouver",englishDistractors:["juggle","sail","cough"],frenchDistractors:["jonglent","naviguent","toussent"]},
 {normalized:"chez",lemmaKey:"chez",headword:"chez",partOfSpeech:"preposition",senseKey:"chez_at_home",gloss:"at the home or premises of",definition:"dans la demeure ou les locaux de",englishDistractors:["beneath","despite","across"],frenchDistractors:["sous","malgré","à travers"]},
 {normalized:"choix",lemmaKey:"choix",headword:"choix",partOfSpeech:"noun",senseKey:"choix_choice",gloss:"choice",definition:"action de sélectionner entre plusieurs possibilités",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"choses",lemmaKey:"chose",headword:"chose",partOfSpeech:"noun",senseKey:"chose_thing",gloss:"things",definition:"réalités, faits ou objets non précisés",englishDistractors:["chimneys","blankets","plums"],frenchDistractors:["cheminées","couvertures","prunes"]},
 {normalized:"chronique",lemmaKey:"chronique",headword:"chronique",partOfSpeech:"noun",senseKey:"chronique_account",gloss:"chronicle; account",definition:"récit d’événements présenté dans leur ordre",englishDistractors:nE,frenchDistractors:nF},
 {normalized:"chuchote",lemmaKey:"chuchoter",headword:"chuchoter",partOfSpeech:"verb",senseKey:"chuchoter_whisper",gloss:"whispers",definition:"parler à voix très basse",englishDistractors:["juggles","sails","coughs"],frenchDistractors:["jongle","navigue","tousse"]},
 {normalized:"civile",lemmaKey:"civil",headword:"civil",partOfSpeech:"adjective",senseKey:"civil_nonmilitary",gloss:"civil; nonmilitary",definition:"qui relève des citoyens et non de l’armée",englishDistractors:["purple","square","peppery"],frenchDistractors:["violette","carrée","poivrée"]},
];
