import type { ZolaVocabularySpec } from "./zola-authoring.js";

const nounEn: [string,string,string] = ["a saucepan", "a balcony", "a tulip"];
const nounFr: [string,string,string] = ["casserole", "balcon", "tulipe"];
const verbEn: [string,string,string] = ["to juggle", "to row", "to nap"];
const verbFr: [string,string,string] = ["jongler", "ramer", "somnoler"];
const adjEn: [string,string,string] = ["violet", "triangular", "salty"];

export const zolaVocabularyBatch04: ZolaVocabularySpec[] = [
  { normalized:"anonymes", lemmaKey:"anonyme", headword:"anonyme", partOfSpeech:"adjective", senseKey:"anonyme_unsigned", gloss:"anonymous", quizMeaning:"anonymous (plural)", definition:"dont l’auteur n’est pas identifié", englishDistractors:adjEn, frenchDistractors:["violettes","triangulaires","salées"] },
  { normalized:"ans", lemmaKey:"an", headword:"an", partOfSpeech:"noun", senseKey:"an_year", gloss:"year", quizMeaning:"years", definition:"durée de douze mois", englishDistractors:["saucepans","balconies","tulips"], frenchDistractors:["casseroles","balcons","tulipes"] },
  { normalized:"antisémite", lemmaKey:"antisemite", headword:"antisémite", partOfSpeech:"adjective", senseKey:"antisemite", gloss:"antisemitic", definition:"hostile ou préjudiciable aux personnes juives", englishDistractors:adjEn, frenchDistractors:["violet","triangulaire","salé"] },
  { normalized:"antisémitisme", lemmaKey:"antisemitisme", headword:"antisémitisme", partOfSpeech:"noun", senseKey:"antisemitisme", gloss:"antisemitism", definition:"hostilité ou préjugé dirigé contre les personnes juives", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"apothéose", lemmaKey:"apotheose", headword:"apothéose", partOfSpeech:"noun", senseKey:"apotheose_glorification", gloss:"apotheosis; glorification", definition:"célébration portée au plus haut degré de gloire", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"apparaissait", lemmaKey:"apparaitre", headword:"apparaître", partOfSpeech:"verb", senseKey:"apparaitre_seem", gloss:"to appear; seem", quizMeaning:"appeared; seemed", definition:"se montrer ou sembler d’une certaine manière", englishDistractors:["juggled","rowed","napped"], frenchDistractors:["jonglait","ramait","somnolait"] },
  { normalized:"apparaissez", lemmaKey:"apparaitre", headword:"apparaître", partOfSpeech:"verb", senseKey:"apparaitre_seem", gloss:"to appear; seem", quizMeaning:"you appear", definition:"se montrer ou sembler d’une certaine manière", englishDistractors:["you juggle","you row","you nap"], frenchDistractors:["vous jonglez","vous ramez","vous somnolez"] },
  { normalized:"apparaît", lemmaKey:"apparaitre", headword:"apparaître", partOfSpeech:"verb", senseKey:"apparaitre_seem", gloss:"to appear; seem", quizMeaning:"appears; seems", definition:"se montrer ou sembler d’une certaine manière", englishDistractors:["juggles","rows","naps"], frenchDistractors:["jongle","rame","somnole"] },
  { normalized:"appartenaient", lemmaKey:"appartenir", headword:"appartenir", partOfSpeech:"verb", senseKey:"appartenir_belong", gloss:"to belong", quizMeaning:"belonged", definition:"faire partie d’un groupe", englishDistractors:["juggled","rowed","napped"], frenchDistractors:["jonglaient","ramaient","somnolaient"] },
  { normalized:"appelle", lemmaKey:"appeler", headword:"appeler", partOfSpeech:"verb", senseKey:"appeler_name", gloss:"to call; name", quizMeaning:"calls; names", definition:"désigner par un nom", englishDistractors:["juggles","rows","naps"], frenchDistractors:["jongle","rame","somnole"] },
  { normalized:"applaudira", lemmaKey:"applaudir", headword:"applaudir", partOfSpeech:"verb", senseKey:"applaudir_approve", gloss:"to applaud; approve", quizMeaning:"will applaud", definition:"manifester vivement son approbation", englishDistractors:["will juggle","will row","will nap"], frenchDistractors:["jonglera","ramera","somnolera"] },
  { normalized:"apportée", lemmaKey:"apporter", headword:"apporter", partOfSpeech:"verb", senseKey:"apporter_bring", gloss:"to bring", quizMeaning:"brought", definition:"amener quelque chose avec soi", englishDistractors:["juggled","rowed","napped"], frenchDistractors:["jonglée","ramée","somnolée"] },
  { normalized:"apprenons", lemmaKey:"apprendre", headword:"apprendre", partOfSpeech:"verb", senseKey:"apprendre_learn", gloss:"to learn", quizMeaning:"we learn", definition:"venir à connaître une information", englishDistractors:["we juggle","we row","we nap"], frenchDistractors:["nous jonglons","nous ramons","nous somnolons"] },
  { normalized:"appuyé", lemmaKey:"appuyer", headword:"appuyer", partOfSpeech:"verb", senseKey:"s_appuyer_rely", gloss:"to rely on; lean on", quizMeaning:"relied on", definition:"prendre pour soutien", englishDistractors:["juggled","rowed","napped"], frenchDistractors:["jonglé","ramé","somnolé"] },
  { normalized:"après", lemmaKey:"apres", headword:"après", partOfSpeech:"preposition", senseKey:"apres_following", gloss:"after", definition:"à la suite de", englishDistractors:["under","despite","toward"], frenchDistractors:["sous","malgré","vers"] },
  { normalized:"arche", lemmaKey:"arche", headword:"arche", partOfSpeech:"noun", senseKey:"arche_sacred_chest", gloss:"ark; sacred chest", definition:"coffre sacré, employé ici comme image", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"armé", lemmaKey:"armer", headword:"armer", partOfSpeech:"adjective", senseKey:"arme_equipped", gloss:"armed; equipped", definition:"muni d’une arme ou d’un instrument", englishDistractors:adjEn, frenchDistractors:["violet","triangulaire","salé"] },
  { normalized:"armée", lemmaKey:"armee", headword:"armée", partOfSpeech:"noun", senseKey:"armee_military", gloss:"army", definition:"ensemble organisé des forces militaires", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"arrachait", lemmaKey:"arracher", headword:"arracher", partOfSpeech:"verb", senseKey:"arracher_tear", gloss:"to tear out", quizMeaning:"was tearing out", definition:"enlever violemment en tirant", englishDistractors:["was juggling","was rowing","was napping"], frenchDistractors:["jonglait","ramait","somnolait"] },
  { normalized:"arrêtera", lemmaKey:"arreter", headword:"arrêter", partOfSpeech:"verb", senseKey:"arreter_stop", gloss:"to stop", quizMeaning:"will stop", definition:"empêcher de continuer", englishDistractors:["will juggle","will row","will nap"], frenchDistractors:["jonglera","ramera","somnolera"] },
  { normalized:"arrête", lemmaKey:"arreter", headword:"arrêter", partOfSpeech:"verb", senseKey:"arreter_arrest", gloss:"to arrest", quizMeaning:"arrests", definition:"placer une personne en état d’arrestation", englishDistractors:["juggles","rows","naps"], frenchDistractors:["jongle","rame","somnole"] },
  { normalized:"arrêts", lemmaKey:"arret", headword:"arrêt", partOfSpeech:"noun", senseKey:"arret_judgment", gloss:"judgments; rulings", definition:"décisions rendues par une juridiction", englishDistractors:["saucepans","balconies","tulips"], frenchDistractors:["casseroles","balcons","tulipes"] },
  { normalized:"articles", lemmaKey:"article", headword:"article", partOfSpeech:"noun", senseKey:"article_law", gloss:"articles; statutory provisions", definition:"divisions numérotées d’un texte de loi", englishDistractors:["saucepans","balconies","tulips"], frenchDistractors:["casseroles","balcons","tulipes"] },
  { normalized:"artillerie", lemmaKey:"artillerie", headword:"artillerie", partOfSpeech:"noun", senseKey:"artillerie", gloss:"artillery", definition:"arme militaire utilisant des canons", englishDistractors:nounEn, frenchDistractors:nounFr },
  { normalized:"asile", lemmaKey:"asile", headword:"asile", partOfSpeech:"noun", senseKey:"asile_refuge", gloss:"refuge; sanctuary", definition:"lieu considéré comme protecteur et inviolable", englishDistractors:nounEn, frenchDistractors:nounFr },
];
