import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch31: ContentBundle["quizItems"] = [
  ...authoredSet({key:"mais",surfaceFormId:"srf_mais",senseId:"sns_mais_primary",target:"mais",meaning:"but",
    early:[["Paul est fatigué, mais il continue à travailler.",["and","because","therefore"]],["La maison est petite, mais très confortable.",["or","since","then"]],["Nina voulait venir, mais son train a été annulé.",["so","when","unless"]]],blank:["Le ciel est sombre, ___ il ne pleut pas.",["mais","et","car","donc"]],comprehension:["Marc voulait faire une randonnée, mais la pluie l’oblige à rester chez lui.","Pourquoi Marc ne part-il pas en randonnée ?",["It is raining.","He is too tired.","The trail is closed.","He lost his shoes."],"It is raining."],advanced:[["Paul connaît la réponse, mais il laisse Nina parler devant toute la classe.","Quel mot introduit une opposition entre savoir et ne pas répondre ?",["Paul","réponse","mais","Nina"]],["La route paraît longue, mais le paysage magnifique encourage les marcheurs.","Quel mot oppose la longueur de la route à l’effet positif du paysage ?",["route","mais","paysage","marcheurs"]],["Le prix est élevé, mais la qualité du manteau convainc finalement Marc.","Quel mot marque le contraste entre le prix et la qualité ?",["prix","mais","qualité","Marc"]]]}),
  ...authoredSet({key:"tard",surfaceFormId:"srf_tard",senseId:"sns_tard_primary",target:"tard",meaning:"late",
    early:[["Paul rentre tard après le concert.",["early","quickly","together"]],["Il est trop tard pour prendre le dernier train.",["soon","near","easy"]],["Nina travaille tard chaque vendredi.",["outside","silently","rarely"]]],blank:["Le train arrive trop ___ pour la correspondance.",["tard","tarde","tarder","tardif"]],comprehension:["Marc arrive tard au musée ; les portes sont déjà fermées.","Pourquoi Marc ne peut-il pas entrer dans le musée ?",["He arrived late.","He forgot his ticket.","The museum moved.","He chose the wrong entrance."],"He arrived late."],advanced:[["Paul se couche tard, éteint enfin la lampe et règle son réveil pour six heures.","Quel mot indique que Paul se couche à une heure avancée ?",["Paul","tard","lampe","réveil"]],["Le train part tard en raison de la neige, laissant les voyageurs attendre sur le quai.","Quel mot décrit le départ après l’heure prévue ?",["train","tard","neige","quai"]],["Nina répond trop tard, car le poste a déjà été proposé à un autre candidat.","Quel mot indique que sa réponse arrive après le moment utile ?",["Nina","tard","poste","candidat"]]]}),
  ...authoredSet({key:"qu_elided",surfaceFormId:"srf_qu_elided",senseId:"sns_que_conjunction",target:"qu’",meaning:"that",
    early:[["Je crois qu’il connaît déjà la réponse.",["how","what","than"]],["Nina annonce qu’elle partira demain.",["why","where","when"]],["Nous savons qu’un train arrive à midi.",["whose","which","whether"]]],blank:["Paul affirme ___il a fermé la porte.",["qu’","que","qui","dont"]],comprehension:["Le guide explique qu’il faut tourner à gauche après le pont.","Quelle direction le guide indique-t-il ?",["Turn left after the bridge.","Cross the bridge twice.","Turn right before the bridge.","Wait beside the bridge."],"Turn left after the bridge."],advanced:[["Paul confirme qu’il viendra demain, puis note l’adresse dans son agenda.","Quel élément est la forme élidée de « que » devant « il » ?",["Paul","qu’","demain","agenda"]],["Nina pense qu’elle réussira l’examen, car elle maîtrise maintenant chaque chapitre.","Quel élément introduit la proposition complétant le verbe « pense » ?",["Nina","qu’","examen","chapitre"]],["Le médecin assure qu’aucun danger ne subsiste et autorise le patient à rentrer.","Quel élément introduit ce que le médecin assure ?",["médecin","qu’","danger","patient"]]]}),
];
