import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch08: ContentBundle["quizItems"] = [
 ...authoredSet({key:"peu",surfaceFormId:"srf_peu",senseId:"sns_peu_primary",target:"peu",meaning:"little; not much",
 early:[["Il reste peu de pain dans le panier.",["a lot","enough","more"]],["Nina dort peu pendant la semaine.",["often","deeply","alone"]],["Nous avons peu de temps avant le départ.",["plenty of","exactly","no"]]],blank:["Elle boit très ___ de café le soir.",["peu","beaucoup","plusieurs","trop"]],comprehension:["Marc mange peu parce qu’il n’a pas faim.","Quelle quantité Marc mange-t-il ?",["a small amount","a large meal","nothing at all","two portions"],"a small amount"],advanced:[["Il reste peu de farine, beaucoup de sucre et assez de beurre dans la cuisine.","Quel mot indique une petite quantité de farine ?",["peu","beaucoup","assez","cuisine"]],["Léa parle peu, écoute beaucoup et répond toujours avec précision.","Quel mot indique que Léa ne parle pas beaucoup ?",["peu","écoute","beaucoup","toujours"]],["Le rapport contient peu d’erreurs, plusieurs tableaux et beaucoup de notes utiles.","Quel mot exprime la faible quantité d’erreurs ?",["rapport","peu","plusieurs","beaucoup"]]]}),
 ...authoredSet({key:"pres",surfaceFormId:"srf_pres",senseId:"sns_pres_primary",target:"près",meaning:"near",
 early:[["La pharmacie se trouve près de la gare.",["far from","inside","above"]],["Paul habite près du parc municipal.",["beyond","under","across"]],["Le chien attend près de son maître.",["behind","without","toward"]]],blank:["Notre hôtel est ___ de la plage.",["près","loin","autour","dessus"]],comprehension:["Le vélo est garé près de l’entrée principale.","Où le vélo est-il garé ?",["near the main entrance","behind the station","inside the garage","far from the building"],"near the main entrance"],advanced:[["La boulangerie est près de l’école, mais la banque se trouve loin du quartier.","Quel mot indique la proximité de la boulangerie ?",["boulangerie","près","banque","loin"]],["Le chat reste près du radiateur tandis que le chien dort sous la table.","Quel mot situe le chat à proximité du radiateur ?",["chat","près","chien","sous"]],["Les secours installent leur poste près du pont, surveillent la rivière et ferment la route.","Quel mot indique la proximité entre le poste et le pont ?",["secours","près","rivière","route"]]]}),
 ...authoredSet({key:"ce",surfaceFormId:"srf_ce",senseId:"sns_ce_primary",target:"ce",meaning:"this; that",
 early:[["Je préfère ce livre à l’autre.",["the","a","every"]],["Ce train part dans cinq minutes.",["some","my","no"]],["Regarde ce tableau près de la fenêtre.",["these","our","each"]]],blank:["___ manteau noir appartient à Paul.",["ce","cet","cette","ces"]],comprehension:["Ce bus conduit les voyageurs directement au musée.","Quel moyen de transport conduit les voyageurs ?",["this bus","a train","a taxi","their car"],"this bus"],advanced:[["Dans la rue, ce voisin prend un vélo, cette voisine marche et les enfants attendent le bus.","Quel mot détermine « voisin » au masculin singulier ?",["ce","vélo","cette","enfants"]],["Dans ce dossier, chaque page porte un numéro et les annexes suivent le rapport.","Quel mot désigne précisément le dossier mentionné ?",["ce","chaque","numéro","annexes"]],["Le juge examine ce document, compare les signatures et consulte cette copie.","Quel mot est le déterminant démonstratif masculin devant « document » ?",["juge","ce","signatures","cette"]]]}),
];
