import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch26: ContentBundle["quizItems"] = [
  ...authoredSet({key:"vit",surfaceFormId:"srf_vit",senseId:"sns_vivre_primary",target:"vit",meaning:"lives",
    early:[["Nina vit dans un village près de Lyon.",["works","travels","waits"]],["Ce poisson vit seulement en eau douce.",["swims","feeds","hides"]],["Paul vit avec sa famille dans une petite maison.",["stays","speaks","leaves"]]],blank:["Le hibou ___ dans ce vieux chêne.",["vit","vis","vivent","vivre"]],comprehension:["Cette abeille vit dans une ruche installée au fond du jardin.","Où se trouve l’habitat de l’abeille ?",["In a hive in the garden.","Under a stone by the road.","Inside the house.","Near a river."],"In a hive in the garden."],advanced:[["Le panda vit dans cette réserve, mange du bambou et dort sous les arbres.","Quel mot indique que la réserve est le milieu de vie du panda ?",["panda","vit","réserve","bambou"]],["Marc vit modestement, cultive son potager et répare lui-même sa maison.","Quel mot désigne le fait que Marc mène son existence de cette manière ?",["Marc","vit","potager","maison"]],["Une colonie de phoques vit sur cette île, se nourrit de poissons et évite les bateaux.","Quel mot exprime que la colonie habite sur l’île ?",["colonie","vit","île","bateaux"]]]}),
  ...authoredSet({key:"aux",surfaceFormId:"srf_aux",senseId:"sns_aux_primary",target:"aux",meaning:"at the",
    early:[["Nous attendons aux portes du théâtre.",["inside the","behind the","far from the"]],["Nina assiste aux réunions du conseil.",["between the","outside the","before the"]],["Les promeneurs restent aux abords du village.",["across the","above the","without the"]]],blank:["Les voyageurs patientent ___ guichets de la gare.",["aux","au","à la","des"]],comprehension:["Les billets sont vendus aux guichets situés près de l’entrée principale.","Où peut-on acheter les billets ?",["At the ticket windows.","On the train.","Inside the café.","At the parking lot."],"At the ticket windows."],advanced:[["Aux portes du stade, les agents contrôlent les billets et dirigent la foule.","Quel mot est la contraction de « à les » devant « portes » ?",["aux","portes","agents","billets"]],["Paul participe aux ateliers, consulte les documents et échange avec les formateurs.","Quel mot contracte la préposition « à » et l’article pluriel « les » ?",["Paul","aux","documents","formateurs"]],["Les élèves répondent aux questions, relisent le texte et corrigent leurs erreurs.","Quel mot combine « à » et « les » devant le nom pluriel « questions » ?",["élèves","aux","questions","erreurs"]]]}),
  ...authoredSet({key:"depens",surfaceFormId:"srf_depens",senseId:"sns_depens_primary",target:"dépens",meaning:"expense",
    early:[["Il réussit aux dépens de son ancien partenaire.",["benefit","permission","advice"]],["La ville s’étend aux dépens des terres agricoles.",["protection","center","border"]],["Paul plaisante souvent aux dépens de son frère.",["request","surprise","praise"]]],blank:["L’entreprise augmente ses profits aux ___ de la qualité.",["dépens","dépenses","coûts","avantages"]],comprehension:["Le projet avance rapidement, mais aux dépens de la sécurité des ouvriers.","Quel aspect est sacrifié pour accélérer le projet ?",["Worker safety.","The project budget.","The delivery date.","Customer demand."],"Worker safety."],advanced:[["Le promoteur construit aux dépens du parc, abat les arbres et réduit les espaces publics.","Quel mot appartient à l’expression indiquant que le parc subit le préjudice ?",["promoteur","dépens","parc","arbres"]],["Nina gagne du temps aux dépens de la précision, termine le rapport et oublie plusieurs détails.","Quel mot complète l’expression qui indique le sacrifice de la précision ?",["Nina","dépens","précision","rapport"]],["La production augmente aux dépens du repos, épuise les équipes et provoque des erreurs.","Quel mot fait partie de l’expression signifiant que le repos est sacrifié ?",["production","dépens","repos","équipes"]]]}),
];
