import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch21: ContentBundle["quizItems"] = [
 ...authoredSet({key:"il",surfaceFormId:"srf_il",senseId:"sns_il_primary",target:"il",meaning:"he; it",
 early:[["Paul est fatigué, mais il continue à marcher.",["she","we","they"]],["Le train arrive et il s’arrête au quai.",["you","I","one"]],["Marc prend son sac parce qu’il part demain.",["she","they","we"]]],blank:["Paul ferme la porte puis ___ descend l’escalier.",["il","elle","ils","on"]],comprehension:["Marc trouve un portefeuille et il le remet au gardien.","Que fait Marc du portefeuille ?",["He gives it to the caretaker.","He keeps it.","He leaves it outside.","He throws it away."],"He gives it to the caretaker."],advanced:[["Paul prend son manteau, il ouvre la porte et Nina attend dehors.","Quel mot reprend le nom Paul comme sujet ?",["Paul","il","porte","Nina"]],["Le moteur chauffe, mais il fonctionne encore tandis que le conducteur ralentit.","Quel mot reprend « le moteur » ?",["moteur","il","conducteur","encore"]],["Marc lit le contrat ; il consulte ensuite son avocat avant de signer.","Quel mot remplace Marc comme sujet de « consulte » ?",["Marc","il","contrat","avocat"]]]}),
 ...authoredSet({key:"ouvre",surfaceFormId:"srf_ouvre",senseId:"sns_ouvrir_primary",target:"ouvre",meaning:"opens",
 early:[["Nina ouvre la fenêtre chaque matin.",["closes","cleans","breaks"]],["Paul ouvre son sac pour chercher la clé.",["carries","buys","loses"]],["Le magasin ouvre à neuf heures.",["moves","ends","waits"]]],blank:["Marc ___ doucement la vieille porte.",["ouvre","ouvres","ouvrent","ouvrir"]],comprehension:["Léa ouvre la boîte et découvre une montre.","Que découvre Léa ?",["a watch","a letter","a ring","a key"],"a watch"],advanced:[["Paul ouvre le livre, lit la première page et pose son crayon sur la table.","Quel mot décrit l’action faite au livre avant la lecture ?",["Paul","ouvre","page","crayon"]],["La gardienne ouvre le portail, salue les visiteurs et vérifie leurs billets.","Quel mot indique qu’elle rend le passage accessible ?",["gardienne","ouvre","visiteurs","billets"]],["Le président ouvre la séance, présente le programme et donne la parole au rapporteur.","Quel mot signifie qu’il commence officiellement la séance ?",["président","ouvre","programme","rapporteur"]]]}),
 ...authoredSet({key:"large",surfaceFormId:"srf_large",senseId:"sns_large_primary",target:"large",meaning:"wide",
 early:[["Une large avenue traverse le centre-ville.",["narrow","short","empty"]],["Paul porte un large chapeau de paille.",["tiny","heavy","dark"]],["La rivière devient très large près de la mer.",["deep","cold","rapid"]]],blank:["Un ___ pont relie les deux quartiers.",["large","larges","longue","étroit"]],comprehension:["Une large fenêtre éclaire toute la cuisine.","Pourquoi la cuisine reçoit-elle beaucoup de lumière ?",["The window is wide.","The door is open.","The walls are white.","A lamp is on."],"The window is wide."],advanced:[["Une large route longe la rivière, tandis qu’un étroit sentier monte vers le village.","Quel mot indique la grande largeur de la route ?",["large","rivière","étroit","village"]],["Le peintre utilise une large brosse, un petit couteau et plusieurs couleurs vives.","Quel mot décrit la grande dimension de la brosse d’un côté à l’autre ?",["peintre","large","couteau","couleurs"]],["La réforme obtient une large majorité, malgré quelques opposants et plusieurs abstentions.","Quel mot indique que la majorité est importante et étendue ?",["réforme","large","opposants","abstentions"]]]}),
];
