import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch09: ContentBundle["quizItems"] = [
 ...authoredSet({key:"langage",surfaceFormId:"srf_langage",senseId:"sns_langage_primary",target:"langage",meaning:"speech; manner of speaking",
 early:[["Son langage poli rassure les visiteurs.",["silence","gesture","clothing"]],["Le langage du diplomate reste très prudent.",["journey","appearance","decision"]],["Ce langage violent choque toute la salle.",["music","painting","movement"]]],blank:["Le professeur emploie un ___ simple pour expliquer la règle.",["langage","langages","discours","silence"]],comprehension:["Le médecin adopte un langage clair avec le patient.","Comment le médecin s’exprime-t-il ?",["clearly","angrily","silently","carelessly"],"clearly"],advanced:[["Son langage demeure courtois, mais son geste brusque surprend le public.","Quel mot désigne sa manière de s’exprimer ?",["langage","geste","public","courtois"]],["Le langage du contrat est précis ; la mise en page et la signature sont également soignées.","Quel mot désigne les mots et formulations employés dans le contrat ?",["langage","contrat","page","signature"]],["Malgré le débat, la ministre conserve un langage mesuré, écoute les critiques et répond aux journalistes.","Quel mot nomme ici la manière dont la ministre formule ses propos ?",["débat","langage","critiques","journalistes"]]]}),
 ...authoredSet({key:"he",surfaceFormId:"srf_he",senseId:"sns_he_primary",target:"Hé",meaning:"hey",
 early:[["« Hé, Paul ! Attends-moi ! » crie Léa.",["goodbye","please","thanks"]],["« Hé ! Regarde ce magnifique bateau ! »",["welcome","sorry","certainly"]],["« Hé, vous là-bas, la route est fermée ! »",["perhaps","never","quietly"]]],blank:["« ___, Luc ! Tu as oublié ton sac ! »",["Hé","Ohé","Bonjour","Merci"]],comprehension:["« Hé, Nina ! Le bus arrive ! » appelle Marc.","Pourquoi Marc interpelle-t-il Nina ?",["The bus is arriving.","Dinner is ready.","Her bag is missing.","The store is closed."],"The bus is arriving."],advanced:[["« Hé, Thomas ! » crie Léa, tandis que Paul ferme la porte et prend son manteau.","Quel mot sert à attirer vivement l’attention de Thomas ?",["Hé","Léa","porte","manteau"]],["« Hé ! Le chien traverse la rue ! » avertit le cycliste près du carrefour.","Quel mot constitue l’interjection d’appel ?",["Hé","chien","cycliste","carrefour"]],["Dans la foule, une voix lance « Hé, monsieur ! », puis le vendeur lève la main et montre un portefeuille.","Quel mot appelle directement la personne ?",["foule","Hé","vendeur","portefeuille"]]]}),
 ...authoredSet({key:"bonjour",surfaceFormId:"srf_bonjour",senseId:"sns_bonjour_primary",target:"bonjour",meaning:"hello; good day",
 early:[["Marie dit bonjour à ses voisins chaque matin.",["goodbye","thank you","good night"]],["« Bonjour, je viens pour mon rendez-vous. »",["sorry","please","welcome back"]],["Le vendeur nous accueille avec un chaleureux bonjour.",["warning","question","farewell"]]],blank:["Paul entre dans le bureau et dit : « ___, Madame. »",["bonjour","bonsoir","adieu","merci"]],comprehension:["Nina dit bonjour au gardien en entrant dans l’immeuble.","Qui Nina salue-t-elle ?",["the caretaker","a neighbor","the mail carrier","her brother"],"the caretaker"],advanced:[["Le matin, Luc dit bonjour au boulanger, achète du pain et quitte la boutique.","Quel mot constitue la salutation de Luc ?",["matin","bonjour","pain","boutique"]],["À l’accueil, la secrétaire sourit, prononce bonjour et demande le nom du visiteur.","Quel mot est la formule de salutation ?",["accueil","secrétaire","bonjour","visiteur"]],["En entrant dans la réunion, la directrice adresse un bonjour général, ouvre son dossier et présente le programme.","Quel mot nomme la salutation adressée au groupe ?",["réunion","bonjour","dossier","programme"]]]}),
];
