import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch32: ContentBundle["quizItems"] = [
  ...authoredSet({key:"on",surfaceFormId:"srf_on",senseId:"sns_on_primary",target:"on",meaning:"one; people",
    early:[["En France, on mange souvent du pain avec le repas.",["I","you","he"]],["On doit montrer son billet avant d’entrer.",["she","we","they"]],["Dans ce village, on connaît bien cette vieille légende.",["it","you","he"]]],blank:["Ici, ___ ferme les magasins à dix-neuf heures.",["on","il","nous","ils"]],comprehension:["Dans cette école, on laisse les vélos près de l’entrée.","Où les gens déposent-ils généralement leurs vélos ?",["Near the entrance.","Inside the classrooms.","Behind the library.","At the train station."],"Near the entrance."],advanced:[["En hiver, on ferme la route, les habitants utilisent le train et les touristes restent au village.","Quel mot désigne les gens en général sans les nommer précisément ?",["hiver","on","habitants","touristes"]],["On raconte cette histoire aux enfants, puis les parents répondent à leurs questions.","Quel mot sert de sujet indéfini au verbe « raconte » ?",["on","histoire","enfants","parents"]],["Dans ce musée, on protège les tableaux, les gardiens surveillent les salles et le public suit les règles.","Quel mot représente les personnes qui protègent les tableaux sans les identifier ?",["musée","on","gardiens","public"]]]}),
  ...authoredSet({key:"y_that_way",surfaceFormId:"srf_y",senseId:"sns_y_primary",target:"y",meaning:"by it; that way",
    early:[["Le mensonge est évident ; Paul ne s’y laisse pas prendre.",["there","from it","with him"]],["Cette ruse paraît habile, mais Nina ne s’y fera pas prendre.",["at home","to them","from there"]],["Le piège a déjà fonctionné, pourtant Marc ne s’y laissera pas prendre.",["nearby","inside","with her"]]],blank:["Ce piège est connu ; il ne s’___ laissera pas prendre.",["y","en","le","lui"]],comprehension:["La fausse annonce promet un prix, mais Paul reconnaît le piège et ne s’y laisse pas prendre.","Pourquoi Paul n’envoie-t-il pas d’argent ?",["He recognizes the trick.","He has already received the prize.","He cannot read the announcement.","He has lost his wallet."],"He recognizes the trick."],advanced:[["Cette fraude paraît crédible, mais Nina ne s’y laisse pas prendre et prévient ses collègues.","Quel mot reprend la fraude comme moyen par lequel Nina pourrait être trompée ?",["fraude","Nina","y","collègues"]],["Le piège semblait convaincant ; Paul ne s’y fit pourtant pas prendre et conserva son argent.","Quel mot renvoie au piège dans l’expression « se faire prendre » ?",["piège","Paul","y","argent"]],["Marc connaît désormais cette ruse, ne s’y laissera plus prendre et avertira ses amis.","Quel mot représente la ruse à laquelle Marc ne succombera pas ?",["Marc","ruse","y","amis"]]]}),
  ...authoredSet({key:"prendrait",surfaceFormId:"srf_prendrait",senseId:"sns_prendre_primary",target:"prendrait",meaning:"would catch; would trick",
    early:[["Avec un meilleur piège, le chasseur prendrait le renard.",["would release","would follow","would feed"]],["Une ruse plus subtile prendrait peut-être Paul.",["would protect","would awaken","would guide"]],["En surveillant cette porte, le policier prendrait le voleur sur le fait.",["would warn","would miss","would question"]]],blank:["Avec ce filet solide, le pêcheur ___ facilement le poisson.",["prendrait","prendra","prenait","prendre"]],comprehension:["Sans l’avertissement de Nina, ce faux message prendrait Paul au piège.","Qu’est-ce qui empêche Paul d’être trompé ?",["Nina’s warning.","A broken telephone.","The message’s disappearance.","Paul’s lack of money."],"Nina’s warning."],advanced:[["Un appât plus réaliste prendrait le poisson, mais celui-ci évite le crochet brillant.","Quel mot exprime au conditionnel l’action d’attraper le poisson ?",["appât","prendrait","poisson","crochet"]],["Cette histoire mensongère prendrait un lecteur inattentif, tandis qu’un expert remarquerait les erreurs.","Quel mot indique que l’histoire pourrait tromper le lecteur ?",["histoire","prendrait","lecteur","expert"]],["Avec une caméra cachée, la police prendrait le voleur, réunirait les preuves et retrouverait les objets.","Quel mot désigne l’arrestation possible du voleur ?",["caméra","police","prendrait","preuves"]]]}),
];
