import type { ContentBundle } from "../../domain/model.js";

export const corbeauQuizBatch03: ContentBundle["quizItems"] = [
  { id: "qiz_en_in_01", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 1, format: "meaning_choice", contextFrench: "Les enfants restent en classe pendant la pluie.", targetText: "en", prompt: "Meaning", choicesEnglish: ["in", "outside", "toward", "behind"], correctAnswer: "in" },
  { id: "qiz_en_in_02", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 2, format: "meaning_choice", contextFrench: "Ce poisson vit en eau douce.", targetText: "en", prompt: "Meaning", choicesEnglish: ["in", "above", "without", "across"], correctAnswer: "in" },
  { id: "qiz_en_in_03", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 3, format: "meaning_choice", contextFrench: "Le village paraît calme en hiver.", targetText: "en", prompt: "Meaning", choicesEnglish: ["in", "before", "despite", "near"], correctAnswer: "in" },
  { id: "qiz_en_in_04", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 4, format: "surface_completion", contextFrench: "Toute la bibliothèque travaille ___ silence.", choicesFrench: ["en", "sur", "vers", "chez"], correctAnswer: "en" },
  { id: "qiz_en_in_05", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 5, format: "comprehension_choice", contextFrench: "Lucie habite en Belgique depuis deux ans.", targetText: "en", promptFrench: "Dans quel pays Lucie habite-t-elle ?", choicesEnglish: ["Belgium", "France", "Canada", "Switzerland"], correctAnswer: "Belgium" },
  { id: "qiz_en_in_06", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 6, format: "target_identification", contextFrench: "En été, Marc travaille dans un café près du port.", promptFrench: "Quel mot introduit la saison pendant laquelle Marc travaille ?", choicesFrench: ["En", "dans", "café", "port"], correctAnswer: "En" },
  { id: "qiz_en_in_07", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 7, format: "target_identification", contextFrench: "La famille vit en ville, mais passe chaque dimanche dans la campagne voisine.", promptFrench: "Quel mot introduit le lieu général où vit la famille ?", choicesFrench: ["famille", "en", "dimanche", "dans"], correctAnswer: "en" },
  { id: "qiz_en_in_08", surfaceFormId: "srf_en", senseId: "sns_en_in", masteryLevel: 8, format: "target_identification", contextFrench: "En période de sécheresse, la rivière baisse et les fermiers surveillent leurs puits.", promptFrench: "Quel mot introduit la période pendant laquelle la rivière baisse ?", choicesFrench: ["En", "sécheresse", "rivière", "puits"], correctAnswer: "En" },

  { id: "qiz_en_it_01", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 1, format: "meaning_choice", contextFrench: "Elle parle de ce film et elle en connaît chaque scène.", targetText: "en", prompt: "Meaning", choicesEnglish: ["of it", "to him", "there", "herself"], correctAnswer: "of it" },
  { id: "qiz_en_it_02", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 2, format: "meaning_choice", contextFrench: "Nous avons du pain et nous en mangeons souvent.", targetText: "en", prompt: "Meaning", choicesEnglish: ["some of it", "with them", "at home", "for her"], correctAnswer: "some of it" },
  { id: "qiz_en_it_03", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 3, format: "meaning_choice", contextFrench: "Paul revient de Lyon et en garde un bon souvenir.", targetText: "en", prompt: "Meaning", choicesEnglish: ["of it", "into it", "beside it", "against it"], correctAnswer: "of it" },
  { id: "qiz_en_it_04", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 4, format: "surface_completion", contextFrench: "Maya achète des fraises et ___ mange quelques-unes.", choicesFrench: ["en", "les", "y", "lui"], correctAnswer: "en" },
  { id: "qiz_en_it_05", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 5, format: "comprehension_choice", contextFrench: "Paul a préparé du pain et il en donne à sa voisine.", targetText: "en", promptFrench: "Que Paul donne-t-il à sa voisine ?", choicesEnglish: ["some bread", "a plate", "some cheese", "a recipe"], correctAnswer: "some bread" },
  { id: "qiz_en_it_06", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 6, format: "target_identification", contextFrench: "Elle parle de ce livre ; elle en admire surtout le style.", promptFrench: "Quel mot remplace ici « de ce livre » ?", choicesFrench: ["Elle", "de", "en", "livre"], correctAnswer: "en" },
  { id: "qiz_en_it_07", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 7, format: "target_identification", contextFrench: "Des cerises remplissent le panier ; Luc en choisit trois et laisse les autres.", promptFrench: "Quel mot reprend « des cerises » sans les répéter ?", choicesFrench: ["cerises", "panier", "en", "autres"], correctAnswer: "en" },
  { id: "qiz_en_it_08", surfaceFormId: "srf_en", senseId: "sns_en_it", masteryLevel: 8, format: "target_identification", contextFrench: "Le comité discute du projet ; plusieurs membres en contestent le coût, mais tous proposent une solution.", promptFrench: "Quel mot reprend le complément introduit par « du » ?", choicesFrench: ["comité", "projet", "en", "solution"], correctAnswer: "en" },

  { id: "qiz_son_possessive_01", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 1, format: "meaning_choice", contextFrench: "Julien cherche son manteau noir.", targetText: "son", prompt: "Meaning", choicesEnglish: ["his", "my", "your", "their"], correctAnswer: "his" },
  { id: "qiz_son_possessive_02", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 2, format: "meaning_choice", contextFrench: "Claire accompagne son frère à la gare.", targetText: "son", prompt: "Meaning", choicesEnglish: ["her", "our", "your", "their"], correctAnswer: "her" },
  { id: "qiz_son_possessive_03", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 3, format: "meaning_choice", contextFrench: "Le chien retrouve son jouet sous le canapé.", targetText: "son", prompt: "Meaning", choicesEnglish: ["its", "your", "my", "our"], correctAnswer: "its" },
  { id: "qiz_son_possessive_04", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 4, format: "surface_completion", contextFrench: "Paul range ___ livre dans son sac.", choicesFrench: ["son", "sa", "ses", "leur"], correctAnswer: "son" },
  { id: "qiz_son_possessive_05", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 5, format: "comprehension_choice", contextFrench: "Émilie prête son vélo à sa voisine.", targetText: "son", promptFrench: "À qui appartient le vélo ?", choicesEnglish: ["Émilie", "the neighbor", "both women", "an unknown owner"], correctAnswer: "Émilie" },
  { id: "qiz_son_possessive_06", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 6, format: "target_identification", contextFrench: "Hugo ouvre son carnet, prend un crayon et montre la page à Marie.", promptFrench: "Quel mot indique que le carnet appartient à Hugo ?", choicesFrench: ["Hugo", "son", "crayon", "Marie"], correctAnswer: "son" },
  { id: "qiz_son_possessive_07", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 7, format: "target_identification", contextFrench: "La musicienne accorde son violon pendant que le pianiste ferme le couvercle.", promptFrench: "Quel mot relie le violon à la musicienne qui le possède ?", choicesFrench: ["musicienne", "son", "pianiste", "couvercle"], correctAnswer: "son" },
  { id: "qiz_son_possessive_08", surfaceFormId: "srf_son", senseId: "sns_son_primary", masteryLevel: 8, format: "target_identification", contextFrench: "Avant l’audience, l’avocate relit son dossier, consulte une note et appelle le témoin.", promptFrench: "Quel mot marque la possession du dossier par l’avocate ?", choicesFrench: ["audience", "son", "note", "témoin"], correctAnswer: "son" },
];
