import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch15: ContentBundle["quizItems"] = [
 ...authoredSet({key:"plumage",surfaceFormId:"srf_plumage",senseId:"sns_plumage_primary",target:"plumage",meaning:"plumage; feathers",
 early:[["Le plumage du paon brille au soleil.",["birdsong","beak","nest"]],["Cet oiseau possède un plumage entièrement blanc.",["claw","wingbeat","call"]],["Le plumage épais protège le canard du froid.",["flight","tailbone","shadow"]]],blank:["Le magnifique ___ du perroquet attire les regards.",["plumage","ramage","feuillage","pelage"]],comprehension:["Le plumage brun permet à l’oiseau de se cacher dans les branches.","Qu’est-ce qui aide l’oiseau à se cacher ?",["its brown feathers","its loud song","its long beak","its large nest"],"its brown feathers"],advanced:[["Le plumage du cygne est blanc, son bec est orange et son chant reste discret.","Quel mot désigne l’ensemble des plumes du cygne ?",["plumage","bec","chant","cygne"]],["L’ornithologue examine le plumage, mesure l’aile et photographie le nid.","Quel mot nomme la couverture de plumes de l’oiseau ?",["ornithologue","plumage","aile","nid"]],["Après la mue, le plumage devient plus sombre, mais les pattes et le bec ne changent pas.","Quel mot désigne les plumes dont la couleur change ?",["mue","plumage","pattes","bec"]]]}),
 ...authoredSet({key:"le",surfaceFormId:"srf_le",senseId:"sns_le_primary",target:"le",meaning:"the",
 early:[["Le train arrive à huit heures.",["a","this","one"]],["Nina ferme le portail avant la nuit.",["a","her","every"]],["Nous suivons le chemin vers le village.",["this","some","our"]]],blank:["Paul ouvre ___ livre déjà posé sur la table.",["le","un","ce","son"]],comprehension:["Le médecin appelle le patient suivant.","Qui appelle le patient ?",["the doctor","a nurse","the receptionist","another patient"],"the doctor"],advanced:[["Dans le jardin, le chien poursuit un ballon et ce chat dort sous son arbre.","Quel mot est l’article défini devant « chien » ?",["le","un","ce","son"]],["Nina prend le dossier, consulte un message et range ce document dans son sac.","Quel mot détermine « dossier » comme déjà identifié ?",["le","un","ce","son"]],["Après le vote, le président signe un décret, remercie ce ministre et rejoint son bureau.","Quel mot est l’article défini masculin devant « président » ?",["le","un","ce","son"]]]}),
 ...authoredSet({key:"des",surfaceFormId:"srf_des",senseId:"sns_des_primary",target:"des",meaning:"of the",
 early:[["La couleur des murs change avec la lumière.",["to the","some","from a"]],["Le chant des oiseaux réveille Paul.",["at the","a few","without the"]],["Nous suivons le conseil des médecins.",["toward the","among","with some"]]],blank:["Le toit ___ maisons est couvert de neige.",["des","du","de la","aux"]],comprehension:["Le directeur écoute les questions des étudiants.","À qui appartiennent les questions ?",["the students","the teachers","the parents","the visitors"],"the students"],advanced:[["La porte des bureaux est fermée, mais le hall et la cour restent ouverts.","Quel mot relie la porte aux bureaux ?",["porte","des","hall","cour"]],["Le maire présente le projet des architectes, puis consulte le budget de la ville.","Quel mot indique que le projet vient des architectes ?",["maire","des","budget","ville"]],["L’avocat analyse les déclarations des témoins, compare les dates et prépare sa réponse.","Quel mot introduit les personnes auxquelles appartiennent les déclarations ?",["avocat","des","dates","réponse"]]]}),
];
