import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch10: ContentBundle["quizItems"] = [
 ...authoredSet({key:"du",surfaceFormId:"srf_du",senseId:"sns_du_primary",target:"du",meaning:"of the; from the",
 early:[["La porte du garage reste ouverte.",["to the","with the","under the"]],["Il revient du marché avec des pommes.",["toward the","inside the","beside the"]],["Nous admirons la vue du sommet.",["at the","without the","behind the"]]],blank:["La couleur ___ mur change avec la lumière.",["du","de la","des","au"]],comprehension:["Luc revient du village avant la nuit.","D’où Luc revient-il ?",["from the village","from the city","from the station","from the forest"],"from the village"],advanced:[["Le toit du musée est rouge, mais la porte du jardin est verte.","Quel mot unit « toit » au musée ?",["toit","du","porte","jardin"]],["Le directeur sort du bureau, traverse le couloir et rejoint la salle.","Quel mot indique le lieu dont sort le directeur ?",["directeur","du","couloir","salle"]],["La décision du tribunal modifie le calendrier et surprend les avocats.","Quel mot introduit le tribunal auquel appartient la décision ?",["décision","du","calendrier","avocats"]]]}),
 ...authoredSet({key:"que_excl",surfaceFormId:"srf_que",senseId:"sns_que_exclamative",target:"Que",meaning:"how",
 early:[["Que cette vallée est belle au printemps !",["that","what","because"]],["Que vous chantez bien ce soir !",["when","if","which"]],["Que ce gâteau semble délicieux !",["where","while","whose"]]],blank:["___ cette lumière est douce !",["Que","Quand","Si","Car"]],comprehension:["Que cette valise est lourde !", "Quelle impression la personne exprime-t-elle ?",["The suitcase is very heavy.","The suitcase is empty.","The suitcase is missing.","The suitcase is new."],"The suitcase is very heavy."],advanced:[["Que ce jardin est calme ! Les oiseaux dorment et la fontaine reste silencieuse.","Quel mot introduit l’exclamation sur le calme du jardin ?",["Que","jardin","oiseaux","fontaine"]],["Que vous êtes patient ! Votre collègue proteste, mais vous gardez le sourire.","Quel mot renforce ici l’exclamation sur la patience ?",["Que","collègue","mais","sourire"]],["Que cette solution paraît simple ! Le comité relit pourtant le rapport avec prudence.","Quel mot ouvre l’exclamation exprimant un degré élevé ?",["Que","solution","comité","rapport"]]]}),
 ...authoredSet({key:"vous",surfaceFormId:"srf_vous",senseId:"sns_vous_primary",target:"vous",meaning:"you",
 early:[["Madame, vous pouvez entrer maintenant.",["we","they","I"]],["Est-ce que vous connaissez cette rue ?",["he","she","one"]],["Paul et Nina, vous partez demain matin.",["they","we","it"]]],blank:["Monsieur, ___ avez oublié votre reçu.",["vous","nous","ils","tu"]],comprehension:["Vous recevrez le document par courrier, Madame.","Comment Madame recevra-t-elle le document ?",["by mail","by hand","by email","at the office"],"by mail"],advanced:[["Madame, vous signez ici ; nous vérifierons ensuite le dossier.","Quel mot désigne poliment la personne à qui l’on parle ?",["Madame","vous","nous","dossier"]],["Paul et Léa, vous préparez la salle pendant que les invités attendent dehors.","Quel mot reprend ensemble Paul et Léa comme destinataires de l’ordre ?",["Paul","vous","invités","dehors"]],["Si vous acceptez la proposition, le comité modifiera le contrat et contactera votre avocat.","Quel mot désigne le destinataire de cette condition ?",["vous","proposition","comité","avocat"]]]}),
];
