import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch17: ContentBundle["quizItems"] = [
 ...authoredSet({key:"bois",surfaceFormId:"srf_bois",senseId:"sns_bois_primary",target:"bois",meaning:"woods",
 early:[["Nous marchons dans les bois après la pluie.",["fields","streets","gardens"]],["Les cerfs se cachent au fond des bois.",["caves","mountains","farms"]],["Une petite rivière traverse les bois.",["desert","village","meadow"]]],blank:["Les promeneurs suivent un sentier à travers les ___.",["bois","boisage","forêt","arbres"]],comprehension:["Paul cherche des champignons dans les bois voisins.","Que Paul cherche-t-il ?",["mushrooms","berries","firewood","a lost dog"],"mushrooms"],advanced:[["Dans les bois, le chevreuil traverse un sentier, longe la rivière et disparaît derrière les arbres.","Quel mot désigne l’étendue couverte d’arbres ?",["bois","sentier","rivière","arbres"]],["Les bois entourent le village, tandis que les champs s’étendent près de la route.","Quel mot nomme la zone forestière autour du village ?",["bois","village","champs","route"]],["Après l’incendie, les gardes inspectent les bois, protègent la faune et ferment plusieurs chemins.","Quel mot désigne le territoire forestier inspecté ?",["incendie","bois","faune","chemins"]]]}),
 ...authoredSet({key:"mots",surfaceFormId:"srf_mots",senseId:"sns_mot_primary",target:"mots",meaning:"words",
 early:[["Elle écrit quelques mots sur une carte.",["numbers","pictures","lines"]],["Ses mots rassurent immédiatement le patient.",["gestures","clothes","footsteps"]],["Je ne comprends pas tous les mots de ce texte.",["pages","letters","titles"]]],blank:["Le dictionnaire explique les ___ difficiles.",["mots","mot","phrases","lettres"]],comprehension:["Paul choisit des mots simples pour expliquer son idée.","Comment Paul explique-t-il son idée ?",["with simple words","with a drawing","with technical terms","without speaking"],"with simple words"],advanced:[["Les mots du poème sont courts, les phrases restent simples et le rythme paraît régulier.","Quel mot désigne les unités écrites qui composent les phrases ?",["mots","poème","phrases","rythme"]],["Nina cherche ses mots, consulte une note et reprend enfin son discours.","Quel mot désigne les éléments de langage qu’elle cherche ?",["Nina","mots","note","discours"]],["Le traducteur compare les mots, vérifie le sens et corrige la ponctuation du document.","Quel mot nomme les éléments lexicaux comparés ?",["traducteur","mots","sens","document"]]]}),
 ...authoredSet({key:"ne",surfaceFormId:"srf_ne",senseId:"sns_ne_primary",target:"ne",meaning:"not",
 early:[["Paul ne mange pas de viande.",["always","already","also"]],["Je ne connais pas cette personne.",["often","still","perhaps"]],["Nous ne partirons jamais sans vous.",["soon","together","outside"]]],blank:["Il ___ comprend pas la question.",["ne","se","le","me"]],comprehension:["Nina ne vient pas au bureau aujourd’hui.","Nina vient-elle au bureau ?",["No, she does not.","Yes, this morning.","Yes, this afternoon.","The sentence does not say."],"No, she does not."],advanced:[["Paul ne dort pas, mais son frère lit encore près de la fenêtre.","Quel mot commence la négation du verbe « dort » ?",["Paul","ne","mais","encore"]],["Le train ne part jamais avant huit heures, tandis que le bus quitte déjà la gare.","Quel mot participe à la négation de « part » ?",["train","ne","jamais","bus"]],["Le comité ne publiera plus ce rapport, mais conservera les archives et la copie signée.","Quel mot ouvre la construction négative autour de « publiera » ?",["comité","ne","rapport","archives"]]]}),
];
