import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch13: ContentBundle["quizItems"] = [
 ...authoredSet({key:"mentir",surfaceFormId:"srf_mentir",senseId:"sns_mentir_primary",target:"mentir",meaning:"to lie",
 early:[["Il refuse de mentir à ses parents.",["to laugh","to leave","to listen"]],["Mentir détruit rapidement la confiance.",["To forgive","To wait","To choose"]],["Elle préfère avouer son erreur plutôt que mentir.",["to forget","to promise","to complain"]]],blank:["Paul invente une fausse histoire pour ___.",["mentir","menti","mens","menteur"]],comprehension:["Nina ne veut pas mentir au professeur sur son devoir.","Que Nina refuse-t-elle de faire ?",["tell a lie","show her work","ask a question","enter the classroom"],"tell a lie"],advanced:[["Mentir peut protéger un secret, mais la vérité finit souvent par apparaître.","Quel mot signifie affirmer volontairement quelque chose de faux ?",["Mentir","secret","vérité","apparaître"]],["Le témoin choisit de mentir, cache la lettre et évite le regard du juge.","Quel mot nomme l’action de ne pas dire la vérité ?",["témoin","mentir","lettre","juge"]],["Dans son rapport, le chercheur ne doit ni mentir, ni supprimer une preuve, ni modifier les résultats.","Quel mot désigne l’action de présenter sciemment une fausseté ?",["rapport","mentir","preuve","résultats"]]]}),
 ...authoredSet({key:"si",surfaceFormId:"srf_si",senseId:"sns_si_primary",target:"si",meaning:"if",
 early:[["Si tu viens tôt, nous déjeunerons ensemble.",["because","although","when"]],["Je prendrai le train si la route est fermée.",["before","without","unless"]],["Si vous acceptez, le travail commencera demain.",["while","since","after"]]],blank:["Nous sortirons ___ la pluie cesse.",["si","car","mais","donc"]],comprehension:["Si Paul termine son travail, il ira au cinéma.","À quelle condition Paul ira-t-il au cinéma ?",["He finishes his work.","He buys a ticket.","His friend calls.","The film starts late."],"He finishes his work."],advanced:[["Si la neige tombe, le bus s’arrête et les écoles ferment.","Quel mot introduit la condition concernant la neige ?",["Si","neige","bus","écoles"]],["Le jardin fleurira si le soleil revient, mais les plantes souffriront sans eau.","Quel mot introduit la condition nécessaire à la floraison ?",["jardin","si","mais","eau"]],["Si le comité approuve le budget, la mairie lancera les travaux après le vote.","Quel mot présente l’approbation comme condition ?",["Si","comité","mairie","vote"]]]}),
 ...authoredSet({key:"votre",surfaceFormId:"srf_votre",senseId:"sns_votre_primary",target:"votre",meaning:"your",
 early:[["Monsieur, votre manteau est sur cette chaise.",["our","their","his"]],["Avez-vous terminé votre travail ?",["my","her","its"]],["Votre réponse aidera toute l’équipe.",["our","their","a"]]],blank:["Madame, voici ___ billet de train.",["votre","vos","notre","son"]],comprehension:["Votre colis arrivera demain matin, Monsieur.","Qu’est-ce qui arrivera demain ?",["your package","your letter","the train","a visitor"],"your package"],advanced:[["Madame, votre dossier est complet, mais vos collègues doivent encore signer leur formulaire.","Quel mot indique que le dossier appartient à la personne à qui l’on parle ?",["votre","mais","collègues","leur"]],["Le patient sait que votre médecin connaît notre infirmière et consulte son rapport.","Quel mot relie le médecin au destinataire de la phrase ?",["votre","notre","son","rapport"]],["Si votre demande est acceptée, le comité contactera vos représentants et publiera sa décision.","Quel mot marque la possession de « demande » par le destinataire ?",["votre","comité","vos","sa"]]]}),
];
