import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch22: ContentBundle["quizItems"] = [
  ...authoredSet({key:"laisse",surfaceFormId:"srf_laisse",senseId:"sns_laisser_primary",target:"laisse",meaning:"lets; allows",
    early:[["La professeure laisse les élèves choisir leur sujet.",["forces","forbids","helps"]],["Le gardien laisse entrer les visiteurs après le contrôle.",["asks","sees","follows"]],["Sa mère laisse Paul jouer dehors jusqu’au dîner.",["makes","hears","watches"]]],blank:["Le chef ___ son équipe décider du meilleur itinéraire.",["laisse","laissent","laisser","oblige"]],comprehension:["Nina laisse son frère utiliser son vélo pour aller au village.","Qu’est-ce que Nina permet à son frère de faire ?",["Use her bicycle.","Buy a bicycle.","Walk to the village.","Repair her bicycle."],"Use her bicycle."],advanced:[["Le professeur laisse Camille répondre, écoute son explication et félicite toute la classe.","Quel mot indique que le professeur autorise Camille à répondre ?",["professeur","laisse","Camille","classe"]],["La barrière laisse passer les piétons, mais bloque encore les voitures devant le chantier.","Quel mot indique que le passage des piétons est permis ?",["barrière","laisse","piétons","voitures"]],["Le médecin laisse le patient se reposer, puis examine les résultats avec son collègue.","Quel mot indique que le médecin permet au patient de se reposer ?",["médecin","laisse","patient","résultats"]]]}),
  ...authoredSet({key:"tomber",surfaceFormId:"srf_tomber",senseId:"sns_tomber_primary",target:"tomber",meaning:"to fall",
    early:[["Les feuilles commencent à tomber en octobre.",["to grow","to shine","to return"]],["Attention à ne pas tomber sur la glace.",["to wait","to speak","to swim"]],["Une tuile risque de tomber du toit.",["to melt","to turn","to rise"]]],blank:["Le vase va ___ si tu pousses la table.",["tomber","tombe","tombent","tenir"]],comprehension:["Le verre vient de tomber sur le carrelage et se brise en morceaux.","Pourquoi le verre est-il maintenant brisé ?",["It fell on the tiled floor.","Someone washed it.","It was left on a shelf.","The floor became wet."],"It fell on the tiled floor."],advanced:[["Le fruit mûr va tomber de la branche, rouler dans l’herbe et attirer les fourmis.","Quel mot désigne le mouvement du fruit vers le sol ?",["fruit","tomber","branche","fourmis"]],["Sans la rampe, Paul pourrait tomber dans l’escalier, perdre son sac et se blesser au genou.","Quel mot indique que Paul risque de chuter ?",["rampe","tomber","sac","genou"]],["La neige commence à tomber sur la route, recouvre les voitures et ralentit la circulation.","Quel mot décrit la descente de la neige ?",["neige","tomber","voitures","circulation"]]]}),
  ...authoredSet({key:"proie",surfaceFormId:"srf_proie",senseId:"sns_proie_primary",target:"proie",meaning:"prey",
    early:[["L’aigle serre sa proie entre ses serres.",["nest","feather","wing"]],["Le renard poursuit une proie dans les hautes herbes.",["shelter","path","shadow"]],["Cette petite souris devient la proie du hibou.",["friend","rival","keeper"]]],blank:["Le faucon emporte sa ___ vers le sommet de la falaise.",["proie","proies","plume","nichée"]],comprehension:["La chouette rapporte une proie au nid où ses petits l’attendent.","Que vont probablement manger les petits de la chouette ?",["The captured animal.","Leaves from the nest.","Seeds from a field.","Fruit from a tree."],"The captured animal."],advanced:[["Le léopard observe sa proie près du ruisseau, avance sans bruit et prépare son attaque.","Quel mot désigne l’animal que le léopard cherche à capturer ?",["léopard","proie","ruisseau","attaque"]],["Une proie rapide peut échapper au loup, traverser la clairière et rejoindre son terrier.","Quel mot désigne l’animal poursuivi par le loup ?",["proie","loup","clairière","terrier"]],["Le serpent repère sa proie sous une pierre, reste immobile puis bondit brusquement.","Quel mot nomme l’animal que le serpent veut manger ?",["serpent","proie","pierre","immobile"]]]}),
];
