import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch28: ContentBundle["quizItems"] = [
  ...authoredSet({key:"ecoute",surfaceFormId:"srf_ecoute",senseId:"sns_ecouter_primary",target:"écoute",meaning:"listens to",
    early:[["Paul écoute la radio pendant le trajet.",["turns off","repairs","carries"]],["Nina écoute attentivement son professeur.",["interrupts","avoids","corrects"]],["L’enfant écoute une histoire avant de dormir.",["writes","forgets","changes"]]],blank:["Marc ___ les nouvelles chaque matin.",["écoute","écoutes","écoutent","écouter"]],comprehension:["Nina écoute les instructions puis assemble correctement l’étagère.","Pourquoi Nina réussit-elle à assembler l’étagère ?",["She listens to the instructions.","She buys new tools.","Someone finishes it for her.","The shelf arrives assembled."],"She listens to the instructions."],advanced:[["Paul écoute le guide, consulte la carte et suit le sentier indiqué.","Quel mot décrit l’action de prêter attention aux paroles du guide ?",["Paul","écoute","carte","sentier"]],["La médecin écoute son patient, note ses symptômes et propose un traitement.","Quel mot indique qu’elle prête attention à ce que dit le patient ?",["médecin","écoute","symptômes","traitement"]],["Nina écoute le concert depuis le balcon, reconnaît la mélodie et applaudit les musiciens.","Quel mot désigne l’action de percevoir attentivement le concert ?",["Nina","écoute","balcon","musiciens"]]]}),
  ...authoredSet({key:"cette",surfaceFormId:"srf_cette",senseId:"sns_ce_primary",target:"cette",meaning:"this",
    early:[["Cette maison appartient à mes grands-parents.",["that","these","those"]],["Je connais bien cette rue étroite.",["these","another","each"]],["Cette réponse semble correcte.",["those","some","which"]]],blank:["___ porte mène au jardin.",["cette","ce","cet","ces"]],comprehension:["Cette clé ouvre la petite armoire, mais les autres clés ne conviennent pas.","Quelle clé faut-il utiliser pour ouvrir l’armoire ?",["This key.","Any other key.","All the keys.","No key."],"This key."],advanced:[["Cette lampe éclaire le bureau, tandis que ces bougies restent éteintes sur la table.","Quel mot désigne précisément la lampe proche ou déjà mentionnée ?",["cette","lampe","ces","table"]],["Nina choisit cette route, évite le tunnel et rejoint rapidement le village.","Quel mot détermine le nom féminin singulier « route » ?",["Nina","cette","tunnel","village"]],["Cette décision surprend Paul, provoque un débat et retarde le projet.","Quel mot accompagne « décision » pour désigner celle dont on parle ?",["cette","Paul","débat","projet"]]]}),
  ...authoredSet({key:"lecon",surfaceFormId:"srf_lecon",senseId:"sns_lecon_primary",target:"leçon",meaning:"lesson",
    early:[["La leçon de français commence à neuf heures.",["vacation","meeting","journey"]],["Paul révise sa leçon avant le contrôle.",["ticket","address","recipe"]],["Cette erreur lui donne une leçon importante.",["reward","excuse","permission"]]],blank:["Le professeur prépare une ___ sur les volcans.",["leçon","leçons","leçonner","leçonne"]],comprehension:["Après une courte leçon, Nina sait faire correctement le nœud marin.","Qu’est-ce que Nina a appris ?",["How to tie the sailor’s knot.","How to repair a boat.","How to read a map.","How to swim faster."],"How to tie the sailor’s knot."],advanced:[["La leçon explique les fractions, propose trois exemples et se termine par un exercice.","Quel mot désigne l’enseignement organisé sur les fractions ?",["leçon","fractions","exemples","exercice"]],["Paul retient la leçon de son échec, modifie sa méthode et prépare mieux la prochaine course.","Quel mot désigne ici l’enseignement tiré de l’échec ?",["Paul","leçon","méthode","course"]],["La professeure commence la leçon, écrit la date au tableau et distribue les cahiers.","Quel mot nomme la partie d’enseignement qui commence ?",["professeure","leçon","tableau","cahiers"]]]}),
];
