import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch25: ContentBundle["quizItems"] = [
  ...authoredSet({key:"que_conjunction",surfaceFormId:"srf_que",senseId:"sns_que_conjunction",target:"que",meaning:"that",
    early:[["Je pense que le train arrivera à l’heure.",["how","what","than"]],["Nina explique que le magasin est fermé.",["why","which","when"]],["Nous savons que Paul habite près d’ici.",["whose","where","whether"]]],blank:["Le témoin affirme ___ la porte était ouverte.",["que","qui","quand","dont"]],comprehension:["Marc annonce que la réunion commencera à neuf heures.","Quelle information Marc communique-t-il ?",["The meeting will begin at nine.","The meeting ended at nine.","The meeting was canceled.","The meeting changed rooms."],"The meeting will begin at nine."],advanced:[["Paul confirme que Nina viendra demain, puis il note son heure d’arrivée.","Quel mot introduit la proposition qui contient l’information confirmée ?",["Paul","que","Nina","demain"]],["Le médecin pense que le patient guérira bientôt, mais il poursuit les examens.","Quel mot relie le verbe « pense » à la proposition qui le complète ?",["médecin","que","patient","examens"]],["La directrice déclare que le bâtiment est sûr avant d’accueillir les visiteurs.","Quel mot introduit ce que la directrice déclare ?",["directrice","que","bâtiment","visiteurs"]]]}),
  ...authoredSet({key:"tout",surfaceFormId:"srf_tout",senseId:"sns_tout_primary",target:"tout",meaning:"every; all",
    early:[["Tout enfant doit être accompagné par un adulte.",["no","this","another"]],["Tout visiteur présente son billet à l’entrée.",["some","which","one"]],["Le règlement concerne tout membre du club.",["few","that","several"]]],blank:["Sans exception, ___ candidat doit signer ce formulaire.",["tout","tous","toute","toutes"]],comprehension:["Tout élève doit rendre les livres à la bibliothèque avant vendredi.","Qui doit rendre les livres avant vendredi ?",["Every student.","Only new students.","The teachers.","One chosen student."],"Every student."],advanced:[["Tout conducteur ralentit devant l’école, respecte le passage et surveille les enfants.","Quel mot indique que la règle s’applique à chaque conducteur sans exception ?",["tout","conducteur","école","enfants"]],["Le guide répond à tout visiteur, consulte le plan et indique les salles ouvertes.","Quel mot signifie que chaque visiteur peut recevoir une réponse ?",["guide","tout","visiteur","salles"]],["Tout participant apporte un carnet, écoute les consignes et rejoint son équipe.","Quel mot étend l’obligation à chaque participant ?",["tout","participant","consignes","équipe"]]]}),
  ...authoredSet({key:"flatteur",surfaceFormId:"srf_flatteur",senseId:"sns_flatteur_primary",target:"flatteur",meaning:"flatterer",
    early:[["Un flatteur adresse des compliments peu sincères au chef.",["critic","teacher","stranger"]],["Le flatteur loue constamment les décisions du ministre.",["adviser","opponent","witness"]],["Méfiez-vous du flatteur qui cherche seulement votre faveur.",["buyer","neighbor","traveler"]]],blank:["Ce ___ exagère les qualités du directeur.",["flatteur","flatteuse","flatter","flatterie"]],comprehension:["Le flatteur complimente sans cesse la directrice parce qu’il espère obtenir une promotion.","Pourquoi cet homme multiplie-t-il les compliments ?",["He hopes to obtain a promotion.","He wants to correct a mistake.","He is welcoming a visitor.","He needs directions."],"He hopes to obtain a promotion."],advanced:[["Le flatteur encense le directeur, ignore ses collègues et espère une récompense.","Quel mot nomme la personne qui donne des éloges intéressés ?",["flatteur","directeur","collègues","récompense"]],["Un flatteur vante chaque discours du candidat, observe sa réaction et sollicite ensuite une faveur.","Quel mot désigne celui qui loue excessivement le candidat par intérêt ?",["flatteur","discours","candidat","faveur"]],["Le roi écoute le flatteur, tandis que le conseiller honnête présente les difficultés du royaume.","Quel mot désigne la personne qui cherche à plaire par des compliments ?",["roi","flatteur","conseiller","royaume"]]]}),
];
