import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch16: ContentBundle["quizItems"] = [
 ...authoredSet({key:"hotes",surfaceFormId:"srf_hotes",senseId:"sns_hote_primary",target:"hôtes",meaning:"inhabitants",
 early:[["Les oiseaux sont les hôtes habituels de ce jardin.",["visitors","owners","hunters"]],["Les poissons sont les hôtes silencieux de l’étang.",["boats","plants","shadows"]],["Ces animaux sont les hôtes naturels de la forêt.",["enemies","guides","farmers"]]],blank:["Les écureuils sont les ___ de ces grands arbres.",["hôtes","hôte","invités","habitants"]],comprehension:["Les cerfs sont les hôtes les plus imposants de cette réserve.","Quels animaux habitent la réserve ?",["deer","foxes","wolves","horses"],"deer"],advanced:[["Les hôtes du marais comprennent les hérons, les grenouilles et plusieurs espèces de poissons.","Quel mot désigne collectivement les êtres qui habitent le marais ?",["hôtes","marais","hérons","poissons"]],["Parmi les hôtes de la forêt, le chevreuil reste discret tandis que le sanglier laisse de nombreuses traces.","Quel mot nomme les animaux qui vivent dans la forêt ?",["hôtes","chevreuil","sanglier","traces"]],["Les scientifiques recensent les hôtes de la grotte, observent les chauves-souris et protègent leurs abris.","Quel mot désigne ici les habitants naturels de la grotte ?",["scientifiques","hôtes","grotte","abris"]]]}),
 ...authoredSet({key:"de",surfaceFormId:"srf_de",senseId:"sns_de_primary",target:"de",meaning:"of; from",
 early:[["La clé de la maison reste sur la table.",["to","with","under"]],["Paul revient de Paris ce soir.",["toward","inside","near"]],["Nous parlons de ce problème demain.",["without","after","against"]]],blank:["Le toit ___ la grange est rouge.",["de","à","par","pour"]],comprehension:["Nina arrive de Marseille par le train.","D’où Nina arrive-t-elle ?",["from Marseille","from Lyon","from Paris","from Nice"],"from Marseille"],advanced:[["La porte de la cuisine est ouverte, mais la fenêtre du salon reste fermée.","Quel mot relie la porte à la cuisine ?",["porte","de","fenêtre","salon"]],["Marc revient de la gare, traverse le parc et entre dans la maison.","Quel mot introduit le lieu d’origine de Marc ?",["Marc","de","parc","maison"]],["Le comité discute de la réforme, consulte les experts et prépare un rapport.","Quel mot introduit le sujet de la discussion ?",["comité","de","experts","rapport"]]]}),
 ...authoredSet({key:"ces",surfaceFormId:"srf_ces",senseId:"sns_ce_primary",target:"ces",meaning:"these; those",
 early:[["Ces livres appartiennent à la bibliothèque.",["this","the","some"]],["Je préfère ces pommes rouges.",["that","a few","our"]],["Ces enfants attendent devant l’école.",["each","one","your"]]],blank:["___ grandes fenêtres donnent sur le jardin.",["ces","ce","cette","cet"]],comprehension:["Ces fleurs jaunes poussent près de la rivière.","Qu’est-ce qui pousse près de la rivière ?",["these yellow flowers","those tall trees","some green plants","a red rose"],"these yellow flowers"],advanced:[["Dans la vitrine, ces chaussures sont neuves, ce manteau est ancien et cette écharpe coûte cher.","Quel mot détermine le nom pluriel « chaussures » ?",["ces","ce","cette","cher"]],["Le professeur corrige ces exercices, distribue ce texte et explique cette règle.","Quel mot désigne précisément plusieurs exercices ?",["professeur","ces","ce","cette"]],["Après l’enquête, ces témoignages restent essentiels, tandis que ce document paraît incomplet.","Quel mot est le déterminant démonstratif pluriel devant « témoignages » ?",["enquête","ces","ce","document"]]]}),
];
