import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch18: ContentBundle["quizItems"] = [
 ...authoredSet({key:"sent",surfaceFormId:"srf_sent",senseId:"sns_sentir_primary",target:"sent",meaning:"feels",
 early:[["Paul se sent mieux après son repos.",["hears","sees","leaves"]],["Elle sent une grande fatigue ce soir.",["hides","forgets","chooses"]],["Le patient sent encore une légère douleur.",["shows","causes","removes"]]],blank:["Nina se ___ prête pour l’examen.",["sent","sens","sentent","sentir"]],comprehension:["Marc se sent heureux dans sa nouvelle maison.","Quel est l’état de Marc ?",["He feels happy.","He feels worried.","He is tired.","He is angry."],"He feels happy."],advanced:[["Paul se sent faible, boit de l’eau et appelle le médecin.","Quel mot exprime l’état éprouvé par Paul ?",["Paul","sent","eau","médecin"]],["Elle sent le froid, ferme la fenêtre et prend une couverture.","Quel mot indique qu’elle éprouve le froid ?",["sent","froid","fenêtre","couverture"]],["Le témoin se sent inquiet, relit sa déclaration et attend le juge.","Quel mot relie le témoin à l’état d’inquiétude qu’il éprouve ?",["témoin","sent","déclaration","juge"]]]}),
 ...authoredSet({key:"pas",surfaceFormId:"srf_pas",senseId:"sns_pas_primary",target:"pas",meaning:"not",
 early:[["Je ne connais pas cette adresse.",["already","still","always"]],["Paul ne travaille pas le dimanche.",["often","also","outside"]],["Nous ne partirons pas sans vous.",["soon","together","perhaps"]]],blank:["Nina ne mange ___ de viande.",["pas","plus","jamais","rien"]],comprehension:["Marc ne prend pas le bus ce matin.","Marc prend-il le bus ?",["No, he does not.","Yes, at eight.","Yes, later.","The sentence does not say."],"No, he does not."],advanced:[["Paul ne dort pas, mais sa sœur lit encore près de la lampe.","Quel mot complète la négation du verbe « dort » ?",["Paul","pas","mais","encore"]],["Le magasin n’ouvre pas le lundi, tandis que la pharmacie reste accessible.","Quel mot indique que l’ouverture n’a pas lieu ?",["magasin","pas","lundi","pharmacie"]],["Le comité ne publiera pas le rapport, conservera les preuves et informera les avocats.","Quel mot ferme la construction négative autour de « publiera » ?",["comité","pas","preuves","avocats"]]]}),
 ...authoredSet({key:"joie",surfaceFormId:"srf_joie",senseId:"sns_joie_primary",target:"joie",meaning:"joy",
 early:[["Une grande joie illumine son visage.",["fear","anger","sadness"]],["Les enfants crient de joie à l’arrivée du train.",["pain","surprise","shame"]],["Cette bonne nouvelle remplit Paul de joie.",["doubt","worry","regret"]]],blank:["Nina pleure de ___ en retrouvant sa sœur.",["joie","peur","colère","fatigue"]],comprehension:["La victoire apporte une immense joie aux supporters.","Que ressentent les supporters ?",["great joy","deep disappointment","strong fear","complete confusion"],"great joy"],advanced:[["La joie de Nina contraste avec la tristesse de Paul et le silence de Marc.","Quel mot désigne le sentiment heureux de Nina ?",["joie","tristesse","silence","Marc"]],["À l’annonce du résultat, une joie soudaine gagne la salle, les étudiants applaudissent et le professeur sourit.","Quel mot nomme l’émotion positive qui se répand ?",["résultat","joie","étudiants","professeur"]],["Malgré les difficultés, la naissance provoque une profonde joie, apaise la famille et rassemble les amis.","Quel mot désigne l’émotion heureuse provoquée par la naissance ?",["difficultés","joie","famille","amis"]]]}),
];
