import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch20: ContentBundle["quizItems"] = [
 ...authoredSet({key:"sa",surfaceFormId:"srf_sa",senseId:"sns_son_primary",target:"sa",meaning:"his; her; its",
 early:[["Paul cherche sa veste noire.",["my","your","our"]],["Nina téléphone à sa mère chaque soir.",["their","your","our"]],["Le chien protège sa nourriture.",["my","your","their"]]],blank:["Élise range ___ montre dans le tiroir.",["sa","son","ses","leur"]],comprehension:["Marc prête sa voiture à Luc.","À qui appartient la voiture ?",["Marc","Luc","both men","an unknown owner"],"Marc"],advanced:[["Nina ouvre sa valise, prend son manteau et montre ses billets à Paul.","Quel mot indique que la valise appartient à Nina ?",["Nina","sa","son","Paul"]],["Le médecin consulte sa montre, ferme le dossier et appelle son patient.","Quel mot relie la montre au médecin qui la possède ?",["médecin","sa","dossier","patient"]],["Avant le vote, la présidente relit sa déclaration, écoute les membres et signe leur rapport.","Quel mot marque la possession de la déclaration par la présidente ?",["présidente","sa","membres","leur"]]]}),
 ...authoredSet({key:"belle",surfaceFormId:"srf_belle",senseId:"sns_beau_primary",target:"belle",meaning:"beautiful",
 early:[["Cette belle maison domine la vallée.",["ugly","empty","dangerous"]],["Nina porte une belle robe bleue.",["torn","dirty","heavy"]],["Nous admirons la belle lumière du soir.",["weak","cold","false"]]],blank:["Le musée conserve une ___ peinture ancienne.",["belle","beau","bel","belles"]],comprehension:["Une belle plage s’étend devant l’hôtel.","Comment la plage est-elle décrite ?",["as beautiful","as crowded","as dirty","as distant"],"as beautiful"],advanced:[["Une belle statue occupe la place, tandis qu’un vieux banc reste près de la fontaine.","Quel mot donne une appréciation esthétique positive de la statue ?",["belle","place","banc","fontaine"]],["La photographe choisit une belle image, corrige la couleur et réduit la lumière.","Quel mot qualifie favorablement l’image ?",["photographe","belle","couleur","lumière"]],["Au sommet, la belle vue sur la mer récompense les marcheurs malgré le vent.","Quel mot exprime la beauté de la vue ?",["sommet","belle","marcheurs","vent"]]]}),
 ...authoredSet({key:"voix",surfaceFormId:"srf_voix",senseId:"sns_voix_primary",target:"voix",meaning:"voice",
 early:[["Sa voix calme rassure le jeune enfant.",["face","hand","step"]],["Paul reconnaît la voix de sa sœur au téléphone.",["name","address","photo"]],["La chanteuse possède une voix puissante.",["memory","gesture","smile"]]],blank:["Le professeur parle d’une ___ claire et forte.",["voix","voie","voile","fois"]],comprehension:["La voix du guide indique le chemin dans l’obscurité.","Qu’est-ce qui aide les visiteurs à suivre le chemin ?",["the guide’s voice","a bright lamp","a printed map","the moonlight"],"the guide’s voice"],advanced:[["La voix de Nina couvre la musique, tandis que Paul ferme la fenêtre.","Quel mot désigne le son produit quand Nina parle ?",["voix","musique","Paul","fenêtre"]],["Le journaliste enregistre la voix du témoin, vérifie le micro et prend des notes.","Quel mot nomme le son parlé qui est enregistré ?",["journaliste","voix","micro","notes"]],["Malgré le bruit, sa voix reste audible, son geste demeure précis et le public écoute.","Quel mot désigne ce que le public entend lorsqu’elle parle ?",["bruit","voix","geste","public"]]]}),
];
