import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch07: ContentBundle["quizItems"] = [
 ...authoredSet({key:"lui",surfaceFormId:"srf_lui",senseId:"sns_lui_primary",target:"lui",meaning:"to him; to her",
 early:[["Paul téléphone à Léa et lui raconte la nouvelle.",["to us","to them","there"]],["Le professeur lui explique la règle calmement.",["to me","to you","of it"]],["Nina voit Marc et lui rend son livre.",["with him","from her","at home"]]],blank:["Marc écoute sa sœur et ___ répond avec patience.",["lui","le","y","en"]],comprehension:["Éva rencontre Paul et lui donne la clé.","Qui reçoit la clé ?",["Paul","Éva","both people","nobody"],"Paul"],advanced:[["Léa voit Marc, lui montre la carte et range son téléphone.","Quel mot remplace « à Marc » ?",["Léa","Marc","lui","carte"]],["Le médecin parle au patient et lui décrit le traitement devant l’infirmière.","Quel mot reprend le complément « au patient » ?",["médecin","lui","traitement","infirmière"]],["Après le débat, Anna rejoint Luc, lui présente ses excuses et quitte la salle.","Quel mot indique que les excuses sont adressées à Luc ?",["débat","Luc","lui","salle"]]]}),
 ...authoredSet({key:"tint_speak",surfaceFormId:"srf_tint",senseId:"sns_tenir_speak",target:"tint",meaning:"addressed; spoke to",
 early:[["Le maire lui tint un discours très bref.",["held","ignored","wrote"]],["Elle tint à son invité des propos rassurants.",["sent","hid","sold"]],["Le diplomate tint au ministre un langage prudent.",["listened to","followed","avoided"]]],blank:["Devant l’assemblée, l’orateur ___ un discours énergique.",["tint","tenait","tient","tinrent"]],comprehension:["Le directeur tint aux employés un discours encourageant.","À qui le directeur adressa-t-il son discours ?",["the employees","the customers","the mayor","the students"],"the employees"],advanced:[["Le président tint un discours, salua le public et quitta la tribune.","Quel mot exprime ici l’action de prononcer le discours ?",["président","tint","public","tribune"]],["L’ambassadeur tint au conseil un langage ferme avant de signer le document.","Quel mot signifie qu’il adressa ces paroles au conseil ?",["ambassadeur","tint","conseil","document"]],["Le témoin tint au juge des propos précis, puis consulta ses notes en silence.","Quel mot décrit l’action d’adresser ces propos au juge ?",["témoin","tint","juge","notes"]]]}),
 ...authoredSet({key:"a_prep",surfaceFormId:"srf_a",senseId:"sns_a_primary",target:"à",meaning:"to; at",
 early:[["Nous allons à la bibliothèque après le déjeuner.",["from","without","under"]],["Le train arrive à midi exactement.",["before","during","despite"]],["Claire donne la lettre à son voisin.",["from","with","behind"]]],blank:["Elle remet le dossier ___ la directrice.",["à","de","par","sans"]],comprehension:["Paul retourne à Lyon demain matin.","Quelle ville Paul rejoint-il ?",["Lyon","Paris","Nice","Lille"],"Lyon"],advanced:[["Paul arrive à midi, rejoint la gare avec sa sœur et prend le train.","Quel mot introduit l’heure de midi ?",["Paul","à","gare","train"]],["Nina apporte un livre à Marc, puis pose son sac sous la table.","Quel mot introduit la personne qui reçoit le livre ?",["livre","à","Marc","sous"]],["Le comité se réunit à Bruxelles, examine le rapport et répond aux journalistes.","Quel mot introduit le lieu de la réunion ?",["comité","à","rapport","journalistes"]]]}),
];
