import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch23: ContentBundle["quizItems"] = [
  ...authoredSet({key:"s_elided",surfaceFormId:"srf_s_elided",senseId:"sns_se_primary",target:"s’",meaning:"oneself; himself; herself",
    early:[["Paul s’habille rapidement avant de partir.",["him","his","to him"]],["Nina s’installe près de la fenêtre.",["her","hers","to her"]],["Le chat s’approche doucement de la porte.",["it","its","to it"]]],blank:["Marc ___assoit au premier rang.",["s’","m’","t’","l’"]],comprehension:["Nina s’arrête au bord du trottoir parce que le feu est rouge.","Pourquoi Nina attend-elle avant de traverser ?",["The light is red.","She lost her bag.","The street is closed.","She is waiting for a bus."],"The light is red."],advanced:[["Paul s’endort dans le fauteuil, tandis que Nina ferme le livre et éteint la lampe.","Quel élément montre que l’action de s’endormir concerne Paul lui-même ?",["Paul","s’","livre","lampe"]],["Le cheval s’élance sur la piste, dépasse son rival et franchit la ligne.","Quel élément est la forme élidée du pronom réfléchi devant « élance » ?",["cheval","s’","rival","ligne"]],["Nina s’excuse auprès de Marc, explique son retard et reprend sa place.","Quel élément relie l’action de s’excuser au sujet Nina ?",["Nina","s’","Marc","retard"]]]}),
  ...authoredSet({key:"saisit",surfaceFormId:"srf_saisit",senseId:"sns_saisir_primary",target:"saisit",meaning:"seizes; grabs",
    early:[["Le gardien saisit le voleur par le bras.",["releases","follows","calls"]],["Nina saisit la corde avant de glisser.",["cuts","drops","hides"]],["Le chat saisit vivement le morceau de viande.",["smells","ignores","loses"]]],blank:["Paul ___ la poignée pour ouvrir la lourde porte.",["saisit","saisis","saisissent","saisir"]],comprehension:["L’enfant saisit la branche et évite de tomber dans le ruisseau.","Qu’est-ce qui empêche l’enfant de tomber ?",["He grabs the branch.","He jumps over the stream.","An adult catches him.","The water is shallow."],"He grabs the branch."],advanced:[["Le policier saisit le suspect, récupère le sac et appelle son collègue.","Quel mot indique que le policier attrape fermement le suspect ?",["policier","saisit","sac","collègue"]],["D’un geste rapide, Nina saisit la balle, protège son visage et recule vers le mur.","Quel mot décrit l’action de prendre vivement la balle ?",["geste","Nina","saisit","mur"]],["L’aigle saisit le poisson près de la rive, reprend de l’altitude et gagne son nid.","Quel mot indique que l’aigle attrape le poisson ?",["aigle","saisit","rive","nid"]]]}),
  ...authoredSet({key:"dit",surfaceFormId:"srf_dit",senseId:"sns_dire_primary",target:"dit",meaning:"says",
    early:[["Paul dit la vérité à ses parents.",["hides","writes","forgets"]],["Nina dit que le train arrivera bientôt.",["asks","doubts","hears"]],["Le médecin dit quelques mots au patient.",["shows","brings","owes"]]],blank:["Marc ___ que la route est fermée.",["dit","dis","disent","dire"]],comprehension:["Le guide dit que le musée ferme à dix-huit heures.","Quelle information le guide donne-t-il ?",["The museum closes at six p.m.","The museum opens at six p.m.","The tour lasts six hours.","The museum is closed today."],"The museum closes at six p.m."],advanced:[["Paul dit son nom, montre sa carte et attend la réponse du gardien.","Quel mot indique que Paul prononce son nom ?",["Paul","dit","carte","gardien"]],["La directrice dit que la réunion commence, présente le programme et salue les invités.","Quel mot introduit ce que la directrice annonce ?",["directrice","dit","programme","invités"]],["Le témoin dit ce qu’il a vu, répond aux questions et signe sa déclaration.","Quel mot désigne l’action de communiquer oralement ce qu’il a vu ?",["témoin","dit","questions","déclaration"]]]}),
];
