import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch19: ContentBundle["quizItems"] = [
 ...authoredSet({key:"et",surfaceFormId:"srf_et",senseId:"sns_et_primary",target:"Et",meaning:"and",
 early:[["Et Paul ferme la porte derrière lui.",["but","or","because"]],["Nina prépare le repas et Marc met la table.",["unless","although","before"]],["Le chat dort et le chien joue dans le jardin.",["while","therefore","without"]]],blank:["Luc prend son manteau ___ quitte la maison.",["Et","mais","ou","car"]],comprehension:["Nina ouvre la fenêtre et regarde la rue.","Que fait Nina après avoir ouvert la fenêtre ?",["She looks at the street.","She closes the curtains.","She leaves the room.","She calls Paul."],"She looks at the street."],advanced:[["Et Paul arrive, mais Nina part tandis que Luc attend dehors.","Quel mot ajoute l’arrivée de Paul à ce qui précède ?",["Et","mais","Nina","dehors"]],["Le médecin examine le patient et consulte le dossier avant de répondre.","Quel mot coordonne les deux actions du médecin ?",["médecin","et","dossier","avant"]],["Le comité approuve le budget et publie le rapport, mais reporte la réunion.","Quel mot relie les deux premières actions ?",["comité","et","mais","réunion"]]]}),
 ...authoredSet({key:"pour",surfaceFormId:"srf_pour",senseId:"sns_pour_primary",target:"pour",meaning:"for; in order to",
 early:[["Ce cadeau est pour Nina.",["from","without","against"]],["Paul étudie pour réussir son examen.",["after","despite","beside"]],["Nous partons tôt pour éviter la circulation.",["during","under","among"]]],blank:["Elle économise ___ acheter un vélo.",["pour","par","sans","chez"]],comprehension:["Marc téléphone pour réserver une table.","Pourquoi Marc téléphone-t-il ?",["to reserve a table","to cancel a trip","to order a taxi","to invite a friend"],"to reserve a table"],advanced:[["Paul court pour attraper le bus, mais Nina marche vers la gare.","Quel mot introduit le but de la course ?",["Paul","pour","mais","gare"]],["Ce dossier est pour la directrice ; le courrier reste sur le bureau.","Quel mot indique la destinataire du dossier ?",["dossier","pour","courrier","bureau"]],["Le comité se réunit pour examiner le budget, entendre les experts et préparer le vote.","Quel mot introduit l’objectif de la réunion ?",["comité","pour","experts","vote"]]]}),
 ...authoredSet({key:"montrer",surfaceFormId:"srf_montrer",senseId:"sns_montrer_primary",target:"montrer",meaning:"to show",
 early:[["Paul veut montrer sa nouvelle bicyclette à Léa.",["to hide","to sell","to repair"]],["Le guide va montrer le château aux visiteurs.",["to leave","to close","to forget"]],["Elle utilise une carte pour montrer le chemin.",["to block","to change","to lose"]]],blank:["Nina ouvre l’album pour ___ les photos.",["montrer","montre","montré","montrent"]],comprehension:["Le professeur va montrer une expérience aux élèves.","Que verront les élèves ?",["an experiment","a film","a painting","a map"],"an experiment"],advanced:[["Paul veut montrer son dessin, expliquer son idée et remercier le professeur.","Quel mot signifie faire voir le dessin ?",["Paul","montrer","idée","professeur"]],["Le témoin utilise une photographie pour montrer la voiture, puis décrit la rue au juge.","Quel mot désigne l’action de faire voir la voiture ?",["témoin","montrer","rue","juge"]],["La chercheuse doit montrer les résultats, défendre sa méthode et répondre au comité.","Quel mot exprime l’action de présenter visiblement les résultats ?",["chercheuse","montrer","méthode","comité"]]]}),
];
