import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch12: ContentBundle["quizItems"] = [
 ...authoredSet({key:"semblez",surfaceFormId:"srf_semblez",senseId:"sns_sembler_primary",target:"semblez",meaning:"seem; appear",
 early:[["Vous semblez fatigué après ce voyage.",["are","become","remain"]],["Madame, vous semblez connaître cette adresse.",["forget","refuse","choose"]],["Vous semblez satisfait du résultat.",["leave","work","answer"]]],blank:["Vous ___ surpris par cette annonce.",["semblez","semble","semblons","semblent"]],comprehension:["Vous semblez inquiet depuis l’appel du médecin.","Quelle impression donne la personne ?",["She appears worried.","She seems delighted.","She looks sleepy.","She appears angry."],"She appears worried."],advanced:[["Vous semblez calme, votre collègue paraît nerveux et le directeur reste silencieux.","Quel mot exprime l’impression donnée par « vous » ?",["semblez","collègue","directeur","silencieux"]],["Madame, vous semblez hésiter, mais votre avocat recommande une réponse rapide.","Quel mot indique une apparence plutôt qu’une certitude ?",["Madame","semblez","avocat","réponse"]],["Vous semblez comprendre le rapport, consultez les annexes et posez une dernière question.","Quel mot présente la compréhension comme une impression ?",["semblez","rapport","annexes","question"]]]}),
 ...authoredSet({key:"beau",surfaceFormId:"srf_beau",senseId:"sns_beau_primary",target:"beau",meaning:"beautiful; handsome",
 early:[["Ce beau cheval court dans le pré.",["ugly","weak","small"]],["Paul porte un beau manteau noir.",["torn","dirty","cheap"]],["Nous admirons un beau paysage de montagne.",["flat","empty","dangerous"]]],blank:["Le musée expose un ___ portrait ancien.",["beau","bel","belle","beaux"]],comprehension:["Un beau jardin entoure la maison blanche.","Comment le jardin est-il décrit ?",["as beautiful","as neglected","as tiny","as closed"],"as beautiful"],advanced:[["Un beau tableau domine la salle, tandis qu’une lampe éclaire le mur.","Quel mot donne une appréciation esthétique positive du tableau ?",["beau","salle","lampe","mur"]],["Le guide montre un beau château, décrit la rivière et traverse le village.","Quel mot qualifie favorablement l’apparence du château ?",["guide","beau","rivière","village"]],["Sous le soleil, le voilier offre un beau spectacle ; le port et les falaises attirent aussi les visiteurs.","Quel mot exprime la beauté du spectacle ?",["soleil","beau","port","visiteurs"]]]}),
 ...authoredSet({key:"sans",surfaceFormId:"srf_sans",senseId:"sns_sans_primary",target:"Sans",meaning:"without",
 early:[["Sans parapluie, Marc rentre sous la pluie.",["with","before","behind"]],["Elle boit son café sans sucre.",["with","after","near"]],["Nous terminons le travail sans difficulté.",["because of","during","toward"]]],blank:["Paul quitte la maison ___ son téléphone.",["Sans","avec","pour","chez"]],comprehension:["Sans billet, Nina ne peut pas prendre le train.","Pourquoi Nina ne peut-elle pas voyager ?",["She has no ticket.","The train is full.","She is late.","The station is closed."],"She has no ticket."],advanced:[["Sans manteau, Paul marche dans le froid, serre son écharpe et cherche un café.","Quel mot indique l’absence de manteau ?",["Sans","froid","écharpe","café"]],["Sans réponse, la cliente ferme son dossier et quitte le bureau après une heure.","Quel mot exprime que la réponse manque ?",["Sans","cliente","dossier","bureau"]],["Sans preuve, le tribunal reporte la décision, écoute les avocats et libère le témoin.","Quel mot introduit l’élément qui fait défaut ?",["Sans","tribunal","avocats","témoin"]]]}),
];
