import type { ContentBundle } from "../../domain/model.js";

export const corbeauQuizBatch02: ContentBundle["quizItems"] = [
  { id: "qiz_arbre_01", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 1, format: "meaning_choice", contextFrench: "Un grand arbre protège la maison du soleil.", targetText: "arbre", prompt: "Meaning", choicesEnglish: ["tree", "wall", "roof", "road"], correctAnswer: "tree" },
  { id: "qiz_arbre_02", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 2, format: "meaning_choice", contextFrench: "Cet arbre perd ses feuilles en automne.", targetText: "arbre", prompt: "Meaning", choicesEnglish: ["tree", "flower", "field", "river"], correctAnswer: "tree" },
  { id: "qiz_arbre_03", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 3, format: "meaning_choice", contextFrench: "Les enfants jouent sous un arbre couvert de pommes.", targetText: "arbre", prompt: "Meaning", choicesEnglish: ["tree", "tent", "bridge", "cloud"], correctAnswer: "tree" },
  { id: "qiz_arbre_04", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 4, format: "surface_completion", contextFrench: "Le pommier est un ___ qui produit des fruits.", choicesFrench: ["arbre", "arbres", "arbuste", "prairie"], correctAnswer: "arbre" },
  { id: "qiz_arbre_05", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 5, format: "comprehension_choice", contextFrench: "Un oiseau construit son nid dans un arbre du jardin.", targetText: "arbre", promptFrench: "Où l’oiseau construit-il son nid ?", choicesEnglish: ["in a tree", "under a bridge", "inside a house", "beside a river"], correctAnswer: "in a tree" },
  { id: "qiz_arbre_06", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 6, format: "target_identification", contextFrench: "Dans le jardin, un arbre porte des feuilles, tandis que la fleur pousse près du mur.", promptFrench: "Quel mot désigne la grande plante qui porte des branches ?", choicesFrench: ["jardin", "arbre", "fleur", "mur"], correctAnswer: "arbre" },
  { id: "qiz_arbre_07", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 7, format: "target_identification", contextFrench: "Après la pluie, le vieux arbre abrite un écureuil ; l’herbe et les pierres restent humides.", promptFrench: "Quel mot désigne ici le végétal ligneux qui abrite l’écureuil ?", choicesFrench: ["pluie", "arbre", "herbe", "pierres"], correctAnswer: "arbre" },
  { id: "qiz_arbre_08", surfaceFormId: "srf_arbre", senseId: "sns_arbre_primary", masteryLevel: 8, format: "target_identification", contextFrench: "Le botaniste observe le tronc de l’arbre, puis compare ses feuilles à celles du buisson voisin.", promptFrench: "Quel mot nomme le végétal possédant le tronc observé ?", choicesFrench: ["botaniste", "tronc", "arbre", "buisson"], correctAnswer: "arbre" },

  { id: "qiz_perche_01", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 1, format: "meaning_choice", contextFrench: "Un moineau perché sur le toit chante dès l’aube.", targetText: "perché", prompt: "Meaning", choicesEnglish: ["perched", "hidden", "injured", "flying"], correctAnswer: "perched" },
  { id: "qiz_perche_02", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 2, format: "meaning_choice", contextFrench: "Le chat perché sur le mur regarde la rue.", targetText: "perché", prompt: "Meaning", choicesEnglish: ["perched", "asleep", "lost", "running"], correctAnswer: "perched" },
  { id: "qiz_perche_03", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 3, format: "meaning_choice", contextFrench: "Nous apercevons un hibou perché au sommet du clocher.", targetText: "perché", prompt: "Meaning", choicesEnglish: ["perched", "buried", "swimming", "approaching"], correctAnswer: "perched" },
  { id: "qiz_perche_04", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 4, format: "surface_completion", contextFrench: "Le coq a quitté le sol et reste ___ sur la barrière.", choicesFrench: ["perché", "perchée", "perchés", "percher"], correctAnswer: "perché" },
  { id: "qiz_perche_05", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 5, format: "comprehension_choice", contextFrench: "Le merle perché sur une branche observe le jardin.", targetText: "perché", promptFrench: "Quelle est la position du merle ?", choicesEnglish: ["It is perched on a branch.", "It is walking on the ground.", "It is inside a nest.", "It is flying away."], correctAnswer: "It is perched on a branch." },
  { id: "qiz_perche_06", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 6, format: "target_identification", contextFrench: "Le pigeon perché sur la statue reste immobile, mais un chien court autour de la fontaine.", promptFrench: "Quel mot décrit l’oiseau installé en hauteur sur la statue ?", choicesFrench: ["pigeon", "perché", "chien", "fontaine"], correctAnswer: "perché" },
  { id: "qiz_perche_07", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 7, format: "target_identification", contextFrench: "Un faucon perché sur un poteau surveille le champ pendant que le cheval avance.", promptFrench: "Quel mot indique que le faucon est posé en hauteur ?", choicesFrench: ["faucon", "perché", "champ", "cheval"], correctAnswer: "perché" },
  { id: "qiz_perche_08", surfaceFormId: "srf_perche", senseId: "sns_percher_primary", masteryLevel: 8, format: "target_identification", contextFrench: "Au-dessus du ravin, un aigle perché sur la falaise replie ses ailes et fixe la vallée.", promptFrench: "Quel mot caractérise la position stable de l’aigle sur la falaise ?", choicesFrench: ["ravin", "aigle", "perché", "vallée"], correctAnswer: "perché" },

  { id: "qiz_tenait_hold_01", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 1, format: "meaning_choice", contextFrench: "Élise tenait une lampe dans sa main droite.", targetText: "tenait", prompt: "Meaning", choicesEnglish: ["was holding", "was dropping", "was buying", "was lighting"], correctAnswer: "was holding" },
  { id: "qiz_tenait_hold_02", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 2, format: "meaning_choice", contextFrench: "Le garçon tenait fermement la corde.", targetText: "tenait", prompt: "Meaning", choicesEnglish: ["was holding", "was cutting", "was measuring", "was throwing"], correctAnswer: "was holding" },
  { id: "qiz_tenait_hold_03", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 3, format: "meaning_choice", contextFrench: "Pendant la photo, elle tenait son chapeau contre le vent.", targetText: "tenait", prompt: "Meaning", choicesEnglish: ["was holding", "was wearing", "was losing", "was finding"], correctAnswer: "was holding" },
  { id: "qiz_tenait_hold_04", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 4, format: "surface_completion", contextFrench: "Pendant toute la cérémonie, Paul ___ le drapeau entre ses mains.", choicesFrench: ["tenait", "tient", "tiendra", "tenaient"], correctAnswer: "tenait" },
  { id: "qiz_tenait_hold_05", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 5, format: "comprehension_choice", contextFrench: "Nina tenait le panier pendant que Marc ouvrait la porte.", targetText: "tenait", promptFrench: "Que faisait Nina avec le panier ?", choicesEnglish: ["She was holding it.", "She was emptying it.", "She was hiding it.", "She was repairing it."], correctAnswer: "She was holding it." },
  { id: "qiz_tenait_hold_06", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 6, format: "target_identification", contextFrench: "Louis tenait la poignée, regardait le quai, puis attendait le signal du conducteur.", promptFrench: "Quel mot indique que Louis gardait la poignée dans sa main ?", choicesFrench: ["tenait", "regardait", "attendait", "conducteur"], correctAnswer: "tenait" },
  { id: "qiz_tenait_hold_07", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 7, format: "target_identification", contextFrench: "La guide tenait une carte, expliquait le trajet et montrait la montagne aux visiteurs.", promptFrench: "Quel mot exprime la possession continue de la carte dans la main de la guide ?", choicesFrench: ["tenait", "expliquait", "montrait", "visiteurs"], correctAnswer: "tenait" },
  { id: "qiz_tenait_hold_08", surfaceFormId: "srf_tenait", senseId: "sns_tenir_hold", masteryLevel: 8, format: "target_identification", contextFrench: "Au moment de l’annonce, le témoin tenait l’enveloppe, lisait le nom et observait le public.", promptFrench: "Quel mot décrit l’action durable exercée sur l’enveloppe ?", choicesFrench: ["annonce", "tenait", "lisait", "public"], correctAnswer: "tenait" },
];
