import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch11: ContentBundle["quizItems"] = [
 ...authoredSet({key:"etes",surfaceFormId:"srf_etes",senseId:"sns_etre_primary",target:"êtes",meaning:"are",
 early:[["Vous êtes en avance ce matin.",["were","will be","have"]],["Madame, vous êtes très patiente.",["seem","become","remain"]],["Paul et Luc, vous êtes prêts à partir.",["go","arrive","wait"]]],blank:["Vous ___ responsable de cette équipe.",["êtes","suis","est","sommes"]],comprehension:["Vous êtes devant la bonne porte, Monsieur.","La personne se trouve-t-elle au bon endroit ?",["Yes, at the correct door.","No, at the wrong building.","No, inside the office.","Yes, beside the station."],"Yes, at the correct door."],advanced:[["Madame, vous êtes calme, votre collègue semble inquiet et nous restons attentifs.","Quel mot est la forme de « être » associée à « vous » ?",["êtes","semble","restons","collègue"]],["Vous êtes médecin, Paul devient infirmier et Léa travaille au laboratoire.","Quel mot relie « vous » à la profession de médecin ?",["êtes","devient","travaille","laboratoire"]],["Si vous êtes disponible, le directeur organisera la réunion et préviendra le comité.","Quel mot exprime l’état de disponibilité du destinataire ?",["êtes","directeur","réunion","comité"]]]}),
 ...authoredSet({key:"joli",surfaceFormId:"srf_joli",senseId:"sns_joli_primary",target:"joli",meaning:"pretty; handsome",
 early:[["Ce joli jardin attire de nombreux visiteurs.",["ugly","empty","dangerous"]],["Paul porte un joli costume bleu.",["dirty","torn","heavy"]],["Le village offre un joli panorama sur la vallée.",["narrow","dark","ordinary"]]],blank:["Nina choisit un ___ bouquet pour sa mère.",["joli","jolie","jolis","jolies"]],comprehension:["Marc habite dans un joli village entouré de montagnes.","Comment le village est-il présenté ?",["as pretty","as crowded","as modern","as distant"],"as pretty"],advanced:[["Un joli tableau couvre le mur, tandis qu’une vieille horloge occupe la table.","Quel mot exprime l’agrément esthétique du tableau ?",["joli","mur","vieille","table"]],["Le jardinier crée un joli massif avec des roses, des pierres et une petite fontaine.","Quel mot donne une appréciation positive de l’apparence du massif ?",["jardinier","joli","pierres","fontaine"]],["Sous la lumière, le tissu révèle un joli motif, une couleur profonde et une texture fine.","Quel mot qualifie favorablement l’aspect du motif ?",["lumière","joli","couleur","texture"]]]}),
 ...authoredSet({key:"me",surfaceFormId:"srf_me",senseId:"sns_me_primary",target:"me",meaning:"to me; me",
 early:[["Paul me donne son adresse.",["to him","to us","to them"]],["Cette musique me calme immédiatement.",["you","her","them"]],["Vous me semblez très occupé aujourd’hui.",["yourself","us","him"]]],blank:["Elle ___ montre le chemin vers la gare.",["me","lui","nous","les"]],comprehension:["Nina me prête son parapluie pendant l’orage.","Que Nina me prête-t-elle ?",["her umbrella","her coat","a map","a bicycle"],"her umbrella"],advanced:[["Paul me remet la clé, garde le reçu et montre la porte à Luc.","Quel mot désigne la personne qui reçoit la clé et qui parle ?",["Paul","me","reçu","Luc"]],["Ce résultat me surprend, rassure mon collègue et satisfait le directeur.","Quel mot représente la personne qui éprouve la surprise ?",["résultat","me","collègue","directeur"]],["La présidente me demande un rapport, vous confie le dossier et appelle son conseiller.","Quel mot désigne le premier destinataire de sa demande ?",["présidente","me","vous","conseiller"]]]}),
];
