import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch30: ContentBundle["quizItems"] = [
  ...authoredSet({key:"honteux",surfaceFormId:"srf_honteux",senseId:"sns_honteux_primary",target:"honteux",meaning:"ashamed",
    early:[["Paul est honteux d’avoir menti à ses amis.",["proud","calm","amused"]],["Le garçon baisse les yeux, honteux de sa faute.",["angry","surprised","careless"]],["Honteux de son comportement, Marc présente ses excuses.",["satisfied","curious","impatient"]]],blank:["Après avoir triché, le garçon paraît ___ devant la classe.",["honteux","honteuse","honte","honteusement"]],comprehension:["Marc est honteux d’avoir accusé Paul sans preuve et va lui demander pardon.","Pourquoi Marc demande-t-il pardon à Paul ?",["He is ashamed of accusing him without evidence.","He lost something Paul lent him.","He arrived late for their meeting.","He forgot to invite Paul."],"He is ashamed of accusing him without evidence."],advanced:[["Paul, honteux de son mensonge, évite le regard de Nina et finit par avouer la vérité.","Quel mot décrit la honte ressentie par Paul ?",["Paul","honteux","mensonge","vérité"]],["Le joueur honteux reconnaît sa tricherie, rend le trophée et quitte silencieusement la salle.","Quel mot indique que le joueur éprouve de la honte ?",["joueur","honteux","trophée","salle"]],["Honteux après sa remarque cruelle, Marc écrit une lettre et présente des excuses sincères.","Quel mot qualifie Marc lorsqu’il regrette sa remarque ?",["honteux","Marc","lettre","excuses"]]]}),
  ...authoredSet({key:"confus_abashed",surfaceFormId:"srf_confus",senseId:"sns_confus_primary",target:"confus",meaning:"abashed; embarrassed",
    early:[["Pris en faute, Paul reste confus devant le directeur.",["confident","delighted","indifferent"]],["Marc paraît confus après que son mensonge est découvert.",["relaxed","triumphant","carefree"]],["Le garçon, confus par le reproche, ne trouve rien à répondre.",["proud","cheerful","bold"]]],blank:["Démasqué devant tous, le tricheur demeure ___ et silencieux.",["confus","confuse","confond","confusion"]],comprehension:["Paul devient confus lorsque Nina révèle devant la classe qu’il a copié son travail.","Pourquoi Paul est-il embarrassé ?",["His copying has been exposed.","He forgot where the classroom is.","He received an unexpected prize.","He cannot hear Nina."],"His copying has been exposed."],advanced:[["Confus après son erreur, Marc rougit, baisse la tête et murmure une excuse.","Quel mot décrit son embarras mêlé de honte ?",["confus","Marc","tête","excuse"]],["Le menteur confus évite les regards, reconnaît les faits et promet de réparer le dommage.","Quel mot indique qu’il est décontenancé et honteux ?",["menteur","confus","faits","dommage"]],["Devant les preuves, Paul reste confus, abandonne ses protestations et admet sa faute.","Quel mot qualifie Paul lorsqu’il se trouve démasqué ?",["preuves","Paul","confus","faute"]]]}),
  ...authoredSet({key:"jura",surfaceFormId:"srf_jura",senseId:"sns_jurer_primary",target:"jura",meaning:"swore",
    early:[["Paul jura de ne jamais révéler le secret.",["forgot","refused","pretended"]],["Le témoin jura de dire toute la vérité.",["guessed","feared","asked"]],["Devant ses amis, Marc jura qu’il tiendrait sa promesse.",["whispered","doubted","noticed"]]],blank:["Ce jour-là, le soldat ___ de protéger le village.",["jura","jure","jurait","jurer"]],comprehension:["Nina jura de rendre le livre avant vendredi et nota la date dans son agenda.","Quel engagement Nina prend-elle ?",["To return the book before Friday.","To buy a new book on Friday.","To lend her agenda to someone.","To visit the library every day."],"To return the book before Friday."],advanced:[["Paul jura de garder le silence, serra la main de Marc et rangea la lettre secrète.","Quel mot indique qu’il fit une promesse solennelle ?",["Paul","jura","Marc","lettre"]],["Le chevalier jura fidélité au roi, reçut son épée et rejoignit les autres gardes.","Quel mot désigne l’action de prononcer un serment ?",["chevalier","jura","roi","épée"]],["Après son erreur, Nina jura qu’elle vérifierait désormais chaque résultat avant de répondre.","Quel mot indique qu’elle prit un engagement ferme ?",["Nina","jura","résultat","répondre"]]]}),
];
