import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch29: ContentBundle["quizItems"] = [
  ...authoredSet({key:"vaut",surfaceFormId:"srf_vaut",senseId:"sns_valoir_primary",target:"vaut",meaning:"is worth",
    early:[["Cette montre vaut cent euros.",["costs less than","weighs","contains"]],["Son avis vaut la peine d’être entendu.",["prevents","changes","forgets"]],["Ce tableau vaut beaucoup plus aujourd’hui.",["looks","measures","travels"]]],blank:["Ce vieux livre ___ une petite fortune.",["vaut","vaux","valent","valoir"]],comprehension:["Cette réparation vaut cinquante euros, mais Paul ne possède que vingt euros.","Pourquoi Paul ne peut-il pas payer la réparation ?",["It costs more money than he has.","The shop is closed.","The repair is impossible.","He forgot the object at home."],"It costs more money than he has."],advanced:[["Cette bague vaut mille euros, possède une pierre rare et appartient à Nina.","Quel mot indique la valeur monétaire de la bague ?",["bague","vaut","pierre","Nina"]],["Un geste sincère vaut parfois un long discours et laisse un souvenir durable.","Quel mot exprime l’équivalence de valeur entre le geste et le discours ?",["geste","vaut","discours","souvenir"]],["Selon l’expert, le terrain vaut davantage depuis la construction de la nouvelle route.","Quel mot attribue une valeur au terrain ?",["expert","terrain","vaut","route"]]]}),
  ...authoredSet({key:"bien_emphatic",surfaceFormId:"srf_bien",senseId:"sns_bien_primary",target:"bien",meaning:"indeed",
    early:[["C’est bien la bonne adresse.",["perhaps","never","elsewhere"]],["Cette signature est bien celle de Paul.",["rarely","almost","otherwise"]],["Nina est bien la personne que nous cherchons.",["formerly","sometimes","nearby"]]],blank:["C’est ___ le document demandé.",["bien","bon","mieux","beau"]],comprehension:["La porte est bien verrouillée ; Paul vérifie la poignée une dernière fois.","Qu’est-ce que Paul confirme ?",["The door is indeed locked.","The key is missing.","The handle is broken.","The door opens outward."],"The door is indeed locked."],advanced:[["Ce train est bien celui de Lyon, comme le confirment le panneau et l’agent du quai.","Quel mot renforce la confirmation de l’identité du train ?",["train","bien","panneau","agent"]],["Nina a bien envoyé le dossier, car le reçu apparaît dans sa boîte électronique.","Quel mot insiste sur la réalité de l’envoi ?",["Nina","bien","dossier","reçu"]],["Le témoin reconnaît bien Paul sur la photographie et confirme son identité au policier.","Quel mot souligne la certitude de la reconnaissance ?",["témoin","bien","Paul","policier"]]]}),
  ...authoredSet({key:"doute",surfaceFormId:"srf_doute",senseId:"sns_doute_primary",target:"doute",meaning:"doubt",
    early:[["J’ai un doute sur l’heure du rendez-vous.",["certainty","memory","plan"]],["Un doute empêche Nina de signer immédiatement.",["promise","reward","rule"]],["Paul exprime un doute au sujet de cette information.",["compliment","request","decision"]]],blank:["Aucun ___ ne subsiste après cette preuve.",["doute","doutes","douter","douteux"]],comprehension:["Un doute subsiste sur la solidité du pont, alors les ingénieurs retardent son ouverture.","Pourquoi l’ouverture du pont est-elle retardée ?",["Its safety remains uncertain.","The road is too narrow.","The workers are on vacation.","A ceremony is being planned."],"Its safety remains uncertain."],advanced:[["Le doute persiste malgré le rapport, inquiète les habitants et pousse le maire à demander une enquête.","Quel mot désigne l’incertitude qui demeure ?",["doute","rapport","habitants","enquête"]],["Nina éprouve un doute, relit le contrat et consulte son avocat avant de répondre.","Quel mot nomme son manque de certitude ?",["Nina","doute","contrat","avocat"]],["Le témoignage dissipe le doute, confirme les faits et permet au juge de décider.","Quel mot désigne l’incertitude supprimée par le témoignage ?",["témoignage","doute","faits","juge"]]]}),
];
