import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch27: ContentBundle["quizItems"] = [
  ...authoredSet({key:"celui",surfaceFormId:"srf_celui",senseId:"sns_celui_primary",target:"celui",meaning:"the one",
    early:[["Parmi les deux sacs, celui de Paul est bleu.",["this","these","theirs"]],["Je préfère celui qui possède une grande poche.",["each","nothing","someone"]],["Le bureau du haut est plus calme que celui du rez-de-chaussée.",["whose","some","both"]]],blank:["De ces deux tableaux, ___ de gauche est le plus ancien.",["celui","celle","ceux","celles"]],comprehension:["Nina essaie deux clés ; celui en cuivre ouvre finalement la porte.","Quelle clé permet à Nina d’ouvrir la porte ?",["The copper one.","The silver one.","Both keys.","Neither key."],"The copper one."],advanced:[["Marc compare les vélos et choisit celui de Nina, car son cadre est plus léger.","Quel mot remplace le nom masculin « vélo » pour éviter sa répétition ?",["Marc","vélos","celui","cadre"]],["Le premier train est complet, mais celui de midi possède encore plusieurs places.","Quel mot désigne le train de midi sans répéter le nom « train » ?",["train","complet","celui","places"]],["Parmi ces chemins, celui du nord traverse la forêt et rejoint directement le village.","Quel mot reprend le nom masculin « chemin » ?",["chemins","celui","forêt","village"]]]}),
  ...authoredSet({key:"qui",surfaceFormId:"srf_qui",senseId:"sns_qui_primary",target:"qui",meaning:"who; which",
    early:[["La femme qui dirige le musée accueille les visiteurs.",["whom","where","when"]],["Voici le livre qui explique cette méthode.",["whose","what","how"]],["Le voisin qui possède ce chien habite au troisième étage.",["why","where","whether"]]],blank:["Le médecin ___ arrive demain connaît déjà le dossier.",["qui","que","dont","où"]],comprehension:["L’oiseau qui chante près de la fenêtre réveille le bébé chaque matin.","Quel oiseau réveille le bébé ?",["The one singing near the window.","The one flying over the roof.","The one inside a cage.","The one beside the river."],"The one singing near the window."],advanced:[["Le guide qui connaît la montagne vérifie la carte et conduit le groupe.","Quel mot relie « guide » au verbe dont il est le sujet ?",["guide","qui","carte","groupe"]],["Paul répare la lampe qui éclaire le bureau avant de ranger ses outils.","Quel mot introduit la proposition décrivant la lampe ?",["Paul","lampe","qui","outils"]],["La chercheuse qui présente les résultats répond ensuite aux questions du public.","Quel mot reprend « chercheuse » comme sujet de « présente » ?",["chercheuse","qui","résultats","public"]]]}),
  ...authoredSet({key:"l_object",surfaceFormId:"srf_l_elided",senseId:"sns_le_object",target:"l’",meaning:"him; her; it",
    early:[["Paul retrouve son frère et l’accompagne à la gare.",["the","there","some"]],["Nina prend la lettre et l’ouvre avec précaution.",["the","from it","hers"]],["Le vétérinaire examine la chatte puis l’opère le lendemain.",["the","to her","there"]]],blank:["Nina voit Paul et ___invite à entrer.",["l’","le","lui","en"]],comprehension:["Marc cherche son chien dans le parc et l’aperçoit derrière un banc.","Qu’est-ce que Marc aperçoit derrière le banc ?",["His dog.","A child.","A bicycle.","His neighbor."],"His dog."],advanced:[["Nina prend la pomme, l’épluche soigneusement et pose la peau dans une assiette.","Quel élément remplace « la pomme » comme objet du verbe « épluche » ?",["Nina","pomme","l’","peau"]],["Paul retrouve Marc, l’invite à déjeuner et réserve une table près de la fenêtre.","Quel élément remplace Marc comme objet du verbe « invite » ?",["Paul","Marc","l’","table"]],["Le mécanicien inspecte la voiture, l’essaie sur la route et vérifie ensuite le moteur.","Quel élément reprend « la voiture » comme objet du verbe « essaie » ?",["mécanicien","voiture","l’","moteur"]]]}),
];
