import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";

export const corbeauQuizBatch24: ContentBundle["quizItems"] = [
  ...authoredSet({key:"mon",surfaceFormId:"srf_mon",senseId:"sns_mon_primary",target:"mon",meaning:"my",
    early:[["Je range mon manteau dans l’armoire.",["your","his","our"]],["Voici mon billet pour le concert.",["her","their","your"]],["Je téléphone à mon frère ce soir.",["his","our","their"]]],blank:["Je cherche ___ chapeau noir.",["mon","ma","mes","son"]],comprehension:["Je prête mon dictionnaire à Nina pour son examen.","À qui appartient le dictionnaire ?",["The speaker.","Nina.","The teacher.","The school."],"The speaker."],advanced:[["Je prends mon sac, vérifie mes billets et rejoins notre groupe devant la gare.","Quel mot indique que le sac appartient à la personne qui parle ?",["mon","mes","notre","gare"]],["Dans mon bureau, je classe ce dossier et pose votre lettre près de la lampe.","Quel mot relie le bureau à la personne qui parle ?",["mon","ce","votre","lampe"]],["Je présente mon projet au directeur, puis son adjointe distribue nos documents.","Quel mot indique que le projet est celui de la personne qui parle ?",["mon","directeur","son","nos"]]]}),
  ...authoredSet({key:"bon",surfaceFormId:"srf_bon",senseId:"sns_bon_primary",target:"bon",meaning:"good",
    early:[["Paul prépare un bon repas pour ses amis.",["bad","cold","small"]],["Ce médecin donne un bon conseil à Nina.",["false","strange","dangerous"]],["Nous avons choisi un bon hôtel près de la plage.",["noisy","empty","distant"]]],blank:["Marc obtient un ___ résultat à l’examen.",["bon","bonne","bons","mauvais"]],comprehension:["Ce pain est encore bon, alors Léa le sert avec le dîner.","Pourquoi Léa décide-t-elle de servir le pain ?",["It is still good.","It is very expensive.","It is already sliced.","It came from Paris."],"It is still good."],advanced:[["Un bon outil facilite le travail, tandis qu’un outil fragile ralentit souvent l’équipe.","Quel mot exprime la qualité positive du premier outil ?",["bon","outil","fragile","équipe"]],["Marc propose un bon plan, explique chaque étape et écoute les remarques de Nina.","Quel mot indique que le plan est jugé favorablement ?",["Marc","bon","étape","Nina"]],["Le restaurant sert un bon café, offre plusieurs desserts et accueille les clients avec soin.","Quel mot exprime la qualité positive du café ?",["restaurant","bon","desserts","clients"]]]}),
  ...authoredSet({key:"apprenez",surfaceFormId:"srf_apprenez",senseId:"sns_apprendre_primary",target:"apprenez",meaning:"learn",
    early:[["Pour progresser, apprenez cinq mots chaque jour.",["forget","repeat","write"]],["Avant le voyage, apprenez les règles locales.",["change","ignore","question"]],["En observant le guide, apprenez à reconnaître ces oiseaux.",["teach","refuse","pretend"]]],blank:["Avant l’examen, ___ cette formule par cœur.",["apprenez","apprends","apprendre","apprenons"]],comprehension:["Pour mieux cuisiner, apprenez d’abord à utiliser correctement ce couteau.","Quelle compétence faut-il acquérir en premier ?",["Using the knife correctly.","Choosing fresh vegetables.","Cleaning the kitchen.","Reading a recipe aloud."],"Using the knife correctly."],advanced:[["En classe, apprenez cette règle, comparez les exemples et corrigez vos réponses.","Quel mot demande aux élèves d’acquérir la connaissance de la règle ?",["classe","apprenez","exemples","réponses"]],["Pendant la formation, apprenez le nouveau procédé, observez le technicien et notez chaque étape.","Quel mot ordonne aux participants d’acquérir un nouveau savoir ?",["formation","apprenez","technicien","étape"]],["Avant de partir, apprenez cet itinéraire, repérez les ponts et mémorisez le nom des villages.","Quel mot invite plusieurs personnes à étudier l’itinéraire ?",["apprenez","itinéraire","ponts","villages"]]]}),
];
