import type { ContentBundle } from "../../domain/model.js";
import { authoredSet } from "./authoring.js";
export const corbeauQuizBatch14: ContentBundle["quizItems"] = [
 ...authoredSet({key:"ramage",surfaceFormId:"srf_ramage",senseId:"sns_ramage_primary",target:"ramage",meaning:"birdsong; warbling",
 early:[["Le ramage du merle réveille le jardinier.",["plumage","nest","flight"]],["On reconnaît l’oiseau à son doux ramage.",["beak","claw","shadow"]],["Le ramage mélodieux du rossignol remplit le bois.",["silence","color","movement"]]],blank:["Au lever du jour, le ___ des oiseaux anime la forêt.",["ramage","plumage","feuillage","nuage"]],comprehension:["Le ramage du canari charme les visiteurs.","Qu’est-ce qui charme les visiteurs ?",["the canary’s song","the canary’s color","the cage","the garden"],"the canary’s song"],advanced:[["Le ramage du pinson traverse le jardin, tandis que son plumage brille au soleil.","Quel mot désigne le chant de l’oiseau ?",["ramage","pinson","plumage","soleil"]],["Dans le bois, le ramage du rossignol domine le bruit du vent et le murmure du ruisseau.","Quel mot nomme la voix chantée du rossignol ?",["bois","ramage","vent","ruisseau"]],["L’ornithologue note le ramage, observe le bec et décrit les ailes de chaque espèce.","Quel mot correspond au chant étudié par l’ornithologue ?",["ornithologue","ramage","bec","ailes"]]]}),
 ...authoredSet({key:"se",surfaceFormId:"srf_se",senseId:"sns_se_primary",target:"se",meaning:"oneself; himself; herself",
 early:[["Paul se regarde dans le miroir.",["him","us","them"]],["Nina se prépare avant le départ.",["you","me","her"]],["Le chat se cache sous le lit.",["it","there","of it"]]],blank:["Marc ___ lave les mains avant le repas.",["se","le","lui","en"]],comprehension:["Léa se couvre avec une couverture chaude.","Qui Léa couvre-t-elle ?",["herself","her sister","the child","the dog"],"herself"],advanced:[["Paul se rase, prend sa veste et ferme la porte.","Quel mot montre que Paul exerce l’action sur lui-même ?",["Paul","se","veste","porte"]],["La danseuse se regarde dans le miroir pendant que son professeur prépare la musique.","Quel mot renvoie au sujet « la danseuse » ?",["danseuse","se","miroir","musique"]],["Avant l’entretien, le candidat se présente, salue le jury et ouvre son dossier.","Quel mot fait revenir l’action de présenter sur le candidat lui-même ?",["candidat","se","jury","dossier"]]]}),
 ...authoredSet({key:"rapporte",surfaceFormId:"srf_rapporte",senseId:"sns_rapporter_primary",target:"rapporte",meaning:"corresponds; matches",
 early:[["Cette description se rapporte exactement au tableau.",["carries back","earns","reports"]],["Le chiffre se rapporte à l’année précédente.",["opposes","replaces","hides"]],["Chaque couleur se rapporte à une catégorie précise.",["moves","returns","speaks"]]],blank:["Dans cette légende, le symbole bleu se ___ à la mer.",["rapporte","rapportent","rapporter","rapporté"]],comprehension:["La dernière remarque se rapporte au problème principal.","À quoi la remarque est-elle liée ?",["the main problem","the final answer","the first chapter","the new employee"],"the main problem"],advanced:[["Le premier chiffre se rapporte aux ventes, le second indique les dépenses et la note explique l’écart.","Quel mot signifie que le chiffre concerne les ventes ?",["chiffre","rapporte","dépenses","note"]],["Dans le guide, cette couleur se rapporte au danger, tandis que le cercle signale une obligation.","Quel mot établit le lien entre la couleur et le danger ?",["guide","couleur","rapporte","cercle"]],["L’article se rapporte à une période ancienne, analyse plusieurs archives et cite un historien.","Quel mot indique que l’article concerne cette période ?",["article","rapporte","archives","historien"]]]}),
];
